# Men's Scrape Schedule

Get schedule of each team in a given year. This file needs to be ran for every relevant year (starting in 2012).

### Web Scraping

Fair warning that this program unfortunately takes a very long time to run due to web scraping limits set by Sports Reference

In [1]:
SEASON = 2025

In [2]:
import pandas as pd
import numpy as np
import time

pd.set_option('display.max_columns', 100)

df_active_teams = pd.read_html('https://www.sports-reference.com/cbb/schools/index.html')[0]
time.sleep(2)

df_active_teams = df_active_teams.loc[~df_active_teams['School'].isin([np.NaN, 'School']), :].reset_index(drop=True)

df_active_teams['From'] = pd.to_numeric(df_active_teams['From'], errors='coerce')
df_active_teams['To'] = pd.to_numeric(df_active_teams['To'], errors='coerce')

df_active_teams = df_active_teams.loc[(df_active_teams['To'] >= SEASON) & (df_active_teams['From'] <= SEASON), :].reset_index(drop=True)

if SEASON == 2021:  # if 2021, remove ivy league because they cancelled their season in 2021
    df_active_teams = df_active_teams.loc[
        ~df_active_teams['School'].isin(['Princeton', 'Harvard', 'Yale', 'Pennsylvania', 'Brown', 'Columbia', 'Cornell', 'Dartmouth']), 
        :
    ].reset_index(drop=True)

df_active_teams

,Rk,School,"City, State",From,To,Yrs,G,W,L,W-L%,SRS,SOS,AP,CREG,CTRN,NCAA,FF,NC
0,1,Abilene Christian,"Abilene, Texas",1971,2025,15,455,242,213,.532,-7.59,-5.33,0,0,2,2,0,0
1,2,Air Force,"USAF Academy, Colorado",1958,2025,68,1875,797,1078,.425,-2.87,1.37,0,1,0,4,0,0
2,3,Akron,"Akron, Ohio",1902,2025,74,1752,1055,697,.602,0.08,-1.62,0,10,6,6,0,0
3,4,Alabama,"Tuscaloosa, Alabama",1913,2025,112,2929,1819,1109,.621,8.18,5.07,18,10,9,25,1,0
4,5,Alabama A&M,"Normal, Alabama",2000,2025,26,755,287,468,.380,-16.75,-11.02,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,489,Wright State,"Dayton, Ohio",1988,2025,38,1161,646,515,.556,-1.42,-2.60,0,4,4,4,0,0
360,490,Wyoming,"Laramie, Wyoming",1905,2025,120,2911,1622,1289,.557,2.69,2.76,4,21,3,16,1,1
361,491,Xavier,"Cincinnati, Ohio",1920,2025,104,2729,1632,1097,.598,6.20,4.06,13,18,9,29,0,0
362,492,Yale,"New Haven, Connecticut",1896,2025,129,3114,1588,1524,.510,-5.82,-4.43,1,17,3,7,0,0
363,493,Youngstown State,"Youngstown, Ohio",1948,2025,45,1326,551,775,.416,-7.88,-3.56,0,1,0,0,0,0

In [3]:
from datetime import datetime

cutoff_dates = {
    2012: datetime(2012, 3, 14),
    2013: datetime(2013, 3, 20),
    2014: datetime(2014, 3, 19),
    2015: datetime(2015, 3, 18),
    2016: datetime(2016, 3, 16),
    2017: datetime(2017, 3, 15),
    2018: datetime(2018, 3, 14),
    2019: datetime(2019, 3, 20),
    2021: datetime(2021, 3, 18),
    2022: datetime(2022, 3, 16),
    2023: datetime(2023, 3, 15),
    2024: datetime(2024, 3, 20),
    2025: datetime(2025, 3, 19),
}

cutoff_dates[SEASON]

datetime.datetime(2025, 3, 19, 0, 0)

Get school names used in Sports Reference URL

In [4]:
df_active_teams['URL School'] = df_active_teams['School']

# hard code some schools that cause issues
df_active_teams.loc[df_active_teams['School'] == 'Bowling Green', 'URL School'] = 'Bowling Green State'
df_active_teams.loc[df_active_teams['School'] == 'BYU', 'URL School'] = 'Brigham Young'
df_active_teams.loc[df_active_teams['School'] == 'Louisiana', 'URL School'] = 'Louisiana Lafayette'
df_active_teams.loc[df_active_teams['School'] == 'LSU', 'URL School'] = 'Louisiana State'
df_active_teams.loc[df_active_teams['School'] == 'Ole Miss', 'URL School'] = 'Mississippi'
df_active_teams.loc[df_active_teams['School'] == 'Pitt', 'URL School'] = 'Pittsburgh'
df_active_teams.loc[df_active_teams['School'] == 'SMU', 'URL School'] = 'Southern Methodist'
df_active_teams.loc[df_active_teams['School'] == 'UAB', 'URL School'] = 'Alabama Birmingham'
df_active_teams.loc[df_active_teams['School'] == 'UCF', 'URL School'] = 'Central Florida'
df_active_teams.loc[df_active_teams['School'] == 'USC', 'URL School'] = 'Southern California'
df_active_teams.loc[df_active_teams['School'] == 'UTEP', 'URL School'] = 'Texas El Paso'
df_active_teams.loc[df_active_teams['School'] == 'UTSA', 'URL School'] = 'Texas San Antonio'
df_active_teams.loc[df_active_teams['School'] == 'Sam Houston', 'URL School'] = 'Sam Houston State'
df_active_teams.loc[df_active_teams['School'] == 'Houston Christian', 'URL School'] = 'Houston Baptist'
df_active_teams.loc[df_active_teams['School'] == 'Kansas City', 'URL School'] = 'Missouri Kansas City'
df_active_teams.loc[df_active_teams['School'] == 'Little Rock', 'URL School'] = 'Arkansas Little Rock'
df_active_teams.loc[df_active_teams['School'] == 'NC State', 'URL School'] = 'North Carolina State'
df_active_teams.loc[df_active_teams['School'] == 'Omaha', 'URL School'] = 'Nebraska Omaha'
df_active_teams.loc[df_active_teams['School'] == 'Purdue Fort Wayne', 'URL School'] = 'IPFW'
df_active_teams.loc[df_active_teams['School'] == 'TCU', 'URL School'] = 'Texas Christian'
df_active_teams.loc[df_active_teams['School'] == 'Texas-Rio Grande Valley', 'URL School'] = 'Texas Pan American'
df_active_teams.loc[df_active_teams['School'] == 'The Citadel', 'URL School'] = 'Citadel'
df_active_teams.loc[df_active_teams['School'] == 'Utah Tech', 'URL School'] = 'Dixie State'
df_active_teams.loc[df_active_teams['School'] == 'St. Thomas', 'URL School'] = 'St. Thomas MN'
df_active_teams.loc[df_active_teams['School'] == 'UC Berkley', 'URL School'] = 'California'
df_active_teams.loc[df_active_teams['School'] == 'UT Arlington', 'URL School'] = 'Texas Arlington'
df_active_teams.loc[df_active_teams['School'] == 'FDU', 'URL School'] = 'Fairleigh Dickinson'
df_active_teams.loc[df_active_teams['School'] == 'Hartford Hawks', 'URL School'] = 'Hartford'
df_active_teams.loc[df_active_teams['School'] == 'Savannah State Tigers', 'URL School'] = 'Savannah State'
df_active_teams.loc[df_active_teams['School'] == 'St. Francis (NY) Terriers', 'URL School'] = 'St. Francis (NY)'
df_active_teams.loc[df_active_teams['School'] == 'East Texas A&M', 'URL School'] = 'Texas A&M Commerce'
df_active_teams.loc[df_active_teams['School'] == 'IU Indy', 'URL School'] = 'IUPUI'

df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UC\s', 'California ', regex=True)
df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UNC\s', 'North Carolina ', regex=True)

In [5]:
urls = (
    'https://www.sports-reference.com/cbb/schools/' +
    df_active_teams['URL School'].str.replace(' ', '-', regex=False).str.replace('[)(&.\']', '', regex=True).str.replace('--', '-', regex=False).str.lower() +
    '/men/' + str(SEASON) +
    '-gamelogs.html'
)

urls

0      https://www.sports-reference.com/cbb/schools/a...
1      https://www.sports-reference.com/cbb/schools/a...
2      https://www.sports-reference.com/cbb/schools/a...
3      https://www.sports-reference.com/cbb/schools/a...
4      https://www.sports-reference.com/cbb/schools/a...
                             ...
359    https://www.sports-reference.com/cbb/schools/w...
360    https://www.sports-reference.com/cbb/schools/w...
361    https://www.sports-reference.com/cbb/schools/x...
362    https://www.sports-reference.com/cbb/schools/y...
363    https://www.sports-reference.com/cbb/schools/y...
Name: URL School, Length: 364, dtype: object

In [6]:
from urllib.error import HTTPError
from tqdm.notebook import tqdm

problems = []

l = []
loop = tqdm(
    np.array((df_active_teams['School'], urls)).transpose(),  # get both school and url into loop iteration
    bar_format='{bar}{percentage:3.0f}%{r_bar}   {desc}'  # make the description not affect bar location
)
for (school, url) in loop:
  try:
    loop.set_description(f'{school}')
    # print(f'{i:03d}: {url}')
    df_team_season = pd.read_html(url)[-1]  # schools that were ranked have that info as the first table on the site
    time.sleep(2)

    df_team_season.columns = [i[1] if 'Unnamed' in i[0] else i[0] + ' ' + i[1] for i in df_team_season.columns]
    df_team_season.insert(2, 'Team', school)
    l.append(df_team_season)
  except ValueError as e:
    print(f'{url} | ValueError: {e}')
    time.sleep(2)
  except HTTPError as e:
    if e.code == 404:
      print(f'{url} | {e}')
      time.sleep(2)
    else:
      print(f'{url} | {e}')
      break

df = pd.concat(l, ignore_index=True)

df

            0%| 0/364 [00:00<?, ?it/s]

,Rk,Gtm,Team,Date,Unnamed: 3_level_1,Opp,Type,Score Rslt,Score Tm,Score Opp,Score OT,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF
0,1,1,Abilene Christian,2024-11-04,NaN,Howard Payne,REG (Non-Conf),W,107,74,NaN,42,73,.575,3,13,.231,39,60,.650,.596,20,33,.606,24,49,73,16,9,4,32,21,24,80,.300,7,41,.171,17,39,.436,.344,19,25,.760,9,8,17,8,20,0,14,24
1,2,2,Abilene Christian,2024-11-09,NaN,Middle Tennessee,REG (Non-Conf),L,56,79,NaN,19,49,.388,2,14,.143,17,35,.486,.408,16,25,.640,9,20,29,9,8,5,19,15,31,60,.517,6,17,.353,25,43,.581,.567,11,14,.786,7,23,30,13,14,4,13,21
2,3,3,Abilene Christian,2024-11-12,NaN,McMurry,REG (Non-Conf),W,101,55,NaN,41,74,.554,13,30,.433,28,44,.636,.642,6,8,.750,10,32,42,23,14,4,9,14,16,55,.291,5,27,.185,11,28,.393,.336,18,23,.783,7,23,30,7,5,1,19,12
3,4,4,Abilene Christian,2024-11-16,NaN,Texas State,REG (Non-Conf),W,72,60,NaN,24,49,.490,8,13,.615,16,36,.444,.571,16,22,.727,9,23,32,14,11,4,19,32,15,37,.405,3,8,.375,12,29,.414,.446,27,38,.711,3,18,21,6,8,3,15,20
4,5,5,Abilene Christian,2024-11-20,@,Kennesaw State,REG (Non-Conf),L,78,84,NaN,27,59,.458,5,15,.333,22,44,.500,.500,19,30,.633,6,14,20,16,13,2,7,25,22,41,.537,7,16,.438,15,25,.600,.622,33,41,.805,7,23,30,13,3,3,19,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12498,Rk,Gtm,Youngstown State,Date,NaN,Opp,Type,Rslt,Tm,Opp,OT,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF
12499,33,33,Youngstown State,2025-03-06,NaN,Purdue Fort Wayne,CTOURN,W,72,67,NaN,21,58,.362,5,28,.179,16,30,.533,.405,25,31,.806,10,34,44,10,6,5,17,20,23,62,.371,8,27,.296,15,35,.429,.435,13,20,.650,6,23,29,11,9,3,13,23
12500,34,34,Youngstown State,2025-03-10,N,Cleveland State,CTOURN,W,56,54,NaN,18,50,.360,8,25,.320,10,25,.400,.440,12,23,.522,12,20,32,11,10,4,11,12,19,46,.413,8,12,.667,11,34,.324,.500,8,12,.667,6,20,26,12,7,5,15,19
12501,35,35,Youngstown State,2025-03-11,N,Robert Morris,CTOURN,L,78,89,NaN,27,63,.429,11,29,.379,16,34,.471,.516,13,17,.765,7,25,32,17,5,7,5,21,29,62,.468,11,22,.500,18,40,.450,.556,20,28,.714,14,26,40,23,2,4,8,16
12502,NaN,NaN,Youngstown State,NaN,NaN,NaN,NaN,21-13,2599,2446,NaN,884,2028,.436,299,934,.320,585,1094,.535,.510,532,726,.733,333,806,1139,469,236,179,391,624,862,2028,.425,224,677,.331,638,1351,.472,.480,498,702,.709,305,785,1090,451,225,91,411,624

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12503 entries, 0 to 12502
Data columns (total 53 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rk                  12139 non-null  object
 1   Gtm                 12125 non-null  object
 2   Team                12503 non-null  object
 3   Date                12139 non-null  object
 4   Unnamed: 3_level_1  6301 non-null   object
 5   Opp                 12139 non-null  object
 6   Type                12139 non-null  object
 7   Score Rslt          12489 non-null  object
 8   Score Tm            12489 non-null  object
 9   Score Opp           12489 non-null  object
 10  Score OT            955 non-null    object
 11  Team FG             12489 non-null  object
 12  Team FGA            12489 non-null  object
 13  Team FG%            12489 non-null  object
 14  Team 3P             12489 non-null  object
 15  Team 3PA            12489 non-null  object
 16  Team 3P%            12489 non-null  object
 17  Team 2P             12489 non-null  object
 18  Team 2PA            12489 non-null  object
 19  Team 2P%            12489 non-null  object
 20  Team eFG%           12489 non-null  object
 21  Team FT             12489 non-null  object
 22  Team FTA            12489 non-null  object
 23  Team FT%            12487 non-null  object
 24  Team ORB            12489 non-null  object
 25  Team DRB            12489 non-null  object
 26  Team TRB            12489 non-null  object
 27  Team AST            12489 non-null  object
 28  Team STL            12489 non-null  object
 29  Team BLK            12489 non-null  object
 30  Team TOV            12489 non-null  object
 31  Team PF             12489 non-null  object
 32  Opponent FG         12489 non-null  object
 33  Opponent FGA        12489 non-null  object
 34  Opponent FG%        12489 non-null  object
 35  Opponent 3P         12489 non-null  object
 36  Opponent 3PA        12489 non-null  object
 37  Opponent 3P%        12489 non-null  object
 38  Opponent 2P         12489 non-null  object
 39  Opponent 2PA        12489 non-null  object
 40  Opponent 2P%        12489 non-null  object
 41  Opponent eFG%       12489 non-null  object
 42  Opponent FT         12489 non-null  object
 43  Opponent FTA        12489 non-null  object
 44  Opponent FT%        12486 non-null  object
 45  Opponent ORB        12489 non-null  object
 46  Opponent DRB        12489 non-null  object
 47  Opponent TRB        12489 non-null  object
 48  Opponent AST        12489 non-null  object
 49  Opponent STL        12489 non-null  object
 50  Opponent BLK        12489 non-null  object
 51  Opponent TOV        12489 non-null  object
 52  Opponent PF         12489 non-null  object
dtypes: object(53)
memory usage: 5.1+ MB

### Data Setup

In [8]:
temp = df.copy()

In [9]:
df = temp.copy()

Fix column names and drop useless columns

In [10]:
df.columns = (
    ['G', 'Gtm', 'Team', 'Date', 'Location', 'Opponent', 'Type', 'Result', 'Team Score', 'Opponent Score', 'OT'] +
    [c for c in df.columns[11:]]
)

# use "Team" as prefix instead of "School"
df.columns = df.columns.str.replace('School', 'Team', regex=False)

# drop columns that are completely null
df = df[[c for c in df.columns if df.loc[:, c].notna().any()]].copy()

# drop columns without a name
df = df.loc[:, ~df.columns.str.contains('^Unnamed', regex=True)]

# drop rows that aren't games
df = df.loc[(df['Date'].notna()) & (df['Result'].isin(['W', 'L'])), :].reset_index(drop=True)

# drop useless columns
df.drop(columns=['G', 'Gtm'], inplace=True)

df

,Team,Date,Location,Opponent,Type,Result,Team Score,Opponent Score,OT,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF
0,Abilene Christian,2024-11-04,NaN,Howard Payne,REG (Non-Conf),W,107,74,NaN,42,73,.575,3,13,.231,39,60,.650,.596,20,33,.606,24,49,73,16,9,4,32,21,24,80,.300,7,41,.171,17,39,.436,.344,19,25,.760,9,8,17,8,20,0,14,24
1,Abilene Christian,2024-11-09,NaN,Middle Tennessee,REG (Non-Conf),L,56,79,NaN,19,49,.388,2,14,.143,17,35,.486,.408,16,25,.640,9,20,29,9,8,5,19,15,31,60,.517,6,17,.353,25,43,.581,.567,11,14,.786,7,23,30,13,14,4,13,21
2,Abilene Christian,2024-11-12,NaN,McMurry,REG (Non-Conf),W,101,55,NaN,41,74,.554,13,30,.433,28,44,.636,.642,6,8,.750,10,32,42,23,14,4,9,14,16,55,.291,5,27,.185,11,28,.393,.336,18,23,.783,7,23,30,7,5,1,19,12
3,Abilene Christian,2024-11-16,NaN,Texas State,REG (Non-Conf),W,72,60,NaN,24,49,.490,8,13,.615,16,36,.444,.571,16,22,.727,9,23,32,14,11,4,19,32,15,37,.405,3,8,.375,12,29,.414,.446,27,38,.711,3,18,21,6,8,3,15,20
4,Abilene Christian,2024-11-20,@,Kennesaw State,REG (Non-Conf),L,78,84,NaN,27,59,.458,5,15,.333,22,44,.500,.500,19,30,.633,6,14,20,16,13,2,7,25,22,41,.537,7,16,.438,15,25,.600,.622,33,41,.805,7,23,30,13,3,3,19,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11805,Youngstown State,2025-02-23,NaN,Green Bay,REG (Conf),W,81,77,NaN,27,55,.491,6,18,.333,21,37,.568,.545,21,31,.677,9,25,34,10,5,5,16,19,27,59,.458,9,29,.310,18,30,.600,.534,14,21,.667,10,21,31,19,9,1,12,23
11806,Youngstown State,2025-03-01,@,Northern Kentucky,REG (Conf),L,79,88,NaN,26,57,.456,14,29,.483,12,28,.429,.579,13,17,.765,7,16,23,18,5,1,10,18,30,58,.517,9,24,.375,21,34,.618,.595,19,23,.826,8,24,32,15,3,4,8,16
11807,Youngstown State,2025-03-06,NaN,Purdue Fort Wayne,CTOURN,W,72,67,NaN,21,58,.362,5,28,.179,16,30,.533,.405,25,31,.806,10,34,44,10,6,5,17,20,23,62,.371,8,27,.296,15,35,.429,.435,13,20,.650,6,23,29,11,9,3,13,23
11808,Youngstown State,2025-03-10,N,Cleveland State,CTOURN,W,56,54,NaN,18,50,.360,8,25,.320,10,25,.400,.440,12,23,.522,12,20,32,11,10,4,11,12,19,46,.413,8,12,.667,11,34,.324,.500,8,12,.667,6,20,26,12,7,5,15,19
11809,Youngstown State,2025-03-11,N,Robert Morris,CTOURN,L,78,89,NaN,27,63,.429,11,29,.379,16,34,.471,.516,13,17,.765,7,25,32,17,5,7,5,21,29,62,.468,11,22,.500,18,40,.450,.556,20,28,.714,14,26,40,23,2,4,8,16

Fix data types

In [11]:
for col in df.columns:
    for dtype in (int, float):
        try:
            df[col] = df[col].astype(dtype)
            break
        except ValueError:
            pass

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11810 entries, 0 to 11809
Data columns (total 51 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Team            11810 non-null  object
 1   Date            11810 non-null  object
 2   Location        6295 non-null   object
 3   Opponent        11810 non-null  object
 4   Type            11810 non-null  object
 5   Result          11810 non-null  object
 6   Team Score      11810 non-null  int32
 7   Opponent Score  11810 non-null  int32
 8   OT              640 non-null    object
 9   Team FG         11810 non-null  int32
 10  Team FGA        11810 non-null  int32
 11  Team FG%        11810 non-null  float64
 12  Team 3P         11810 non-null  int32
 13  Team 3PA        11810 non-null  int32
 14  Team 3P%        11810 non-null  float64
 15  Team 2P         11810 non-null  int32
 16  Team 2PA        11810 non-null  int32
 17  Team 2P%        11810 non-null  float64
 18  Team eFG%       11810 non-null  float64
 19  Team FT         11810 non-null  int32
 20  Team FTA        11810 non-null  int32
 21  Team FT%        11808 non-null  float64
 22  Team ORB        11810 non-null  int32
 23  Team DRB        11810 non-null  int32
 24  Team TRB        11810 non-null  int32
 25  Team AST        11810 non-null  int32
 26  Team STL        11810 non-null  int32
 27  Team BLK        11810 non-null  int32
 28  Team TOV        11810 non-null  int32
 29  Team PF         11810 non-null  int32
 30  Opponent FG     11810 non-null  int32
 31  Opponent FGA    11810 non-null  int32
 32  Opponent FG%    11810 non-null  float64
 33  Opponent 3P     11810 non-null  int32
 34  Opponent 3PA    11810 non-null  int32
 35  Opponent 3P%    11810 non-null  float64
 36  Opponent 2P     11810 non-null  int32
 37  Opponent 2PA    11810 non-null  int32
 38  Opponent 2P%    11810 non-null  float64
 39  Opponent eFG%   11810 non-null  float64
 40  Opponent FT     11810 non-null  int32
 41  Opponent FTA    11810 non-null  int32
 42  Opponent FT%    11807 non-null  float64
 43  Opponent ORB    11810 non-null  int32
 44  Opponent DRB    11810 non-null  int32
 45  Opponent TRB    11810 non-null  int32
 46  Opponent AST    11810 non-null  int32
 47  Opponent STL    11810 non-null  int32
 48  Opponent BLK    11810 non-null  int32
 49  Opponent TOV    11810 non-null  int32
 50  Opponent PF     11810 non-null  int32
dtypes: float64(10), int32(34), object(7)
memory usage: 3.1+ MB

Get overtime information

In [12]:
# remove games that have not been played
df = df.loc[(df['Result'].notna()) & (df['Result'] != 'W/L'), :].reset_index(drop=True)

# get overtimes amount
df['Overtimes Amount'] = (
    df['OT']
    .apply(
        lambda x: 
        1 if x == 'OT' 
        else int(x[:-2]) if isinstance(x, str) and x.endswith('OT') and len(x) > 2 
        else 0
    )
)

# binary overtime flag
df['Overtime'] = df.pop('OT').notna().astype('int8')

# reformat result column
df['Result'] = df['Result'].str[:1].map({'W': 1, 'L': -1}).astype('int8')

df

,Team,Date,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,Abilene Christian,2024-11-04,NaN,Howard Payne,REG (Non-Conf),1,107,74,42,73,0.575,3,13,0.231,39,60,0.650,0.596,20,33,0.606,24,49,73,16,9,4,32,21,24,80,0.300,7,41,0.171,17,39,0.436,0.344,19,25,0.760,9,8,17,8,20,0,14,24,0,0
1,Abilene Christian,2024-11-09,NaN,Middle Tennessee,REG (Non-Conf),-1,56,79,19,49,0.388,2,14,0.143,17,35,0.486,0.408,16,25,0.640,9,20,29,9,8,5,19,15,31,60,0.517,6,17,0.353,25,43,0.581,0.567,11,14,0.786,7,23,30,13,14,4,13,21,0,0
2,Abilene Christian,2024-11-12,NaN,McMurry,REG (Non-Conf),1,101,55,41,74,0.554,13,30,0.433,28,44,0.636,0.642,6,8,0.750,10,32,42,23,14,4,9,14,16,55,0.291,5,27,0.185,11,28,0.393,0.336,18,23,0.783,7,23,30,7,5,1,19,12,0,0
3,Abilene Christian,2024-11-16,NaN,Texas State,REG (Non-Conf),1,72,60,24,49,0.490,8,13,0.615,16,36,0.444,0.571,16,22,0.727,9,23,32,14,11,4,19,32,15,37,0.405,3,8,0.375,12,29,0.414,0.446,27,38,0.711,3,18,21,6,8,3,15,20,0,0
4,Abilene Christian,2024-11-20,@,Kennesaw State,REG (Non-Conf),-1,78,84,27,59,0.458,5,15,0.333,22,44,0.500,0.500,19,30,0.633,6,14,20,16,13,2,7,25,22,41,0.537,7,16,0.438,15,25,0.600,0.622,33,41,0.805,7,23,30,13,3,3,19,20,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11805,Youngstown State,2025-02-23,NaN,Green Bay,REG (Conf),1,81,77,27,55,0.491,6,18,0.333,21,37,0.568,0.545,21,31,0.677,9,25,34,10,5,5,16,19,27,59,0.458,9,29,0.310,18,30,0.600,0.534,14,21,0.667,10,21,31,19,9,1,12,23,0,0
11806,Youngstown State,2025-03-01,@,Northern Kentucky,REG (Conf),-1,79,88,26,57,0.456,14,29,0.483,12,28,0.429,0.579,13,17,0.765,7,16,23,18,5,1,10,18,30,58,0.517,9,24,0.375,21,34,0.618,0.595,19,23,0.826,8,24,32,15,3,4,8,16,0,0
11807,Youngstown State,2025-03-06,NaN,Purdue Fort Wayne,CTOURN,1,72,67,21,58,0.362,5,28,0.179,16,30,0.533,0.405,25,31,0.806,10,34,44,10,6,5,17,20,23,62,0.371,8,27,0.296,15,35,0.429,0.435,13,20,0.650,6,23,29,11,9,3,13,23,0,0
11808,Youngstown State,2025-03-10,N,Cleveland State,CTOURN,1,56,54,18,50,0.360,8,25,0.320,10,25,0.400,0.440,12,23,0.522,12,20,32,11,10,4,11,12,19,46,0.413,8,12,0.667,11,34,0.324,0.500,8,12,0.667,6,20,26,12,7,5,15,19,0,0
11809,Youngstown State,2025-03-11,N,Robert Morris,CTOURN,-1,78,89,27,63,0.429,11,29,0.379,16,34,0.471,0.516,13,17,0.765,7,25,32,17,5,7,5,21,29,62,0.468,11,22,0.500,18,40,0.450,0.556,20,28,0.714,14,26,40,23,2,4,8,16,0,0

Reformat location column for home/neutral/away

In [13]:
df['Location'] = df['Location'].map({np.NaN: 1, 'N': 0, '@': -1}).astype('int8')

df['Location']

0        1
1        1
2        1
3        1
4       -1
        ..
11805    1
11806   -1
11807    1
11808    0
11809    0
Name: Location, Length: 11810, dtype: int8

Other general fixes

In [14]:
# fix dates
df['Date'] = pd.to_datetime(df['Date'])

# specify before and after NCAA tournament
df.insert(df.columns.get_loc('Date') + 1, 'NCAA Tournament', (df['Date'] > cutoff_dates[SEASON]).astype(int))

# fix column types
df.loc[:, df.columns.str.contains('Team ', regex=False)] = df.loc[:, df.columns.str.contains('Team ', regex=False)].astype('float64')
df.loc[:, df.columns.str.contains('Opponent ', regex=False)] = df.loc[:, df.columns.str.contains('Opponent ', regex=False)].astype('float64')

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,Abilene Christian,2024-11-04,0,1,Howard Payne,REG (Non-Conf),1,107,74,42,73,0.575,3,13,0.231,39,60,0.650,0.596,20,33,0.606,24,49,73,16,9,4,32,21,24,80,0.300,7,41,0.171,17,39,0.436,0.344,19,25,0.760,9,8,17,8,20,0,14,24,0,0
1,Abilene Christian,2024-11-09,0,1,Middle Tennessee,REG (Non-Conf),-1,56,79,19,49,0.388,2,14,0.143,17,35,0.486,0.408,16,25,0.640,9,20,29,9,8,5,19,15,31,60,0.517,6,17,0.353,25,43,0.581,0.567,11,14,0.786,7,23,30,13,14,4,13,21,0,0
2,Abilene Christian,2024-11-12,0,1,McMurry,REG (Non-Conf),1,101,55,41,74,0.554,13,30,0.433,28,44,0.636,0.642,6,8,0.750,10,32,42,23,14,4,9,14,16,55,0.291,5,27,0.185,11,28,0.393,0.336,18,23,0.783,7,23,30,7,5,1,19,12,0,0
3,Abilene Christian,2024-11-16,0,1,Texas State,REG (Non-Conf),1,72,60,24,49,0.490,8,13,0.615,16,36,0.444,0.571,16,22,0.727,9,23,32,14,11,4,19,32,15,37,0.405,3,8,0.375,12,29,0.414,0.446,27,38,0.711,3,18,21,6,8,3,15,20,0,0
4,Abilene Christian,2024-11-20,0,-1,Kennesaw State,REG (Non-Conf),-1,78,84,27,59,0.458,5,15,0.333,22,44,0.500,0.500,19,30,0.633,6,14,20,16,13,2,7,25,22,41,0.537,7,16,0.438,15,25,0.600,0.622,33,41,0.805,7,23,30,13,3,3,19,20,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11805,Youngstown State,2025-02-23,0,1,Green Bay,REG (Conf),1,81,77,27,55,0.491,6,18,0.333,21,37,0.568,0.545,21,31,0.677,9,25,34,10,5,5,16,19,27,59,0.458,9,29,0.310,18,30,0.600,0.534,14,21,0.667,10,21,31,19,9,1,12,23,0,0
11806,Youngstown State,2025-03-01,0,-1,Northern Kentucky,REG (Conf),-1,79,88,26,57,0.456,14,29,0.483,12,28,0.429,0.579,13,17,0.765,7,16,23,18,5,1,10,18,30,58,0.517,9,24,0.375,21,34,0.618,0.595,19,23,0.826,8,24,32,15,3,4,8,16,0,0
11807,Youngstown State,2025-03-06,0,1,Purdue Fort Wayne,CTOURN,1,72,67,21,58,0.362,5,28,0.179,16,30,0.533,0.405,25,31,0.806,10,34,44,10,6,5,17,20,23,62,0.371,8,27,0.296,15,35,0.429,0.435,13,20,0.650,6,23,29,11,9,3,13,23,0,0
11808,Youngstown State,2025-03-10,0,0,Cleveland State,CTOURN,1,56,54,18,50,0.360,8,25,0.320,10,25,0.400,0.440,12,23,0.522,12,20,32,11,10,4,11,12,19,46,0.413,8,12,0.667,11,34,0.324,0.500,8,12,0.667,6,20,26,12,7,5,15,19,0,0
11809,Youngstown State,2025-03-11,0,0,Robert Morris,CTOURN,-1,78,89,27,63,0.429,11,29,0.379,16,34,0.471,0.516,13,17,0.765,7,25,32,17,5,7,5,21,29,62,0.468,11,22,0.500,18,40,0.450,0.556,20,28,0.714,14,26,40,23,2,4,8,16,0,0

Remap opponent names because the opponents sometimes have a different naming convention than the team names

In [15]:
# create new dataframe from opposite perspective    team <--> opponent
df_switch = df.copy()

df_switch.columns = df_switch.columns.str.replace(
    'Team', '_TEMP_', regex=False
).str.replace(
    'Opponent', 'Team', regex=False
).str.replace(
    '_TEMP_', 'Opponent', regex=False
)

df_switch[['Location', 'Result']] *= -1

# get fixed opponent names
df['Opponent'] = pd.merge(
    df, df_switch,
    how='left',
    on=(
        ['Date', 'Location', 'Result'] +
        list(df.loc[:, df.columns.str.contains('Team ')].columns) +
        list(df.loc[:, df.columns.str.contains('Opponent ')].columns)
    )
)['Opponent_y']

# Remove matchups that are not division 1
df = df.loc[df['Opponent'].notna(), :].reset_index(drop=True)

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,Abilene Christian,2024-11-09,0,1,Middle Tennessee,REG (Non-Conf),-1,56,79,19,49,0.388,2,14,0.143,17,35,0.486,0.408,16,25,0.640,9,20,29,9,8,5,19,15,31,60,0.517,6,17,0.353,25,43,0.581,0.567,11,14,0.786,7,23,30,13,14,4,13,21,0,0
1,Abilene Christian,2024-11-16,0,1,Texas State,REG (Non-Conf),1,72,60,24,49,0.490,8,13,0.615,16,36,0.444,0.571,16,22,0.727,9,23,32,14,11,4,19,32,15,37,0.405,3,8,0.375,12,29,0.414,0.446,27,38,0.711,3,18,21,6,8,3,15,20,0,0
2,Abilene Christian,2024-11-20,0,-1,Kennesaw State,REG (Non-Conf),-1,78,84,27,59,0.458,5,15,0.333,22,44,0.500,0.500,19,30,0.633,6,14,20,16,13,2,7,25,22,41,0.537,7,16,0.438,15,25,0.600,0.622,33,41,0.805,7,23,30,13,3,3,19,20,0,0
3,Abilene Christian,2024-11-25,0,0,Southern Mississippi,REG (Non-Conf),1,82,74,24,47,0.511,3,9,0.333,21,38,0.553,0.543,31,40,0.775,10,21,31,12,8,2,12,24,23,49,0.469,9,16,0.563,14,33,0.424,0.561,19,32,0.594,8,15,23,14,4,2,12,26,0,0
4,Abilene Christian,2024-11-26,0,-1,Montana State,REG (Non-Conf),-1,59,85,24,58,0.414,3,18,0.167,21,40,0.525,0.440,8,12,0.667,6,15,21,11,6,2,7,12,29,50,0.580,17,26,0.654,12,24,0.500,0.750,10,13,0.769,5,26,31,20,4,4,13,15,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11277,Youngstown State,2025-02-23,0,1,Green Bay,REG (Conf),1,81,77,27,55,0.491,6,18,0.333,21,37,0.568,0.545,21,31,0.677,9,25,34,10,5,5,16,19,27,59,0.458,9,29,0.310,18,30,0.600,0.534,14,21,0.667,10,21,31,19,9,1,12,23,0,0
11278,Youngstown State,2025-03-01,0,-1,Northern Kentucky,REG (Conf),-1,79,88,26,57,0.456,14,29,0.483,12,28,0.429,0.579,13,17,0.765,7,16,23,18,5,1,10,18,30,58,0.517,9,24,0.375,21,34,0.618,0.595,19,23,0.826,8,24,32,15,3,4,8,16,0,0
11279,Youngstown State,2025-03-06,0,1,Purdue Fort Wayne,CTOURN,1,72,67,21,58,0.362,5,28,0.179,16,30,0.533,0.405,25,31,0.806,10,34,44,10,6,5,17,20,23,62,0.371,8,27,0.296,15,35,0.429,0.435,13,20,0.650,6,23,29,11,9,3,13,23,0,0
11280,Youngstown State,2025-03-10,0,0,Cleveland State,CTOURN,1,56,54,18,50,0.360,8,25,0.320,10,25,0.400,0.440,12,23,0.522,12,20,32,11,10,4,11,12,19,46,0.413,8,12,0.667,11,34,0.324,0.500,8,12,0.667,6,20,26,12,7,5,15,19,0,0
11281,Youngstown State,2025-03-11,0,0,Robert Morris,CTOURN,-1,78,89,27,63,0.429,11,29,0.379,16,34,0.471,0.516,13,17,0.765,7,25,32,17,5,7,5,21,29,62,0.468,11,22,0.500,18,40,0.450,0.556,20,28,0.714,14,26,40,23,2,4,8,16,0,0

Set up adjusted Score Differential

In [16]:
blowout_threshold = 18  # adjusted score differential will only account up to this score difference

df['Score Differential'] = df['Team Score'] - df['Opponent Score']

df['Adjusted Score Differential'] = df['Score Differential'].abs()

df.loc[df['Adjusted Score Differential'] > blowout_threshold, 'Adjusted Score Differential'] = blowout_threshold

df['Adjusted Score Differential'] = df['Adjusted Score Differential']**(np.log(1.5)/np.log(blowout_threshold))

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential
0,Abilene Christian,2024-11-09,0,1,Middle Tennessee,REG (Non-Conf),-1,56,79,19,49,0.388,2,14,0.143,17,35,0.486,0.408,16,25,0.640,9,20,29,9,8,5,19,15,31,60,0.517,6,17,0.353,25,43,0.581,0.567,11,14,0.786,7,23,30,13,14,4,13,21,0,0,-23,1.500000
1,Abilene Christian,2024-11-16,0,1,Texas State,REG (Non-Conf),1,72,60,24,49,0.490,8,13,0.615,16,36,0.444,0.571,16,22,0.727,9,23,32,14,11,4,19,32,15,37,0.405,3,8,0.375,12,29,0.414,0.446,27,38,0.711,3,18,21,6,8,3,15,20,0,0,12,1.417062
2,Abilene Christian,2024-11-20,0,-1,Kennesaw State,REG (Non-Conf),-1,78,84,27,59,0.458,5,15,0.333,22,44,0.500,0.500,19,30,0.633,6,14,20,16,13,2,7,25,22,41,0.537,7,16,0.438,15,25,0.600,0.622,33,41,0.805,7,23,30,13,3,3,19,20,0,0,-6,1.285760
3,Abilene Christian,2024-11-25,0,0,Southern Mississippi,REG (Non-Conf),1,82,74,24,47,0.511,3,9,0.333,21,38,0.553,0.543,31,40,0.775,10,21,31,12,8,2,12,24,23,49,0.469,9,16,0.563,14,33,0.424,0.561,19,32,0.594,8,15,23,14,4,2,12,26,0,0,8,1.338710
4,Abilene Christian,2024-11-26,0,-1,Montana State,REG (Non-Conf),-1,59,85,24,58,0.414,3,18,0.167,21,40,0.525,0.440,8,12,0.667,6,15,21,11,6,2,7,12,29,50,0.580,17,26,0.654,12,24,0.500,0.750,10,13,0.769,5,26,31,20,4,4,13,15,0,0,-26,1.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11277,Youngstown State,2025-02-23,0,1,Green Bay,REG (Conf),1,81,77,27,55,0.491,6,18,0.333,21,37,0.568,0.545,21,31,0.677,9,25,34,10,5,5,16,19,27,59,0.458,9,29,0.310,18,30,0.600,0.534,14,21,0.667,10,21,31,19,9,1,12,23,0,0,4,1.214668
11278,Youngstown State,2025-03-01,0,-1,Northern Kentucky,REG (Conf),-1,79,88,26,57,0.456,14,29,0.483,12,28,0.429,0.579,13,17,0.765,7,16,23,18,5,1,10,18,30,58,0.517,9,24,0.375,21,34,0.618,0.595,19,23,0.826,8,24,32,15,3,4,8,16,0,0,-9,1.361013
11279,Youngstown State,2025-03-06,0,1,Purdue Fort Wayne,CTOURN,1,72,67,21,58,0.362,5,28,0.179,16,30,0.533,0.405,25,31,0.806,10,34,44,10,6,5,17,20,23,62,0.371,8,27,0.296,15,35,0.429,0.435,13,20,0.650,6,23,29,11,9,3,13,23,0,0,5,1.253292
11280,Youngstown State,2025-03-10,0,0,Cleveland State,CTOURN,1,56,54,18,50,0.360,8,25,0.320,10,25,0.400,0.440,12,23,0.522,12,20,32,11,10,4,11,12,19,46,0.413,8,12,0.667,11,34,0.324,0.500,8,12,0.667,6,20,26,12,7,5,15,19,0,0,2,1.102120
11281,Youngstown State,2025-03-11,0,0,Robert Morris,CTOURN,-1,78,89,27,63,0.429,11,29,0.379,16,34,0.471,0.516,13,17,0.765,7,25,32,17,5,7,5,21,29,62,0.468,11,22,0.500,18,40,0.450,0.556,20,28,0.714,14,26,40,23,2,4,8,16,0,0,-11,1.399871

Get per possession stats

In [17]:
Y = 0.44

df['Possessions'] = (
    df['Team FGA'] - df['Team ORB'] + df['Team TOV'] + Y*df['Team FTA'] +
    df['Opponent FGA'] - df['Opponent ORB'] + df['Opponent TOV'] + Y*df['Opponent FTA']
)/2

df['Team PPP'] = df['Team Score'] / df['Possessions']
df['Opponent PPP'] = df['Opponent Score'] / df['Possessions']
df['Tempo'] = 40*df['Possessions'] / (40 + 5*df['Overtimes Amount'])

# some games are missing stats due to delay/finished recently
df = df.loc[df['Team PPP'].notna(), :].reset_index(drop=True)

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo
0,Abilene Christian,2024-11-09,0,1,Middle Tennessee,REG (Non-Conf),-1,56,79,19,49,0.388,2,14,0.143,17,35,0.486,0.408,16,25,0.640,9,20,29,9,8,5,19,15,31,60,0.517,6,17,0.353,25,43,0.581,0.567,11,14,0.786,7,23,30,13,14,4,13,21,0,0,-23,1.500000,71.08,0.787845,1.111424,71.08
1,Abilene Christian,2024-11-16,0,1,Texas State,REG (Non-Conf),1,72,60,24,49,0.490,8,13,0.615,16,36,0.444,0.571,16,22,0.727,9,23,32,14,11,4,19,32,15,37,0.405,3,8,0.375,12,29,0.414,0.446,27,38,0.711,3,18,21,6,8,3,15,20,0,0,12,1.417062,67.20,1.071429,0.892857,67.20
2,Abilene Christian,2024-11-20,0,-1,Kennesaw State,REG (Non-Conf),-1,78,84,27,59,0.458,5,15,0.333,22,44,0.500,0.500,19,30,0.633,6,14,20,16,13,2,7,25,22,41,0.537,7,16,0.438,15,25,0.600,0.622,33,41,0.805,7,23,30,13,3,3,19,20,0,0,-6,1.285760,72.12,1.081531,1.164725,72.12
3,Abilene Christian,2024-11-25,0,0,Southern Mississippi,REG (Non-Conf),1,82,74,24,47,0.511,3,9,0.333,21,38,0.553,0.543,31,40,0.775,10,21,31,12,8,2,12,24,23,49,0.469,9,16,0.563,14,33,0.424,0.561,19,32,0.594,8,15,23,14,4,2,12,26,0,0,8,1.338710,66.84,1.226810,1.107121,66.84
4,Abilene Christian,2024-11-26,0,-1,Montana State,REG (Non-Conf),-1,59,85,24,58,0.414,3,18,0.167,21,40,0.525,0.440,8,12,0.667,6,15,21,11,6,2,7,12,29,50,0.580,17,26,0.654,12,24,0.500,0.750,10,13,0.769,5,26,31,20,4,4,13,15,0,0,-26,1.500000,64.00,0.921875,1.328125,64.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11277,Youngstown State,2025-02-23,0,1,Green Bay,REG (Conf),1,81,77,27,55,0.491,6,18,0.333,21,37,0.568,0.545,21,31,0.677,9,25,34,10,5,5,16,19,27,59,0.458,9,29,0.310,18,30,0.600,0.534,14,21,0.667,10,21,31,19,9,1,12,23,0,0,4,1.214668,72.94,1.110502,1.055662,72.94
11278,Youngstown State,2025-03-01,0,-1,Northern Kentucky,REG (Conf),-1,79,88,26,57,0.456,14,29,0.483,12,28,0.429,0.579,13,17,0.765,7,16,23,18,5,1,10,18,30,58,0.517,9,24,0.375,21,34,0.618,0.595,19,23,0.826,8,24,32,15,3,4,8,16,0,0,-9,1.361013,67.80,1.165192,1.297935,67.80
11279,Youngstown State,2025-03-06,0,1,Purdue Fort Wayne,CTOURN,1,72,67,21,58,0.362,5,28,0.179,16,30,0.533,0.405,25,31,0.806,10,34,44,10,6,5,17,20,23,62,0.371,8,27,0.296,15,35,0.429,0.435,13,20,0.650,6,23,29,11,9,3,13,23,0,0,5,1.253292,78.22,0.920481,0.856558,78.22
11280,Youngstown State,2025-03-10,0,0,Cleveland State,CTOURN,1,56,54,18,50,0.360,8,25,0.320,10,25,0.400,0.440,12,23,0.522,12,20,32,11,10,4,11,12,19,46,0.413,8,12,0.667,11,34,0.324,0.500,8,12,0.667,6,20,26,12,7,5,15,19,0,0,2,1.102120,59.70,0.938023,0.904523,59.70
11281,Youngstown State,2025-03-11,0,0,Robert Morris,CTOURN,-1,78,89,27,63,0.429,11,29,0.379,16,34,0.471,0.516,13,17,0.765,7,25,32,17,5,7,5,21,29,62,0.468,11,22,0.500,18,40,0.450,0.556,20,28,0.714,14,26,40,23,2,4,8,16,0,0,-11,1.399871,68.40,1.140351,1.301170,68.40

### Save

In [18]:
df.to_parquet(f'../data/unprocessed/mens_sports_reference/full_season_sports_reference_{SEASON}.parquet')

'Done'

'Done'