# Men's Scrape Schedule

Get schedule of each team in a given year. This file needs to be ran for every relevant year (starting in 2012).

### Web Scraping

Fair warning that this program unfortunately takes a very long time to run due to web scraping limits set by Sports Reference

In [1]:
SEASON = 2012

In [2]:
import pandas as pd
import numpy as np
import time

pd.set_option('display.max_columns', 100)

df_active_teams = pd.read_html('https://www.sports-reference.com/cbb/schools/index.html')[0]
time.sleep(2)

df_active_teams = df_active_teams.loc[~df_active_teams['School'].isin([np.NaN, 'School']), :].reset_index(drop=True)

df_active_teams['From'] = pd.to_numeric(df_active_teams['From'], errors='coerce')
df_active_teams['To'] = pd.to_numeric(df_active_teams['To'], errors='coerce')

df_active_teams = df_active_teams.loc[(df_active_teams['To'] >= SEASON) & (df_active_teams['From'] <= SEASON), :].reset_index(drop=True)

if SEASON == 2021:  # if 2021, remove ivy league because they cancelled their season in 2021
    df_active_teams = df_active_teams.loc[
        ~df_active_teams['School'].isin(['Princeton', 'Harvard', 'Yale', 'Pennsylvania', 'Brown', 'Columbia', 'Cornell', 'Dartmouth']), 
        :
    ].reset_index(drop=True)

df_active_teams

,Rk,School,"City, State",From,To,Yrs,G,W,L,W-L%,SRS,SOS,AP,CREG,CTRN,NCAA,FF,NC
0,1,Abilene Christian,"Abilene, Texas",1971,2025,15,454,242,212,.533,-7.57,-5.32,0,0,2,2,0,0
1,2,Air Force,"USAF Academy, Colorado",1958,2025,68,1874,797,1077,.425,-2.87,1.37,0,1,0,4,0,0
2,3,Akron,"Akron, Ohio",1902,2025,74,1749,1052,697,.601,0.07,-1.61,0,10,6,6,0,0
3,4,Alabama,"Tuscaloosa, Alabama",1913,2025,112,2927,1818,1108,.621,8.18,5.07,18,10,9,25,1,0
4,5,Alabama A&M,"Normal, Alabama",2000,2025,26,754,287,467,.381,-16.73,-11.01,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,489,Wright State,"Dayton, Ohio",1988,2025,38,1161,646,515,.556,-1.42,-2.59,0,4,4,4,0,0
343,490,Wyoming,"Laramie, Wyoming",1905,2025,120,2910,1622,1288,.557,2.69,2.76,4,21,3,16,1,1
344,491,Xavier,"Cincinnati, Ohio",1920,2025,104,2728,1632,1096,.598,6.20,4.05,13,18,9,29,0,0
345,492,Yale,"New Haven, Connecticut",1896,2025,129,3112,1586,1524,.510,-5.82,-4.43,1,17,3,7,0,0
346,493,Youngstown State,"Youngstown, Ohio",1948,2025,45,1325,551,774,.416,-7.87,-3.55,0,1,0,0,0,0

In [3]:
from datetime import datetime

cutoff_dates = {
    2012: datetime(2012, 3, 14),
    2013: datetime(2013, 3, 20),
    2014: datetime(2014, 3, 19),
    2015: datetime(2015, 3, 18),
    2016: datetime(2016, 3, 16),
    2017: datetime(2017, 3, 15),
    2018: datetime(2018, 3, 14),
    2019: datetime(2019, 3, 20),
    2021: datetime(2021, 3, 18),
    2022: datetime(2022, 3, 16),
    2023: datetime(2023, 3, 15),
    2024: datetime(2024, 3, 20),
    2025: datetime(2025, 3, 19),
}

cutoff_dates[SEASON]

datetime.datetime(2012, 3, 14, 0, 0)

Get school names used in Sports Reference URL

In [4]:
df_active_teams['URL School'] = df_active_teams['School']

# hard code some schools that cause issues
df_active_teams.loc[df_active_teams['School'] == 'Bowling Green', 'URL School'] = 'Bowling Green State'
df_active_teams.loc[df_active_teams['School'] == 'BYU', 'URL School'] = 'Brigham Young'
df_active_teams.loc[df_active_teams['School'] == 'Louisiana', 'URL School'] = 'Louisiana Lafayette'
df_active_teams.loc[df_active_teams['School'] == 'LSU', 'URL School'] = 'Louisiana State'
df_active_teams.loc[df_active_teams['School'] == 'Ole Miss', 'URL School'] = 'Mississippi'
df_active_teams.loc[df_active_teams['School'] == 'Pitt', 'URL School'] = 'Pittsburgh'
df_active_teams.loc[df_active_teams['School'] == 'SMU', 'URL School'] = 'Southern Methodist'
df_active_teams.loc[df_active_teams['School'] == 'UAB', 'URL School'] = 'Alabama Birmingham'
df_active_teams.loc[df_active_teams['School'] == 'UCF', 'URL School'] = 'Central Florida'
df_active_teams.loc[df_active_teams['School'] == 'USC', 'URL School'] = 'Southern California'
df_active_teams.loc[df_active_teams['School'] == 'UTEP', 'URL School'] = 'Texas El Paso'
df_active_teams.loc[df_active_teams['School'] == 'UTSA', 'URL School'] = 'Texas San Antonio'
df_active_teams.loc[df_active_teams['School'] == 'Sam Houston', 'URL School'] = 'Sam Houston State'
df_active_teams.loc[df_active_teams['School'] == 'Houston Christian', 'URL School'] = 'Houston Baptist'
df_active_teams.loc[df_active_teams['School'] == 'Kansas City', 'URL School'] = 'Missouri Kansas City'
df_active_teams.loc[df_active_teams['School'] == 'Little Rock', 'URL School'] = 'Arkansas Little Rock'
df_active_teams.loc[df_active_teams['School'] == 'NC State', 'URL School'] = 'North Carolina State'
df_active_teams.loc[df_active_teams['School'] == 'Omaha', 'URL School'] = 'Nebraska Omaha'
df_active_teams.loc[df_active_teams['School'] == 'Purdue Fort Wayne', 'URL School'] = 'IPFW'
df_active_teams.loc[df_active_teams['School'] == 'TCU', 'URL School'] = 'Texas Christian'
df_active_teams.loc[df_active_teams['School'] == 'Texas-Rio Grande Valley', 'URL School'] = 'Texas Pan American'
df_active_teams.loc[df_active_teams['School'] == 'The Citadel', 'URL School'] = 'Citadel'
df_active_teams.loc[df_active_teams['School'] == 'Utah Tech', 'URL School'] = 'Dixie State'
df_active_teams.loc[df_active_teams['School'] == 'St. Thomas', 'URL School'] = 'St. Thomas MN'
df_active_teams.loc[df_active_teams['School'] == 'UC Berkley', 'URL School'] = 'California'
df_active_teams.loc[df_active_teams['School'] == 'UT Arlington', 'URL School'] = 'Texas Arlington'
df_active_teams.loc[df_active_teams['School'] == 'FDU', 'URL School'] = 'Fairleigh Dickinson'
df_active_teams.loc[df_active_teams['School'] == 'Hartford Hawks', 'URL School'] = 'Hartford'
df_active_teams.loc[df_active_teams['School'] == 'Savannah State Tigers', 'URL School'] = 'Savannah State'
df_active_teams.loc[df_active_teams['School'] == 'St. Francis (NY) Terriers', 'URL School'] = 'St. Francis (NY)'
df_active_teams.loc[df_active_teams['School'] == 'East Texas A&M', 'URL School'] = 'Texas A&M Commerce'
df_active_teams.loc[df_active_teams['School'] == 'IU Indy', 'URL School'] = 'IUPUI'

df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UC\s', 'California ', regex=True)
df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UNC\s', 'North Carolina ', regex=True)

In [5]:
urls = (
    'https://www.sports-reference.com/cbb/schools/' +
    df_active_teams['URL School'].str.replace(' ', '-', regex=False).str.replace('[)(&.\']', '', regex=True).str.replace('--', '-', regex=False).str.lower() +
    '/men/' + str(SEASON) +
    '-gamelogs.html'
)

urls

0      https://www.sports-reference.com/cbb/schools/a...
1      https://www.sports-reference.com/cbb/schools/a...
2      https://www.sports-reference.com/cbb/schools/a...
3      https://www.sports-reference.com/cbb/schools/a...
4      https://www.sports-reference.com/cbb/schools/a...
                             ...
342    https://www.sports-reference.com/cbb/schools/w...
343    https://www.sports-reference.com/cbb/schools/w...
344    https://www.sports-reference.com/cbb/schools/x...
345    https://www.sports-reference.com/cbb/schools/y...
346    https://www.sports-reference.com/cbb/schools/y...
Name: URL School, Length: 347, dtype: object

In [6]:
from urllib.error import HTTPError
from tqdm.notebook import tqdm

problems = []

l = []
loop = tqdm(
    np.array((df_active_teams['School'], urls)).transpose(),  # get both school and url into loop iteration
    bar_format='{bar}{percentage:3.0f}%{r_bar}   {desc}'  # make the description not affect bar location
)
for (school, url) in loop:
  try:
    loop.set_description(f'{school}')
    # print(f'{i:03d}: {url}')
    df_team_season = pd.read_html(url)[-1]  # schools that were ranked have that info as the first table on the site
    time.sleep(2)

    df_team_season.columns = [i[1] if 'Unnamed' in i[0] else i[0] + ' ' + i[1] for i in df_team_season.columns]
    df_team_season.insert(2, 'Team', school)
    l.append(df_team_season)
  except ValueError as e:
    print(f'{url} | ValueError: {e}')
    time.sleep(2)
  except HTTPError as e:
    if e.code == 404:
      print(f'{url} | {e}')
      time.sleep(2)
    else:
      print(f'{url} | {e}')
      break

df = pd.concat(l, ignore_index=True)

df

            0%| 0/347 [00:00<?, ?it/s]

https://www.sports-reference.com/cbb/schools/abilene-christian/men/2012-gamelogs.html | HTTP Error 404: Not Found
https://www.sports-reference.com/cbb/schools/massachusetts-lowell/men/2012-gamelogs.html | HTTP Error 404: Not Found
https://www.sports-reference.com/cbb/schools/new-orleans/men/2012-gamelogs.html | HTTP Error 404: Not Found

,Rk,Gtm,Team,Date,Unnamed: 3_level_1,Opp,Type,Score Rslt,Score Tm,Score Opp,Score OT,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF
0,1,1,Air Force,2011-11-11,NaN,Army,REG (Non-Conf),W,87,71,NaN,29,52,.558,3,14,.214,26,38,.684,.587,26,36,.722,7,30,37,25,15,1,23,25,23,58,.397,6,29,.207,17,29,.586,.448,19,26,.731,6,18,24,13,11,0,24,29
1,2,2,Air Force,2011-11-12,N,VMI,REG (Non-Conf),W,75,65,NaN,28,56,.500,6,22,.273,22,34,.647,.554,13,18,.722,11,29,40,20,5,4,14,16,22,56,.393,10,30,.333,12,26,.462,.482,11,15,.733,6,19,25,11,6,4,14,21
2,3,3,Air Force,2011-11-18,NaN,Western Co.,REG (Non-Conf),W,65,37,NaN,24,55,.436,10,35,.286,14,20,.700,.527,7,12,.583,6,25,31,18,11,2,8,15,15,48,.313,5,22,.227,10,26,.385,.365,2,10,.200,8,24,32,11,1,0,18,12
3,4,4,Air Force,2011-11-23,NaN,Colorado,REG (Non-Conf),L,73,76,OT,25,62,.403,5,19,.263,20,43,.465,.444,18,25,.720,10,16,26,14,9,4,6,14,29,60,.483,10,24,.417,19,36,.528,.567,8,14,.571,12,30,42,15,1,4,17,22
4,5,5,Air Force,2011-12-03,@,Drake,REG (Non-Conf),L,60,62,NaN,16,41,.390,6,15,.400,10,26,.385,.463,22,35,.629,4,23,27,6,9,2,15,24,18,45,.400,6,20,.300,12,25,.480,.467,20,31,.645,5,25,30,8,9,4,13,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11935,29,29,Youngstown State,2012-02-25,NaN,Detroit Mercy,REG (Conf),L,74,76,NaN,23,50,.460,11,26,.423,12,24,.500,.570,17,22,.773,5,16,21,13,5,0,12,13,29,51,.569,7,16,.438,22,35,.629,.637,11,14,.786,5,19,24,18,5,4,11,24
11936,Rk,Gtm,Youngstown State,Date,NaN,Opp,Type,Rslt,Tm,Opp,OT,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF
11937,30,30,Youngstown State,2012-02-28,NaN,Green Bay,CTOURN,W,77,60,NaN,29,61,.475,10,23,.435,19,38,.500,.557,9,13,.692,10,18,28,17,13,5,6,10,24,53,.453,4,12,.333,20,41,.488,.491,8,10,.800,8,21,29,15,3,1,17,15
11938,31,31,Youngstown State,2012-03-02,N,Detroit Mercy,CTOURN,L,76,93,NaN,29,53,.547,6,20,.300,23,33,.697,.604,12,22,.545,6,15,21,16,4,2,15,20,33,55,.600,8,17,.471,25,38,.658,.673,19,25,.760,7,21,28,16,7,2,13,21
11939,NaN,NaN,Youngstown State,NaN,NaN,NaN,NaN,16-15,2095,2047,NaN,746,1729,.431,270,708,.381,476,1021,.466,.510,333,514,.648,240,647,887,405,201,164,342,503,739,1718,.430,200,555,.360,539,1163,.463,.488,369,549,.672,315,709,1024,414,166,73,397,504

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11940 entries, 0 to 11939
Data columns (total 53 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rk                  11596 non-null  object
 1   Gtm                 11596 non-null  object
 2   Team                11940 non-null  object
 3   Date                11596 non-null  object
 4   Unnamed: 3_level_1  6022 non-null   object
 5   Opp                 11596 non-null  object
 6   Type                11596 non-null  object
 7   Score Rslt          11940 non-null  object
 8   Score Tm            11940 non-null  object
 9   Score Opp           11940 non-null  object
 10  Score OT            1083 non-null   object
 11  Team FG             11940 non-null  object
 12  Team FGA            11940 non-null  object
 13  Team FG%            11940 non-null  object
 14  Team 3P             11940 non-null  object
 15  Team 3PA            11940 non-null  object
 16  Team 3P%            11940 non-null  object
 17  Team 2P             11940 non-null  object
 18  Team 2PA            11940 non-null  object
 19  Team 2P%            11940 non-null  object
 20  Team eFG%           11940 non-null  object
 21  Team FT             11940 non-null  object
 22  Team FTA            11940 non-null  object
 23  Team FT%            11938 non-null  object
 24  Team ORB            11940 non-null  object
 25  Team DRB            11940 non-null  object
 26  Team TRB            11940 non-null  object
 27  Team AST            11940 non-null  object
 28  Team STL            11940 non-null  object
 29  Team BLK            11940 non-null  object
 30  Team TOV            11940 non-null  object
 31  Team PF             11940 non-null  object
 32  Opponent FG         11939 non-null  object
 33  Opponent FGA        11939 non-null  object
 34  Opponent FG%        11939 non-null  object
 35  Opponent 3P         11939 non-null  object
 36  Opponent 3PA        11939 non-null  object
 37  Opponent 3P%        11939 non-null  object
 38  Opponent 2P         11939 non-null  object
 39  Opponent 2PA        11939 non-null  object
 40  Opponent 2P%        11939 non-null  object
 41  Opponent eFG%       11939 non-null  object
 42  Opponent FT         11939 non-null  object
 43  Opponent FTA        11939 non-null  object
 44  Opponent FT%        11937 non-null  object
 45  Opponent ORB        11939 non-null  object
 46  Opponent DRB        11939 non-null  object
 47  Opponent TRB        11939 non-null  object
 48  Opponent AST        11939 non-null  object
 49  Opponent STL        11939 non-null  object
 50  Opponent BLK        11939 non-null  object
 51  Opponent TOV        11939 non-null  object
 52  Opponent PF         11939 non-null  object
dtypes: object(53)
memory usage: 4.8+ MB

### Data Setup

In [8]:
temp = df.copy()

In [9]:
df = temp.copy()

Fix column names and drop useless columns

In [10]:
df.columns = (
    ['G', 'Gtm', 'Team', 'Date', 'Location', 'Opponent', 'Type', 'Result', 'Team Score', 'Opponent Score', 'OT'] +
    [c for c in df.columns[11:]]
)

# use "Team" as prefix instead of "School"
df.columns = df.columns.str.replace('School', 'Team', regex=False)

# drop columns that are completely null
df = df[[c for c in df.columns if df.loc[:, c].notna().any()]].copy()

# drop columns without a name
df = df.loc[:, ~df.columns.str.contains('^Unnamed', regex=True)]

# drop rows that aren't games
df = df.loc[(df['Date'].notna()) & (df['Result'].isin(['W', 'L'])), :].reset_index(drop=True)

# drop useless columns
df.drop(columns=['G', 'Gtm'], inplace=True)

df

,Team,Date,Location,Opponent,Type,Result,Team Score,Opponent Score,OT,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF
0,Air Force,2011-11-11,NaN,Army,REG (Non-Conf),W,87,71,NaN,29,52,.558,3,14,.214,26,38,.684,.587,26,36,.722,7,30,37,25,15,1,23,25,23,58,.397,6,29,.207,17,29,.586,.448,19,26,.731,6,18,24,13,11,0,24,29
1,Air Force,2011-11-12,N,VMI,REG (Non-Conf),W,75,65,NaN,28,56,.500,6,22,.273,22,34,.647,.554,13,18,.722,11,29,40,20,5,4,14,16,22,56,.393,10,30,.333,12,26,.462,.482,11,15,.733,6,19,25,11,6,4,14,21
2,Air Force,2011-11-18,NaN,Western Co.,REG (Non-Conf),W,65,37,NaN,24,55,.436,10,35,.286,14,20,.700,.527,7,12,.583,6,25,31,18,11,2,8,15,15,48,.313,5,22,.227,10,26,.385,.365,2,10,.200,8,24,32,11,1,0,18,12
3,Air Force,2011-11-23,NaN,Colorado,REG (Non-Conf),L,73,76,OT,25,62,.403,5,19,.263,20,43,.465,.444,18,25,.720,10,16,26,14,9,4,6,14,29,60,.483,10,24,.417,19,36,.528,.567,8,14,.571,12,30,42,15,1,4,17,22
4,Air Force,2011-12-03,@,Drake,REG (Non-Conf),L,60,62,NaN,16,41,.390,6,15,.400,10,26,.385,.463,22,35,.629,4,23,27,6,9,2,15,24,18,45,.400,6,20,.300,12,25,.480,.467,20,31,.645,5,25,30,8,9,4,13,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11140,Youngstown State,2012-02-18,@,Austin Peay,REG (Non-Conf),L,68,71,NaN,24,56,.429,13,29,.448,11,27,.407,.545,7,10,.700,9,19,28,13,6,7,14,18,22,66,.333,6,22,.273,16,44,.364,.379,21,27,.778,24,23,47,10,5,1,13,16
11141,Youngstown State,2012-02-23,NaN,Wright State,REG (Conf),W,61,54,NaN,22,49,.449,6,19,.316,16,30,.533,.510,11,16,.688,5,29,34,14,5,7,14,15,18,56,.321,8,23,.348,10,33,.303,.393,10,19,.526,12,24,36,11,11,1,15,16
11142,Youngstown State,2012-02-25,NaN,Detroit Mercy,REG (Conf),L,74,76,NaN,23,50,.460,11,26,.423,12,24,.500,.570,17,22,.773,5,16,21,13,5,0,12,13,29,51,.569,7,16,.438,22,35,.629,.637,11,14,.786,5,19,24,18,5,4,11,24
11143,Youngstown State,2012-02-28,NaN,Green Bay,CTOURN,W,77,60,NaN,29,61,.475,10,23,.435,19,38,.500,.557,9,13,.692,10,18,28,17,13,5,6,10,24,53,.453,4,12,.333,20,41,.488,.491,8,10,.800,8,21,29,15,3,1,17,15
11144,Youngstown State,2012-03-02,N,Detroit Mercy,CTOURN,L,76,93,NaN,29,53,.547,6,20,.300,23,33,.697,.604,12,22,.545,6,15,21,16,4,2,15,20,33,55,.600,8,17,.471,25,38,.658,.673,19,25,.760,7,21,28,16,7,2,13,21

Fix data types

In [11]:
for col in df.columns:
    for dtype in (int, float):
        try:
            df[col] = df[col].astype(dtype)
            break
        except ValueError:
            pass

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11145 entries, 0 to 11144
Data columns (total 51 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Team            11145 non-null  object
 1   Date            11145 non-null  object
 2   Location        6022 non-null   object
 3   Opponent        11145 non-null  object
 4   Type            11145 non-null  object
 5   Result          11145 non-null  object
 6   Team Score      11145 non-null  int32
 7   Opponent Score  11145 non-null  int32
 8   OT              632 non-null    object
 9   Team FG         11145 non-null  int32
 10  Team FGA        11145 non-null  int32
 11  Team FG%        11145 non-null  float64
 12  Team 3P         11145 non-null  int32
 13  Team 3PA        11145 non-null  int32
 14  Team 3P%        11145 non-null  float64
 15  Team 2P         11145 non-null  int32
 16  Team 2PA        11145 non-null  int32
 17  Team 2P%        11145 non-null  float64
 18  Team eFG%       11145 non-null  float64
 19  Team FT         11145 non-null  int32
 20  Team FTA        11145 non-null  int32
 21  Team FT%        11143 non-null  float64
 22  Team ORB        11145 non-null  int32
 23  Team DRB        11145 non-null  int32
 24  Team TRB        11145 non-null  int32
 25  Team AST        11145 non-null  int32
 26  Team STL        11145 non-null  int32
 27  Team BLK        11145 non-null  int32
 28  Team TOV        11145 non-null  int32
 29  Team PF         11145 non-null  int32
 30  Opponent FG     11144 non-null  float64
 31  Opponent FGA    11144 non-null  float64
 32  Opponent FG%    11144 non-null  float64
 33  Opponent 3P     11144 non-null  float64
 34  Opponent 3PA    11144 non-null  float64
 35  Opponent 3P%    11144 non-null  float64
 36  Opponent 2P     11144 non-null  float64
 37  Opponent 2PA    11144 non-null  float64
 38  Opponent 2P%    11144 non-null  float64
 39  Opponent eFG%   11144 non-null  float64
 40  Opponent FT     11144 non-null  float64
 41  Opponent FTA    11144 non-null  float64
 42  Opponent FT%    11142 non-null  float64
 43  Opponent ORB    11144 non-null  float64
 44  Opponent DRB    11144 non-null  float64
 45  Opponent TRB    11144 non-null  float64
 46  Opponent AST    11144 non-null  float64
 47  Opponent STL    11144 non-null  float64
 48  Opponent BLK    11144 non-null  float64
 49  Opponent TOV    11144 non-null  float64
 50  Opponent PF     11144 non-null  float64
dtypes: float64(26), int32(18), object(7)
memory usage: 3.6+ MB

Get overtime information

In [12]:
# remove games that have not been played
df = df.loc[(df['Result'].notna()) & (df['Result'] != 'W/L'), :].reset_index(drop=True)

# get overtimes amount
df['Overtimes Amount'] = (
    df['OT']
    .apply(
        lambda x: 
        1 if x == 'OT' 
        else int(x[:-2]) if isinstance(x, str) and x.endswith('OT') and len(x) > 2 
        else 0
    )
)

# binary overtime flag
df['Overtime'] = df.pop('OT').notna().astype('int8')

# reformat result column
df['Result'] = df['Result'].str[:1].map({'W': 1, 'L': -1}).astype('int8')

df

,Team,Date,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,Air Force,2011-11-11,NaN,Army,REG (Non-Conf),1,87,71,29,52,0.558,3,14,0.214,26,38,0.684,0.587,26,36,0.722,7,30,37,25,15,1,23,25,23.0,58.0,0.397,6.0,29.0,0.207,17.0,29.0,0.586,0.448,19.0,26.0,0.731,6.0,18.0,24.0,13.0,11.0,0.0,24.0,29.0,0,0
1,Air Force,2011-11-12,N,VMI,REG (Non-Conf),1,75,65,28,56,0.500,6,22,0.273,22,34,0.647,0.554,13,18,0.722,11,29,40,20,5,4,14,16,22.0,56.0,0.393,10.0,30.0,0.333,12.0,26.0,0.462,0.482,11.0,15.0,0.733,6.0,19.0,25.0,11.0,6.0,4.0,14.0,21.0,0,0
2,Air Force,2011-11-18,NaN,Western Co.,REG (Non-Conf),1,65,37,24,55,0.436,10,35,0.286,14,20,0.700,0.527,7,12,0.583,6,25,31,18,11,2,8,15,15.0,48.0,0.313,5.0,22.0,0.227,10.0,26.0,0.385,0.365,2.0,10.0,0.200,8.0,24.0,32.0,11.0,1.0,0.0,18.0,12.0,0,0
3,Air Force,2011-11-23,NaN,Colorado,REG (Non-Conf),-1,73,76,25,62,0.403,5,19,0.263,20,43,0.465,0.444,18,25,0.720,10,16,26,14,9,4,6,14,29.0,60.0,0.483,10.0,24.0,0.417,19.0,36.0,0.528,0.567,8.0,14.0,0.571,12.0,30.0,42.0,15.0,1.0,4.0,17.0,22.0,1,1
4,Air Force,2011-12-03,@,Drake,REG (Non-Conf),-1,60,62,16,41,0.390,6,15,0.400,10,26,0.385,0.463,22,35,0.629,4,23,27,6,9,2,15,24,18.0,45.0,0.400,6.0,20.0,0.300,12.0,25.0,0.480,0.467,20.0,31.0,0.645,5.0,25.0,30.0,8.0,9.0,4.0,13.0,26.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11140,Youngstown State,2012-02-18,@,Austin Peay,REG (Non-Conf),-1,68,71,24,56,0.429,13,29,0.448,11,27,0.407,0.545,7,10,0.700,9,19,28,13,6,7,14,18,22.0,66.0,0.333,6.0,22.0,0.273,16.0,44.0,0.364,0.379,21.0,27.0,0.778,24.0,23.0,47.0,10.0,5.0,1.0,13.0,16.0,0,0
11141,Youngstown State,2012-02-23,NaN,Wright State,REG (Conf),1,61,54,22,49,0.449,6,19,0.316,16,30,0.533,0.510,11,16,0.688,5,29,34,14,5,7,14,15,18.0,56.0,0.321,8.0,23.0,0.348,10.0,33.0,0.303,0.393,10.0,19.0,0.526,12.0,24.0,36.0,11.0,11.0,1.0,15.0,16.0,0,0
11142,Youngstown State,2012-02-25,NaN,Detroit Mercy,REG (Conf),-1,74,76,23,50,0.460,11,26,0.423,12,24,0.500,0.570,17,22,0.773,5,16,21,13,5,0,12,13,29.0,51.0,0.569,7.0,16.0,0.438,22.0,35.0,0.629,0.637,11.0,14.0,0.786,5.0,19.0,24.0,18.0,5.0,4.0,11.0,24.0,0,0
11143,Youngstown State,2012-02-28,NaN,Green Bay,CTOURN,1,77,60,29,61,0.475,10,23,0.435,19,38,0.500,0.557,9,13,0.692,10,18,28,17,13,5,6,10,24.0,53.0,0.453,4.0,12.0,0.333,20.0,41.0,0.488,0.491,8.0,10.0,0.800,8.0,21.0,29.0,15.0,3.0,1.0,17.0,15.0,0,0
11144,Youngstown State,2012-03-02,N,Detroit Mercy,CTOURN,-1,76,93,29,53,0.547,6,20,0.300,23,33,0.697,0.604,12,22,0.545,6,15,21,16,4,2,15,20,33.0,55.0,0.600,8.0,17.0,0.471,25.0,38.0,0.658,0.673,19.0,25.0,0.760,7.0,21.0,28.0,16.0,7.0,2.0,13.0,21.0,0,0

Reformat location column for home/neutral/away

In [13]:
df['Location'] = df['Location'].map({np.NaN: 1, 'N': 0, '@': -1}).astype('int8')

df['Location']

0        1
1        0
2        1
3        1
4       -1
        ..
11140   -1
11141    1
11142    1
11143    1
11144    0
Name: Location, Length: 11145, dtype: int8

Other general fixes

In [14]:
# fix dates
df['Date'] = pd.to_datetime(df['Date'])

# specify before and after NCAA tournament
df.insert(df.columns.get_loc('Date') + 1, 'NCAA Tournament', (df['Date'] > cutoff_dates[SEASON]).astype(int))

# fix column types
df.loc[:, df.columns.str.contains('Team ', regex=False)] = df.loc[:, df.columns.str.contains('Team ', regex=False)].astype('float64')
df.loc[:, df.columns.str.contains('Opponent ', regex=False)] = df.loc[:, df.columns.str.contains('Opponent ', regex=False)].astype('float64')

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,Air Force,2011-11-11,0,1,Army,REG (Non-Conf),1,87,71,29,52,0.558,3,14,0.214,26,38,0.684,0.587,26,36,0.722,7,30,37,25,15,1,23,25,23.0,58.0,0.397,6.0,29.0,0.207,17.0,29.0,0.586,0.448,19.0,26.0,0.731,6.0,18.0,24.0,13.0,11.0,0.0,24.0,29.0,0,0
1,Air Force,2011-11-12,0,0,VMI,REG (Non-Conf),1,75,65,28,56,0.500,6,22,0.273,22,34,0.647,0.554,13,18,0.722,11,29,40,20,5,4,14,16,22.0,56.0,0.393,10.0,30.0,0.333,12.0,26.0,0.462,0.482,11.0,15.0,0.733,6.0,19.0,25.0,11.0,6.0,4.0,14.0,21.0,0,0
2,Air Force,2011-11-18,0,1,Western Co.,REG (Non-Conf),1,65,37,24,55,0.436,10,35,0.286,14,20,0.700,0.527,7,12,0.583,6,25,31,18,11,2,8,15,15.0,48.0,0.313,5.0,22.0,0.227,10.0,26.0,0.385,0.365,2.0,10.0,0.200,8.0,24.0,32.0,11.0,1.0,0.0,18.0,12.0,0,0
3,Air Force,2011-11-23,0,1,Colorado,REG (Non-Conf),-1,73,76,25,62,0.403,5,19,0.263,20,43,0.465,0.444,18,25,0.720,10,16,26,14,9,4,6,14,29.0,60.0,0.483,10.0,24.0,0.417,19.0,36.0,0.528,0.567,8.0,14.0,0.571,12.0,30.0,42.0,15.0,1.0,4.0,17.0,22.0,1,1
4,Air Force,2011-12-03,0,-1,Drake,REG (Non-Conf),-1,60,62,16,41,0.390,6,15,0.400,10,26,0.385,0.463,22,35,0.629,4,23,27,6,9,2,15,24,18.0,45.0,0.400,6.0,20.0,0.300,12.0,25.0,0.480,0.467,20.0,31.0,0.645,5.0,25.0,30.0,8.0,9.0,4.0,13.0,26.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11140,Youngstown State,2012-02-18,0,-1,Austin Peay,REG (Non-Conf),-1,68,71,24,56,0.429,13,29,0.448,11,27,0.407,0.545,7,10,0.700,9,19,28,13,6,7,14,18,22.0,66.0,0.333,6.0,22.0,0.273,16.0,44.0,0.364,0.379,21.0,27.0,0.778,24.0,23.0,47.0,10.0,5.0,1.0,13.0,16.0,0,0
11141,Youngstown State,2012-02-23,0,1,Wright State,REG (Conf),1,61,54,22,49,0.449,6,19,0.316,16,30,0.533,0.510,11,16,0.688,5,29,34,14,5,7,14,15,18.0,56.0,0.321,8.0,23.0,0.348,10.0,33.0,0.303,0.393,10.0,19.0,0.526,12.0,24.0,36.0,11.0,11.0,1.0,15.0,16.0,0,0
11142,Youngstown State,2012-02-25,0,1,Detroit Mercy,REG (Conf),-1,74,76,23,50,0.460,11,26,0.423,12,24,0.500,0.570,17,22,0.773,5,16,21,13,5,0,12,13,29.0,51.0,0.569,7.0,16.0,0.438,22.0,35.0,0.629,0.637,11.0,14.0,0.786,5.0,19.0,24.0,18.0,5.0,4.0,11.0,24.0,0,0
11143,Youngstown State,2012-02-28,0,1,Green Bay,CTOURN,1,77,60,29,61,0.475,10,23,0.435,19,38,0.500,0.557,9,13,0.692,10,18,28,17,13,5,6,10,24.0,53.0,0.453,4.0,12.0,0.333,20.0,41.0,0.488,0.491,8.0,10.0,0.800,8.0,21.0,29.0,15.0,3.0,1.0,17.0,15.0,0,0
11144,Youngstown State,2012-03-02,0,0,Detroit Mercy,CTOURN,-1,76,93,29,53,0.547,6,20,0.300,23,33,0.697,0.604,12,22,0.545,6,15,21,16,4,2,15,20,33.0,55.0,0.600,8.0,17.0,0.471,25.0,38.0,0.658,0.673,19.0,25.0,0.760,7.0,21.0,28.0,16.0,7.0,2.0,13.0,21.0,0,0

Remap opponent names because the opponents sometimes have a different naming convention than the team names

In [15]:
# create new dataframe from opposite perspective    team <--> opponent
df_switch = df.copy()

df_switch.columns = df_switch.columns.str.replace(
    'Team', '_TEMP_', regex=False
).str.replace(
    'Opponent', 'Team', regex=False
).str.replace(
    '_TEMP_', 'Opponent', regex=False
)

df_switch[['Location', 'Result']] *= -1

# get fixed opponent names
df['Opponent'] = pd.merge(
    df, df_switch,
    how='left',
    on=(
        ['Date', 'Location', 'Result'] +
        list(df.loc[:, df.columns.str.contains('Team ')].columns) +
        list(df.loc[:, df.columns.str.contains('Opponent ')].columns)
    )
)['Opponent_y']

# Remove matchups that are not division 1
df = df.loc[df['Opponent'].notna(), :].reset_index(drop=True)

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,Air Force,2011-11-11,0,1,Army,REG (Non-Conf),1,87,71,29,52,0.558,3,14,0.214,26,38,0.684,0.587,26,36,0.722,7,30,37,25,15,1,23,25,23.0,58.0,0.397,6.0,29.0,0.207,17.0,29.0,0.586,0.448,19.0,26.0,0.731,6.0,18.0,24.0,13.0,11.0,0.0,24.0,29.0,0,0
1,Air Force,2011-11-12,0,0,Virginia Military Institute,REG (Non-Conf),1,75,65,28,56,0.500,6,22,0.273,22,34,0.647,0.554,13,18,0.722,11,29,40,20,5,4,14,16,22.0,56.0,0.393,10.0,30.0,0.333,12.0,26.0,0.462,0.482,11.0,15.0,0.733,6.0,19.0,25.0,11.0,6.0,4.0,14.0,21.0,0,0
2,Air Force,2011-11-23,0,1,Colorado,REG (Non-Conf),-1,73,76,25,62,0.403,5,19,0.263,20,43,0.465,0.444,18,25,0.720,10,16,26,14,9,4,6,14,29.0,60.0,0.483,10.0,24.0,0.417,19.0,36.0,0.528,0.567,8.0,14.0,0.571,12.0,30.0,42.0,15.0,1.0,4.0,17.0,22.0,1,1
3,Air Force,2011-12-03,0,-1,Drake,REG (Non-Conf),-1,60,62,16,41,0.390,6,15,0.400,10,26,0.385,0.463,22,35,0.629,4,23,27,6,9,2,15,24,18.0,45.0,0.400,6.0,20.0,0.300,12.0,25.0,0.480,0.467,20.0,31.0,0.645,5.0,25.0,30.0,8.0,9.0,4.0,13.0,26.0,0,0
4,Air Force,2011-12-07,0,1,Wright State,REG (Non-Conf),1,55,34,19,45,0.422,9,25,0.360,10,20,0.500,0.522,8,12,0.667,3,25,28,15,7,4,12,15,9.0,46.0,0.196,2.0,19.0,0.105,7.0,27.0,0.259,0.217,14.0,18.0,0.778,9.0,22.0,31.0,4.0,5.0,5.0,16.0,14.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10761,Youngstown State,2012-02-18,0,-1,Austin Peay,REG (Non-Conf),-1,68,71,24,56,0.429,13,29,0.448,11,27,0.407,0.545,7,10,0.700,9,19,28,13,6,7,14,18,22.0,66.0,0.333,6.0,22.0,0.273,16.0,44.0,0.364,0.379,21.0,27.0,0.778,24.0,23.0,47.0,10.0,5.0,1.0,13.0,16.0,0,0
10762,Youngstown State,2012-02-23,0,1,Wright State,REG (Conf),1,61,54,22,49,0.449,6,19,0.316,16,30,0.533,0.510,11,16,0.688,5,29,34,14,5,7,14,15,18.0,56.0,0.321,8.0,23.0,0.348,10.0,33.0,0.303,0.393,10.0,19.0,0.526,12.0,24.0,36.0,11.0,11.0,1.0,15.0,16.0,0,0
10763,Youngstown State,2012-02-25,0,1,Detroit Mercy,REG (Conf),-1,74,76,23,50,0.460,11,26,0.423,12,24,0.500,0.570,17,22,0.773,5,16,21,13,5,0,12,13,29.0,51.0,0.569,7.0,16.0,0.438,22.0,35.0,0.629,0.637,11.0,14.0,0.786,5.0,19.0,24.0,18.0,5.0,4.0,11.0,24.0,0,0
10764,Youngstown State,2012-02-28,0,1,Green Bay,CTOURN,1,77,60,29,61,0.475,10,23,0.435,19,38,0.500,0.557,9,13,0.692,10,18,28,17,13,5,6,10,24.0,53.0,0.453,4.0,12.0,0.333,20.0,41.0,0.488,0.491,8.0,10.0,0.800,8.0,21.0,29.0,15.0,3.0,1.0,17.0,15.0,0,0
10765,Youngstown State,2012-03-02,0,0,Detroit Mercy,CTOURN,-1,76,93,29,53,0.547,6,20,0.300,23,33,0.697,0.604,12,22,0.545,6,15,21,16,4,2,15,20,33.0,55.0,0.600,8.0,17.0,0.471,25.0,38.0,0.658,0.673,19.0,25.0,0.760,7.0,21.0,28.0,16.0,7.0,2.0,13.0,21.0,0,0

Set up adjusted Score Differential

In [16]:
blowout_threshold = 18  # adjusted score differential will only account up to this score difference

df['Score Differential'] = df['Team Score'] - df['Opponent Score']

df['Adjusted Score Differential'] = df['Score Differential'].abs()

df.loc[df['Adjusted Score Differential'] > blowout_threshold, 'Adjusted Score Differential'] = blowout_threshold

df['Adjusted Score Differential'] = df['Adjusted Score Differential']**(np.log(1.5)/np.log(blowout_threshold))

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential
0,Air Force,2011-11-11,0,1,Army,REG (Non-Conf),1,87,71,29,52,0.558,3,14,0.214,26,38,0.684,0.587,26,36,0.722,7,30,37,25,15,1,23,25,23.0,58.0,0.397,6.0,29.0,0.207,17.0,29.0,0.586,0.448,19.0,26.0,0.731,6.0,18.0,24.0,13.0,11.0,0.0,24.0,29.0,0,0,16,1.475419
1,Air Force,2011-11-12,0,0,Virginia Military Institute,REG (Non-Conf),1,75,65,28,56,0.500,6,22,0.273,22,34,0.647,0.554,13,18,0.722,11,29,40,20,5,4,14,16,22.0,56.0,0.393,10.0,30.0,0.333,12.0,26.0,0.462,0.482,11.0,15.0,0.733,6.0,19.0,25.0,11.0,6.0,4.0,14.0,21.0,0,0,10,1.381279
2,Air Force,2011-11-23,0,1,Colorado,REG (Non-Conf),-1,73,76,25,62,0.403,5,19,0.263,20,43,0.465,0.444,18,25,0.720,10,16,26,14,9,4,6,14,29.0,60.0,0.483,10.0,24.0,0.417,19.0,36.0,0.528,0.567,8.0,14.0,0.571,12.0,30.0,42.0,15.0,1.0,4.0,17.0,22.0,1,1,-3,1.166625
3,Air Force,2011-12-03,0,-1,Drake,REG (Non-Conf),-1,60,62,16,41,0.390,6,15,0.400,10,26,0.385,0.463,22,35,0.629,4,23,27,6,9,2,15,24,18.0,45.0,0.400,6.0,20.0,0.300,12.0,25.0,0.480,0.467,20.0,31.0,0.645,5.0,25.0,30.0,8.0,9.0,4.0,13.0,26.0,0,0,-2,1.102120
4,Air Force,2011-12-07,0,1,Wright State,REG (Non-Conf),1,55,34,19,45,0.422,9,25,0.360,10,20,0.500,0.522,8,12,0.667,3,25,28,15,7,4,12,15,9.0,46.0,0.196,2.0,19.0,0.105,7.0,27.0,0.259,0.217,14.0,18.0,0.778,9.0,22.0,31.0,4.0,5.0,5.0,16.0,14.0,0,0,21,1.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10761,Youngstown State,2012-02-18,0,-1,Austin Peay,REG (Non-Conf),-1,68,71,24,56,0.429,13,29,0.448,11,27,0.407,0.545,7,10,0.700,9,19,28,13,6,7,14,18,22.0,66.0,0.333,6.0,22.0,0.273,16.0,44.0,0.364,0.379,21.0,27.0,0.778,24.0,23.0,47.0,10.0,5.0,1.0,13.0,16.0,0,0,-3,1.166625
10762,Youngstown State,2012-02-23,0,1,Wright State,REG (Conf),1,61,54,22,49,0.449,6,19,0.316,16,30,0.533,0.510,11,16,0.688,5,29,34,14,5,7,14,15,18.0,56.0,0.321,8.0,23.0,0.348,10.0,33.0,0.303,0.393,10.0,19.0,0.526,12.0,24.0,36.0,11.0,11.0,1.0,15.0,16.0,0,0,7,1.313867
10763,Youngstown State,2012-02-25,0,1,Detroit Mercy,REG (Conf),-1,74,76,23,50,0.460,11,26,0.423,12,24,0.500,0.570,17,22,0.773,5,16,21,13,5,0,12,13,29.0,51.0,0.569,7.0,16.0,0.438,22.0,35.0,0.629,0.637,11.0,14.0,0.786,5.0,19.0,24.0,18.0,5.0,4.0,11.0,24.0,0,0,-2,1.102120
10764,Youngstown State,2012-02-28,0,1,Green Bay,CTOURN,1,77,60,29,61,0.475,10,23,0.435,19,38,0.500,0.557,9,13,0.692,10,18,28,17,13,5,6,10,24.0,53.0,0.453,4.0,12.0,0.333,20.0,41.0,0.488,0.491,8.0,10.0,0.800,8.0,21.0,29.0,15.0,3.0,1.0,17.0,15.0,0,0,17,1.488021
10765,Youngstown State,2012-03-02,0,0,Detroit Mercy,CTOURN,-1,76,93,29,53,0.547,6,20,0.300,23,33,0.697,0.604,12,22,0.545,6,15,21,16,4,2,15,20,33.0,55.0,0.600,8.0,17.0,0.471,25.0,38.0,0.658,0.673,19.0,25.0,0.760,7.0,21.0,28.0,16.0,7.0,2.0,13.0,21.0,0,0,-17,1.488021

Get per possession stats

In [17]:
Y = 0.44

df['Possessions'] = (
    df['Team FGA'] - df['Team ORB'] + df['Team TOV'] + Y*df['Team FTA'] +
    df['Opponent FGA'] - df['Opponent ORB'] + df['Opponent TOV'] + Y*df['Opponent FTA']
)/2

df['Team PPP'] = df['Team Score'] / df['Possessions']
df['Opponent PPP'] = df['Opponent Score'] / df['Possessions']
df['Tempo'] = 40*df['Possessions'] / (40 + 5*df['Overtimes Amount'])

# some games are missing stats due to delay/finished recently
df = df.loc[df['Team PPP'].notna(), :].reset_index(drop=True)

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo
0,Air Force,2011-11-11,0,1,Army,REG (Non-Conf),1,87,71,29,52,0.558,3,14,0.214,26,38,0.684,0.587,26,36,0.722,7,30,37,25,15,1,23,25,23.0,58.0,0.397,6.0,29.0,0.207,17.0,29.0,0.586,0.448,19.0,26.0,0.731,6.0,18.0,24.0,13.0,11.0,0.0,24.0,29.0,0,0,16,1.475419,85.64,1.015880,0.829052,85.640000
1,Air Force,2011-11-12,0,0,Virginia Military Institute,REG (Non-Conf),1,75,65,28,56,0.500,6,22,0.273,22,34,0.647,0.554,13,18,0.722,11,29,40,20,5,4,14,16,22.0,56.0,0.393,10.0,30.0,0.333,12.0,26.0,0.462,0.482,11.0,15.0,0.733,6.0,19.0,25.0,11.0,6.0,4.0,14.0,21.0,0,0,10,1.381279,68.76,1.090750,0.945317,68.760000
2,Air Force,2011-11-23,0,1,Colorado,REG (Non-Conf),-1,73,76,25,62,0.403,5,19,0.263,20,43,0.465,0.444,18,25,0.720,10,16,26,14,9,4,6,14,29.0,60.0,0.483,10.0,24.0,0.417,19.0,36.0,0.528,0.567,8.0,14.0,0.571,12.0,30.0,42.0,15.0,1.0,4.0,17.0,22.0,1,1,-3,1.166625,70.08,1.041667,1.084475,62.293333
3,Air Force,2011-12-03,0,-1,Drake,REG (Non-Conf),-1,60,62,16,41,0.390,6,15,0.400,10,26,0.385,0.463,22,35,0.629,4,23,27,6,9,2,15,24,18.0,45.0,0.400,6.0,20.0,0.300,12.0,25.0,0.480,0.467,20.0,31.0,0.645,5.0,25.0,30.0,8.0,9.0,4.0,13.0,26.0,0,0,-2,1.102120,67.02,0.895255,0.925097,67.020000
4,Air Force,2011-12-07,0,1,Wright State,REG (Non-Conf),1,55,34,19,45,0.422,9,25,0.360,10,20,0.500,0.522,8,12,0.667,3,25,28,15,7,4,12,15,9.0,46.0,0.196,2.0,19.0,0.105,7.0,27.0,0.259,0.217,14.0,18.0,0.778,9.0,22.0,31.0,4.0,5.0,5.0,16.0,14.0,0,0,21,1.500000,60.10,0.915141,0.565724,60.100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10761,Youngstown State,2012-02-18,0,-1,Austin Peay,REG (Non-Conf),-1,68,71,24,56,0.429,13,29,0.448,11,27,0.407,0.545,7,10,0.700,9,19,28,13,6,7,14,18,22.0,66.0,0.333,6.0,22.0,0.273,16.0,44.0,0.364,0.379,21.0,27.0,0.778,24.0,23.0,47.0,10.0,5.0,1.0,13.0,16.0,0,0,-3,1.166625,66.14,1.028122,1.073480,66.140000
10762,Youngstown State,2012-02-23,0,1,Wright State,REG (Conf),1,61,54,22,49,0.449,6,19,0.316,16,30,0.533,0.510,11,16,0.688,5,29,34,14,5,7,14,15,18.0,56.0,0.321,8.0,23.0,0.348,10.0,33.0,0.303,0.393,10.0,19.0,0.526,12.0,24.0,36.0,11.0,11.0,1.0,15.0,16.0,0,0,7,1.313867,66.20,0.921450,0.815710,66.200000
10763,Youngstown State,2012-02-25,0,1,Detroit Mercy,REG (Conf),-1,74,76,23,50,0.460,11,26,0.423,12,24,0.500,0.570,17,22,0.773,5,16,21,13,5,0,12,13,29.0,51.0,0.569,7.0,16.0,0.438,22.0,35.0,0.629,0.637,11.0,14.0,0.786,5.0,19.0,24.0,18.0,5.0,4.0,11.0,24.0,0,0,-2,1.102120,64.92,1.139864,1.170672,64.920000
10764,Youngstown State,2012-02-28,0,1,Green Bay,CTOURN,1,77,60,29,61,0.475,10,23,0.435,19,38,0.500,0.557,9,13,0.692,10,18,28,17,13,5,6,10,24.0,53.0,0.453,4.0,12.0,0.333,20.0,41.0,0.488,0.491,8.0,10.0,0.800,8.0,21.0,29.0,15.0,3.0,1.0,17.0,15.0,0,0,17,1.488021,64.56,1.192689,0.929368,64.560000
10765,Youngstown State,2012-03-02,0,0,Detroit Mercy,CTOURN,-1,76,93,29,53,0.547,6,20,0.300,23,33,0.697,0.604,12,22,0.545,6,15,21,16,4,2,15,20,33.0,55.0,0.600,8.0,17.0,0.471,25.0,38.0,0.658,0.673,19.0,25.0,0.760,7.0,21.0,28.0,16.0,7.0,2.0,13.0,21.0,0,0,-17,1.488021,71.84,1.057906,1.294543,71.840000

### Save

In [18]:
df.to_parquet(f'../data/unprocessed/mens_sports_reference/full_season_sports_reference_{SEASON}.parquet')

'Done'

'Done'