# Men's Scrape Starters

Get data of each team's starters in a given year. This file needs to be ran for every relevant year (2012 to 2024).

### Web Scraping

Fair warning that this program unfortunately takes a very long time to run due to web scraping limits set by Sports Reference

In [1]:
import pandas as pd
import numpy as np
import time

season = 2025

df_active_teams = pd.read_html('https://www.sports-reference.com/cbb/schools/index.html')[0]
time.sleep(2)

df_active_teams = df_active_teams.loc[~df_active_teams['School'].isin([np.NaN, 'School']), :].reset_index(drop=True)

df_active_teams['From'] = pd.to_numeric(df_active_teams['From'], errors='coerce')
df_active_teams['To'] = pd.to_numeric(df_active_teams['To'], errors='coerce')

df_active_teams = df_active_teams.loc[(df_active_teams['To'] >= season) & (df_active_teams['From'] <= season), :].reset_index(drop=True)

if season == 2021:  # if 2021, remove ivy league because they cancelled their season in 2021
    df_active_teams = df_active_teams.loc[
        ~df_active_teams['School'].isin(['Princeton', 'Harvard', 'Yale', 'Pennsylvania', 'Brown', 'Columbia', 'Cornell', 'Dartmouth']),
        :
    ].reset_index(drop=True)

df_active_teams

,Rk,School,"City, State",From,To,Yrs,G,W,L,W-L%,SRS,SOS,AP,CREG,CTRN,NCAA,FF,NC
0,1,Abilene Christian,"Abilene, Texas",1971,2025,15,455,242,213,.532,-7.59,-5.33,0,0,2,2,0,0
1,2,Air Force,"USAF Academy, Colorado",1958,2025,68,1875,797,1078,.425,-2.87,1.37,0,1,0,4,0,0
2,3,Akron,"Akron, Ohio",1902,2025,74,1752,1055,697,.602,0.08,-1.62,0,10,6,6,0,0
3,4,Alabama,"Tuscaloosa, Alabama",1913,2025,112,2929,1819,1109,.621,8.18,5.07,18,10,9,25,1,0
4,5,Alabama A&M,"Normal, Alabama",2000,2025,26,755,287,468,.380,-16.75,-11.02,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,489,Wright State,"Dayton, Ohio",1988,2025,38,1161,646,515,.556,-1.42,-2.60,0,4,4,4,0,0
360,490,Wyoming,"Laramie, Wyoming",1905,2025,120,2911,1622,1289,.557,2.69,2.76,4,21,3,16,1,1
361,491,Xavier,"Cincinnati, Ohio",1920,2025,104,2729,1632,1097,.598,6.20,4.06,13,18,9,29,0,0
362,492,Yale,"New Haven, Connecticut",1896,2025,129,3114,1588,1524,.510,-5.82,-4.43,1,17,3,7,0,0
363,493,Youngstown State,"Youngstown, Ohio",1948,2025,45,1326,551,775,.416,-7.88,-3.56,0,1,0,0,0,0

In [2]:
from datetime import datetime

cutoff_dates = {
    2012: datetime(2012, 3, 14),
    2013: datetime(2013, 3, 20),
    2014: datetime(2014, 3, 19),
    2015: datetime(2015, 3, 18),
    2016: datetime(2016, 3, 16),
    2017: datetime(2017, 3, 15),
    2018: datetime(2018, 3, 14),
    2019: datetime(2019, 3, 20),
    2021: datetime(2021, 3, 18),
    2022: datetime(2022, 3, 16),
    2023: datetime(2023, 3, 15),
    2024: datetime(2024, 3, 20),
    2025: datetime(2025, 3, 19),
}

cutoff_dates[season]

datetime.datetime(2025, 3, 19, 0, 0)

Get school names used in Sports Reference URL

In [3]:
df_active_teams.loc[df_active_teams['School'] == 'Hartford Hawks', 'School'] = 'Hartford'
df_active_teams.loc[df_active_teams['School'] == 'Savannah State Tigers', 'School'] = 'Savannah State'
df_active_teams.loc[df_active_teams['School'] == 'St. Francis (NY) Terriers', 'School'] = 'St. Francis (NY)'

df_active_teams['URL School'] = df_active_teams['School']

# hard code some schools that cause issues
df_active_teams.loc[df_active_teams['School'] == 'Bowling Green', 'URL School'] = 'Bowling Green State'
df_active_teams.loc[df_active_teams['School'] == 'BYU', 'URL School'] = 'Brigham Young'
df_active_teams.loc[df_active_teams['School'] == 'Louisiana', 'URL School'] = 'Louisiana Lafayette'
df_active_teams.loc[df_active_teams['School'] == 'LSU', 'URL School'] = 'Louisiana State'
df_active_teams.loc[df_active_teams['School'] == 'Ole Miss', 'URL School'] = 'Mississippi'
df_active_teams.loc[df_active_teams['School'] == 'Pitt', 'URL School'] = 'Pittsburgh'
df_active_teams.loc[df_active_teams['School'] == 'SMU', 'URL School'] = 'Southern Methodist'
df_active_teams.loc[df_active_teams['School'] == 'UAB', 'URL School'] = 'Alabama Birmingham'
df_active_teams.loc[df_active_teams['School'] == 'UCF', 'URL School'] = 'Central Florida'
df_active_teams.loc[df_active_teams['School'] == 'USC', 'URL School'] = 'Southern California'
df_active_teams.loc[df_active_teams['School'] == 'UTEP', 'URL School'] = 'Texas El Paso'
df_active_teams.loc[df_active_teams['School'] == 'UTSA', 'URL School'] = 'Texas San Antonio'
df_active_teams.loc[df_active_teams['School'] == 'Sam Houston', 'URL School'] = 'Sam Houston State'
df_active_teams.loc[df_active_teams['School'] == 'Houston Christian', 'URL School'] = 'Houston Baptist'
df_active_teams.loc[df_active_teams['School'] == 'Kansas City', 'URL School'] = 'Missouri Kansas City'
df_active_teams.loc[df_active_teams['School'] == 'Little Rock', 'URL School'] = 'Arkansas Little Rock'
df_active_teams.loc[df_active_teams['School'] == 'NC State', 'URL School'] = 'North Carolina State'
df_active_teams.loc[df_active_teams['School'] == 'Omaha', 'URL School'] = 'Nebraska Omaha'
df_active_teams.loc[df_active_teams['School'] == 'Purdue Fort Wayne', 'URL School'] = 'IPFW'
df_active_teams.loc[df_active_teams['School'] == 'TCU', 'URL School'] = 'Texas Christian'
df_active_teams.loc[df_active_teams['School'] == 'Texas-Rio Grande Valley', 'URL School'] = 'Texas Pan American'
df_active_teams.loc[df_active_teams['School'] == 'The Citadel', 'URL School'] = 'Citadel'
df_active_teams.loc[df_active_teams['School'] == 'Utah Tech', 'URL School'] = 'Dixie State'
df_active_teams.loc[df_active_teams['School'] == 'St. Thomas', 'URL School'] = 'St. Thomas MN'
df_active_teams.loc[df_active_teams['School'] == 'UC Berkley', 'URL School'] = 'California'
df_active_teams.loc[df_active_teams['School'] == 'UT Arlington', 'URL School'] = 'Texas Arlington'
df_active_teams.loc[df_active_teams['School'] == 'FDU', 'URL School'] = 'Fairleigh Dickinson'
df_active_teams.loc[df_active_teams['School'] == 'Hartford Hawks', 'URL School'] = 'Hartford'
df_active_teams.loc[df_active_teams['School'] == 'Savannah State Tigers', 'URL School'] = 'Savannah State'
df_active_teams.loc[df_active_teams['School'] == 'St. Francis (NY) Terriers', 'URL School'] = 'St. Francis (NY)'
df_active_teams.loc[df_active_teams['School'] == 'East Texas A&M', 'URL School'] = 'Texas A&M Commerce'
df_active_teams.loc[df_active_teams['School'] == 'IU Indy', 'URL School'] = 'IUPUI'

df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UC\s', 'California ', regex=True)
df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UNC\s', 'North Carolina ', regex=True)

In [4]:
urls = (
    'https://www.sports-reference.com/cbb/schools/' +
    df_active_teams['URL School'].str.replace(' ', '-', regex=False).str.replace('[)(&.\']', '', regex=True).str.replace('--', '-', regex=False).str.lower() +
    '/men/' + str(season) +
    '-starters.html'
)

urls

0      https://www.sports-reference.com/cbb/schools/a...
1      https://www.sports-reference.com/cbb/schools/a...
2      https://www.sports-reference.com/cbb/schools/a...
3      https://www.sports-reference.com/cbb/schools/a...
4      https://www.sports-reference.com/cbb/schools/a...
                             ...
359    https://www.sports-reference.com/cbb/schools/w...
360    https://www.sports-reference.com/cbb/schools/w...
361    https://www.sports-reference.com/cbb/schools/x...
362    https://www.sports-reference.com/cbb/schools/y...
363    https://www.sports-reference.com/cbb/schools/y...
Name: URL School, Length: 364, dtype: object

In [5]:
from urllib.error import HTTPError
from tqdm.notebook import tqdm

problems = []

l = []
loop = tqdm(
    np.array((df_active_teams['School'], urls)).transpose(),  # get both school and url into loop iteration
    bar_format='{bar}{percentage:3.0f}%{r_bar}   {desc}'  # make the description not affect bar location
)

for (school, url) in loop:
  try:
    loop.set_description(f'{school}')
    # print(f'{i:03d}: {url}')
    df_team_season = pd.read_html(url)[0]  # starters should be initial table on site
    time.sleep(2)
    
    df_team_season.insert(4, 'Team', school)
    l.append(df_team_season)
  except HTTPError as e:
    if e.code == 404:
      print(f'{url} | {e}')
      time.sleep(2)
    else:
      print(f'{url} | {e}')
      break

df = pd.concat(l, ignore_index=True)

df

            0%| 0/364 [00:00<?, ?it/s]

,G,Date,Unnamed: 2,Unnamed: 3,Team,Unnamed: 4,Opponent,Unnamed: 6,OT,Tm,Opp,W,L,Unnamed: 12
0,1,"Mon, Nov 4, 2024",NaN,Box Score,Abilene Christian,NaN,Howard Payne,W,NaN,107,74,1,0,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
1,2,"Sat, Nov 9, 2024",NaN,Box Score,Abilene Christian,NaN,Middle Tennessee,L,NaN,56,79,1,1,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
2,3,"Tue, Nov 12, 2024",NaN,Box Score,Abilene Christian,NaN,McMurry,W,NaN,101,55,2,1,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...
3,4,"Sat, Nov 16, 2024",NaN,Box Score,Abilene Christian,NaN,Texas State,W,NaN,72,60,3,1,N. DeGruy · C. Hornecker · H. Madden · J. Venz...
4,5,"Wed, Nov 20, 2024",NaN,Box Score,Abilene Christian,@,Kennesaw State,L,NaN,78,84,3,2,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11805,30,"Sun, Feb 23, 2025",NaN,Box Score,Youngstown State,NaN,Green Bay,W,NaN,81,77,19,11,C. Carroll · N. Galette · T. Harper · J. Maxey...
11806,31,"Sat, Mar 1, 2025",NaN,Box Score,Youngstown State,@,Northern Kentucky,L,NaN,79,88,19,12,C. Carroll · N. Galette · T. Harper · J. Maxey...
11807,32,"Thu, Mar 6, 2025",NaN,Box Score,Youngstown State,NaN,Purdue Fort Wayne,W,NaN,72,67,20,12,C. Carroll · N. Galette · T. Harper · J. Maxey...
11808,33,"Mon, Mar 10, 2025",NaN,Box Score,Youngstown State,N,Cleveland State,W,NaN,56,54,21,12,C. Carroll · N. Galette · T. Harper · J. Maxey...
11809,34,"Tue, Mar 11, 2025",NaN,Box Score,Youngstown State,N,Robert Morris,L,NaN,78,89,21,13,C. Carroll · N. Galette · T. Harper · J. Maxey...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11810 entries, 0 to 11809
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   G            11810 non-null  int64
 1   Date         11810 non-null  object
 2   Unnamed: 2   0 non-null      float64
 3   Unnamed: 3   11810 non-null  object
 4   Team         11810 non-null  object
 5   Unnamed: 4   6295 non-null   object
 6   Opponent     11810 non-null  object
 7   Unnamed: 6   11810 non-null  object
 8   OT           640 non-null    object
 9   Tm           11810 non-null  int64
 10  Opp          11810 non-null  int64
 11  W            11810 non-null  int64
 12  L            11810 non-null  int64
 13  Unnamed: 12  11810 non-null  object
dtypes: float64(1), int64(5), object(8)
memory usage: 1.3+ MB

### Data Setup

In [7]:
temp = df.copy()

In [8]:
df = temp.copy()

Fix column names and drop useless columns

In [9]:
df.drop(columns=['G', 'Unnamed: 2', 'Unnamed: 3', 'W', 'L'], inplace=True)

df.columns = ['Date', 'Team', 'Location', 'Opponent', 'Result', 'Overtime', 'Team Score', 'Opponent Score', 'Starters']

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters
0,"Mon, Nov 4, 2024",Abilene Christian,NaN,Howard Payne,W,NaN,107,74,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
1,"Sat, Nov 9, 2024",Abilene Christian,NaN,Middle Tennessee,L,NaN,56,79,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
2,"Tue, Nov 12, 2024",Abilene Christian,NaN,McMurry,W,NaN,101,55,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...
3,"Sat, Nov 16, 2024",Abilene Christian,NaN,Texas State,W,NaN,72,60,N. DeGruy · C. Hornecker · H. Madden · J. Venz...
4,"Wed, Nov 20, 2024",Abilene Christian,@,Kennesaw State,L,NaN,78,84,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
...,...,...,...,...,...,...,...,...,...
11805,"Sun, Feb 23, 2025",Youngstown State,NaN,Green Bay,W,NaN,81,77,C. Carroll · N. Galette · T. Harper · J. Maxey...
11806,"Sat, Mar 1, 2025",Youngstown State,@,Northern Kentucky,L,NaN,79,88,C. Carroll · N. Galette · T. Harper · J. Maxey...
11807,"Thu, Mar 6, 2025",Youngstown State,NaN,Purdue Fort Wayne,W,NaN,72,67,C. Carroll · N. Galette · T. Harper · J. Maxey...
11808,"Mon, Mar 10, 2025",Youngstown State,N,Cleveland State,W,NaN,56,54,C. Carroll · N. Galette · T. Harper · J. Maxey...
11809,"Tue, Mar 11, 2025",Youngstown State,N,Robert Morris,L,NaN,78,89,C. Carroll · N. Galette · T. Harper · J. Maxey...

In [10]:
# remove games that have not been played
df = df.loc[(df['Result'].notna()) & (df['Result'] != 'W/L'), :].reset_index(drop=True)

# get overtime info
df['Overtime'] = df['Overtime'].notna().astype('int8')

# reformat result column
df['Result'] = df['Result'].str[:1].map({'W': 1, 'L': -1}).astype('int8')

# remove games with non-D1 opponents
df = df.loc[df['Opponent'].isin(df['Team']), :].reset_index(drop=True)

# remove games where starters are not listed
df = df.loc[df['Starters'].notna(), :].reset_index(drop=True)

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters
0,"Sat, Nov 9, 2024",Abilene Christian,NaN,Middle Tennessee,-1,0,56,79,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
1,"Sat, Nov 16, 2024",Abilene Christian,NaN,Texas State,1,0,72,60,N. DeGruy · C. Hornecker · H. Madden · J. Venz...
2,"Wed, Nov 20, 2024",Abilene Christian,@,Kennesaw State,-1,0,78,84,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
3,"Mon, Nov 25, 2024",Abilene Christian,N,Southern Mississippi,1,0,82,74,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
4,"Tue, Nov 26, 2024",Abilene Christian,@,Montana State,-1,0,59,85,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...
...,...,...,...,...,...,...,...,...,...
11277,"Sun, Feb 23, 2025",Youngstown State,NaN,Green Bay,1,0,81,77,C. Carroll · N. Galette · T. Harper · J. Maxey...
11278,"Sat, Mar 1, 2025",Youngstown State,@,Northern Kentucky,-1,0,79,88,C. Carroll · N. Galette · T. Harper · J. Maxey...
11279,"Thu, Mar 6, 2025",Youngstown State,NaN,Purdue Fort Wayne,1,0,72,67,C. Carroll · N. Galette · T. Harper · J. Maxey...
11280,"Mon, Mar 10, 2025",Youngstown State,N,Cleveland State,1,0,56,54,C. Carroll · N. Galette · T. Harper · J. Maxey...
11281,"Tue, Mar 11, 2025",Youngstown State,N,Robert Morris,-1,0,78,89,C. Carroll · N. Galette · T. Harper · J. Maxey...

Reformat location column for home/neutral/away

In [11]:
df['Location'] = df['Location'].map({np.NaN: 1, 'N': 0, '@': -1}).astype('int8')

df['Location']

0        1
1        1
2       -1
3        0
4       -1
        ..
11277    1
11278   -1
11279    1
11280    0
11281    0
Name: Location, Length: 11282, dtype: int8

Other general fixes

In [12]:
# fix dates
df['Date'] = pd.to_datetime(df['Date'])

# only include games before NCAA tournament
df = df.loc[df['Date'] <= cutoff_dates[season], :].reset_index(drop=True)

# fix column types
df.loc[:, df.columns.str.contains('Team ', regex=False)] = df.loc[:, df.columns.str.contains('Team ', regex=False)].astype('float64')
df.loc[:, df.columns.str.contains('Opponent ', regex=False)] = df.loc[:, df.columns.str.contains('Opponent ', regex=False)].astype('float64')

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters
0,2024-11-09,Abilene Christian,1,Middle Tennessee,-1,0,56,79,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
1,2024-11-16,Abilene Christian,1,Texas State,1,0,72,60,N. DeGruy · C. Hornecker · H. Madden · J. Venz...
2,2024-11-20,Abilene Christian,-1,Kennesaw State,-1,0,78,84,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
3,2024-11-25,Abilene Christian,0,Southern Mississippi,1,0,82,74,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
4,2024-11-26,Abilene Christian,-1,Montana State,-1,0,59,85,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...
...,...,...,...,...,...,...,...,...,...
11277,2025-02-23,Youngstown State,1,Green Bay,1,0,81,77,C. Carroll · N. Galette · T. Harper · J. Maxey...
11278,2025-03-01,Youngstown State,-1,Northern Kentucky,-1,0,79,88,C. Carroll · N. Galette · T. Harper · J. Maxey...
11279,2025-03-06,Youngstown State,1,Purdue Fort Wayne,1,0,72,67,C. Carroll · N. Galette · T. Harper · J. Maxey...
11280,2025-03-10,Youngstown State,0,Cleveland State,1,0,56,54,C. Carroll · N. Galette · T. Harper · J. Maxey...
11281,2025-03-11,Youngstown State,0,Robert Morris,-1,0,78,89,C. Carroll · N. Galette · T. Harper · J. Maxey...

Get opponent starters

In [13]:
# create a pseudo game ID that can be looked at from opponent's perspective to get opposing starters
key_to_starters = dict(zip(
    df['Date'].astype(str) + ' ' + df['Team'] + ' ' + df['Opponent'] + ' ' + df['Team Score'].astype(str) + ' ' + df['Opponent Score'].astype(str),
    df['Starters']
))

df['Opponent Starters'] = (df['Date'].astype(str) + ' ' + df['Opponent'] + ' ' + df['Team'] + ' ' + df['Opponent Score'].astype(str) + ' ' + df['Team Score'].astype(str)).map(key_to_starters)

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters,Opponent Starters
0,2024-11-09,Abilene Christian,1,Middle Tennessee,-1,0,56,79,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,J. Bufford · K. Lands · E. Mostafa · J. Porter...
1,2024-11-16,Abilene Christian,1,Texas State,1,0,72,60,N. DeGruy · C. Hornecker · H. Madden · J. Venz...,D. Drinnon · K. Gumbs · J. O'Garro · T. Pope ·...
2,2024-11-20,Abilene Christian,-1,Kennesaw State,-1,0,78,84,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,S. Cottle · B. Lue · J. Miller · A. Weir · A. ...
3,2024-11-25,Abilene Christian,0,Southern Mississippi,1,0,82,74,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,N. Alvarez · D. Harris · C. Montgomery · C. Wa...
4,2024-11-26,Abilene Christian,-1,Montana State,-1,0,59,85,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...,M. Agbonkpolo · P. McMahon · J. Mullins · T. P...
...,...,...,...,...,...,...,...,...,...,...
11277,2025-02-23,Youngstown State,1,Green Bay,1,0,81,77,C. Carroll · N. Galette · T. Harper · J. Maxey...,M. Hall · J. Johnson · Y. Levy · P. Ruedinger ...
11278,2025-03-01,Youngstown State,-1,Northern Kentucky,-1,0,79,88,C. Carroll · N. Galette · T. Harper · J. Maxey...,J. Dilling · D. Gherezgher · K. Itejere · T. R...
11279,2025-03-06,Youngstown State,1,Purdue Fort Wayne,1,0,72,67,C. Carroll · N. Galette · T. Harper · J. Maxey...,R. Bello · J. Jackson · Q. Morton-Robertson · ...
11280,2025-03-10,Youngstown State,0,Cleveland State,1,0,56,54,C. Carroll · N. Galette · T. Harper · J. Maxey...,I. Abidde · D. Arnett · E. Dibba · T. Smith · ...
11281,2025-03-11,Youngstown State,0,Robert Morris,-1,0,78,89,C. Carroll · N. Galette · T. Harper · J. Maxey...,A. Dickerson · A. Folgueiras · J. Omojafo · D....

In [14]:
df.loc[df['Opponent Starters'].isna(), :]

Empty DataFrame
Columns: [Date, Team, Location, Opponent, Result, Overtime, Team Score, Opponent Score, Starters, Opponent Starters]
Index: []

Split starters into separate columns

In [15]:
# rename starters column
df.rename(columns={'Starters': 'Team Starters'}, inplace=True)

df[[f'Team Starter {i}' for i in range(1, 6)]] = df['Team Starters'].str.split(r'\xa0· | \·', regex=True, expand=True)

for i in range(1, 6):
    df[f'Team Starter {i}'] = df['Team'] + ' ' + df[f'Team Starter {i}']

df[[f'Opponent Starter {i}' for i in range(1, 6)]] = df['Opponent Starters'].str.split(r'\xa0· | \·', regex=True, expand=True)

for i in range(1, 6):
    df[f'Opponent Starter {i}'] = df['Opponent'] + ' ' + df[f'Opponent Starter {i}']

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Team Starters,Opponent Starters,Team Starter 1,Team Starter 2,Team Starter 3,Team Starter 4,Team Starter 5,Opponent Starter 1,Opponent Starter 2,Opponent Starter 3,Opponent Starter 4,Opponent Starter 5
0,2024-11-09,Abilene Christian,1,Middle Tennessee,-1,0,56,79,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,J. Bufford · K. Lands · E. Mostafa · J. Porter...,Abilene Christian L. Bettiol,Abilene Christian N. DeGruy,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Middle Tennessee J. Bufford,Middle Tennessee K. Lands,Middle Tennessee E. Mostafa,Middle Tennessee J. Porter,Middle Tennessee C. Weston
1,2024-11-16,Abilene Christian,1,Texas State,1,0,72,60,N. DeGruy · C. Hornecker · H. Madden · J. Venz...,D. Drinnon · K. Gumbs · J. O'Garro · T. Pope ·...,Abilene Christian N. DeGruy,Abilene Christian C. Hornecker,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Texas State D. Drinnon,Texas State K. Gumbs,Texas State J. O'Garro,Texas State T. Pope,Texas State C. Turner
2,2024-11-20,Abilene Christian,-1,Kennesaw State,-1,0,78,84,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,S. Cottle · B. Lue · J. Miller · A. Weir · A. ...,Abilene Christian L. Bettiol,Abilene Christian N. DeGruy,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Kennesaw State S. Cottle,Kennesaw State B. Lue,Kennesaw State J. Miller,Kennesaw State A. Weir,Kennesaw State A. Wooley
3,2024-11-25,Abilene Christian,0,Southern Mississippi,1,0,82,74,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,N. Alvarez · D. Harris · C. Montgomery · C. Wa...,Abilene Christian L. Bettiol,Abilene Christian N. DeGruy,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Southern Mississippi N. Alvarez,Southern Mississippi D. Harris,Southern Mississippi C. Montgomery,Southern Mississippi C. Watson,Southern Mississippi L. Yat
4,2024-11-26,Abilene Christian,-1,Montana State,-1,0,59,85,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...,M. Agbonkpolo · P. McMahon · J. Mullins · T. P...,Abilene Christian L. Bettiol,Abilene Christian N. DeGruy,Abilene Christian B. Hubbard,Abilene Christian H. Madden,Abilene Christian Q. Williams,Montana State M. Agbonkpolo,Montana State P. McMahon,Montana State J. Mullins,Montana State T. Patterson,Montana State B. Walker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11277,2025-02-23,Youngstown State,1,Green Bay,1,0,81,77,C. Carroll · N. Galette · T. Harper · J. Maxey...,M. Hall · J. Johnson · Y. Levy · P. Ruedinger ...,Youngstown State C. Carroll,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,Green Bay M. Hall,Green Bay J. Johnson,Green Bay Y. Levy,Green Bay P. Ruedinger,Green Bay B. Tweedy
11278,2025-03-01,Youngstown State,-1,Northern Kentucky,-1,0,79,88,C. Carroll · N. Galette · T. Harper · J. Maxey...,J. Dilling · D. Gherezgher · K. Itejere · T. R...,Youngstown State C. Carroll,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,Northern Kentucky J. Dilling,Northern Kentucky D. Gherezgher,Northern Kentucky K. Itejere,Northern Kentucky T. Robinson,Northern Kentucky S. Vinson
11279,2025-03-06,Youngstown State,1,Purdue Fort Wayne,1,0,72,67,C. Carroll · N. Galette · T. Harper · J. Maxey...,R. Bello · J. Jackson · Q. Morton-Robertson · ...,Youngstown State C. Carroll,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,Purdue Fort Wayne R. Bello,Purdue Fort Wayne J. Jackson,Purdue Fort Wayne Q. Morton-Robertson,Purdue Fort Wayne E. Mulder,Purdue Fort Wayne M. Nelson
11280,2025-03-10,Youngstown State,0,Cleveland State,1,0,56,54,C. Carroll · N. Galette · T. Harper · J. Maxey...,I. Abidde · D. Arnett · E. Dibba · T. Smith · ...,Youngstown State C. Carroll,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,Cleveland State I. Abidde,Cleveland State D. Arnett,Cleveland State E. Dibba,Cleveland State T. Smith,Cleveland State T. Staveskie
11281,2025-03-11,Youngstown State,0,Robert Morris,-1,0,78,89,C. Carroll · N. Galette · T. Harper · J. Maxey...,A. Dickerson · A. Folgueiras · J. Omojafo · D....,Youngstown State C. Carroll,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,Robert Morris A. Dickerson,Robert Morris A. Folgueiras,Robert Morris J. Omojafo,Robert Morris D. Smith,Robert Morris K. Woods

Set up adjusted Score Differential

In [16]:
blowout_threshold = 18  # adjusted score differential will only account up to this score difference

df['Score Differential'] = df['Team Score'] - df['Opponent Score']

df['Adjusted Score Differential'] = df['Score Differential'].abs()

df.loc[df['Adjusted Score Differential'] > blowout_threshold, 'Adjusted Score Differential'] = blowout_threshold

df['Adjusted Score Differential'] = df['Adjusted Score Differential']**(np.log(1.5)/np.log(blowout_threshold))

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Team Starters,Opponent Starters,...,Team Starter 3,Team Starter 4,Team Starter 5,Opponent Starter 1,Opponent Starter 2,Opponent Starter 3,Opponent Starter 4,Opponent Starter 5,Score Differential,Adjusted Score Differential
0,2024-11-09,Abilene Christian,1,Middle Tennessee,-1,0,56,79,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,J. Bufford · K. Lands · E. Mostafa · J. Porter...,...,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Middle Tennessee J. Bufford,Middle Tennessee K. Lands,Middle Tennessee E. Mostafa,Middle Tennessee J. Porter,Middle Tennessee C. Weston,-23,1.500000
1,2024-11-16,Abilene Christian,1,Texas State,1,0,72,60,N. DeGruy · C. Hornecker · H. Madden · J. Venz...,D. Drinnon · K. Gumbs · J. O'Garro · T. Pope ·...,...,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Texas State D. Drinnon,Texas State K. Gumbs,Texas State J. O'Garro,Texas State T. Pope,Texas State C. Turner,12,1.417062
2,2024-11-20,Abilene Christian,-1,Kennesaw State,-1,0,78,84,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,S. Cottle · B. Lue · J. Miller · A. Weir · A. ...,...,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Kennesaw State S. Cottle,Kennesaw State B. Lue,Kennesaw State J. Miller,Kennesaw State A. Weir,Kennesaw State A. Wooley,-6,1.285760
3,2024-11-25,Abilene Christian,0,Southern Mississippi,1,0,82,74,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,N. Alvarez · D. Harris · C. Montgomery · C. Wa...,...,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Southern Mississippi N. Alvarez,Southern Mississippi D. Harris,Southern Mississippi C. Montgomery,Southern Mississippi C. Watson,Southern Mississippi L. Yat,8,1.338710
4,2024-11-26,Abilene Christian,-1,Montana State,-1,0,59,85,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...,M. Agbonkpolo · P. McMahon · J. Mullins · T. P...,...,Abilene Christian B. Hubbard,Abilene Christian H. Madden,Abilene Christian Q. Williams,Montana State M. Agbonkpolo,Montana State P. McMahon,Montana State J. Mullins,Montana State T. Patterson,Montana State B. Walker,-26,1.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11277,2025-02-23,Youngstown State,1,Green Bay,1,0,81,77,C. Carroll · N. Galette · T. Harper · J. Maxey...,M. Hall · J. Johnson · Y. Levy · P. Ruedinger ...,...,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,Green Bay M. Hall,Green Bay J. Johnson,Green Bay Y. Levy,Green Bay P. Ruedinger,Green Bay B. Tweedy,4,1.214668
11278,2025-03-01,Youngstown State,-1,Northern Kentucky,-1,0,79,88,C. Carroll · N. Galette · T. Harper · J. Maxey...,J. Dilling · D. Gherezgher · K. Itejere · T. R...,...,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,Northern Kentucky J. Dilling,Northern Kentucky D. Gherezgher,Northern Kentucky K. Itejere,Northern Kentucky T. Robinson,Northern Kentucky S. Vinson,-9,1.361013
11279,2025-03-06,Youngstown State,1,Purdue Fort Wayne,1,0,72,67,C. Carroll · N. Galette · T. Harper · J. Maxey...,R. Bello · J. Jackson · Q. Morton-Robertson · ...,...,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,Purdue Fort Wayne R. Bello,Purdue Fort Wayne J. Jackson,Purdue Fort Wayne Q. Morton-Robertson,Purdue Fort Wayne E. Mulder,Purdue Fort Wayne M. Nelson,5,1.253292
11280,2025-03-10,Youngstown State,0,Cleveland State,1,0,56,54,C. Carroll · N. Galette · T. Harper · J. Maxey...,I. Abidde · D. Arnett · E. Dibba · T. Smith · ...,...,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,Cleveland State I. Abidde,Cleveland State D. Arnett,Cleveland State E. Dibba,Cleveland State T. Smith,Cleveland State T. Staveskie,2,1.102120
11281,2025-03-11,Youngstown State,0,Robert Morris,-1,0,78,89,C. Carroll · N. Galette · T. Harper · J. Maxey...,A. Dickerson · A. Folgueiras · J. Omojafo · D....,...,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,Robert Morris A. Dickerson,Robert Morris A. Folgueiras,Robert Morris J. Omojafo,Robert Morris D. Smith,Robert Morris K. Woods,-11,1.399871

##### Save

In [26]:
df.to_parquet(f'../data/unprocessed/mens_starters/starters_{season}.parquet', index=False)

'Done'

'Done'