# Men's Scrape Starters

Get data of each team's starters in a given year. This file needs to be ran for every relevant year (2012 to 2024).

### Web Scraping

Fair warning that this program unfortunately takes a very long time to run due to web scraping limits set by Sports Reference

In [1]:
import pandas as pd
import numpy as np
import time

season = 2025

df_active_teams = pd.read_html('https://www.sports-reference.com/cbb/schools/index.html')[0]
time.sleep(2)

df_active_teams = df_active_teams.loc[~df_active_teams['School'].isin([np.NaN, 'School']), :].reset_index(drop=True)

df_active_teams['From'] = pd.to_numeric(df_active_teams['From'], errors='coerce')
df_active_teams['To'] = pd.to_numeric(df_active_teams['To'], errors='coerce')

df_active_teams = df_active_teams.loc[(df_active_teams['To'] >= season) & (df_active_teams['From'] <= season), :].reset_index(drop=True)

if season == 2021:  # if 2021, remove ivy league because they cancelled their season in 2021
    df_active_teams = df_active_teams.loc[
        ~df_active_teams['School'].isin(['Princeton', 'Harvard', 'Yale', 'Pennsylvania', 'Brown', 'Columbia', 'Cornell', 'Dartmouth']),
        :
    ].reset_index(drop=True)

df_active_teams

,Rk,School,"City, State",From,To,Yrs,G,W,L,W-L%,SRS,SOS,AP,CREG,CTRN,NCAA,FF,NC
0,1,Abilene Christian,"Abilene, Texas",1971,2025,15,449,239,210,.532,-7.57,-5.30,0,0,2,2,0,0
1,2,Air Force,"USAF Academy, Colorado",1958,2025,68,1869,796,1073,.426,-2.87,1.35,0,1,0,4,0,0
2,3,Akron,"Akron, Ohio",1902,2025,74,1744,1048,696,.601,0.09,-1.60,0,9,6,6,0,0
3,4,Alabama,"Tuscaloosa, Alabama",1913,2025,112,2922,1815,1106,.621,8.16,5.05,18,10,9,25,1,0
4,5,Alabama A&M,"Normal, Alabama",2000,2025,26,749,286,463,.382,-16.71,-11.01,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,489,Wright State,"Dayton, Ohio",1988,2025,38,1157,644,513,.557,-1.40,-2.58,0,4,4,4,0,0
360,490,Wyoming,"Laramie, Wyoming",1905,2025,120,2906,1622,1284,.558,2.70,2.76,4,21,3,16,1,1
361,491,Xavier,"Cincinnati, Ohio",1920,2025,104,2724,1628,1096,.598,6.19,4.05,13,18,9,29,0,0
362,492,Yale,"New Haven, Connecticut",1896,2025,129,3108,1583,1523,.510,-5.80,-4.42,1,16,3,7,0,0
363,493,Youngstown State,"Youngstown, Ohio",1948,2025,45,1321,548,773,.415,-7.86,-3.55,0,1,0,0,0,0

In [ ]:
from datetime import datetime

cutoff_dates = {
    2012: datetime(2012, 3, 14),
    2013: datetime(2013, 3, 20),
    2014: datetime(2014, 3, 19),
    2015: datetime(2015, 3, 18),
    2016: datetime(2016, 3, 16),
    2017: datetime(2017, 3, 15),
    2018: datetime(2018, 3, 14),
    2019: datetime(2019, 3, 20),
    2021: datetime(2021, 3, 18),
    2022: datetime(2022, 3, 16),
    2023: datetime(2023, 3, 15),
    2024: datetime(2024, 3, 20),
    2025: datetime(2025, 3, 19),
}

cutoff_dates[season]

datetime.datetime(2025, 3, 16, 0, 0)

Get school names used in Sports Reference URL

In [3]:
df_active_teams.loc[df_active_teams['School'] == 'Hartford Hawks', 'School'] = 'Hartford'
df_active_teams.loc[df_active_teams['School'] == 'Savannah State Tigers', 'School'] = 'Savannah State'
df_active_teams.loc[df_active_teams['School'] == 'St. Francis (NY) Terriers', 'School'] = 'St. Francis (NY)'

df_active_teams['URL School'] = df_active_teams['School']

# hard code some schools that cause issues
df_active_teams.loc[df_active_teams['School'] == 'Bowling Green', 'URL School'] = 'Bowling Green State'
df_active_teams.loc[df_active_teams['School'] == 'BYU', 'URL School'] = 'Brigham Young'
df_active_teams.loc[df_active_teams['School'] == 'Louisiana', 'URL School'] = 'Louisiana Lafayette'
df_active_teams.loc[df_active_teams['School'] == 'LSU', 'URL School'] = 'Louisiana State'
df_active_teams.loc[df_active_teams['School'] == 'Ole Miss', 'URL School'] = 'Mississippi'
df_active_teams.loc[df_active_teams['School'] == 'Pitt', 'URL School'] = 'Pittsburgh'
df_active_teams.loc[df_active_teams['School'] == 'SMU', 'URL School'] = 'Southern Methodist'
df_active_teams.loc[df_active_teams['School'] == 'UAB', 'URL School'] = 'Alabama Birmingham'
df_active_teams.loc[df_active_teams['School'] == 'UCF', 'URL School'] = 'Central Florida'
df_active_teams.loc[df_active_teams['School'] == 'USC', 'URL School'] = 'Southern California'
df_active_teams.loc[df_active_teams['School'] == 'UTEP', 'URL School'] = 'Texas El Paso'
df_active_teams.loc[df_active_teams['School'] == 'UTSA', 'URL School'] = 'Texas San Antonio'
df_active_teams.loc[df_active_teams['School'] == 'Sam Houston', 'URL School'] = 'Sam Houston State'
df_active_teams.loc[df_active_teams['School'] == 'Houston Christian', 'URL School'] = 'Houston Baptist'
df_active_teams.loc[df_active_teams['School'] == 'Kansas City', 'URL School'] = 'Missouri Kansas City'
df_active_teams.loc[df_active_teams['School'] == 'Little Rock', 'URL School'] = 'Arkansas Little Rock'
df_active_teams.loc[df_active_teams['School'] == 'NC State', 'URL School'] = 'North Carolina State'
df_active_teams.loc[df_active_teams['School'] == 'Omaha', 'URL School'] = 'Nebraska Omaha'
df_active_teams.loc[df_active_teams['School'] == 'Purdue Fort Wayne', 'URL School'] = 'IPFW'
df_active_teams.loc[df_active_teams['School'] == 'TCU', 'URL School'] = 'Texas Christian'
df_active_teams.loc[df_active_teams['School'] == 'Texas-Rio Grande Valley', 'URL School'] = 'Texas Pan American'
df_active_teams.loc[df_active_teams['School'] == 'The Citadel', 'URL School'] = 'Citadel'
df_active_teams.loc[df_active_teams['School'] == 'Utah Tech', 'URL School'] = 'Dixie State'
df_active_teams.loc[df_active_teams['School'] == 'St. Thomas', 'URL School'] = 'St. Thomas MN'
df_active_teams.loc[df_active_teams['School'] == 'UC Berkley', 'URL School'] = 'California'
df_active_teams.loc[df_active_teams['School'] == 'UT Arlington', 'URL School'] = 'Texas Arlington'
df_active_teams.loc[df_active_teams['School'] == 'FDU', 'URL School'] = 'Fairleigh Dickinson'
df_active_teams.loc[df_active_teams['School'] == 'Hartford Hawks', 'URL School'] = 'Hartford'
df_active_teams.loc[df_active_teams['School'] == 'Savannah State Tigers', 'URL School'] = 'Savannah State'
df_active_teams.loc[df_active_teams['School'] == 'St. Francis (NY) Terriers', 'URL School'] = 'St. Francis (NY)'
df_active_teams.loc[df_active_teams['School'] == 'East Texas A&M', 'URL School'] = 'Texas A&M Commerce'
df_active_teams.loc[df_active_teams['School'] == 'IU Indy', 'URL School'] = 'IUPUI'

df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UC\s', 'California ', regex=True)
df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UNC\s', 'North Carolina ', regex=True)

In [4]:
urls = (
    'https://www.sports-reference.com/cbb/schools/' +
    df_active_teams['URL School'].str.replace(' ', '-', regex=False).str.replace('[)(&.\']', '', regex=True).str.replace('--', '-', regex=False).str.lower() +
    '/men/' + str(season) +
    '-starters.html'
)

urls

0      https://www.sports-reference.com/cbb/schools/a...
1      https://www.sports-reference.com/cbb/schools/a...
2      https://www.sports-reference.com/cbb/schools/a...
3      https://www.sports-reference.com/cbb/schools/a...
4      https://www.sports-reference.com/cbb/schools/a...
                             ...
359    https://www.sports-reference.com/cbb/schools/w...
360    https://www.sports-reference.com/cbb/schools/w...
361    https://www.sports-reference.com/cbb/schools/x...
362    https://www.sports-reference.com/cbb/schools/y...
363    https://www.sports-reference.com/cbb/schools/y...
Name: URL School, Length: 364, dtype: object

In [5]:
from urllib.error import HTTPError
from tqdm.notebook import tqdm

problems = []

l = []
loop = tqdm(
    np.array((df_active_teams['School'], urls)).transpose(),  # get both school and url into loop iteration
    bar_format='{bar}{percentage:3.0f}%{r_bar}   {desc}'  # make the description not affect bar location
)

for (school, url) in loop:
  try:
    loop.set_description(f'{school}')
    # print(f'{i:03d}: {url}')
    df_team_season = pd.read_html(url)[0]  # starters should be initial table on site
    time.sleep(2)
    
    df_team_season.insert(4, 'Team', school)
    l.append(df_team_season)
  except HTTPError as e:
    if e.code == 404:
      print(f'{url} | {e}')
      time.sleep(2)
    else:
      print(f'{url} | {e}')
      break

df = pd.concat(l, ignore_index=True)

df

            0%| 0/364 [00:00<?, ?it/s]

,G,Date,Unnamed: 2,Unnamed: 3,Team,Unnamed: 4,Opponent,Unnamed: 6,OT,Tm,Opp,W,L,Unnamed: 12
0,1,"Mon, Nov 4, 2024",NaN,Box Score,Abilene Christian,NaN,Howard Payne,W,NaN,107,74,1,0,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
1,2,"Sat, Nov 9, 2024",NaN,Box Score,Abilene Christian,NaN,Middle Tennessee,L,NaN,56,79,1,1,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
2,3,"Tue, Nov 12, 2024",NaN,Box Score,Abilene Christian,NaN,McMurry,W,NaN,101,55,2,1,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...
3,4,"Sat, Nov 16, 2024",NaN,Box Score,Abilene Christian,NaN,Texas State,W,NaN,72,60,3,1,N. DeGruy · C. Hornecker · H. Madden · J. Venz...
4,5,"Wed, Nov 20, 2024",NaN,Box Score,Abilene Christian,@,Kennesaw State,L,NaN,78,84,3,2,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9781,25,"Thu, Feb 6, 2025",NaN,Box Score,Youngstown State,@,Oakland,W,NaN,84,75,15,10,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9782,26,"Sat, Feb 8, 2025",NaN,Box Score,Youngstown State,@,Detroit Mercy,W,NaN,87,72,16,10,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9783,27,"Wed, Feb 12, 2025",NaN,Box Score,Youngstown State,NaN,Purdue Fort Wayne,W,NaN,93,71,17,10,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9784,28,"Sun, Feb 16, 2025",NaN,Box Score,Youngstown State,@,Cleveland State,W,NaN,68,60,18,10,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9785,29,"Fri, Feb 21, 2025",NaN,Box Score,Youngstown State,NaN,Milwaukee,L,NaN,74,84,18,11,C. Carroll · N. Galette · T. Harper · J. Maxey...

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9786 entries, 0 to 9785
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   G            9786 non-null   int64
 1   Date         9786 non-null   object
 2   Unnamed: 2   0 non-null      float64
 3   Unnamed: 3   9784 non-null   object
 4   Team         9786 non-null   object
 5   Unnamed: 4   5019 non-null   object
 6   Opponent     9786 non-null   object
 7   Unnamed: 6   9786 non-null   object
 8   OT           516 non-null    object
 9   Tm           9786 non-null   int64
 10  Opp          9786 non-null   int64
 11  W            9786 non-null   int64
 12  L            9786 non-null   int64
 13  Unnamed: 12  9784 non-null   object
dtypes: float64(1), int64(5), object(8)
memory usage: 1.0+ MB

### Data Setup

In [7]:
temp = df.copy()

In [8]:
df = temp.copy()

Fix column names and drop useless columns

In [9]:
df.drop(columns=['G', 'Unnamed: 2', 'Unnamed: 3', 'W', 'L'], inplace=True)

df.columns = ['Date', 'Team', 'Location', 'Opponent', 'Result', 'Overtime', 'Team Score', 'Opponent Score', 'Starters']

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters
0,"Mon, Nov 4, 2024",Abilene Christian,NaN,Howard Payne,W,NaN,107,74,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
1,"Sat, Nov 9, 2024",Abilene Christian,NaN,Middle Tennessee,L,NaN,56,79,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
2,"Tue, Nov 12, 2024",Abilene Christian,NaN,McMurry,W,NaN,101,55,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...
3,"Sat, Nov 16, 2024",Abilene Christian,NaN,Texas State,W,NaN,72,60,N. DeGruy · C. Hornecker · H. Madden · J. Venz...
4,"Wed, Nov 20, 2024",Abilene Christian,@,Kennesaw State,L,NaN,78,84,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
...,...,...,...,...,...,...,...,...,...
9781,"Thu, Feb 6, 2025",Youngstown State,@,Oakland,W,NaN,84,75,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9782,"Sat, Feb 8, 2025",Youngstown State,@,Detroit Mercy,W,NaN,87,72,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9783,"Wed, Feb 12, 2025",Youngstown State,NaN,Purdue Fort Wayne,W,NaN,93,71,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9784,"Sun, Feb 16, 2025",Youngstown State,@,Cleveland State,W,NaN,68,60,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9785,"Fri, Feb 21, 2025",Youngstown State,NaN,Milwaukee,L,NaN,74,84,C. Carroll · N. Galette · T. Harper · J. Maxey...

In [10]:
# remove games that have not been played
df = df.loc[(df['Result'].notna()) & (df['Result'] != 'W/L'), :].reset_index(drop=True)

# get overtime info
df['Overtime'] = df['Overtime'].notna().astype('int8')

# reformat result column
df['Result'] = df['Result'].str[:1].map({'W': 1, 'L': -1}).astype('int8')

# remove games with non-D1 opponents
df = df.loc[df['Opponent'].isin(df['Team']), :].reset_index(drop=True)

# remove games where starters are not listed
df = df.loc[df['Starters'].notna(), :].reset_index(drop=True)

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters
0,"Sat, Nov 9, 2024",Abilene Christian,NaN,Middle Tennessee,-1,0,56,79,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
1,"Sat, Nov 16, 2024",Abilene Christian,NaN,Texas State,1,0,72,60,N. DeGruy · C. Hornecker · H. Madden · J. Venz...
2,"Wed, Nov 20, 2024",Abilene Christian,@,Kennesaw State,-1,0,78,84,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
3,"Mon, Nov 25, 2024",Abilene Christian,N,Southern Mississippi,1,0,82,74,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
4,"Tue, Nov 26, 2024",Abilene Christian,@,Montana State,-1,0,59,85,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...
...,...,...,...,...,...,...,...,...,...
9251,"Thu, Feb 6, 2025",Youngstown State,@,Oakland,1,0,84,75,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9252,"Sat, Feb 8, 2025",Youngstown State,@,Detroit Mercy,1,0,87,72,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9253,"Wed, Feb 12, 2025",Youngstown State,NaN,Purdue Fort Wayne,1,0,93,71,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9254,"Sun, Feb 16, 2025",Youngstown State,@,Cleveland State,1,0,68,60,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9255,"Fri, Feb 21, 2025",Youngstown State,NaN,Milwaukee,-1,0,74,84,C. Carroll · N. Galette · T. Harper · J. Maxey...

Reformat location column for home/neutral/away

In [11]:
df['Location'] = df['Location'].map({np.NaN: 1, 'N': 0, '@': -1}).astype('int8')

df['Location']

0       1
1       1
2      -1
3       0
4      -1
       ..
9251   -1
9252   -1
9253    1
9254   -1
9255    1
Name: Location, Length: 9256, dtype: int8

Other general fixes

In [12]:
# fix dates
df['Date'] = pd.to_datetime(df['Date'])

# only include games before NCAA tournament
df = df.loc[df['Date'] <= cutoff_dates[season], :].reset_index(drop=True)

# fix column types
df.loc[:, df.columns.str.contains('Team ', regex=False)] = df.loc[:, df.columns.str.contains('Team ', regex=False)].astype('float64')
df.loc[:, df.columns.str.contains('Opponent ', regex=False)] = df.loc[:, df.columns.str.contains('Opponent ', regex=False)].astype('float64')

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters
0,2024-11-09,Abilene Christian,1,Middle Tennessee,-1,0,56,79,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
1,2024-11-16,Abilene Christian,1,Texas State,1,0,72,60,N. DeGruy · C. Hornecker · H. Madden · J. Venz...
2,2024-11-20,Abilene Christian,-1,Kennesaw State,-1,0,78,84,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
3,2024-11-25,Abilene Christian,0,Southern Mississippi,1,0,82,74,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...
4,2024-11-26,Abilene Christian,-1,Montana State,-1,0,59,85,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...
...,...,...,...,...,...,...,...,...,...
9251,2025-02-06,Youngstown State,-1,Oakland,1,0,84,75,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9252,2025-02-08,Youngstown State,-1,Detroit Mercy,1,0,87,72,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9253,2025-02-12,Youngstown State,1,Purdue Fort Wayne,1,0,93,71,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9254,2025-02-16,Youngstown State,-1,Cleveland State,1,0,68,60,C. Carroll · E. Farmer · N. Galette · T. Harpe...
9255,2025-02-21,Youngstown State,1,Milwaukee,-1,0,74,84,C. Carroll · N. Galette · T. Harper · J. Maxey...

Get opponent starters

In [13]:
# create a pseudo game ID that can be looked at from opponent's perspective to get opposing starters
key_to_starters = dict(zip(
    df['Date'].astype(str) + ' ' + df['Team'] + ' ' + df['Opponent'] + ' ' + df['Team Score'].astype(str) + ' ' + df['Opponent Score'].astype(str),
    df['Starters']
))

df['Opponent Starters'] = (df['Date'].astype(str) + ' ' + df['Opponent'] + ' ' + df['Team'] + ' ' + df['Opponent Score'].astype(str) + ' ' + df['Team Score'].astype(str)).map(key_to_starters)

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters,Opponent Starters
0,2024-11-09,Abilene Christian,1,Middle Tennessee,-1,0,56,79,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,J. Bufford · K. Lands · E. Mostafa · J. Porter...
1,2024-11-16,Abilene Christian,1,Texas State,1,0,72,60,N. DeGruy · C. Hornecker · H. Madden · J. Venz...,D. Drinnon · K. Gumbs · J. O'Garro · T. Pope ·...
2,2024-11-20,Abilene Christian,-1,Kennesaw State,-1,0,78,84,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,S. Cottle · B. Lue · J. Miller · A. Weir · A. ...
3,2024-11-25,Abilene Christian,0,Southern Mississippi,1,0,82,74,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,N. Alvarez · D. Harris · C. Montgomery · C. Wa...
4,2024-11-26,Abilene Christian,-1,Montana State,-1,0,59,85,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...,M. Agbonkpolo · P. McMahon · J. Mullins · T. P...
...,...,...,...,...,...,...,...,...,...,...
9251,2025-02-06,Youngstown State,-1,Oakland,1,0,84,75,C. Carroll · E. Farmer · N. Galette · T. Harpe...,D. Cole · I. Jones · A. Mukeba · T. Naivalurua...
9252,2025-02-08,Youngstown State,-1,Detroit Mercy,1,0,87,72,C. Carroll · E. Farmer · N. Galette · T. Harpe...,L. Geeter · N. Johnson · R. Kalambay · O. Love...
9253,2025-02-12,Youngstown State,1,Purdue Fort Wayne,1,0,93,71,C. Carroll · E. Farmer · N. Galette · T. Harpe...,R. Bello · J. Jackson · Q. Morton-Robertson · ...
9254,2025-02-16,Youngstown State,-1,Cleveland State,1,0,68,60,C. Carroll · E. Farmer · N. Galette · T. Harpe...,D. Arnett · E. Dibba · R. Robinson · T. Smith ...
9255,2025-02-21,Youngstown State,1,Milwaukee,-1,0,74,84,C. Carroll · N. Galette · T. Harper · J. Maxey...,D. Duffy · T. Fulks · A. McKee · K. Pullian · ...

In [14]:
df.loc[df['Opponent Starters'].isna(), :]

Empty DataFrame
Columns: [Date, Team, Location, Opponent, Result, Overtime, Team Score, Opponent Score, Starters, Opponent Starters]
Index: []

Split starters into separate columns

In [15]:
# rename starters column
df.rename(columns={'Starters': 'Team Starters'}, inplace=True)

df[[f'Team Starter {i}' for i in range(1, 6)]] = df['Team Starters'].str.split(r'\xa0· | \·', regex=True, expand=True)

for i in range(1, 6):
    df[f'Team Starter {i}'] = df['Team'] + ' ' + df[f'Team Starter {i}']

df[[f'Opponent Starter {i}' for i in range(1, 6)]] = df['Opponent Starters'].str.split(r'\xa0· | \·', regex=True, expand=True)

for i in range(1, 6):
    df[f'Opponent Starter {i}'] = df['Opponent'] + ' ' + df[f'Opponent Starter {i}']

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Team Starters,Opponent Starters,Team Starter 1,Team Starter 2,Team Starter 3,Team Starter 4,Team Starter 5,Opponent Starter 1,Opponent Starter 2,Opponent Starter 3,Opponent Starter 4,Opponent Starter 5
0,2024-11-09,Abilene Christian,1,Middle Tennessee,-1,0,56,79,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,J. Bufford · K. Lands · E. Mostafa · J. Porter...,Abilene Christian L. Bettiol,Abilene Christian N. DeGruy,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Middle Tennessee J. Bufford,Middle Tennessee K. Lands,Middle Tennessee E. Mostafa,Middle Tennessee J. Porter,Middle Tennessee C. Weston
1,2024-11-16,Abilene Christian,1,Texas State,1,0,72,60,N. DeGruy · C. Hornecker · H. Madden · J. Venz...,D. Drinnon · K. Gumbs · J. O'Garro · T. Pope ·...,Abilene Christian N. DeGruy,Abilene Christian C. Hornecker,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Texas State D. Drinnon,Texas State K. Gumbs,Texas State J. O'Garro,Texas State T. Pope,Texas State C. Turner
2,2024-11-20,Abilene Christian,-1,Kennesaw State,-1,0,78,84,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,S. Cottle · B. Lue · J. Miller · A. Weir · A. ...,Abilene Christian L. Bettiol,Abilene Christian N. DeGruy,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Kennesaw State S. Cottle,Kennesaw State B. Lue,Kennesaw State J. Miller,Kennesaw State A. Weir,Kennesaw State A. Wooley
3,2024-11-25,Abilene Christian,0,Southern Mississippi,1,0,82,74,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,N. Alvarez · D. Harris · C. Montgomery · C. Wa...,Abilene Christian L. Bettiol,Abilene Christian N. DeGruy,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Southern Mississippi N. Alvarez,Southern Mississippi D. Harris,Southern Mississippi C. Montgomery,Southern Mississippi C. Watson,Southern Mississippi L. Yat
4,2024-11-26,Abilene Christian,-1,Montana State,-1,0,59,85,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...,M. Agbonkpolo · P. McMahon · J. Mullins · T. P...,Abilene Christian L. Bettiol,Abilene Christian N. DeGruy,Abilene Christian B. Hubbard,Abilene Christian H. Madden,Abilene Christian Q. Williams,Montana State M. Agbonkpolo,Montana State P. McMahon,Montana State J. Mullins,Montana State T. Patterson,Montana State B. Walker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9251,2025-02-06,Youngstown State,-1,Oakland,1,0,84,75,C. Carroll · E. Farmer · N. Galette · T. Harpe...,D. Cole · I. Jones · A. Mukeba · T. Naivalurua...,Youngstown State C. Carroll,Youngstown State E. Farmer,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Oakland D. Cole,Oakland I. Jones,Oakland A. Mukeba,Oakland T. Naivalurua,Oakland J. Woodrich
9252,2025-02-08,Youngstown State,-1,Detroit Mercy,1,0,87,72,C. Carroll · E. Farmer · N. Galette · T. Harpe...,L. Geeter · N. Johnson · R. Kalambay · O. Love...,Youngstown State C. Carroll,Youngstown State E. Farmer,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Detroit Mercy L. Geeter,Detroit Mercy N. Johnson,Detroit Mercy R. Kalambay,Detroit Mercy O. Lovejoy,Detroit Mercy T. Nadeau
9253,2025-02-12,Youngstown State,1,Purdue Fort Wayne,1,0,93,71,C. Carroll · E. Farmer · N. Galette · T. Harpe...,R. Bello · J. Jackson · Q. Morton-Robertson · ...,Youngstown State C. Carroll,Youngstown State E. Farmer,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Purdue Fort Wayne R. Bello,Purdue Fort Wayne J. Jackson,Purdue Fort Wayne Q. Morton-Robertson,Purdue Fort Wayne E. Mulder,Purdue Fort Wayne M. Nelson
9254,2025-02-16,Youngstown State,-1,Cleveland State,1,0,68,60,C. Carroll · E. Farmer · N. Galette · T. Harpe...,D. Arnett · E. Dibba · R. Robinson · T. Smith ...,Youngstown State C. Carroll,Youngstown State E. Farmer,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Cleveland State D. Arnett,Cleveland State E. Dibba,Cleveland State R. Robinson,Cleveland State T. Smith,Cleveland State T. Staveskie
9255,2025-02-21,Youngstown State,1,Milwaukee,-1,0,74,84,C. Carroll · N. Galette · T. Harper · J. Maxey...,D. Duffy · T. Fulks · A. McKee · K. Pullian · ...,Youngstown State C. Carroll,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,Milwaukee D. Duffy,Milwaukee T. Fulks,Milwaukee A. McKee,Milwaukee K. Pullian,Milwaukee J. Stillwell

Set up adjusted Score Differential

In [16]:
blowout_threshold = 18  # adjusted score differential will only account up to this score difference

df['Score Differential'] = df['Team Score'] - df['Opponent Score']

df['Adjusted Score Differential'] = df['Score Differential'].abs()

df.loc[df['Adjusted Score Differential'] > blowout_threshold, 'Adjusted Score Differential'] = blowout_threshold

df['Adjusted Score Differential'] = df['Adjusted Score Differential']**(np.log(1.5)/np.log(blowout_threshold))

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Team Starters,Opponent Starters,...,Team Starter 3,Team Starter 4,Team Starter 5,Opponent Starter 1,Opponent Starter 2,Opponent Starter 3,Opponent Starter 4,Opponent Starter 5,Score Differential,Adjusted Score Differential
0,2024-11-09,Abilene Christian,1,Middle Tennessee,-1,0,56,79,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,J. Bufford · K. Lands · E. Mostafa · J. Porter...,...,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Middle Tennessee J. Bufford,Middle Tennessee K. Lands,Middle Tennessee E. Mostafa,Middle Tennessee J. Porter,Middle Tennessee C. Weston,-23,1.500000
1,2024-11-16,Abilene Christian,1,Texas State,1,0,72,60,N. DeGruy · C. Hornecker · H. Madden · J. Venz...,D. Drinnon · K. Gumbs · J. O'Garro · T. Pope ·...,...,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Texas State D. Drinnon,Texas State K. Gumbs,Texas State J. O'Garro,Texas State T. Pope,Texas State C. Turner,12,1.417062
2,2024-11-20,Abilene Christian,-1,Kennesaw State,-1,0,78,84,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,S. Cottle · B. Lue · J. Miller · A. Weir · A. ...,...,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Kennesaw State S. Cottle,Kennesaw State B. Lue,Kennesaw State J. Miller,Kennesaw State A. Weir,Kennesaw State A. Wooley,-6,1.285760
3,2024-11-25,Abilene Christian,0,Southern Mississippi,1,0,82,74,L. Bettiol · N. DeGruy · H. Madden · J. Venzan...,N. Alvarez · D. Harris · C. Montgomery · C. Wa...,...,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian Q. Williams,Southern Mississippi N. Alvarez,Southern Mississippi D. Harris,Southern Mississippi C. Montgomery,Southern Mississippi C. Watson,Southern Mississippi L. Yat,8,1.338710
4,2024-11-26,Abilene Christian,-1,Montana State,-1,0,59,85,L. Bettiol · N. DeGruy · B. Hubbard · H. Madde...,M. Agbonkpolo · P. McMahon · J. Mullins · T. P...,...,Abilene Christian B. Hubbard,Abilene Christian H. Madden,Abilene Christian Q. Williams,Montana State M. Agbonkpolo,Montana State P. McMahon,Montana State J. Mullins,Montana State T. Patterson,Montana State B. Walker,-26,1.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9251,2025-02-06,Youngstown State,-1,Oakland,1,0,84,75,C. Carroll · E. Farmer · N. Galette · T. Harpe...,D. Cole · I. Jones · A. Mukeba · T. Naivalurua...,...,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Oakland D. Cole,Oakland I. Jones,Oakland A. Mukeba,Oakland T. Naivalurua,Oakland J. Woodrich,9,1.361013
9252,2025-02-08,Youngstown State,-1,Detroit Mercy,1,0,87,72,C. Carroll · E. Farmer · N. Galette · T. Harpe...,L. Geeter · N. Johnson · R. Kalambay · O. Love...,...,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Detroit Mercy L. Geeter,Detroit Mercy N. Johnson,Detroit Mercy R. Kalambay,Detroit Mercy O. Lovejoy,Detroit Mercy T. Nadeau,15,1.462122
9253,2025-02-12,Youngstown State,1,Purdue Fort Wayne,1,0,93,71,C. Carroll · E. Farmer · N. Galette · T. Harpe...,R. Bello · J. Jackson · Q. Morton-Robertson · ...,...,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Purdue Fort Wayne R. Bello,Purdue Fort Wayne J. Jackson,Purdue Fort Wayne Q. Morton-Robertson,Purdue Fort Wayne E. Mulder,Purdue Fort Wayne M. Nelson,22,1.500000
9254,2025-02-16,Youngstown State,-1,Cleveland State,1,0,68,60,C. Carroll · E. Farmer · N. Galette · T. Harpe...,D. Arnett · E. Dibba · R. Robinson · T. Smith ...,...,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Cleveland State D. Arnett,Cleveland State E. Dibba,Cleveland State R. Robinson,Cleveland State T. Smith,Cleveland State T. Staveskie,8,1.338710
9255,2025-02-21,Youngstown State,1,Milwaukee,-1,0,74,84,C. Carroll · N. Galette · T. Harper · J. Maxey...,D. Duffy · T. Fulks · A. McKee · K. Pullian · ...,...,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,Milwaukee D. Duffy,Milwaukee T. Fulks,Milwaukee A. McKee,Milwaukee K. Pullian,Milwaukee J. Stillwell,-10,1.381279

### Model Building

##### Starters Ratings

Unfortunately, there is no way to differentiate between 2 starters with the same name on the same team. In such circumstances, we double count the entity.

In [17]:
X = (
    pd.get_dummies(df['Team Starter 1']).astype('int8')
).add(
    pd.get_dummies(df['Team Starter 2']).astype('int8'), fill_value=0
).add(
    pd.get_dummies(df['Team Starter 3']).astype('int8'), fill_value=0 
).add(
    pd.get_dummies(df['Team Starter 4']).astype('int8'), fill_value=0 
).add(
    pd.get_dummies(df['Team Starter 5']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 1']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 2']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 3']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 4']).astype('int8'), fill_value=0 
).add(
    -pd.get_dummies(df['Opponent Starter 5']).astype('int8'), fill_value=0 
)

X['Home Field Advantage'] = df['Location'].copy()

X

C:\Users\mhugh\AppData\Local\Temp\ipykernel_21188\563957636.py:23: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  X['Home Field Advantage'] = df['Location'].copy()

,Abilene Christian B. Hubbard,Abilene Christian C. Hornecker,Abilene Christian H. Madden,Abilene Christian J. Venzant,Abilene Christian L. Bettiol,Abilene Christian M. Hill,Abilene Christian N. DeGruy,Abilene Christian Q. Williams,Abilene Christian R. Smith,Abilene Christian Y. Rivera,...,Yale Y. Gharram,Youngstown State C. Carroll,Youngstown State E. Farmer,Youngstown State G. Dynes,Youngstown State J. Maxey,Youngstown State J. Nelson,Youngstown State N. Galette,Youngstown State S. Uijtendaal,Youngstown State T. Harper,Home Field Advantage
0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
1,0.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1
3,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
4,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9251,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,-1
9252,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,-1
9253,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1
9254,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,-1
9255,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1

In [18]:
from sklearn.model_selection import GroupKFold

def get_gkf_data(X, y, w, groups, cv=3):
    """
    Converts training data to list of folds
    """
    np.random.seed(22)
    gkf = GroupKFold(n_splits=cv)

    data = []
    for train_index, test_index in gkf.split(X, y, groups=groups):
        X_train = X[train_index]
        X_test = X[test_index]

        y_train = y[train_index]
        y_test = y[test_index]

        # sample weights
        w_train = w[train_index]

        data.append((X_train, X_test, y_train, y_test, w_train))

    return data

cv_data = get_gkf_data(X.to_numpy(), df['Result'].to_numpy(), df[['Adjusted Score Differential']].to_numpy(), df['Date'].to_numpy())

len(cv_data)

3

In [19]:
from sklearn.metrics import log_loss
from sklearn.linear_model import LogisticRegression
import warnings
import optuna

from sklearn.preprocessing import MinMaxScaler
optuna.logging.set_verbosity(optuna.logging.WARNING)

def objective(trial, cv_data=cv_data):
    # model tuning
    C = trial.suggest_float('C', 0.1, 10, log=True)
    mod = LogisticRegression(penalty='l2', C=C, fit_intercept=False)
    minimum = trial.suggest_float('minimum', 0.1, 1.0, step=0.1)
    maximum = trial.suggest_float('maximum', 1.0, 8.0, step=0.5)
    if minimum >= maximum:
        maximum = minimum + 0.0001

    # cross validation
    y_actuals = []
    y_preds = []
    for X_train, X_test, y_train, y_test, w_train in cv_data:
        y_actuals.append(y_test)

        weights = MinMaxScaler(feature_range=(minimum, maximum)).fit_transform(w_train).reshape(-1)

        with warnings.catch_warnings():
            warnings.filterwarnings('ignore')  # prevent convergence warnings
            mod.fit(X_train, y_train, sample_weight=weights)

        y_preds.append(mod.predict_proba(X_test)[:, 1])

    return log_loss(np.hstack(y_actuals), np.hstack(y_preds))

study = optuna.create_study(direction='minimize', sampler=optuna.samplers.TPESampler(seed=22))
study.optimize(objective, n_trials=100, show_progress_bar=True)

study.best_params

  0%|          | 0/100 [00:00<?, ?it/s]

{'C': 0.1732917297270907, 'minimum': 0.4, 'maximum': 1.5}

In [20]:
optuna.importance.get_param_importances(study)

{'C': 0.8032264690388522,
 'maximum': 0.1617201781434899,
 'minimum': 0.03505335281765791}

In [21]:
minimum = study.best_params['minimum']
maximum = study.best_params['maximum']

if minimum >= maximum:
        maximum = minimum + 0.0001

weight = MinMaxScaler(
    feature_range=(minimum, maximum)
).fit_transform(df[['Adjusted Score Differential']]).reshape(-1)

mod = LogisticRegression(penalty='l2', C=study.best_params['C'], fit_intercept=False)

mod.fit(X, df['Result'], sample_weight=weight)

df_ratings = pd.DataFrame(
    {
        'Starter': X.columns,
        'Rating': mod.coef_[0]
    }
).sort_values(by=['Rating'], ascending=False, ignore_index=True)

df_ratings_display = df_ratings.loc[df_ratings['Starter'] != 'Home Field Advantage', :].reset_index(drop=True)
df_ratings_display.index += 1

df_ratings_display.head(25)

                      Starter    Rating
1           Houston J. Tugler  0.836506
2          Auburn D. Cardwell  0.824883
3             Auburn D. Jones  0.824883
4        Arizona A. Dell'Orso  0.822138
5    Iowa State M. Momcilovic  0.783961
6               Duke S. James  0.737114
7            Drake I. Jackson  0.725402
8          Florida W. Richard  0.720603
9         Florida R. Chinyelu  0.720603
10            Auburn M. Kelly  0.717288
11   New Mexico F. Borvicanin  0.707936
12         Florida W. Clayton  0.685095
13    Wichita State B. Cortes  0.680640
14   St. John's (NY) A. Scott  0.678743
15   George Mason Z. Anderson  0.666079
16       Texas A&M H. Coleman  0.664557
17   Michigan State J. Kohler  0.664006
18          Florida A. Condon  0.660175
19            Akron S. Wilson  0.657442
20       Virginia B. Buchanan  0.656315
21  Pittsburgh G. Diaz Graham  0.650718
22        Texas A&M Z. Phelps  0.649620
23      Louisville T. Edwards  0.648978
24  Brown M. Wrisby-Jefferson  0.646065
25           UC Irvine M. Che  0.644541

### Miscellaneous

##### Save Rankings

Get last available lineup for each team

In [22]:
starter_to_rating = dict(zip(df_ratings_display['Starter'], df_ratings_display['Rating']))

len(starter_to_rating)

3149

In [23]:
df_last_starters = df.sort_values(by=['Date']).groupby(['Team']).tail(1).reset_index(drop=True)[['Team'] + [f'Team Starter {i}' for i in range(1, 6)]]

df_last_starters

,Team,Team Starter 1,Team Starter 2,Team Starter 3,Team Starter 4,Team Starter 5
0,Indiana,Indiana O. Ballo,Indiana T. Galloway,Indiana L. Goode,Indiana A. Leal,Indiana M. Mgbako
1,Saint Louis,Saint Louis K. Anya,Saint Louis R. Avila,Saint Louis G. Jimerson,Saint Louis K. Johnson,Saint Louis I. Swope
2,Hampton,Hampton G. Beale,Hampton N. Farrakhan,Hampton D. Johnson,Hampton X. Long,Hampton K. Mullen
3,Wake Forest,Wake Forest J. Harris,Wake Forest T. Johnson,Wake Forest E. Reid,Wake Forest H. Sallis,Wake Forest T. Spillers
4,San Diego,San Diego N. Beniwal,San Diego D. Dahlke,San Diego S. Jamerson,San Diego B. Pierre,San Diego S. Trouet
...,...,...,...,...,...,...
359,Yale,Yale S. Aletan,Yale B. Mbeng,Yale J. Poulakidas,Yale C. Simmons,Yale N. Townsend
360,Princeton,Princeton M. Abdullahi,Princeton C. Happy,Princeton X. Lee,Princeton B. Peters,Princeton C. Pierce
361,Bowling Green State,Bowling Green State D. Butler,Bowling Green State J. Felt,Bowling Green State B. Green,Bowling Green State D. Humphrey,Bowling Green State M. Johnson
362,Cornell,Cornell J. Fiegen,Cornell C. Noard,Cornell A. Okereke,Cornell G. Ragland,Cornell N. Williams
363,Youngstown State,Youngstown State C. Carroll,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal

In [24]:
for i in range(1, 6):
    df_last_starters[f'Team Starter {i} Rating'] = df_last_starters[f'Team Starter {i}'].map(starter_to_rating)

df_last_starters['Rating'] = df_last_starters[[f'Team Starter {i} Rating' for i in range(1, 6)]].mean(axis=1)

df_last_starters

,Team,Team Starter 1,Team Starter 2,Team Starter 3,Team Starter 4,Team Starter 5,Team Starter 1 Rating,Team Starter 2 Rating,Team Starter 3 Rating,Team Starter 4 Rating,Team Starter 5 Rating,Rating
0,Indiana,Indiana O. Ballo,Indiana T. Galloway,Indiana L. Goode,Indiana A. Leal,Indiana M. Mgbako,0.171283,0.504755,0.113006,-0.116893,0.294211,0.193272
1,Saint Louis,Saint Louis K. Anya,Saint Louis R. Avila,Saint Louis G. Jimerson,Saint Louis K. Johnson,Saint Louis I. Swope,0.125863,0.263080,0.125863,0.039886,0.125863,0.136111
2,Hampton,Hampton G. Beale,Hampton N. Farrakhan,Hampton D. Johnson,Hampton X. Long,Hampton K. Mullen,0.124078,0.275045,-0.090825,0.185451,0.095665,0.117883
3,Wake Forest,Wake Forest J. Harris,Wake Forest T. Johnson,Wake Forest E. Reid,Wake Forest H. Sallis,Wake Forest T. Spillers,0.207898,0.376248,0.404583,0.430481,0.430481,0.369938
4,San Diego,San Diego N. Beniwal,San Diego D. Dahlke,San Diego S. Jamerson,San Diego B. Pierre,San Diego S. Trouet,-0.066636,-0.103590,-0.817465,-0.109995,-0.376684,-0.294874
...,...,...,...,...,...,...,...,...,...,...,...,...
359,Yale,Yale S. Aletan,Yale B. Mbeng,Yale J. Poulakidas,Yale C. Simmons,Yale N. Townsend,0.292248,0.292248,0.175991,0.599962,0.292248,0.330540
360,Princeton,Princeton M. Abdullahi,Princeton C. Happy,Princeton X. Lee,Princeton B. Peters,Princeton C. Pierce,0.121823,0.064509,0.169483,-0.127434,0.169483,0.079573
361,Bowling Green State,Bowling Green State D. Butler,Bowling Green State J. Felt,Bowling Green State B. Green,Bowling Green State D. Humphrey,Bowling Green State M. Johnson,-0.115462,-0.066367,0.100016,0.142471,-0.332001,-0.054269
362,Cornell,Cornell J. Fiegen,Cornell C. Noard,Cornell A. Okereke,Cornell G. Ragland,Cornell N. Williams,0.083494,0.083494,0.083494,0.083494,0.083494,0.083494
363,Youngstown State,Youngstown State C. Carroll,Youngstown State N. Galette,Youngstown State T. Harper,Youngstown State J. Maxey,Youngstown State S. Uijtendaal,0.537031,-0.038903,-0.038903,0.042873,-0.192346,0.061950

In [25]:
df_sheet = df_last_starters[['Team', 'Rating']].copy().sort_values(by=['Rating'], ascending=False, ignore_index=True)

df_sheet.head(25)

                     Team    Rating
0                  Auburn  0.658849
1                    Duke  0.644413
2                 Houston  0.608796
3                 Florida  0.546858
4               Tennessee  0.543321
5          Michigan State  0.523251
6              Iowa State  0.517616
7               Wisconsin  0.498081
8                 Alabama  0.495080
9                 Clemson  0.494572
10      Saint Mary's (CA)  0.493931
11                  Drake  0.491126
12               Missouri  0.479058
13                 Purdue  0.476209
14      Mississippi State  0.471054
15               Michigan  0.461927
16                Arizona  0.456406
17             Texas Tech  0.453406
18                Memphis  0.452496
19              Texas A&M  0.447597
20             Louisville  0.440550
21        St. John's (NY)  0.436051
22               Maryland  0.434777
23  Virginia Commonwealth  0.434659
24                Gonzaga  0.427021

In [26]:
df_sheet.to_parquet(f'../data/preprocessed/starters/starters_{season}.parquet', index=False)
df.to_parquet(f'../data/unprocessed/sports_reference_starters/sports_reference_starters_{season}.parquet', index=False)

'Done'

'Done'