# Women's Starters

Get ratings of each team's starters in a given year. This file needs to be ran for every relevant year.

### Web Scraping

Fair warning that this program unfortunately takes a very long time to run due to web scraping limits set by Sports Reference

In [1]:
import pandas as pd
import numpy as np
import time

season = 2012

df_active_teams = pd.read_html('https://www.sports-reference.com/cbb/schools/index.html')[0]
time.sleep(2)

df_active_teams = df_active_teams.loc[~df_active_teams['School'].isin([np.NaN, 'School']), :].reset_index(drop=True)

df_active_teams['From'] = pd.to_numeric(df_active_teams['From'], errors='coerce')
df_active_teams['To'] = pd.to_numeric(df_active_teams['To'], errors='coerce')

df_active_teams = df_active_teams.loc[(df_active_teams['To'] >= season) & (df_active_teams['From'] <= season), :].reset_index(drop=True)

if season == 2021:  # if 2021, remove ivy league because they cancelled their season in 2021
    df_active_teams = df_active_teams.loc[
        ~df_active_teams['School'].isin(['Princeton', 'Harvard', 'Yale', 'Pennsylvania', 'Brown', 'Columbia', 'Cornell', 'Dartmouth']),
        :
    ].reset_index(drop=True)

df_active_teams

,Rk,School,"City, State",From,To,Yrs,G,W,L,W-L%,SRS,SOS,AP,CREG,CTRN,NCAA,FF,NC
0,1,Abilene Christian,"Abilene, Texas",1971,2025,15,452,241,211,.533,-7.59,-5.36,0,0,2,2,0,0
1,2,Air Force,"USAF Academy, Colorado",1958,2025,68,1873,797,1076,.426,-2.86,1.37,0,1,0,4,0,0
2,3,Akron,"Akron, Ohio",1902,2025,74,1748,1051,697,.601,0.07,-1.60,0,9,6,6,0,0
3,4,Alabama,"Tuscaloosa, Alabama",1913,2025,112,2926,1817,1108,.621,8.18,5.06,18,10,9,25,1,0
4,5,Alabama A&M,"Normal, Alabama",2000,2025,26,752,287,465,.382,-16.72,-11.01,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
342,489,Wright State,"Dayton, Ohio",1988,2025,38,1160,646,514,.557,-1.41,-2.60,0,4,4,4,0,0
343,490,Wyoming,"Laramie, Wyoming",1905,2025,120,2910,1622,1288,.557,2.69,2.76,4,21,3,16,1,1
344,491,Xavier,"Cincinnati, Ohio",1920,2025,104,2727,1631,1096,.598,6.20,4.05,13,18,9,29,0,0
345,492,Yale,"New Haven, Connecticut",1896,2025,129,3111,1585,1524,.510,-5.81,-4.43,1,16,3,7,0,0
346,493,Youngstown State,"Youngstown, Ohio",1948,2025,45,1323,549,774,.415,-7.88,-3.56,0,1,0,0,0,0

Heads up that there is an issue with 2023. Some games from UAB and Florida international have either more or less than 5 starters listed. I manually removed those games from this analysis.

In [2]:
from datetime import datetime

cutoff_dates = {
    2008: datetime(2008, 3, 21),
    2009: datetime(2009, 3, 20),
    2010: datetime(2010, 3, 19),
    2011: datetime(2011, 3, 18),
    2012: datetime(2012, 3, 16),
    2013: datetime(2013, 3, 22),
    2014: datetime(2014, 3, 21),
    2015: datetime(2015, 3, 19),
    2016: datetime(2016, 3, 17),
    2017: datetime(2017, 3, 16),
    2018: datetime(2018, 3, 15),
    2019: datetime(2019, 3, 21),
    2020: datetime(2020, 3, 13),  # cancelled
    2021: datetime(2021, 3, 24),
    2022: datetime(2022, 3, 17),
    2023: datetime(2023, 3, 16),
    2024: datetime(2024, 3, 21),
    2025: datetime(2025, 3, 20),
}

cutoff_dates[season]

datetime.datetime(2012, 3, 16, 0, 0)

Get school names used in Sports Reference URL

In [3]:
df_active_teams['URL School'] = df_active_teams['School']

# hard code some schools that cause issues
df_active_teams.loc[df_active_teams['School'] == 'Bowling Green', 'URL School'] = 'Bowling Green State'
df_active_teams.loc[df_active_teams['School'] == 'BYU', 'URL School'] = 'Brigham Young'
df_active_teams.loc[df_active_teams['School'] == 'Louisiana', 'URL School'] = 'Louisiana Lafayette'
df_active_teams.loc[df_active_teams['School'] == 'LSU', 'URL School'] = 'Louisiana State'
df_active_teams.loc[df_active_teams['School'] == 'Ole Miss', 'URL School'] = 'Mississippi'
df_active_teams.loc[df_active_teams['School'] == 'Pitt', 'URL School'] = 'Pittsburgh'
df_active_teams.loc[df_active_teams['School'] == 'SMU', 'URL School'] = 'Southern Methodist'
df_active_teams.loc[df_active_teams['School'] == 'UAB', 'URL School'] = 'Alabama Birmingham'
df_active_teams.loc[df_active_teams['School'] == 'UCF', 'URL School'] = 'Central Florida'
df_active_teams.loc[df_active_teams['School'] == 'USC', 'URL School'] = 'Southern California'
df_active_teams.loc[df_active_teams['School'] == 'UTEP', 'URL School'] = 'Texas El Paso'
df_active_teams.loc[df_active_teams['School'] == 'UTSA', 'URL School'] = 'Texas San Antonio'
df_active_teams.loc[df_active_teams['School'] == 'Sam Houston', 'URL School'] = 'Sam Houston State'
df_active_teams.loc[df_active_teams['School'] == 'Houston Christian', 'URL School'] = 'Houston Baptist'
df_active_teams.loc[df_active_teams['School'] == 'Kansas City', 'URL School'] = 'Missouri Kansas City'
df_active_teams.loc[df_active_teams['School'] == 'Little Rock', 'URL School'] = 'Arkansas Little Rock'
df_active_teams.loc[df_active_teams['School'] == 'NC State', 'URL School'] = 'North Carolina State'
df_active_teams.loc[df_active_teams['School'] == 'Omaha', 'URL School'] = 'Nebraska Omaha'
df_active_teams.loc[df_active_teams['School'] == 'Purdue Fort Wayne', 'URL School'] = 'IPFW'
df_active_teams.loc[df_active_teams['School'] == 'TCU', 'URL School'] = 'Texas Christian'
df_active_teams.loc[df_active_teams['School'] == 'Texas-Rio Grande Valley', 'URL School'] = 'Texas Pan American'
df_active_teams.loc[df_active_teams['School'] == 'The Citadel', 'URL School'] = 'Citadel'
df_active_teams.loc[df_active_teams['School'] == 'Utah Tech', 'URL School'] = 'Dixie State'
df_active_teams.loc[df_active_teams['School'] == 'St. Thomas', 'URL School'] = 'St. Thomas MN'
df_active_teams.loc[df_active_teams['School'] == 'UC Berkley', 'URL School'] = 'California'
df_active_teams.loc[df_active_teams['School'] == 'UT Arlington', 'URL School'] = 'Texas Arlington'
df_active_teams.loc[df_active_teams['School'] == 'FDU', 'URL School'] = 'Fairleigh Dickinson'
df_active_teams.loc[df_active_teams['School'] == 'Hartford Hawks', 'URL School'] = 'Hartford'
df_active_teams.loc[df_active_teams['School'] == 'Savannah State Tigers', 'URL School'] = 'Savannah State'
df_active_teams.loc[df_active_teams['School'] == 'St. Francis (NY) Terriers', 'URL School'] = 'St. Francis (NY)'
df_active_teams.loc[df_active_teams['School'] == 'East Texas A&M', 'URL School'] = 'Texas A&M Commerce'
df_active_teams.loc[df_active_teams['School'] == 'IU Indy', 'URL School'] = 'IUPUI'

df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UC\s', 'California ', regex=True)
df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UNC\s', 'North Carolina ', regex=True)

In [4]:
urls = (
    'https://www.sports-reference.com/cbb/schools/' +
    df_active_teams['URL School'].str.replace(' ', '-', regex=False).str.replace('[)(&.\']', '', regex=True).str.replace('--', '-', regex=False).str.lower() +
    '/women/' + str(season) +
    '-starters.html'
)

urls

0      https://www.sports-reference.com/cbb/schools/a...
1      https://www.sports-reference.com/cbb/schools/a...
2      https://www.sports-reference.com/cbb/schools/a...
3      https://www.sports-reference.com/cbb/schools/a...
4      https://www.sports-reference.com/cbb/schools/a...
                             ...
342    https://www.sports-reference.com/cbb/schools/w...
343    https://www.sports-reference.com/cbb/schools/w...
344    https://www.sports-reference.com/cbb/schools/x...
345    https://www.sports-reference.com/cbb/schools/y...
346    https://www.sports-reference.com/cbb/schools/y...
Name: URL School, Length: 347, dtype: object

In [5]:
from urllib.error import HTTPError
from tqdm.notebook import tqdm

problems = []

l = []
loop = tqdm(
    np.array((df_active_teams['School'], urls)).transpose(),  # get both school and url into loop iteration
    bar_format='{bar}{percentage:3.0f}%{r_bar}   {desc}'  # make the description not affect bar location
)

for (school, url) in loop:
  try:
    loop.set_description(f'{school}')
    # print(f'{i:03d}: {url}')
    df_team_season = pd.read_html(url)[0]  # starters should be initial table on site
    time.sleep(2)
    
    df_team_season.insert(4, 'Team', school)
    l.append(df_team_season)
  except HTTPError as e:
    if e.code == 404:
      print(f'{url} | {e}')
      time.sleep(2)
    else:
      print(f'{url} | {e}')
      break

df = pd.concat(l, ignore_index=True)

df

            0%| 0/347 [00:00<?, ?it/s]

https://www.sports-reference.com/cbb/schools/abilene-christian/women/2012-starters.html | HTTP Error 404: Not Found
https://www.sports-reference.com/cbb/schools/longwood/women/2012-starters.html | HTTP Error 404: Not Found
https://www.sports-reference.com/cbb/schools/massachusetts-lowell/women/2012-starters.html | HTTP Error 404: Not Found
https://www.sports-reference.com/cbb/schools/citadel/women/2012-starters.html | HTTP Error 404: Not Found
https://www.sports-reference.com/cbb/schools/virginia-military-institute/women/2012-starters.html | HTTP Error 404: Not Found

,G,Date,Unnamed: 2,Unnamed: 3,Team,Unnamed: 4,Opponent,Unnamed: 6,OT,Tm,Opp,W,L,Unnamed: 12
0,1,"Fri, Nov 11, 2011",NaN,Box Score,Air Force,@,Lipscomb,W,NaN,68,59,1,0,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...
1,2,"Sun, Nov 13, 2011",NaN,Box Score,Air Force,@,Tennessee-Martin,L,NaN,60,84,1,1,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...
2,3,"Thu, Nov 17, 2011",NaN,Box Score,Air Force,NaN,Denver,L,NaN,52,54,1,2,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...
3,4,"Sat, Nov 19, 2011",NaN,Box Score,Air Force,@,Texas Southern,W,NaN,64,54,2,2,D. James · A. Leipprandt · C. Medina · M. O'Ne...
4,5,"Mon, Nov 21, 2011",NaN,Box Score,Air Force,@,Texas State,W,NaN,77,69,3,2,D. James · A. Leipprandt · M. O'Neil · D. Sorr...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10694,26,"Sat, Feb 18, 2012",NaN,Box Score,Youngstown State,NaN,Green Bay,L,OT,72,77,10,16,B. Brown · K. Fickiesen · T. Jones · K. Middle...
10695,27,"Thu, Feb 23, 2012",NaN,Box Score,Youngstown State,@,Wright State,L,NaN,62,84,10,17,B. Brown · K. Fickiesen · T. Jones · K. Middle...
10696,28,"Sat, Feb 25, 2012",NaN,Box Score,Youngstown State,@,Detroit Mercy,L,NaN,64,67,10,18,B. Brown · K. Fickiesen · L. Hornberger · K. M...
10697,29,"Sat, Mar 3, 2012",NaN,Box Score,Youngstown State,@,Cleveland State,L,NaN,69,79,10,19,B. Brown · K. Fickiesen · K. Middlebrooks · H....
10698,30,"Mon, Mar 5, 2012",NaN,Box Score,Youngstown State,@,Cleveland State,L,NaN,56,59,10,20,B. Brown · K. Fickiesen · K. Middlebrooks · H....

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10699 entries, 0 to 10698
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   G            10699 non-null  int64
 1   Date         10699 non-null  object
 2   Unnamed: 2   0 non-null      float64
 3   Unnamed: 3   10697 non-null  object
 4   Team         10699 non-null  object
 5   Unnamed: 4   5309 non-null   object
 6   Opponent     10699 non-null  object
 7   Unnamed: 6   10699 non-null  object
 8   OT           448 non-null    object
 9   Tm           10699 non-null  int64
 10  Opp          10699 non-null  int64
 11  W            10699 non-null  int64
 12  L            10699 non-null  int64
 13  Unnamed: 12  10696 non-null  object
dtypes: float64(1), int64(5), object(8)
memory usage: 1.1+ MB

### Data Setup

In [7]:
temp = df.copy()

In [8]:
df = temp.copy()

Fix column names and drop useless columns

In [9]:
df.drop(columns=['G', 'Unnamed: 2', 'Unnamed: 3', 'W', 'L'], inplace=True)

df.columns = ['Date', 'Team', 'Location', 'Opponent', 'Result', 'Overtime', 'Team Score', 'Opponent Score', 'Starters']

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters
0,"Fri, Nov 11, 2011",Air Force,@,Lipscomb,W,NaN,68,59,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...
1,"Sun, Nov 13, 2011",Air Force,@,Tennessee-Martin,L,NaN,60,84,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...
2,"Thu, Nov 17, 2011",Air Force,NaN,Denver,L,NaN,52,54,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...
3,"Sat, Nov 19, 2011",Air Force,@,Texas Southern,W,NaN,64,54,D. James · A. Leipprandt · C. Medina · M. O'Ne...
4,"Mon, Nov 21, 2011",Air Force,@,Texas State,W,NaN,77,69,D. James · A. Leipprandt · M. O'Neil · D. Sorr...
...,...,...,...,...,...,...,...,...,...
10694,"Sat, Feb 18, 2012",Youngstown State,NaN,Green Bay,L,OT,72,77,B. Brown · K. Fickiesen · T. Jones · K. Middle...
10695,"Thu, Feb 23, 2012",Youngstown State,@,Wright State,L,NaN,62,84,B. Brown · K. Fickiesen · T. Jones · K. Middle...
10696,"Sat, Feb 25, 2012",Youngstown State,@,Detroit Mercy,L,NaN,64,67,B. Brown · K. Fickiesen · L. Hornberger · K. M...
10697,"Sat, Mar 3, 2012",Youngstown State,@,Cleveland State,L,NaN,69,79,B. Brown · K. Fickiesen · K. Middlebrooks · H....
10698,"Mon, Mar 5, 2012",Youngstown State,@,Cleveland State,L,NaN,56,59,B. Brown · K. Fickiesen · K. Middlebrooks · H....

In [10]:
# remove games that have not been played
df = df.loc[(df['Result'].notna()) & (df['Result'] != 'W/L'), :].reset_index(drop=True)

# get overtime info
df['Overtime'] = df['Overtime'].notna().astype('int8')

# reformat result column
df['Result'] = df['Result'].str[:1].map({'W': 1, 'L': -1}).astype('int8')

# remove games with non-D1 opponents
df = df.loc[df['Opponent'].isin(df['Team']), :].reset_index(drop=True)

# remove games where starters are not listed
df = df.loc[df['Starters'].notna(), :].reset_index(drop=True)

df

,Date,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters
0,"Fri, Nov 11, 2011",Air Force,@,Lipscomb,1,0,68,59,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...
1,"Sun, Nov 13, 2011",Air Force,@,Tennessee-Martin,-1,0,60,84,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...
2,"Thu, Nov 17, 2011",Air Force,NaN,Denver,-1,0,52,54,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...
3,"Sat, Nov 19, 2011",Air Force,@,Texas Southern,1,0,64,54,D. James · A. Leipprandt · C. Medina · M. O'Ne...
4,"Mon, Nov 21, 2011",Air Force,@,Texas State,1,0,77,69,D. James · A. Leipprandt · M. O'Neil · D. Sorr...
...,...,...,...,...,...,...,...,...,...
10365,"Sat, Feb 18, 2012",Youngstown State,NaN,Green Bay,-1,1,72,77,B. Brown · K. Fickiesen · T. Jones · K. Middle...
10366,"Thu, Feb 23, 2012",Youngstown State,@,Wright State,-1,0,62,84,B. Brown · K. Fickiesen · T. Jones · K. Middle...
10367,"Sat, Feb 25, 2012",Youngstown State,@,Detroit Mercy,-1,0,64,67,B. Brown · K. Fickiesen · L. Hornberger · K. M...
10368,"Sat, Mar 3, 2012",Youngstown State,@,Cleveland State,-1,0,69,79,B. Brown · K. Fickiesen · K. Middlebrooks · H....
10369,"Mon, Mar 5, 2012",Youngstown State,@,Cleveland State,-1,0,56,59,B. Brown · K. Fickiesen · K. Middlebrooks · H....

Reformat location column for home/neutral/away

In [11]:
df['Location'] = df['Location'].map({np.NaN: 1, 'N': 0, '@': -1}).astype('int8')

df['Location']

0       -1
1       -1
2        1
3       -1
4       -1
        ..
10365    1
10366   -1
10367   -1
10368   -1
10369   -1
Name: Location, Length: 10370, dtype: int8

Other general fixes

In [12]:
# fix dates
df['Date'] = pd.to_datetime(df['Date'])

# specify before and after NCAA tournament
df.insert(df.columns.get_loc('Date') + 1, 'NCAA Tournament', (df['Date'] > cutoff_dates[season]).astype(int))

# for starters, we only look at pre-tournament games as we are not looking at past years
df = df.loc[df['NCAA Tournament'] == 0, :].reset_index(drop=True)

# fix column types
df.loc[:, df.columns.str.contains('Team ', regex=False)] = df.loc[:, df.columns.str.contains('Team ', regex=False)].astype('float64')
df.loc[:, df.columns.str.contains('Opponent ', regex=False)] = df.loc[:, df.columns.str.contains('Opponent ', regex=False)].astype('float64')

df

,Date,NCAA Tournament,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters
0,2011-11-11,0,Air Force,-1,Lipscomb,1,0,68,59,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...
1,2011-11-13,0,Air Force,-1,Tennessee-Martin,-1,0,60,84,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...
2,2011-11-17,0,Air Force,1,Denver,-1,0,52,54,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...
3,2011-11-19,0,Air Force,-1,Texas Southern,1,0,64,54,D. James · A. Leipprandt · C. Medina · M. O'Ne...
4,2011-11-21,0,Air Force,-1,Texas State,1,0,77,69,D. James · A. Leipprandt · M. O'Neil · D. Sorr...
...,...,...,...,...,...,...,...,...,...,...
10163,2012-02-18,0,Youngstown State,1,Green Bay,-1,1,72,77,B. Brown · K. Fickiesen · T. Jones · K. Middle...
10164,2012-02-23,0,Youngstown State,-1,Wright State,-1,0,62,84,B. Brown · K. Fickiesen · T. Jones · K. Middle...
10165,2012-02-25,0,Youngstown State,-1,Detroit Mercy,-1,0,64,67,B. Brown · K. Fickiesen · L. Hornberger · K. M...
10166,2012-03-03,0,Youngstown State,-1,Cleveland State,-1,0,69,79,B. Brown · K. Fickiesen · K. Middlebrooks · H....
10167,2012-03-05,0,Youngstown State,-1,Cleveland State,-1,0,56,59,B. Brown · K. Fickiesen · K. Middlebrooks · H....

Get opponent starters

In [13]:
# create a pseudo game ID that can be looked at from opponent's perspective to get opposing starters
key_to_starters = dict(zip(
    df['Date'].astype(str) + ' ' + df['Team'] + ' ' + df['Opponent'] + ' ' + df['Team Score'].astype(str) + ' ' + df['Opponent Score'].astype(str),
    df['Starters']
))

df['Opponent Starters'] = (df['Date'].astype(str) + ' ' + df['Opponent'] + ' ' + df['Team'] + ' ' + df['Opponent Score'].astype(str) + ' ' + df['Team Score'].astype(str)).map(key_to_starters)

df

,Date,NCAA Tournament,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters,Opponent Starters
0,2011-11-11,0,Air Force,-1,Lipscomb,1,0,68,59,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,A. Bowers · M. Faulkner · H. Phillips · O. Smi...
1,2011-11-13,0,Air Force,-1,Tennessee-Martin,-1,0,60,84,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,H. Butler · S. Crawford · J. Haislip · T. Hall...
2,2011-11-17,0,Air Force,1,Denver,-1,0,52,54,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,M. Michel · K. Murdoch · Q. Noonan · M. Shell ...
3,2011-11-19,0,Air Force,-1,Texas Southern,1,0,64,54,D. James · A. Leipprandt · C. Medina · M. O'Ne...,C. Anyiam · G. Fleming · A. Hall · J. McQueen ...
4,2011-11-21,0,Air Force,-1,Texas State,1,0,77,69,D. James · A. Leipprandt · M. O'Neil · D. Sorr...,D. Clinch · A. Ezeh · D. Ford · I. Johnson · V...
...,...,...,...,...,...,...,...,...,...,...,...
10163,2012-02-18,0,Youngstown State,1,Green Bay,-1,1,72,77,B. Brown · K. Fickiesen · T. Jones · K. Middle...,L. Bauer · M. Lukan · H. Quilling · A. Ritchie...
10164,2012-02-23,0,Youngstown State,-1,Wright State,-1,0,62,84,B. Brown · K. Fickiesen · T. Jones · K. Middle...,C. Boyd · K. Demmings · M. Fox · K. Lamotte · ...
10165,2012-02-25,0,Youngstown State,-1,Detroit Mercy,-1,0,64,67,B. Brown · K. Fickiesen · L. Hornberger · K. M...,L. Allen · S. Brown · M. Hatter · J. Jones · S...
10166,2012-03-03,0,Youngstown State,-1,Cleveland State,-1,0,69,79,B. Brown · K. Fickiesen · K. Middlebrooks · H....,J. Adams · C. Coleman · T. Keane · H. King · S...
10167,2012-03-05,0,Youngstown State,-1,Cleveland State,-1,0,56,59,B. Brown · K. Fickiesen · K. Middlebrooks · H....,J. Adams · C. Coleman · T. Keane · H. King · S...

In [14]:
df.loc[df['Opponent Starters'].isna(), :]

,Date,NCAA Tournament,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters,Opponent Starters
3075,2011-11-11,0,Hartford Hawks,1,Manhattan,1,0,64,45,A. Bepko · R. Doherty · D. Elliott · A. Hall ·...,NaN
3076,2011-11-13,0,Hartford Hawks,1,Long Island University,1,0,54,45,A. Bepko · R. Doherty · D. Elliott · A. Hall ·...,NaN
3077,2011-11-17,0,Hartford Hawks,-1,Notre Dame,-1,0,43,98,A. Bepko · R. Doherty · D. Elliott · A. Hall ·...,NaN
3078,2011-11-22,0,Hartford Hawks,1,Central Connecticut State,1,0,65,56,A. Bepko · R. Doherty · D. Elliott · A. Hall ·...,NaN
3079,2011-11-25,0,Hartford Hawks,1,TCU,1,0,64,60,A. Bepko · R. Doherty · D. Elliott · A. Hall ·...,NaN
...,...,...,...,...,...,...,...,...,...,...,...
8153,2012-02-15,0,St. Francis (NY) Terriers,1,Long Island University,-1,0,53,60,S. Benedetti · K. Fox · J. Kaufman · J. Robins...,NaN
8154,2012-02-18,0,St. Francis (NY) Terriers,1,Sacred Heart,-1,0,53,57,S. Benedetti · K. Fox · J. Kaufman · J. Robins...,NaN
8155,2012-02-20,0,St. Francis (NY) Terriers,-1,Quinnipiac,-1,0,41,64,S. Benedetti · K. Fox · J. Kaufman · J. Robins...,NaN
8156,2012-02-25,0,St. Francis (NY) Terriers,-1,FDU,1,0,62,47,S. Benedetti · T. Dunson · J. Kaufman · J. Rob...,NaN
8157,2012-02-27,0,St. Francis (NY) Terriers,-1,Monmouth,-1,0,61,66,S. Benedetti · K. Fox · J. Robinson · K. Snauw...,NaN

In [15]:
df = df.loc[df['Opponent Starters'].notna(), :].reset_index(drop=True)

df

,Date,NCAA Tournament,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Starters,Opponent Starters
0,2011-11-11,0,Air Force,-1,Lipscomb,1,0,68,59,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,A. Bowers · M. Faulkner · H. Phillips · O. Smi...
1,2011-11-13,0,Air Force,-1,Tennessee-Martin,-1,0,60,84,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,H. Butler · S. Crawford · J. Haislip · T. Hall...
2,2011-11-17,0,Air Force,1,Denver,-1,0,52,54,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,M. Michel · K. Murdoch · Q. Noonan · M. Shell ...
3,2011-11-19,0,Air Force,-1,Texas Southern,1,0,64,54,D. James · A. Leipprandt · C. Medina · M. O'Ne...,C. Anyiam · G. Fleming · A. Hall · J. McQueen ...
4,2011-11-21,0,Air Force,-1,Texas State,1,0,77,69,D. James · A. Leipprandt · M. O'Neil · D. Sorr...,D. Clinch · A. Ezeh · D. Ford · I. Johnson · V...
...,...,...,...,...,...,...,...,...,...,...,...
10075,2012-02-18,0,Youngstown State,1,Green Bay,-1,1,72,77,B. Brown · K. Fickiesen · T. Jones · K. Middle...,L. Bauer · M. Lukan · H. Quilling · A. Ritchie...
10076,2012-02-23,0,Youngstown State,-1,Wright State,-1,0,62,84,B. Brown · K. Fickiesen · T. Jones · K. Middle...,C. Boyd · K. Demmings · M. Fox · K. Lamotte · ...
10077,2012-02-25,0,Youngstown State,-1,Detroit Mercy,-1,0,64,67,B. Brown · K. Fickiesen · L. Hornberger · K. M...,L. Allen · S. Brown · M. Hatter · J. Jones · S...
10078,2012-03-03,0,Youngstown State,-1,Cleveland State,-1,0,69,79,B. Brown · K. Fickiesen · K. Middlebrooks · H....,J. Adams · C. Coleman · T. Keane · H. King · S...
10079,2012-03-05,0,Youngstown State,-1,Cleveland State,-1,0,56,59,B. Brown · K. Fickiesen · K. Middlebrooks · H....,J. Adams · C. Coleman · T. Keane · H. King · S...

Split starters into separate columns

In [16]:
# rename starters column
df.rename(columns={'Starters': 'Team Starters'}, inplace=True)

df[[f'Team Starter {i}' for i in range(1, 6)]] = df['Team Starters'].str.split(r'\xa0· | \·', regex=True, expand=True)

for i in range(1, 6):
    df[f'Team Starter {i}'] = df['Team'] + ' ' + df[f'Team Starter {i}']

df[[f'Opponent Starter {i}' for i in range(1, 6)]] = df['Opponent Starters'].str.split(r'\xa0· | \·', regex=True, expand=True)

for i in range(1, 6):
    df[f'Opponent Starter {i}'] = df['Opponent'] + ' ' + df[f'Opponent Starter {i}']

df

,Date,NCAA Tournament,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Team Starters,...,Team Starter 1,Team Starter 2,Team Starter 3,Team Starter 4,Team Starter 5,Opponent Starter 1,Opponent Starter 2,Opponent Starter 3,Opponent Starter 4,Opponent Starter 5
0,2011-11-11,0,Air Force,-1,Lipscomb,1,0,68,59,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,...,Air Force K. Hilbig,Air Force A. Leipprandt,Air Force C. Medina,Air Force J. Satterfield,Air Force C. Thompson,Lipscomb A. Bowers,Lipscomb M. Faulkner,Lipscomb H. Phillips,Lipscomb O. Smith,Lipscomb E. Thornsberry
1,2011-11-13,0,Air Force,-1,Tennessee-Martin,-1,0,60,84,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,...,Air Force K. Hilbig,Air Force A. Leipprandt,Air Force C. Medina,Air Force J. Satterfield,Air Force C. Thompson,Tennessee-Martin H. Butler,Tennessee-Martin S. Crawford,Tennessee-Martin J. Haislip,Tennessee-Martin T. Hall,Tennessee-Martin J. Newsome
2,2011-11-17,0,Air Force,1,Denver,-1,0,52,54,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,...,Air Force K. Hilbig,Air Force A. Leipprandt,Air Force C. Medina,Air Force J. Satterfield,Air Force C. Thompson,Denver M. Michel,Denver K. Murdoch,Denver Q. Noonan,Denver M. Shell,Denver E. Smith
3,2011-11-19,0,Air Force,-1,Texas Southern,1,0,64,54,D. James · A. Leipprandt · C. Medina · M. O'Ne...,...,Air Force D. James,Air Force A. Leipprandt,Air Force C. Medina,Air Force M. O'Neil,Air Force C. Thompson,Texas Southern C. Anyiam,Texas Southern G. Fleming,Texas Southern A. Hall,Texas Southern J. McQueen,Texas Southern K. West
4,2011-11-21,0,Air Force,-1,Texas State,1,0,77,69,D. James · A. Leipprandt · M. O'Neil · D. Sorr...,...,Air Force D. James,Air Force A. Leipprandt,Air Force M. O'Neil,Air Force D. Sorrera,Air Force C. Thompson,Texas State D. Clinch,Texas State A. Ezeh,Texas State D. Ford,Texas State I. Johnson,Texas State V. Kalu
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10075,2012-02-18,0,Youngstown State,1,Green Bay,-1,1,72,77,B. Brown · K. Fickiesen · T. Jones · K. Middle...,...,Youngstown State B. Brown,Youngstown State K. Fickiesen,Youngstown State T. Jones,Youngstown State K. Middlebrooks,Youngstown State M. Nortey,Green Bay L. Bauer,Green Bay M. Lukan,Green Bay H. Quilling,Green Bay A. Ritchie,Green Bay J. Wojta
10076,2012-02-23,0,Youngstown State,-1,Wright State,-1,0,62,84,B. Brown · K. Fickiesen · T. Jones · K. Middle...,...,Youngstown State B. Brown,Youngstown State K. Fickiesen,Youngstown State T. Jones,Youngstown State K. Middlebrooks,Youngstown State M. Nortey,Wright State C. Boyd,Wright State K. Demmings,Wright State M. Fox,Wright State K. Lamotte,Wright State S. Sandifer
10077,2012-02-25,0,Youngstown State,-1,Detroit Mercy,-1,0,64,67,B. Brown · K. Fickiesen · L. Hornberger · K. M...,...,Youngstown State B. Brown,Youngstown State K. Fickiesen,Youngstown State L. Hornberger,Youngstown State K. Middlebrooks,Youngstown State H. Schlegel,Detroit Mercy L. Allen,Detroit Mercy S. Brown,Detroit Mercy M. Hatter,Detroit Mercy J. Jones,Detroit Mercy S. Shearer
10078,2012-03-03,0,Youngstown State,-1,Cleveland State,-1,0,69,79,B. Brown · K. Fickiesen · K. Middlebrooks · H....,...,Youngstown State B. Brown,Youngstown State K. Fickiesen,Youngstown State K. Middlebrooks,Youngstown State H. Schlegel,Youngstown State M. Touvelle,Cleveland State J. Adams,Cleveland State C. Coleman,Cleveland State T. Keane,Cleveland State H. King,Cleveland State S. Winton
10079,2012-03-05,0,Youngstown State,-1,Cleveland State,-1,0,56,59,B. Brown · K. Fickiesen · K. Middlebrooks · H....,...,Youngstown State B. Brown,Youngstown State K. Fickiesen,Youngstown State K. Middlebrooks,Youngstown State H. Schlegel,Youngstown State M. Thompson,Cleveland State J. Adams,Cleveland State C. Coleman,Cleveland State T. Keane,Cleveland State H. King,Cleveland State S. Winton

Set up adjusted Score Differential

In [17]:
blowout_threshold = 18  # adjusted score differential will only account up to this score difference

df['Score Differential'] = df['Team Score'] - df['Opponent Score']

df['Adjusted Score Differential'] = df['Score Differential'].abs()

df.loc[df['Adjusted Score Differential'] > blowout_threshold, 'Adjusted Score Differential'] = blowout_threshold

df['Adjusted Score Differential'] = df['Adjusted Score Differential']**(np.log(1.5)/np.log(blowout_threshold))

df

,Date,NCAA Tournament,Team,Location,Opponent,Result,Overtime,Team Score,Opponent Score,Team Starters,...,Team Starter 3,Team Starter 4,Team Starter 5,Opponent Starter 1,Opponent Starter 2,Opponent Starter 3,Opponent Starter 4,Opponent Starter 5,Score Differential,Adjusted Score Differential
0,2011-11-11,0,Air Force,-1,Lipscomb,1,0,68,59,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,...,Air Force C. Medina,Air Force J. Satterfield,Air Force C. Thompson,Lipscomb A. Bowers,Lipscomb M. Faulkner,Lipscomb H. Phillips,Lipscomb O. Smith,Lipscomb E. Thornsberry,9,1.361013
1,2011-11-13,0,Air Force,-1,Tennessee-Martin,-1,0,60,84,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,...,Air Force C. Medina,Air Force J. Satterfield,Air Force C. Thompson,Tennessee-Martin H. Butler,Tennessee-Martin S. Crawford,Tennessee-Martin J. Haislip,Tennessee-Martin T. Hall,Tennessee-Martin J. Newsome,-24,1.500000
2,2011-11-17,0,Air Force,1,Denver,-1,0,52,54,K. Hilbig · A. Leipprandt · C. Medina · J. Sat...,...,Air Force C. Medina,Air Force J. Satterfield,Air Force C. Thompson,Denver M. Michel,Denver K. Murdoch,Denver Q. Noonan,Denver M. Shell,Denver E. Smith,-2,1.102120
3,2011-11-19,0,Air Force,-1,Texas Southern,1,0,64,54,D. James · A. Leipprandt · C. Medina · M. O'Ne...,...,Air Force C. Medina,Air Force M. O'Neil,Air Force C. Thompson,Texas Southern C. Anyiam,Texas Southern G. Fleming,Texas Southern A. Hall,Texas Southern J. McQueen,Texas Southern K. West,10,1.381279
4,2011-11-21,0,Air Force,-1,Texas State,1,0,77,69,D. James · A. Leipprandt · M. O'Neil · D. Sorr...,...,Air Force M. O'Neil,Air Force D. Sorrera,Air Force C. Thompson,Texas State D. Clinch,Texas State A. Ezeh,Texas State D. Ford,Texas State I. Johnson,Texas State V. Kalu,8,1.338710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10075,2012-02-18,0,Youngstown State,1,Green Bay,-1,1,72,77,B. Brown · K. Fickiesen · T. Jones · K. Middle...,...,Youngstown State T. Jones,Youngstown State K. Middlebrooks,Youngstown State M. Nortey,Green Bay L. Bauer,Green Bay M. Lukan,Green Bay H. Quilling,Green Bay A. Ritchie,Green Bay J. Wojta,-5,1.253292
10076,2012-02-23,0,Youngstown State,-1,Wright State,-1,0,62,84,B. Brown · K. Fickiesen · T. Jones · K. Middle...,...,Youngstown State T. Jones,Youngstown State K. Middlebrooks,Youngstown State M. Nortey,Wright State C. Boyd,Wright State K. Demmings,Wright State M. Fox,Wright State K. Lamotte,Wright State S. Sandifer,-22,1.500000
10077,2012-02-25,0,Youngstown State,-1,Detroit Mercy,-1,0,64,67,B. Brown · K. Fickiesen · L. Hornberger · K. M...,...,Youngstown State L. Hornberger,Youngstown State K. Middlebrooks,Youngstown State H. Schlegel,Detroit Mercy L. Allen,Detroit Mercy S. Brown,Detroit Mercy M. Hatter,Detroit Mercy J. Jones,Detroit Mercy S. Shearer,-3,1.166625
10078,2012-03-03,0,Youngstown State,-1,Cleveland State,-1,0,69,79,B. Brown · K. Fickiesen · K. Middlebrooks · H....,...,Youngstown State K. Middlebrooks,Youngstown State H. Schlegel,Youngstown State M. Touvelle,Cleveland State J. Adams,Cleveland State C. Coleman,Cleveland State T. Keane,Cleveland State H. King,Cleveland State S. Winton,-10,1.381279
10079,2012-03-05,0,Youngstown State,-1,Cleveland State,-1,0,56,59,B. Brown · K. Fickiesen · K. Middlebrooks · H....,...,Youngstown State K. Middlebrooks,Youngstown State H. Schlegel,Youngstown State M. Thompson,Cleveland State J. Adams,Cleveland State C. Coleman,Cleveland State T. Keane,Cleveland State H. King,Cleveland State S. Winton,-3,1.166625

In [18]:
df.to_parquet(f'../data/unprocessed/womens_starters/starters_{season}.parquet')

'Done'

'Done'