# Women's Scrape Schedule

Get schedule of each team in a given year. This file needs to be ran for every relevant year (starting in 2008).

### Web Scraping

Fair warning that this program unfortunately takes a very long time to run due to web scraping limits set by Sports Reference

In [1]:
SEASON = 2025

In [2]:
import pandas as pd
import numpy as np
import time

pd.set_option('display.max_columns', 100)

df_active_teams = pd.read_html('https://www.sports-reference.com/cbb/schools/index.html')[0]
time.sleep(2)

df_active_teams = df_active_teams.loc[~df_active_teams['School'].isin([np.NaN, 'School']), :].reset_index(drop=True)

df_active_teams['From'] = pd.to_numeric(df_active_teams['From'], errors='coerce')
df_active_teams['To'] = pd.to_numeric(df_active_teams['To'], errors='coerce')

df_active_teams = df_active_teams.loc[(df_active_teams['To'] >= SEASON) & (df_active_teams['From'] <= SEASON), :].reset_index(drop=True)

if SEASON == 2021:  # if 2021, remove ivy league because they cancelled their season in 2021
    df_active_teams = df_active_teams.loc[
        ~df_active_teams['School'].isin(['Princeton', 'Harvard', 'Yale', 'Pennsylvania', 'Brown', 'Columbia', 'Cornell', 'Dartmouth']), 
        :
    ].reset_index(drop=True)

df_active_teams

,Rk,School,"City, State",From,To,Yrs,G,W,L,W-L%,SRS,SOS,AP,CREG,CTRN,NCAA,FF,NC
0,1,Abilene Christian,"Abilene, Texas",1971,2025,15,455,242,213,.532,-7.59,-5.33,0,0,2,2,0,0
1,2,Air Force,"USAF Academy, Colorado",1958,2025,68,1875,797,1078,.425,-2.87,1.37,0,1,0,4,0,0
2,3,Akron,"Akron, Ohio",1902,2025,74,1752,1055,697,.602,0.08,-1.62,0,10,6,6,0,0
3,4,Alabama,"Tuscaloosa, Alabama",1913,2025,112,2929,1819,1109,.621,8.18,5.07,18,10,9,25,1,0
4,5,Alabama A&M,"Normal, Alabama",2000,2025,26,755,287,468,.380,-16.75,-11.02,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
359,489,Wright State,"Dayton, Ohio",1988,2025,38,1161,646,515,.556,-1.42,-2.60,0,4,4,4,0,0
360,490,Wyoming,"Laramie, Wyoming",1905,2025,120,2911,1622,1289,.557,2.69,2.76,4,21,3,16,1,1
361,491,Xavier,"Cincinnati, Ohio",1920,2025,104,2729,1632,1097,.598,6.20,4.06,13,18,9,29,0,0
362,492,Yale,"New Haven, Connecticut",1896,2025,129,3114,1588,1524,.510,-5.82,-4.43,1,17,3,7,0,0
363,493,Youngstown State,"Youngstown, Ohio",1948,2025,45,1326,551,775,.416,-7.88,-3.56,0,1,0,0,0,0

In [3]:
from datetime import datetime

cutoff_dates = {
    2008: datetime(2008, 3, 21),
    2009: datetime(2009, 3, 20),
    2010: datetime(2010, 3, 19),
    2011: datetime(2011, 3, 18),
    2012: datetime(2012, 3, 16),
    2013: datetime(2013, 3, 22),
    2014: datetime(2014, 3, 21),
    2015: datetime(2015, 3, 19),
    2016: datetime(2016, 3, 17),
    2017: datetime(2017, 3, 16),
    2018: datetime(2018, 3, 15),
    2019: datetime(2019, 3, 21),
    2020: datetime(2020, 3, 13),  # cancelled
    2021: datetime(2021, 3, 24),
    2022: datetime(2022, 3, 17),
    2023: datetime(2023, 3, 16),
    2024: datetime(2024, 3, 21),
    2025: datetime(2025, 3, 20),
}

cutoff_dates[SEASON]

datetime.datetime(2025, 3, 20, 0, 0)

Get school names used in Sports Reference URL

In [4]:
df_active_teams['URL School'] = df_active_teams['School']

# hard code some schools that cause issues
df_active_teams.loc[df_active_teams['School'] == 'Bowling Green', 'URL School'] = 'Bowling Green State'
df_active_teams.loc[df_active_teams['School'] == 'BYU', 'URL School'] = 'Brigham Young'
df_active_teams.loc[df_active_teams['School'] == 'Louisiana', 'URL School'] = 'Louisiana Lafayette'
df_active_teams.loc[df_active_teams['School'] == 'LSU', 'URL School'] = 'Louisiana State'
df_active_teams.loc[df_active_teams['School'] == 'Ole Miss', 'URL School'] = 'Mississippi'
df_active_teams.loc[df_active_teams['School'] == 'Pitt', 'URL School'] = 'Pittsburgh'
df_active_teams.loc[df_active_teams['School'] == 'SMU', 'URL School'] = 'Southern Methodist'
df_active_teams.loc[df_active_teams['School'] == 'UAB', 'URL School'] = 'Alabama Birmingham'
df_active_teams.loc[df_active_teams['School'] == 'UCF', 'URL School'] = 'Central Florida'
df_active_teams.loc[df_active_teams['School'] == 'USC', 'URL School'] = 'Southern California'
df_active_teams.loc[df_active_teams['School'] == 'UTEP', 'URL School'] = 'Texas El Paso'
df_active_teams.loc[df_active_teams['School'] == 'UTSA', 'URL School'] = 'Texas San Antonio'
df_active_teams.loc[df_active_teams['School'] == 'Sam Houston', 'URL School'] = 'Sam Houston State'
df_active_teams.loc[df_active_teams['School'] == 'Houston Christian', 'URL School'] = 'Houston Baptist'
df_active_teams.loc[df_active_teams['School'] == 'Kansas City', 'URL School'] = 'Missouri Kansas City'
df_active_teams.loc[df_active_teams['School'] == 'Little Rock', 'URL School'] = 'Arkansas Little Rock'
df_active_teams.loc[df_active_teams['School'] == 'NC State', 'URL School'] = 'North Carolina State'
df_active_teams.loc[df_active_teams['School'] == 'Omaha', 'URL School'] = 'Nebraska Omaha'
df_active_teams.loc[df_active_teams['School'] == 'Purdue Fort Wayne', 'URL School'] = 'IPFW'
df_active_teams.loc[df_active_teams['School'] == 'TCU', 'URL School'] = 'Texas Christian'
df_active_teams.loc[df_active_teams['School'] == 'Texas-Rio Grande Valley', 'URL School'] = 'Texas Pan American'
df_active_teams.loc[df_active_teams['School'] == 'The Citadel', 'URL School'] = 'Citadel'
df_active_teams.loc[df_active_teams['School'] == 'Utah Tech', 'URL School'] = 'Dixie State'
df_active_teams.loc[df_active_teams['School'] == 'St. Thomas', 'URL School'] = 'St. Thomas MN'
df_active_teams.loc[df_active_teams['School'] == 'UC Berkley', 'URL School'] = 'California'
df_active_teams.loc[df_active_teams['School'] == 'UT Arlington', 'URL School'] = 'Texas Arlington'
df_active_teams.loc[df_active_teams['School'] == 'FDU', 'URL School'] = 'Fairleigh Dickinson'
df_active_teams.loc[df_active_teams['School'] == 'Hartford Hawks', 'URL School'] = 'Hartford'
df_active_teams.loc[df_active_teams['School'] == 'Savannah State Tigers', 'URL School'] = 'Savannah State'
df_active_teams.loc[df_active_teams['School'] == 'St. Francis (NY) Terriers', 'URL School'] = 'St. Francis (NY)'
df_active_teams.loc[df_active_teams['School'] == 'East Texas A&M', 'URL School'] = 'Texas A&M Commerce'
df_active_teams.loc[df_active_teams['School'] == 'IU Indy', 'URL School'] = 'IUPUI'

df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UC\s', 'California ', regex=True)
df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UNC\s', 'North Carolina ', regex=True)

In [5]:
urls = (
    'https://www.sports-reference.com/cbb/schools/' +
    df_active_teams['URL School'].str.replace(' ', '-', regex=False).str.replace('[)(&.\']', '', regex=True).str.replace('--', '-', regex=False).str.lower() +
    '/women/' + str(SEASON) +
    '-gamelogs.html'
)

urls

0      https://www.sports-reference.com/cbb/schools/a...
1      https://www.sports-reference.com/cbb/schools/a...
2      https://www.sports-reference.com/cbb/schools/a...
3      https://www.sports-reference.com/cbb/schools/a...
4      https://www.sports-reference.com/cbb/schools/a...
                             ...
359    https://www.sports-reference.com/cbb/schools/w...
360    https://www.sports-reference.com/cbb/schools/w...
361    https://www.sports-reference.com/cbb/schools/x...
362    https://www.sports-reference.com/cbb/schools/y...
363    https://www.sports-reference.com/cbb/schools/y...
Name: URL School, Length: 364, dtype: object

In [6]:
from urllib.error import HTTPError
from tqdm.notebook import tqdm

problems = []

l = []
loop = tqdm(
    np.array((df_active_teams['School'], urls)).transpose(),  # get both school and url into loop iteration
    bar_format='{bar}{percentage:3.0f}%{r_bar}   {desc}'  # make the description not affect bar location
)
for (school, url) in loop:
  try:
    loop.set_description(f'{school}')
    # print(f'{i:03d}: {url}')
    df_team_season = pd.read_html(url)[-1]  # schools that were ranked have that info as the first table on the site
    time.sleep(2)

    df_team_season.columns = [i[1] if 'Unnamed' in i[0] else i[0] + ' ' + i[1] for i in df_team_season.columns]
    df_team_season.insert(2, 'Team', school)
    l.append(df_team_season)
  except ValueError as e:
    print(f'{url} | ValueError: {e}')
    time.sleep(2)
  except HTTPError as e:
    if e.code == 404:
      print(f'{url} | {e}')
      time.sleep(2)
    else:
      print(f'{url} | {e}')
      break

df = pd.concat(l, ignore_index=True)

df

            0%| 0/364 [00:00<?, ?it/s]

https://www.sports-reference.com/cbb/schools/citadel/women/2025-gamelogs.html | HTTP Error 404: Not Found
https://www.sports-reference.com/cbb/schools/virginia-military-institute/women/2025-gamelogs.html | HTTP Error 404: Not Found

,Rk,Gtm,Team,Date,Unnamed: 3_level_1,Opp,Type,Score Rslt,Score Tm,Score Opp,Score OT,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF
0,1,1,Abilene Christian,2024-11-04,NaN,Univ of the SW,REG (Non-Conf),W,95,38,NaN,36,78,.462,14,41,.341,22,37,.595,.551,9,14,.643,18,26,44,22,21,5,13,16,13,48,.271,7,29,.241,6,19,.316,.344,5,10,.500,4,20,24,11,6,3,32,19
1,2,2,Abilene Christian,2024-11-08,@,Florida International,REG (Non-Conf),W,76,73,NaN,21,51,.412,9,24,.375,12,27,.444,.500,25,30,.833,5,21,26,16,4,2,26,33,23,56,.411,3,19,.158,20,37,.541,.438,24,36,.667,10,22,32,10,13,2,18,32
2,3,3,Abilene Christian,2024-11-12,NaN,Stephen F. Austin,REG (Non-Conf),L,65,68,NaN,25,67,.373,6,31,.194,19,36,.528,.418,9,11,.818,14,21,35,12,9,3,15,21,23,50,.460,5,20,.250,18,30,.600,.510,17,25,.680,7,26,33,8,12,1,22,22
3,4,4,Abilene Christian,2024-11-16,NaN,North Texas,REG (Non-Conf),L,60,71,NaN,24,69,.348,8,35,.229,16,34,.471,.406,4,7,.571,12,16,28,13,10,0,19,19,26,49,.531,3,10,.300,23,39,.590,.561,16,22,.727,7,25,32,11,12,7,23,17
4,5,5,Abilene Christian,2024-11-19,@,Texas Tech,REG (Non-Conf),L,40,66,NaN,12,52,.231,3,23,.130,9,29,.310,.260,13,15,.867,13,12,25,6,13,0,21,20,20,46,.435,11,23,.478,9,23,.391,.554,15,21,.714,13,21,34,17,11,10,26,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12050,30,30,Youngstown State,2025-02-26,@,Robert Morris,REG (Conf),L,53,76,NaN,18,55,.327,5,18,.278,13,37,.351,.373,12,14,.857,10,21,31,12,6,0,17,15,29,57,.509,10,22,.455,19,35,.543,.596,8,13,.615,7,27,34,19,8,6,13,15
12051,31,31,Youngstown State,2025-03-01,NaN,Cleveland State,REG (Conf),W,73,70,NaN,24,66,.364,6,19,.316,18,47,.383,.409,19,22,.864,14,19,33,17,6,2,5,16,23,54,.426,9,27,.333,14,27,.519,.509,15,20,.750,8,26,34,20,3,7,11,21
12052,Rk,Gtm,Youngstown State,Date,NaN,Opp,Type,Rslt,Tm,Opp,OT,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF
12053,32,32,Youngstown State,2025-03-04,@,Wright State,CTOURN,L,58,73,NaN,21,52,.404,4,11,.364,17,41,.415,.442,12,18,.667,4,20,24,10,9,4,12,12,26,61,.426,10,23,.435,16,38,.421,.508,11,13,.846,15,28,43,14,7,4,16,15
12054,NaN,NaN,Youngstown State,NaN,NaN,NaN,NaN,12-19,1852,1948,NaN,666,1762,.378,181,639,.283,485,1123,.432,.429,339,480,.706,276,721,997,398,217,103,486,515,684,1712,.400,172,561,.307,512,1151,.445,.450,408,560,.729,236,722,958,377,221,109,447,530

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12055 entries, 0 to 12054
Data columns (total 53 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rk                  11693 non-null  object
 1   Gtm                 11594 non-null  object
 2   Team                12055 non-null  object
 3   Date                11693 non-null  object
 4   Unnamed: 3_level_1  6064 non-null   object
 5   Opp                 11688 non-null  object
 6   Type                11693 non-null  object
 7   Score Rslt          11956 non-null  object
 8   Score Tm            11956 non-null  object
 9   Score Opp           11956 non-null  object
 10  Score OT            780 non-null    object
 11  Team FG             11956 non-null  object
 12  Team FGA            11956 non-null  object
 13  Team FG%            11956 non-null  object
 14  Team 3P             11956 non-null  object
 15  Team 3PA            11956 non-null  object
 16  Team 3P%            11956 non-null  object
 17  Team 2P             11956 non-null  object
 18  Team 2PA            11956 non-null  object
 19  Team 2P%            11956 non-null  object
 20  Team eFG%           11956 non-null  object
 21  Team FT             11956 non-null  object
 22  Team FTA            11956 non-null  object
 23  Team FT%            11948 non-null  object
 24  Team ORB            11956 non-null  object
 25  Team DRB            11956 non-null  object
 26  Team TRB            11956 non-null  object
 27  Team AST            11956 non-null  object
 28  Team STL            11956 non-null  object
 29  Team BLK            11956 non-null  object
 30  Team TOV            11956 non-null  object
 31  Team PF             11956 non-null  object
 32  Opponent FG         11956 non-null  object
 33  Opponent FGA        11956 non-null  object
 34  Opponent FG%        11956 non-null  object
 35  Opponent 3P         11956 non-null  object
 36  Opponent 3PA        11956 non-null  object
 37  Opponent 3P%        11956 non-null  object
 38  Opponent 2P         11956 non-null  object
 39  Opponent 2PA        11956 non-null  object
 40  Opponent 2P%        11956 non-null  object
 41  Opponent eFG%       11956 non-null  object
 42  Opponent FT         11956 non-null  object
 43  Opponent FTA        11956 non-null  object
 44  Opponent FT%        11946 non-null  object
 45  Opponent ORB        11956 non-null  object
 46  Opponent DRB        11956 non-null  object
 47  Opponent TRB        11956 non-null  object
 48  Opponent AST        11956 non-null  object
 49  Opponent STL        11956 non-null  object
 50  Opponent BLK        11956 non-null  object
 51  Opponent TOV        11956 non-null  object
 52  Opponent PF         11956 non-null  object
dtypes: object(53)
memory usage: 4.9+ MB

### Data Setup

In [8]:
temp = df.copy()

In [9]:
df = temp.copy()

Fix column names and drop useless columns

In [10]:
df.columns = (
    ['G', 'Gtm', 'Team', 'Date', 'Location', 'Opponent', 'Type', 'Result', 'Team Score', 'Opponent Score', 'OT'] +
    [c for c in df.columns[11:]]
)

# use "Team" as prefix instead of "School"
df.columns = df.columns.str.replace('School', 'Team', regex=False)

# drop columns that are completely null
df = df[[c for c in df.columns if df.loc[:, c].notna().any()]].copy()

# drop columns without a name
df = df.loc[:, ~df.columns.str.contains('^Unnamed', regex=True)]

# drop rows that aren't games
df = df.loc[(df['Date'].notna()) & (df['Result'].isin(['W', 'L'])), :].reset_index(drop=True)

# drop useless columns
df.drop(columns=['G', 'Gtm'], inplace=True)

df

,Team,Date,Location,Opponent,Type,Result,Team Score,Opponent Score,OT,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF
0,Abilene Christian,2024-11-04,NaN,Univ of the SW,REG (Non-Conf),W,95,38,NaN,36,78,.462,14,41,.341,22,37,.595,.551,9,14,.643,18,26,44,22,21,5,13,16,13,48,.271,7,29,.241,6,19,.316,.344,5,10,.500,4,20,24,11,6,3,32,19
1,Abilene Christian,2024-11-08,@,Florida International,REG (Non-Conf),W,76,73,NaN,21,51,.412,9,24,.375,12,27,.444,.500,25,30,.833,5,21,26,16,4,2,26,33,23,56,.411,3,19,.158,20,37,.541,.438,24,36,.667,10,22,32,10,13,2,18,32
2,Abilene Christian,2024-11-12,NaN,Stephen F. Austin,REG (Non-Conf),L,65,68,NaN,25,67,.373,6,31,.194,19,36,.528,.418,9,11,.818,14,21,35,12,9,3,15,21,23,50,.460,5,20,.250,18,30,.600,.510,17,25,.680,7,26,33,8,12,1,22,22
3,Abilene Christian,2024-11-16,NaN,North Texas,REG (Non-Conf),L,60,71,NaN,24,69,.348,8,35,.229,16,34,.471,.406,4,7,.571,12,16,28,13,10,0,19,19,26,49,.531,3,10,.300,23,39,.590,.561,16,22,.727,7,25,32,11,12,7,23,17
4,Abilene Christian,2024-11-19,@,Texas Tech,REG (Non-Conf),L,40,66,NaN,12,52,.231,3,23,.130,9,29,.310,.260,13,15,.867,13,12,25,6,13,0,21,20,20,46,.435,11,23,.478,9,23,.391,.554,15,21,.714,13,21,34,17,11,10,26,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11260,Youngstown State,2025-02-20,@,Detroit Mercy,REG (Conf),W,67,59,NaN,26,49,.531,4,11,.364,22,38,.579,.571,11,16,.688,5,30,35,12,8,1,22,10,23,66,.348,5,23,.217,18,43,.419,.386,8,9,.889,10,17,27,10,10,3,14,21
11261,Youngstown State,2025-02-22,@,Oakland,REG (Conf),W,52,51,NaN,19,49,.388,3,11,.273,16,38,.421,.418,11,18,.611,8,26,34,9,8,3,19,13,20,59,.339,6,16,.375,14,43,.326,.390,5,6,.833,7,23,30,10,10,4,13,19
11262,Youngstown State,2025-02-26,@,Robert Morris,REG (Conf),L,53,76,NaN,18,55,.327,5,18,.278,13,37,.351,.373,12,14,.857,10,21,31,12,6,0,17,15,29,57,.509,10,22,.455,19,35,.543,.596,8,13,.615,7,27,34,19,8,6,13,15
11263,Youngstown State,2025-03-01,NaN,Cleveland State,REG (Conf),W,73,70,NaN,24,66,.364,6,19,.316,18,47,.383,.409,19,22,.864,14,19,33,17,6,2,5,16,23,54,.426,9,27,.333,14,27,.519,.509,15,20,.750,8,26,34,20,3,7,11,21
11264,Youngstown State,2025-03-04,@,Wright State,CTOURN,L,58,73,NaN,21,52,.404,4,11,.364,17,41,.415,.442,12,18,.667,4,20,24,10,9,4,12,12,26,61,.426,10,23,.435,16,38,.421,.508,11,13,.846,15,28,43,14,7,4,16,15

Get overtime information

In [11]:
# remove games that have not been played
df = df.loc[(df['Result'].notna()) & (df['Result'] != 'W/L'), :].reset_index(drop=True)

# get overtimes amount
df['Overtimes Amount'] = (
    df['OT']
    .apply(
        lambda x: 
        1 if x == 'OT' 
        else int(x[:-2]) if isinstance(x, str) and x.endswith('OT') and len(x) > 2 
        else 0
    )
)

# binary overtime flag
df['Overtime'] = df.pop('OT').notna().astype('int8')

# reformat result column
df['Result'] = df['Result'].str[:1].map({'W': 1, 'L': -1}).astype('int8')

df

,Team,Date,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,Abilene Christian,2024-11-04,NaN,Univ of the SW,REG (Non-Conf),1,95,38,36,78,.462,14,41,.341,22,37,.595,.551,9,14,.643,18,26,44,22,21,5,13,16,13,48,.271,7,29,.241,6,19,.316,.344,5,10,.500,4,20,24,11,6,3,32,19,0,0
1,Abilene Christian,2024-11-08,@,Florida International,REG (Non-Conf),1,76,73,21,51,.412,9,24,.375,12,27,.444,.500,25,30,.833,5,21,26,16,4,2,26,33,23,56,.411,3,19,.158,20,37,.541,.438,24,36,.667,10,22,32,10,13,2,18,32,0,0
2,Abilene Christian,2024-11-12,NaN,Stephen F. Austin,REG (Non-Conf),-1,65,68,25,67,.373,6,31,.194,19,36,.528,.418,9,11,.818,14,21,35,12,9,3,15,21,23,50,.460,5,20,.250,18,30,.600,.510,17,25,.680,7,26,33,8,12,1,22,22,0,0
3,Abilene Christian,2024-11-16,NaN,North Texas,REG (Non-Conf),-1,60,71,24,69,.348,8,35,.229,16,34,.471,.406,4,7,.571,12,16,28,13,10,0,19,19,26,49,.531,3,10,.300,23,39,.590,.561,16,22,.727,7,25,32,11,12,7,23,17,0,0
4,Abilene Christian,2024-11-19,@,Texas Tech,REG (Non-Conf),-1,40,66,12,52,.231,3,23,.130,9,29,.310,.260,13,15,.867,13,12,25,6,13,0,21,20,20,46,.435,11,23,.478,9,23,.391,.554,15,21,.714,13,21,34,17,11,10,26,20,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11260,Youngstown State,2025-02-20,@,Detroit Mercy,REG (Conf),1,67,59,26,49,.531,4,11,.364,22,38,.579,.571,11,16,.688,5,30,35,12,8,1,22,10,23,66,.348,5,23,.217,18,43,.419,.386,8,9,.889,10,17,27,10,10,3,14,21,0,0
11261,Youngstown State,2025-02-22,@,Oakland,REG (Conf),1,52,51,19,49,.388,3,11,.273,16,38,.421,.418,11,18,.611,8,26,34,9,8,3,19,13,20,59,.339,6,16,.375,14,43,.326,.390,5,6,.833,7,23,30,10,10,4,13,19,0,0
11262,Youngstown State,2025-02-26,@,Robert Morris,REG (Conf),-1,53,76,18,55,.327,5,18,.278,13,37,.351,.373,12,14,.857,10,21,31,12,6,0,17,15,29,57,.509,10,22,.455,19,35,.543,.596,8,13,.615,7,27,34,19,8,6,13,15,0,0
11263,Youngstown State,2025-03-01,NaN,Cleveland State,REG (Conf),1,73,70,24,66,.364,6,19,.316,18,47,.383,.409,19,22,.864,14,19,33,17,6,2,5,16,23,54,.426,9,27,.333,14,27,.519,.509,15,20,.750,8,26,34,20,3,7,11,21,0,0
11264,Youngstown State,2025-03-04,@,Wright State,CTOURN,-1,58,73,21,52,.404,4,11,.364,17,41,.415,.442,12,18,.667,4,20,24,10,9,4,12,12,26,61,.426,10,23,.435,16,38,.421,.508,11,13,.846,15,28,43,14,7,4,16,15,0,0

Reformat location column for home/neutral/away

In [12]:
df['Location'] = df['Location'].map({np.NaN: 1, 'N': 0, '@': -1}).astype('int8')

df['Location']

0        1
1       -1
2        1
3        1
4       -1
        ..
11260   -1
11261   -1
11262   -1
11263    1
11264   -1
Name: Location, Length: 11265, dtype: int8

Other general fixes

In [13]:
# fix dates
df['Date'] = pd.to_datetime(df['Date'])

# specify before and after NCAA tournament
df.insert(df.columns.get_loc('Date') + 1, 'NCAA Tournament', (df['Date'] > cutoff_dates[SEASON]).astype(int))

# fix column types
df.loc[:, df.columns.str.contains('Team ', regex=False)] = df.loc[:, df.columns.str.contains('Team ', regex=False)].astype('float64')
df.loc[:, df.columns.str.contains('Opponent ', regex=False)] = df.loc[:, df.columns.str.contains('Opponent ', regex=False)].astype('float64')

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,Abilene Christian,2024-11-04,0,1,Univ of the SW,REG (Non-Conf),1,95.0,38.0,36.0,78.0,0.462,14.0,41.0,0.341,22.0,37.0,0.595,0.551,9.0,14.0,0.643,18.0,26.0,44.0,22.0,21.0,5.0,13.0,16.0,13.0,48.0,0.271,7.0,29.0,0.241,6.0,19.0,0.316,0.344,5.0,10.0,0.5,4.0,20.0,24.0,11.0,6.0,3.0,32.0,19.0,0,0
1,Abilene Christian,2024-11-08,0,-1,Florida International,REG (Non-Conf),1,76.0,73.0,21.0,51.0,0.412,9.0,24.0,0.375,12.0,27.0,0.444,0.5,25.0,30.0,0.833,5.0,21.0,26.0,16.0,4.0,2.0,26.0,33.0,23.0,56.0,0.411,3.0,19.0,0.158,20.0,37.0,0.541,0.438,24.0,36.0,0.667,10.0,22.0,32.0,10.0,13.0,2.0,18.0,32.0,0,0
2,Abilene Christian,2024-11-12,0,1,Stephen F. Austin,REG (Non-Conf),-1,65.0,68.0,25.0,67.0,0.373,6.0,31.0,0.194,19.0,36.0,0.528,0.418,9.0,11.0,0.818,14.0,21.0,35.0,12.0,9.0,3.0,15.0,21.0,23.0,50.0,0.46,5.0,20.0,0.25,18.0,30.0,0.6,0.51,17.0,25.0,0.68,7.0,26.0,33.0,8.0,12.0,1.0,22.0,22.0,0,0
3,Abilene Christian,2024-11-16,0,1,North Texas,REG (Non-Conf),-1,60.0,71.0,24.0,69.0,0.348,8.0,35.0,0.229,16.0,34.0,0.471,0.406,4.0,7.0,0.571,12.0,16.0,28.0,13.0,10.0,0.0,19.0,19.0,26.0,49.0,0.531,3.0,10.0,0.3,23.0,39.0,0.59,0.561,16.0,22.0,0.727,7.0,25.0,32.0,11.0,12.0,7.0,23.0,17.0,0,0
4,Abilene Christian,2024-11-19,0,-1,Texas Tech,REG (Non-Conf),-1,40.0,66.0,12.0,52.0,0.231,3.0,23.0,0.13,9.0,29.0,0.31,0.26,13.0,15.0,0.867,13.0,12.0,25.0,6.0,13.0,0.0,21.0,20.0,20.0,46.0,0.435,11.0,23.0,0.478,9.0,23.0,0.391,0.554,15.0,21.0,0.714,13.0,21.0,34.0,17.0,11.0,10.0,26.0,20.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11260,Youngstown State,2025-02-20,0,-1,Detroit Mercy,REG (Conf),1,67.0,59.0,26.0,49.0,0.531,4.0,11.0,0.364,22.0,38.0,0.579,0.571,11.0,16.0,0.688,5.0,30.0,35.0,12.0,8.0,1.0,22.0,10.0,23.0,66.0,0.348,5.0,23.0,0.217,18.0,43.0,0.419,0.386,8.0,9.0,0.889,10.0,17.0,27.0,10.0,10.0,3.0,14.0,21.0,0,0
11261,Youngstown State,2025-02-22,0,-1,Oakland,REG (Conf),1,52.0,51.0,19.0,49.0,0.388,3.0,11.0,0.273,16.0,38.0,0.421,0.418,11.0,18.0,0.611,8.0,26.0,34.0,9.0,8.0,3.0,19.0,13.0,20.0,59.0,0.339,6.0,16.0,0.375,14.0,43.0,0.326,0.39,5.0,6.0,0.833,7.0,23.0,30.0,10.0,10.0,4.0,13.0,19.0,0,0
11262,Youngstown State,2025-02-26,0,-1,Robert Morris,REG (Conf),-1,53.0,76.0,18.0,55.0,0.327,5.0,18.0,0.278,13.0,37.0,0.351,0.373,12.0,14.0,0.857,10.0,21.0,31.0,12.0,6.0,0.0,17.0,15.0,29.0,57.0,0.509,10.0,22.0,0.455,19.0,35.0,0.543,0.596,8.0,13.0,0.615,7.0,27.0,34.0,19.0,8.0,6.0,13.0,15.0,0,0
11263,Youngstown State,2025-03-01,0,1,Cleveland State,REG (Conf),1,73.0,70.0,24.0,66.0,0.364,6.0,19.0,0.316,18.0,47.0,0.383,0.409,19.0,22.0,0.864,14.0,19.0,33.0,17.0,6.0,2.0,5.0,16.0,23.0,54.0,0.426,9.0,27.0,0.333,14.0,27.0,0.519,0.509,15.0,20.0,0.75,8.0,26.0,34.0,20.0,3.0,7.0,11.0,21.0,0,0
11264,Youngstown State,2025-03-04,0,-1,Wright State,CTOURN,-1,58.0,73.0,21.0,52.0,0.404,4.0,11.0,0.364,17.0,41.0,0.415,0.442,12.0,18.0,0.667,4.0,20.0,24.0,10.0,9.0,4.0,12.0,12.0,26.0,61.0,0.426,10.0,23.0,0.435,16.0,38.0,0.421,0.508,11.0,13.0,0.846,15.0,28.0,43.0,14.0,7.0,4.0,16.0,15.0,0,0

Remap opponent names because the opponents sometimes have a different naming convention than the team names

In [14]:
# create new dataframe from opposite perspective    team <--> opponent
df_switch = df.copy()

df_switch.columns = df_switch.columns.str.replace(
    'Team', '_TEMP_', regex=False
).str.replace(
    'Opponent', 'Team', regex=False
).str.replace(
    '_TEMP_', 'Opponent', regex=False
)

df_switch[['Location', 'Result']] *= -1

# get fixed opponent names
df['Opponent'] = pd.merge(
    df, df_switch,
    how='left',
    on=(
        ['Date', 'Location', 'Result'] +
        list(df.loc[:, df.columns.str.contains('Team ')].columns) +
        list(df.loc[:, df.columns.str.contains('Opponent ')].columns)
    )
)['Opponent_y']

# Remove matchups that are not division 1
df = df.loc[df['Opponent'].notna(), :].reset_index(drop=True)

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,Abilene Christian,2024-11-08,0,-1,Florida International,REG (Non-Conf),1,76.0,73.0,21.0,51.0,0.412,9.0,24.0,0.375,12.0,27.0,0.444,0.5,25.0,30.0,0.833,5.0,21.0,26.0,16.0,4.0,2.0,26.0,33.0,23.0,56.0,0.411,3.0,19.0,0.158,20.0,37.0,0.541,0.438,24.0,36.0,0.667,10.0,22.0,32.0,10.0,13.0,2.0,18.0,32.0,0,0
1,Abilene Christian,2024-11-12,0,1,Stephen F. Austin,REG (Non-Conf),-1,65.0,68.0,25.0,67.0,0.373,6.0,31.0,0.194,19.0,36.0,0.528,0.418,9.0,11.0,0.818,14.0,21.0,35.0,12.0,9.0,3.0,15.0,21.0,23.0,50.0,0.46,5.0,20.0,0.25,18.0,30.0,0.6,0.51,17.0,25.0,0.68,7.0,26.0,33.0,8.0,12.0,1.0,22.0,22.0,0,0
2,Abilene Christian,2024-11-16,0,1,North Texas,REG (Non-Conf),-1,60.0,71.0,24.0,69.0,0.348,8.0,35.0,0.229,16.0,34.0,0.471,0.406,4.0,7.0,0.571,12.0,16.0,28.0,13.0,10.0,0.0,19.0,19.0,26.0,49.0,0.531,3.0,10.0,0.3,23.0,39.0,0.59,0.561,16.0,22.0,0.727,7.0,25.0,32.0,11.0,12.0,7.0,23.0,17.0,0,0
3,Abilene Christian,2024-11-19,0,-1,Texas Tech,REG (Non-Conf),-1,40.0,66.0,12.0,52.0,0.231,3.0,23.0,0.13,9.0,29.0,0.31,0.26,13.0,15.0,0.867,13.0,12.0,25.0,6.0,13.0,0.0,21.0,20.0,20.0,46.0,0.435,11.0,23.0,0.478,9.0,23.0,0.391,0.554,15.0,21.0,0.714,13.0,21.0,34.0,17.0,11.0,10.0,26.0,20.0,0,0
4,Abilene Christian,2024-11-21,0,1,Western Kentucky,REG (Non-Conf),-1,64.0,68.0,23.0,51.0,0.451,6.0,22.0,0.273,17.0,29.0,0.586,0.51,12.0,17.0,0.706,9.0,21.0,30.0,12.0,9.0,0.0,20.0,15.0,26.0,66.0,0.394,8.0,33.0,0.242,18.0,33.0,0.545,0.455,8.0,13.0,0.615,14.0,16.0,30.0,15.0,13.0,2.0,17.0,16.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10883,Youngstown State,2025-02-20,0,-1,Detroit Mercy,REG (Conf),1,67.0,59.0,26.0,49.0,0.531,4.0,11.0,0.364,22.0,38.0,0.579,0.571,11.0,16.0,0.688,5.0,30.0,35.0,12.0,8.0,1.0,22.0,10.0,23.0,66.0,0.348,5.0,23.0,0.217,18.0,43.0,0.419,0.386,8.0,9.0,0.889,10.0,17.0,27.0,10.0,10.0,3.0,14.0,21.0,0,0
10884,Youngstown State,2025-02-22,0,-1,Oakland,REG (Conf),1,52.0,51.0,19.0,49.0,0.388,3.0,11.0,0.273,16.0,38.0,0.421,0.418,11.0,18.0,0.611,8.0,26.0,34.0,9.0,8.0,3.0,19.0,13.0,20.0,59.0,0.339,6.0,16.0,0.375,14.0,43.0,0.326,0.39,5.0,6.0,0.833,7.0,23.0,30.0,10.0,10.0,4.0,13.0,19.0,0,0
10885,Youngstown State,2025-02-26,0,-1,Robert Morris,REG (Conf),-1,53.0,76.0,18.0,55.0,0.327,5.0,18.0,0.278,13.0,37.0,0.351,0.373,12.0,14.0,0.857,10.0,21.0,31.0,12.0,6.0,0.0,17.0,15.0,29.0,57.0,0.509,10.0,22.0,0.455,19.0,35.0,0.543,0.596,8.0,13.0,0.615,7.0,27.0,34.0,19.0,8.0,6.0,13.0,15.0,0,0
10886,Youngstown State,2025-03-01,0,1,Cleveland State,REG (Conf),1,73.0,70.0,24.0,66.0,0.364,6.0,19.0,0.316,18.0,47.0,0.383,0.409,19.0,22.0,0.864,14.0,19.0,33.0,17.0,6.0,2.0,5.0,16.0,23.0,54.0,0.426,9.0,27.0,0.333,14.0,27.0,0.519,0.509,15.0,20.0,0.75,8.0,26.0,34.0,20.0,3.0,7.0,11.0,21.0,0,0
10887,Youngstown State,2025-03-04,0,-1,Wright State,CTOURN,-1,58.0,73.0,21.0,52.0,0.404,4.0,11.0,0.364,17.0,41.0,0.415,0.442,12.0,18.0,0.667,4.0,20.0,24.0,10.0,9.0,4.0,12.0,12.0,26.0,61.0,0.426,10.0,23.0,0.435,16.0,38.0,0.421,0.508,11.0,13.0,0.846,15.0,28.0,43.0,14.0,7.0,4.0,16.0,15.0,0,0

Set up adjusted Score Differential

In [15]:
blowout_threshold = 18  # adjusted score differential will only account up to this score difference

df['Score Differential'] = df['Team Score'] - df['Opponent Score']

df['Adjusted Score Differential'] = df['Score Differential'].abs()

df.loc[df['Adjusted Score Differential'] > blowout_threshold, 'Adjusted Score Differential'] = blowout_threshold

df['Adjusted Score Differential'] = df['Adjusted Score Differential']**(np.log(1.5)/np.log(blowout_threshold))

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential
0,Abilene Christian,2024-11-08,0,-1,Florida International,REG (Non-Conf),1,76.0,73.0,21.0,51.0,0.412,9.0,24.0,0.375,12.0,27.0,0.444,0.5,25.0,30.0,0.833,5.0,21.0,26.0,16.0,4.0,2.0,26.0,33.0,23.0,56.0,0.411,3.0,19.0,0.158,20.0,37.0,0.541,0.438,24.0,36.0,0.667,10.0,22.0,32.0,10.0,13.0,2.0,18.0,32.0,0,0,3.0,1.166625
1,Abilene Christian,2024-11-12,0,1,Stephen F. Austin,REG (Non-Conf),-1,65.0,68.0,25.0,67.0,0.373,6.0,31.0,0.194,19.0,36.0,0.528,0.418,9.0,11.0,0.818,14.0,21.0,35.0,12.0,9.0,3.0,15.0,21.0,23.0,50.0,0.46,5.0,20.0,0.25,18.0,30.0,0.6,0.51,17.0,25.0,0.68,7.0,26.0,33.0,8.0,12.0,1.0,22.0,22.0,0,0,-3.0,1.166625
2,Abilene Christian,2024-11-16,0,1,North Texas,REG (Non-Conf),-1,60.0,71.0,24.0,69.0,0.348,8.0,35.0,0.229,16.0,34.0,0.471,0.406,4.0,7.0,0.571,12.0,16.0,28.0,13.0,10.0,0.0,19.0,19.0,26.0,49.0,0.531,3.0,10.0,0.3,23.0,39.0,0.59,0.561,16.0,22.0,0.727,7.0,25.0,32.0,11.0,12.0,7.0,23.0,17.0,0,0,-11.0,1.399871
3,Abilene Christian,2024-11-19,0,-1,Texas Tech,REG (Non-Conf),-1,40.0,66.0,12.0,52.0,0.231,3.0,23.0,0.13,9.0,29.0,0.31,0.26,13.0,15.0,0.867,13.0,12.0,25.0,6.0,13.0,0.0,21.0,20.0,20.0,46.0,0.435,11.0,23.0,0.478,9.0,23.0,0.391,0.554,15.0,21.0,0.714,13.0,21.0,34.0,17.0,11.0,10.0,26.0,20.0,0,0,-26.0,1.5
4,Abilene Christian,2024-11-21,0,1,Western Kentucky,REG (Non-Conf),-1,64.0,68.0,23.0,51.0,0.451,6.0,22.0,0.273,17.0,29.0,0.586,0.51,12.0,17.0,0.706,9.0,21.0,30.0,12.0,9.0,0.0,20.0,15.0,26.0,66.0,0.394,8.0,33.0,0.242,18.0,33.0,0.545,0.455,8.0,13.0,0.615,14.0,16.0,30.0,15.0,13.0,2.0,17.0,16.0,0,0,-4.0,1.214668
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10883,Youngstown State,2025-02-20,0,-1,Detroit Mercy,REG (Conf),1,67.0,59.0,26.0,49.0,0.531,4.0,11.0,0.364,22.0,38.0,0.579,0.571,11.0,16.0,0.688,5.0,30.0,35.0,12.0,8.0,1.0,22.0,10.0,23.0,66.0,0.348,5.0,23.0,0.217,18.0,43.0,0.419,0.386,8.0,9.0,0.889,10.0,17.0,27.0,10.0,10.0,3.0,14.0,21.0,0,0,8.0,1.33871
10884,Youngstown State,2025-02-22,0,-1,Oakland,REG (Conf),1,52.0,51.0,19.0,49.0,0.388,3.0,11.0,0.273,16.0,38.0,0.421,0.418,11.0,18.0,0.611,8.0,26.0,34.0,9.0,8.0,3.0,19.0,13.0,20.0,59.0,0.339,6.0,16.0,0.375,14.0,43.0,0.326,0.39,5.0,6.0,0.833,7.0,23.0,30.0,10.0,10.0,4.0,13.0,19.0,0,0,1.0,1.0
10885,Youngstown State,2025-02-26,0,-1,Robert Morris,REG (Conf),-1,53.0,76.0,18.0,55.0,0.327,5.0,18.0,0.278,13.0,37.0,0.351,0.373,12.0,14.0,0.857,10.0,21.0,31.0,12.0,6.0,0.0,17.0,15.0,29.0,57.0,0.509,10.0,22.0,0.455,19.0,35.0,0.543,0.596,8.0,13.0,0.615,7.0,27.0,34.0,19.0,8.0,6.0,13.0,15.0,0,0,-23.0,1.5
10886,Youngstown State,2025-03-01,0,1,Cleveland State,REG (Conf),1,73.0,70.0,24.0,66.0,0.364,6.0,19.0,0.316,18.0,47.0,0.383,0.409,19.0,22.0,0.864,14.0,19.0,33.0,17.0,6.0,2.0,5.0,16.0,23.0,54.0,0.426,9.0,27.0,0.333,14.0,27.0,0.519,0.509,15.0,20.0,0.75,8.0,26.0,34.0,20.0,3.0,7.0,11.0,21.0,0,0,3.0,1.166625
10887,Youngstown State,2025-03-04,0,-1,Wright State,CTOURN,-1,58.0,73.0,21.0,52.0,0.404,4.0,11.0,0.364,17.0,41.0,0.415,0.442,12.0,18.0,0.667,4.0,20.0,24.0,10.0,9.0,4.0,12.0,12.0,26.0,61.0,0.426,10.0,23.0,0.435,16.0,38.0,0.421,0.508,11.0,13.0,0.846,15.0,28.0,43.0,14.0,7.0,4.0,16.0,15.0,0,0,-15.0,1.462122

Get per possession stats

In [16]:
Y = 0.44

df['Possessions'] = (
    df['Team FGA'] - df['Team ORB'] + df['Team TOV'] + Y*df['Team FTA'] +
    df['Opponent FGA'] - df['Opponent ORB'] + df['Opponent TOV'] + Y*df['Opponent FTA']
)/2

df['Team PPP'] = df['Team Score'] / df['Possessions']
df['Opponent PPP'] = df['Opponent Score'] / df['Possessions']
df['Tempo'] = 40*df['Possessions'] / (40 + 5*df['Overtimes Amount'])

# some games are missing stats due to delay/finished recently
df = df.loc[df['Team PPP'].notna(), :].reset_index(drop=True)

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo
0,Abilene Christian,2024-11-08,0,-1,Florida International,REG (Non-Conf),1,76.0,73.0,21.0,51.0,0.412,9.0,24.0,0.375,12.0,27.0,0.444,0.5,25.0,30.0,0.833,5.0,21.0,26.0,16.0,4.0,2.0,26.0,33.0,23.0,56.0,0.411,3.0,19.0,0.158,20.0,37.0,0.541,0.438,24.0,36.0,0.667,10.0,22.0,32.0,10.0,13.0,2.0,18.0,32.0,0,0,3.0,1.166625,82.52,0.920989,0.884634,82.52
1,Abilene Christian,2024-11-12,0,1,Stephen F. Austin,REG (Non-Conf),-1,65.0,68.0,25.0,67.0,0.373,6.0,31.0,0.194,19.0,36.0,0.528,0.418,9.0,11.0,0.818,14.0,21.0,35.0,12.0,9.0,3.0,15.0,21.0,23.0,50.0,0.46,5.0,20.0,0.25,18.0,30.0,0.6,0.51,17.0,25.0,0.68,7.0,26.0,33.0,8.0,12.0,1.0,22.0,22.0,0,0,-3.0,1.166625,74.42,0.873421,0.913733,74.42
2,Abilene Christian,2024-11-16,0,1,North Texas,REG (Non-Conf),-1,60.0,71.0,24.0,69.0,0.348,8.0,35.0,0.229,16.0,34.0,0.471,0.406,4.0,7.0,0.571,12.0,16.0,28.0,13.0,10.0,0.0,19.0,19.0,26.0,49.0,0.531,3.0,10.0,0.3,23.0,39.0,0.59,0.561,16.0,22.0,0.727,7.0,25.0,32.0,11.0,12.0,7.0,23.0,17.0,0,0,-11.0,1.399871,76.88,0.780437,0.923517,76.88
3,Abilene Christian,2024-11-19,0,-1,Texas Tech,REG (Non-Conf),-1,40.0,66.0,12.0,52.0,0.231,3.0,23.0,0.13,9.0,29.0,0.31,0.26,13.0,15.0,0.867,13.0,12.0,25.0,6.0,13.0,0.0,21.0,20.0,20.0,46.0,0.435,11.0,23.0,0.478,9.0,23.0,0.391,0.554,15.0,21.0,0.714,13.0,21.0,34.0,17.0,11.0,10.0,26.0,20.0,0,0,-26.0,1.5,67.42,0.593296,0.978938,67.42
4,Abilene Christian,2024-11-21,0,1,Western Kentucky,REG (Non-Conf),-1,64.0,68.0,23.0,51.0,0.451,6.0,22.0,0.273,17.0,29.0,0.586,0.51,12.0,17.0,0.706,9.0,21.0,30.0,12.0,9.0,0.0,20.0,15.0,26.0,66.0,0.394,8.0,33.0,0.242,18.0,33.0,0.545,0.455,8.0,13.0,0.615,14.0,16.0,30.0,15.0,13.0,2.0,17.0,16.0,0,0,-4.0,1.214668,72.1,0.887656,0.943135,72.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10883,Youngstown State,2025-02-20,0,-1,Detroit Mercy,REG (Conf),1,67.0,59.0,26.0,49.0,0.531,4.0,11.0,0.364,22.0,38.0,0.579,0.571,11.0,16.0,0.688,5.0,30.0,35.0,12.0,8.0,1.0,22.0,10.0,23.0,66.0,0.348,5.0,23.0,0.217,18.0,43.0,0.419,0.386,8.0,9.0,0.889,10.0,17.0,27.0,10.0,10.0,3.0,14.0,21.0,0,0,8.0,1.33871,73.5,0.911565,0.802721,73.5
10884,Youngstown State,2025-02-22,0,-1,Oakland,REG (Conf),1,52.0,51.0,19.0,49.0,0.388,3.0,11.0,0.273,16.0,38.0,0.421,0.418,11.0,18.0,0.611,8.0,26.0,34.0,9.0,8.0,3.0,19.0,13.0,20.0,59.0,0.339,6.0,16.0,0.375,14.0,43.0,0.326,0.39,5.0,6.0,0.833,7.0,23.0,30.0,10.0,10.0,4.0,13.0,19.0,0,0,1.0,1.0,67.78,0.767188,0.752434,67.78
10885,Youngstown State,2025-02-26,0,-1,Robert Morris,REG (Conf),-1,53.0,76.0,18.0,55.0,0.327,5.0,18.0,0.278,13.0,37.0,0.351,0.373,12.0,14.0,0.857,10.0,21.0,31.0,12.0,6.0,0.0,17.0,15.0,29.0,57.0,0.509,10.0,22.0,0.455,19.0,35.0,0.543,0.596,8.0,13.0,0.615,7.0,27.0,34.0,19.0,8.0,6.0,13.0,15.0,0,0,-23.0,1.5,68.44,0.774401,1.110462,68.44
10886,Youngstown State,2025-03-01,0,1,Cleveland State,REG (Conf),1,73.0,70.0,24.0,66.0,0.364,6.0,19.0,0.316,18.0,47.0,0.383,0.409,19.0,22.0,0.864,14.0,19.0,33.0,17.0,6.0,2.0,5.0,16.0,23.0,54.0,0.426,9.0,27.0,0.333,14.0,27.0,0.519,0.509,15.0,20.0,0.75,8.0,26.0,34.0,20.0,3.0,7.0,11.0,21.0,0,0,3.0,1.166625,66.24,1.102053,1.056763,66.24
10887,Youngstown State,2025-03-04,0,-1,Wright State,CTOURN,-1,58.0,73.0,21.0,52.0,0.404,4.0,11.0,0.364,17.0,41.0,0.415,0.442,12.0,18.0,0.667,4.0,20.0,24.0,10.0,9.0,4.0,12.0,12.0,26.0,61.0,0.426,10.0,23.0,0.435,16.0,38.0,0.421,0.508,11.0,13.0,0.846,15.0,28.0,43.0,14.0,7.0,4.0,16.0,15.0,0,0,-15.0,1.462122,67.82,0.855205,1.076379,67.82

Save

In [17]:
df.to_parquet(f'../data/unprocessed/womens_sports_reference/full_season_sports_reference_{SEASON}.parquet')

'Done'

'Done'