# Women's Scrape Schedule

Get ratings of each team in a given year. This file needs to be ran for every relevant year (starting in 2008).

### Web Scraping

Fair warning that this program unfortunately takes a very long time to run due to web scraping limits set by Sports Reference

In [1]:
import pandas as pd
import numpy as np
import time

pd.set_option('display.max_columns', 100)

season = 2019

df_active_teams = pd.read_html('https://www.sports-reference.com/cbb/schools/index.html')[0]
time.sleep(2)

df_active_teams = df_active_teams.loc[~df_active_teams['School'].isin([np.NaN, 'School']), :].reset_index(drop=True)

df_active_teams['From'] = pd.to_numeric(df_active_teams['From'], errors='coerce')
df_active_teams['To'] = pd.to_numeric(df_active_teams['To'], errors='coerce')

df_active_teams = df_active_teams.loc[(df_active_teams['To'] >= season) & (df_active_teams['From'] <= season), :].reset_index(drop=True)

if season == 2021:  # if 2021, remove ivy league because they cancelled their season in 2021
    df_active_teams = df_active_teams.loc[
        ~df_active_teams['School'].isin(['Princeton', 'Harvard', 'Yale', 'Pennsylvania', 'Brown', 'Columbia', 'Cornell', 'Dartmouth']), 
        :
    ].reset_index(drop=True)

df_active_teams

,Rk,School,"City, State",From,To,Yrs,G,W,L,W-L%,SRS,SOS,AP,CREG,CTRN,NCAA,FF,NC
0,1,Abilene Christian,"Abilene, Texas",1971,2025,15,452,241,211,.533,-7.59,-5.35,0,0,2,2,0,0
1,2,Air Force,"USAF Academy, Colorado",1958,2025,68,1873,797,1076,.426,-2.86,1.37,0,1,0,4,0,0
2,3,Akron,"Akron, Ohio",1902,2025,74,1748,1051,697,.601,0.07,-1.60,0,9,6,6,0,0
3,4,Alabama,"Tuscaloosa, Alabama",1913,2025,112,2925,1817,1107,.621,8.18,5.06,18,10,9,25,1,0
4,5,Alabama A&M,"Normal, Alabama",2000,2025,26,752,287,465,.382,-16.72,-11.01,0,1,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
348,489,Wright State,"Dayton, Ohio",1988,2025,38,1160,646,514,.557,-1.41,-2.60,0,4,4,4,0,0
349,490,Wyoming,"Laramie, Wyoming",1905,2025,120,2910,1622,1288,.557,2.69,2.76,4,21,3,16,1,1
350,491,Xavier,"Cincinnati, Ohio",1920,2025,104,2726,1630,1096,.598,6.19,4.05,13,18,9,29,0,0
351,492,Yale,"New Haven, Connecticut",1896,2025,129,3111,1585,1524,.510,-5.81,-4.43,1,16,3,7,0,0
352,493,Youngstown State,"Youngstown, Ohio",1948,2025,45,1323,549,774,.415,-7.88,-3.56,0,1,0,0,0,0

In [2]:
from datetime import datetime

cutoff_dates = {
    2008: datetime(2008, 3, 21),
    2009: datetime(2009, 3, 20),
    2010: datetime(2010, 3, 19),
    2011: datetime(2011, 3, 18),
    2012: datetime(2012, 3, 16),
    2013: datetime(2013, 3, 22),
    2014: datetime(2014, 3, 21),
    2015: datetime(2015, 3, 19),
    2016: datetime(2016, 3, 17),
    2017: datetime(2017, 3, 16),
    2018: datetime(2018, 3, 15),
    2019: datetime(2019, 3, 21),
    2020: datetime(2020, 3, 13),  # cancelled
    2021: datetime(2021, 3, 24),
    2022: datetime(2022, 3, 17),
    2023: datetime(2023, 3, 16),
    2024: datetime(2024, 3, 21),
    2025: datetime(2025, 3, 20),
}

cutoff_dates[season]

datetime.datetime(2019, 3, 21, 0, 0)

Get school names used in Sports Reference URL

In [3]:
df_active_teams['URL School'] = df_active_teams['School']

# hard code some schools that cause issues
df_active_teams.loc[df_active_teams['School'] == 'Bowling Green', 'URL School'] = 'Bowling Green State'
df_active_teams.loc[df_active_teams['School'] == 'BYU', 'URL School'] = 'Brigham Young'
df_active_teams.loc[df_active_teams['School'] == 'Louisiana', 'URL School'] = 'Louisiana Lafayette'
df_active_teams.loc[df_active_teams['School'] == 'LSU', 'URL School'] = 'Louisiana State'
df_active_teams.loc[df_active_teams['School'] == 'Ole Miss', 'URL School'] = 'Mississippi'
df_active_teams.loc[df_active_teams['School'] == 'Pitt', 'URL School'] = 'Pittsburgh'
df_active_teams.loc[df_active_teams['School'] == 'SMU', 'URL School'] = 'Southern Methodist'
df_active_teams.loc[df_active_teams['School'] == 'UAB', 'URL School'] = 'Alabama Birmingham'
df_active_teams.loc[df_active_teams['School'] == 'UCF', 'URL School'] = 'Central Florida'
df_active_teams.loc[df_active_teams['School'] == 'USC', 'URL School'] = 'Southern California'
df_active_teams.loc[df_active_teams['School'] == 'UTEP', 'URL School'] = 'Texas El Paso'
df_active_teams.loc[df_active_teams['School'] == 'UTSA', 'URL School'] = 'Texas San Antonio'
df_active_teams.loc[df_active_teams['School'] == 'Sam Houston', 'URL School'] = 'Sam Houston State'
df_active_teams.loc[df_active_teams['School'] == 'Houston Christian', 'URL School'] = 'Houston Baptist'
df_active_teams.loc[df_active_teams['School'] == 'Kansas City', 'URL School'] = 'Missouri Kansas City'
df_active_teams.loc[df_active_teams['School'] == 'Little Rock', 'URL School'] = 'Arkansas Little Rock'
df_active_teams.loc[df_active_teams['School'] == 'NC State', 'URL School'] = 'North Carolina State'
df_active_teams.loc[df_active_teams['School'] == 'Omaha', 'URL School'] = 'Nebraska Omaha'
df_active_teams.loc[df_active_teams['School'] == 'Purdue Fort Wayne', 'URL School'] = 'IPFW'
df_active_teams.loc[df_active_teams['School'] == 'TCU', 'URL School'] = 'Texas Christian'
df_active_teams.loc[df_active_teams['School'] == 'Texas-Rio Grande Valley', 'URL School'] = 'Texas Pan American'
df_active_teams.loc[df_active_teams['School'] == 'The Citadel', 'URL School'] = 'Citadel'
df_active_teams.loc[df_active_teams['School'] == 'Utah Tech', 'URL School'] = 'Dixie State'
df_active_teams.loc[df_active_teams['School'] == 'St. Thomas', 'URL School'] = 'St. Thomas MN'
df_active_teams.loc[df_active_teams['School'] == 'UC Berkley', 'URL School'] = 'California'
df_active_teams.loc[df_active_teams['School'] == 'UT Arlington', 'URL School'] = 'Texas Arlington'
df_active_teams.loc[df_active_teams['School'] == 'FDU', 'URL School'] = 'Fairleigh Dickinson'
df_active_teams.loc[df_active_teams['School'] == 'Hartford Hawks', 'URL School'] = 'Hartford'
df_active_teams.loc[df_active_teams['School'] == 'Savannah State Tigers', 'URL School'] = 'Savannah State'
df_active_teams.loc[df_active_teams['School'] == 'St. Francis (NY) Terriers', 'URL School'] = 'St. Francis (NY)'
df_active_teams.loc[df_active_teams['School'] == 'East Texas A&M', 'URL School'] = 'Texas A&M Commerce'
df_active_teams.loc[df_active_teams['School'] == 'IU Indy', 'URL School'] = 'IUPUI'

df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UC\s', 'California ', regex=True)
df_active_teams['URL School'] = df_active_teams['URL School'].str.replace(r'^UNC\s', 'North Carolina ', regex=True)

In [4]:
urls = (
    'https://www.sports-reference.com/cbb/schools/' +
    df_active_teams['URL School'].str.replace(' ', '-', regex=False).str.replace('[)(&.\']', '', regex=True).str.replace('--', '-', regex=False).str.lower() +
    '/women/' + str(season) +
    '-gamelogs.html'
)

urls

0      https://www.sports-reference.com/cbb/schools/a...
1      https://www.sports-reference.com/cbb/schools/a...
2      https://www.sports-reference.com/cbb/schools/a...
3      https://www.sports-reference.com/cbb/schools/a...
4      https://www.sports-reference.com/cbb/schools/a...
                             ...
348    https://www.sports-reference.com/cbb/schools/w...
349    https://www.sports-reference.com/cbb/schools/w...
350    https://www.sports-reference.com/cbb/schools/x...
351    https://www.sports-reference.com/cbb/schools/y...
352    https://www.sports-reference.com/cbb/schools/y...
Name: URL School, Length: 353, dtype: object

In [5]:
from urllib.error import HTTPError
from tqdm.notebook import tqdm

problems = []

l = []
loop = tqdm(
    np.array((df_active_teams['School'], urls)).transpose(),  # get both school and url into loop iteration
    bar_format='{bar}{percentage:3.0f}%{r_bar}   {desc}'  # make the description not affect bar location
)
for (school, url) in loop:
  try:
    loop.set_description(f'{school}')
    # print(f'{i:03d}: {url}')
    df_team_season = pd.read_html(url)[-1]  # schools that were ranked have that info as the first table on the site
    time.sleep(2)

    df_team_season.columns = [i[1] if 'Unnamed' in i[0] else i[0] + ' ' + i[1] for i in df_team_season.columns]
    df_team_season.insert(2, 'Team', school)
    l.append(df_team_season)
  except ValueError as e:
    print(f'{url} | ValueError: {e}')
    time.sleep(2)
  except HTTPError as e:
    if e.code == 404:
      print(f'{url} | {e}')
      time.sleep(2)
    else:
      print(f'{url} | {e}')
      break

df = pd.concat(l, ignore_index=True)

df

            0%| 0/353 [00:00<?, ?it/s]

https://www.sports-reference.com/cbb/schools/citadel/women/2019-gamelogs.html | HTTP Error 404: Not Found
https://www.sports-reference.com/cbb/schools/virginia-military-institute/women/2019-gamelogs.html | HTTP Error 404: Not Found

,Rk,Gtm,Team,Date,Unnamed: 3_level_1,Opp,Type,Score Rslt,Score Tm,Score Opp,Score OT,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF
0,1,1,Abilene Christian,2018-11-09,NaN,Univ of the SW,REG (Non-Conf),W,90,47,NaN,32,62,.516,11,30,.367,21,32,.656,.605,15,29,.517,15,20,35,23,19,2,15,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2,Abilene Christian,2018-11-15,NaN,Howard Payne,REG (Non-Conf),W,98,43,NaN,36,79,.456,12,36,.333,24,43,.558,.532,14,20,.700,23,36,59,27,11,7,19,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,3,Abilene Christian,2018-11-17,NaN,Eastern N.M.,REG (Non-Conf),W,78,46,NaN,29,64,.453,9,21,.429,20,43,.465,.523,11,15,.733,17,31,48,16,4,7,20,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,4,Abilene Christian,2018-11-20,@,New Mexico State,REG (Non-Conf),W,58,46,NaN,18,63,.286,5,29,.172,13,34,.382,.325,17,24,.708,14,23,37,10,5,2,12,15,16,52,.308,4,22,.182,12,30,.400,.346,10,19,.526,9,22,31,10,8,7,21,19
4,5,5,Abilene Christian,2018-11-23,NaN,Texas Southern,REG (Non-Conf),W,81,39,NaN,30,58,.517,6,21,.286,24,37,.649,.569,15,22,.682,12,30,42,22,9,7,15,18,11,57,.193,4,22,.182,7,35,.200,.228,13,25,.520,14,16,30,7,9,0,15,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11855,30,30,Youngstown State,2019-03-06,NaN,Milwaukee,CTOURN,W,64,58,NaN,18,50,.360,6,15,.400,12,35,.343,.420,22,28,.786,11,23,34,9,5,5,17,9,24,60,.400,2,18,.111,22,42,.524,.417,8,14,.571,6,16,22,12,9,9,7,25
11856,31,31,Youngstown State,2019-03-11,@,Green Bay,CTOURN,L,53,55,NaN,17,52,.327,13,32,.406,4,20,.200,.452,6,7,.857,5,27,32,14,4,0,13,16,21,55,.382,4,16,.250,17,39,.436,.418,9,18,.500,10,25,35,18,11,4,8,13
11857,Rk,Gtm,Youngstown State,Date,NaN,Opp,Type,Rslt,Tm,Opp,OT,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,FG,FGA,FG%,3P,3PA,3P%,2P,2PA,2P%,eFG%,FT,FTA,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF
11858,32,32,Youngstown State,2019-03-21,@,Cincinnati,WNIT,L,62,76,NaN,24,55,.436,5,21,.238,19,34,.559,.482,9,14,.643,3,25,28,13,3,2,15,9,29,69,.420,5,9,.556,24,60,.400,.457,13,13,1.000,13,25,38,19,8,3,7,14
11859,NaN,NaN,Youngstown State,NaN,NaN,NaN,NaN,22-10,2204,1842,NaN,761,1802,.422,273,816,.335,488,986,.495,.498,409,534,.766,263,861,1124,492,143,111,432,433,663,1770,.375,169,550,.307,494,1220,.405,.422,263,401,.656,246,660,906,329,224,104,351,533

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11860 entries, 0 to 11859
Data columns (total 53 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rk                  11509 non-null  object
 1   Gtm                 11509 non-null  object
 2   Team                11860 non-null  object
 3   Date                11509 non-null  object
 4   Unnamed: 3_level_1  5403 non-null   object
 5   Opp                 11509 non-null  object
 6   Type                11509 non-null  object
 7   Score Rslt          11860 non-null  object
 8   Score Tm            11860 non-null  object
 9   Score Opp           11860 non-null  object
 10  Score OT            906 non-null    object
 11  Team FG             11860 non-null  object
 12  Team FGA            11860 non-null  object
 13  Team FG%            11860 non-null  object
 14  Team 3P             11860 non-null  object
 15  Team 3PA            11860 non-null  object
 16  Team 3P%            11860 non-null  object
 17  Team 2P             11860 non-null  object
 18  Team 2PA            11860 non-null  object
 19  Team 2P%            11860 non-null  object
 20  Team eFG%           11860 non-null  object
 21  Team FT             11860 non-null  object
 22  Team FTA            11860 non-null  object
 23  Team FT%            11851 non-null  object
 24  Team ORB            11860 non-null  object
 25  Team DRB            11860 non-null  object
 26  Team TRB            11860 non-null  object
 27  Team AST            11860 non-null  object
 28  Team STL            11860 non-null  object
 29  Team BLK            11860 non-null  object
 30  Team TOV            11860 non-null  object
 31  Team PF             11860 non-null  object
 32  Opponent FG         11590 non-null  object
 33  Opponent FGA        11590 non-null  object
 34  Opponent FG%        11590 non-null  object
 35  Opponent 3P         11590 non-null  object
 36  Opponent 3PA        11590 non-null  object
 37  Opponent 3P%        11590 non-null  object
 38  Opponent 2P         11590 non-null  object
 39  Opponent 2PA        11590 non-null  object
 40  Opponent 2P%        11590 non-null  object
 41  Opponent eFG%       11590 non-null  object
 42  Opponent FT         11590 non-null  object
 43  Opponent FTA        11590 non-null  object
 44  Opponent FT%        11581 non-null  object
 45  Opponent ORB        11590 non-null  object
 46  Opponent DRB        11590 non-null  object
 47  Opponent TRB        11590 non-null  object
 48  Opponent AST        11590 non-null  object
 49  Opponent STL        11590 non-null  object
 50  Opponent BLK        11590 non-null  object
 51  Opponent TOV        11590 non-null  object
 52  Opponent PF         11590 non-null  object
dtypes: object(53)
memory usage: 4.8+ MB

### Data Setup

In [7]:
temp = df.copy()

In [8]:
df = temp.copy()

Fix column names and drop useless columns

In [9]:
df.columns = (
    ['G', 'Gtm', 'Team', 'Date', 'Location', 'Opponent', 'Type', 'Result', 'Team Score', 'Opponent Score', 'OT'] +
    [c for c in df.columns[11:]]
)

# use "Team" as prefix instead of "School"
df.columns = df.columns.str.replace('School', 'Team', regex=False)

# drop columns that are completely null
df = df[[c for c in df.columns if df.loc[:, c].notna().any()]].copy()

# drop columns without a name
df = df.loc[:, ~df.columns.str.contains('^Unnamed', regex=True)]

# drop rows that aren't games
df = df.loc[(df['Date'].notna()) & (df['Result'].isin(['W', 'L'])), :].reset_index(drop=True)

# drop useless columns
df.drop(columns=['G', 'Gtm'], inplace=True)

df

,Team,Date,Location,Opponent,Type,Result,Team Score,Opponent Score,OT,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF
0,Abilene Christian,2018-11-09,NaN,Univ of the SW,REG (Non-Conf),W,90,47,NaN,32,62,.516,11,30,.367,21,32,.656,.605,15,29,.517,15,20,35,23,19,2,15,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abilene Christian,2018-11-15,NaN,Howard Payne,REG (Non-Conf),W,98,43,NaN,36,79,.456,12,36,.333,24,43,.558,.532,14,20,.700,23,36,59,27,11,7,19,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Abilene Christian,2018-11-17,NaN,Eastern N.M.,REG (Non-Conf),W,78,46,NaN,29,64,.453,9,21,.429,20,43,.465,.523,11,15,.733,17,31,48,16,4,7,20,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Abilene Christian,2018-11-20,@,New Mexico State,REG (Non-Conf),W,58,46,NaN,18,63,.286,5,29,.172,13,34,.382,.325,17,24,.708,14,23,37,10,5,2,12,15,16,52,.308,4,22,.182,12,30,.400,.346,10,19,.526,9,22,31,10,8,7,21,19
4,Abilene Christian,2018-11-23,NaN,Texas Southern,REG (Non-Conf),W,81,39,NaN,30,58,.517,6,21,.286,24,37,.649,.569,15,22,.682,12,30,42,22,9,7,15,18,11,57,.193,4,22,.182,7,35,.200,.228,13,25,.520,14,16,30,7,9,0,15,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11036,Youngstown State,2019-02-24,@,Wright State,REG (Conf),L,65,70,NaN,24,57,.421,6,26,.231,18,31,.581,.474,11,13,.846,7,22,29,12,3,2,12,17,27,68,.397,2,14,.143,25,54,.463,.412,14,20,.700,19,25,44,6,6,1,5,15
11037,Youngstown State,2019-03-02,@,Cleveland State,REG (Conf),W,74,61,NaN,28,57,.491,13,28,.464,15,29,.517,.605,5,9,.556,8,29,37,18,3,5,13,19,21,59,.356,3,16,.188,18,43,.419,.381,16,22,.727,8,23,31,7,9,2,10,13
11038,Youngstown State,2019-03-06,NaN,Milwaukee,CTOURN,W,64,58,NaN,18,50,.360,6,15,.400,12,35,.343,.420,22,28,.786,11,23,34,9,5,5,17,9,24,60,.400,2,18,.111,22,42,.524,.417,8,14,.571,6,16,22,12,9,9,7,25
11039,Youngstown State,2019-03-11,@,Green Bay,CTOURN,L,53,55,NaN,17,52,.327,13,32,.406,4,20,.200,.452,6,7,.857,5,27,32,14,4,0,13,16,21,55,.382,4,16,.250,17,39,.436,.418,9,18,.500,10,25,35,18,11,4,8,13
11040,Youngstown State,2019-03-21,@,Cincinnati,WNIT,L,62,76,NaN,24,55,.436,5,21,.238,19,34,.559,.482,9,14,.643,3,25,28,13,3,2,15,9,29,69,.420,5,9,.556,24,60,.400,.457,13,13,1.000,13,25,38,19,8,3,7,14

Get overtime information

In [10]:
# remove games that have not been played
df = df.loc[(df['Result'].notna()) & (df['Result'] != 'W/L'), :].reset_index(drop=True)

# get overtimes amount
df['Overtimes Amount'] = (
    df['OT']
    .apply(
        lambda x: 
        1 if x == 'OT' 
        else int(x[:-2]) if isinstance(x, str) and x.endswith('OT') and len(x) > 2 
        else 0
    )
)

# binary overtime flag
df['Overtime'] = df.pop('OT').notna().astype('int8')

# reformat result column
df['Result'] = df['Result'].str[:1].map({'W': 1, 'L': -1}).astype('int8')

df

,Team,Date,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,Abilene Christian,2018-11-09,NaN,Univ of the SW,REG (Non-Conf),1,90,47,32,62,.516,11,30,.367,21,32,.656,.605,15,29,.517,15,20,35,23,19,2,15,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
1,Abilene Christian,2018-11-15,NaN,Howard Payne,REG (Non-Conf),1,98,43,36,79,.456,12,36,.333,24,43,.558,.532,14,20,.700,23,36,59,27,11,7,19,24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2,Abilene Christian,2018-11-17,NaN,Eastern N.M.,REG (Non-Conf),1,78,46,29,64,.453,9,21,.429,20,43,.465,.523,11,15,.733,17,31,48,16,4,7,20,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
3,Abilene Christian,2018-11-20,@,New Mexico State,REG (Non-Conf),1,58,46,18,63,.286,5,29,.172,13,34,.382,.325,17,24,.708,14,23,37,10,5,2,12,15,16,52,.308,4,22,.182,12,30,.400,.346,10,19,.526,9,22,31,10,8,7,21,19,0,0
4,Abilene Christian,2018-11-23,NaN,Texas Southern,REG (Non-Conf),1,81,39,30,58,.517,6,21,.286,24,37,.649,.569,15,22,.682,12,30,42,22,9,7,15,18,11,57,.193,4,22,.182,7,35,.200,.228,13,25,.520,14,16,30,7,9,0,15,24,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11036,Youngstown State,2019-02-24,@,Wright State,REG (Conf),-1,65,70,24,57,.421,6,26,.231,18,31,.581,.474,11,13,.846,7,22,29,12,3,2,12,17,27,68,.397,2,14,.143,25,54,.463,.412,14,20,.700,19,25,44,6,6,1,5,15,0,0
11037,Youngstown State,2019-03-02,@,Cleveland State,REG (Conf),1,74,61,28,57,.491,13,28,.464,15,29,.517,.605,5,9,.556,8,29,37,18,3,5,13,19,21,59,.356,3,16,.188,18,43,.419,.381,16,22,.727,8,23,31,7,9,2,10,13,0,0
11038,Youngstown State,2019-03-06,NaN,Milwaukee,CTOURN,1,64,58,18,50,.360,6,15,.400,12,35,.343,.420,22,28,.786,11,23,34,9,5,5,17,9,24,60,.400,2,18,.111,22,42,.524,.417,8,14,.571,6,16,22,12,9,9,7,25,0,0
11039,Youngstown State,2019-03-11,@,Green Bay,CTOURN,-1,53,55,17,52,.327,13,32,.406,4,20,.200,.452,6,7,.857,5,27,32,14,4,0,13,16,21,55,.382,4,16,.250,17,39,.436,.418,9,18,.500,10,25,35,18,11,4,8,13,0,0
11040,Youngstown State,2019-03-21,@,Cincinnati,WNIT,-1,62,76,24,55,.436,5,21,.238,19,34,.559,.482,9,14,.643,3,25,28,13,3,2,15,9,29,69,.420,5,9,.556,24,60,.400,.457,13,13,1.000,13,25,38,19,8,3,7,14,0,0

Reformat location column for home/neutral/away

In [11]:
df['Location'] = df['Location'].map({np.NaN: 1, 'N': 0, '@': -1}).astype('int8')

df['Location']

0        1
1        1
2        1
3       -1
4        1
        ..
11036   -1
11037   -1
11038    1
11039   -1
11040   -1
Name: Location, Length: 11041, dtype: int8

Other general fixes

In [12]:
# fix dates
df['Date'] = pd.to_datetime(df['Date'])

# specify before and after NCAA tournament
df.insert(df.columns.get_loc('Date') + 1, 'NCAA Tournament', (df['Date'] > cutoff_dates[season]).astype(int))

# fix column types
df.loc[:, df.columns.str.contains('Team ', regex=False)] = df.loc[:, df.columns.str.contains('Team ', regex=False)].astype('float64')
df.loc[:, df.columns.str.contains('Opponent ', regex=False)] = df.loc[:, df.columns.str.contains('Opponent ', regex=False)].astype('float64')

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,Abilene Christian,2018-11-09,0,1,Univ of the SW,REG (Non-Conf),1,90.0,47.0,32.0,62.0,0.516,11.0,30.0,0.367,21.0,32.0,0.656,0.605,15.0,29.0,0.517,15.0,20.0,35.0,23.0,19.0,2.0,15.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
1,Abilene Christian,2018-11-15,0,1,Howard Payne,REG (Non-Conf),1,98.0,43.0,36.0,79.0,0.456,12.0,36.0,0.333,24.0,43.0,0.558,0.532,14.0,20.0,0.7,23.0,36.0,59.0,27.0,11.0,7.0,19.0,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
2,Abilene Christian,2018-11-17,0,1,Eastern N.M.,REG (Non-Conf),1,78.0,46.0,29.0,64.0,0.453,9.0,21.0,0.429,20.0,43.0,0.465,0.523,11.0,15.0,0.733,17.0,31.0,48.0,16.0,4.0,7.0,20.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0
3,Abilene Christian,2018-11-20,0,-1,New Mexico State,REG (Non-Conf),1,58.0,46.0,18.0,63.0,0.286,5.0,29.0,0.172,13.0,34.0,0.382,0.325,17.0,24.0,0.708,14.0,23.0,37.0,10.0,5.0,2.0,12.0,15.0,16.0,52.0,0.308,4.0,22.0,0.182,12.0,30.0,0.4,0.346,10.0,19.0,0.526,9.0,22.0,31.0,10.0,8.0,7.0,21.0,19.0,0,0
4,Abilene Christian,2018-11-23,0,1,Texas Southern,REG (Non-Conf),1,81.0,39.0,30.0,58.0,0.517,6.0,21.0,0.286,24.0,37.0,0.649,0.569,15.0,22.0,0.682,12.0,30.0,42.0,22.0,9.0,7.0,15.0,18.0,11.0,57.0,0.193,4.0,22.0,0.182,7.0,35.0,0.2,0.228,13.0,25.0,0.52,14.0,16.0,30.0,7.0,9.0,0.0,15.0,24.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11036,Youngstown State,2019-02-24,0,-1,Wright State,REG (Conf),-1,65.0,70.0,24.0,57.0,0.421,6.0,26.0,0.231,18.0,31.0,0.581,0.474,11.0,13.0,0.846,7.0,22.0,29.0,12.0,3.0,2.0,12.0,17.0,27.0,68.0,0.397,2.0,14.0,0.143,25.0,54.0,0.463,0.412,14.0,20.0,0.7,19.0,25.0,44.0,6.0,6.0,1.0,5.0,15.0,0,0
11037,Youngstown State,2019-03-02,0,-1,Cleveland State,REG (Conf),1,74.0,61.0,28.0,57.0,0.491,13.0,28.0,0.464,15.0,29.0,0.517,0.605,5.0,9.0,0.556,8.0,29.0,37.0,18.0,3.0,5.0,13.0,19.0,21.0,59.0,0.356,3.0,16.0,0.188,18.0,43.0,0.419,0.381,16.0,22.0,0.727,8.0,23.0,31.0,7.0,9.0,2.0,10.0,13.0,0,0
11038,Youngstown State,2019-03-06,0,1,Milwaukee,CTOURN,1,64.0,58.0,18.0,50.0,0.36,6.0,15.0,0.4,12.0,35.0,0.343,0.42,22.0,28.0,0.786,11.0,23.0,34.0,9.0,5.0,5.0,17.0,9.0,24.0,60.0,0.4,2.0,18.0,0.111,22.0,42.0,0.524,0.417,8.0,14.0,0.571,6.0,16.0,22.0,12.0,9.0,9.0,7.0,25.0,0,0
11039,Youngstown State,2019-03-11,0,-1,Green Bay,CTOURN,-1,53.0,55.0,17.0,52.0,0.327,13.0,32.0,0.406,4.0,20.0,0.2,0.452,6.0,7.0,0.857,5.0,27.0,32.0,14.0,4.0,0.0,13.0,16.0,21.0,55.0,0.382,4.0,16.0,0.25,17.0,39.0,0.436,0.418,9.0,18.0,0.5,10.0,25.0,35.0,18.0,11.0,4.0,8.0,13.0,0,0
11040,Youngstown State,2019-03-21,0,-1,Cincinnati,WNIT,-1,62.0,76.0,24.0,55.0,0.436,5.0,21.0,0.238,19.0,34.0,0.559,0.482,9.0,14.0,0.643,3.0,25.0,28.0,13.0,3.0,2.0,15.0,9.0,29.0,69.0,0.42,5.0,9.0,0.556,24.0,60.0,0.4,0.457,13.0,13.0,1.0,13.0,25.0,38.0,19.0,8.0,3.0,7.0,14.0,0,0

Remap opponent names because the opponents sometimes have a different naming convention than the team names

In [13]:
# create new dataframe from opposite perspective    team <--> opponent
df_switch = df.copy()

df_switch.columns = df_switch.columns.str.replace(
    'Team', '_TEMP_', regex=False
).str.replace(
    'Opponent', 'Team', regex=False
).str.replace(
    '_TEMP_', 'Opponent', regex=False
)

df_switch[['Location', 'Result']] *= -1

# get fixed opponent names
df['Opponent'] = pd.merge(
    df, df_switch,
    how='left',
    on=(
        ['Date', 'Location', 'Result'] +
        list(df.loc[:, df.columns.str.contains('Team ')].columns) +
        list(df.loc[:, df.columns.str.contains('Opponent ')].columns)
    )
)['Opponent_y']

# Remove matchups that are not division 1
df = df.loc[df['Opponent'].notna(), :].reset_index(drop=True)

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime
0,Abilene Christian,2018-11-20,0,-1,New Mexico State,REG (Non-Conf),1,58.0,46.0,18.0,63.0,0.286,5.0,29.0,0.172,13.0,34.0,0.382,0.325,17.0,24.0,0.708,14.0,23.0,37.0,10.0,5.0,2.0,12.0,15.0,16.0,52.0,0.308,4.0,22.0,0.182,12.0,30.0,0.4,0.346,10.0,19.0,0.526,9.0,22.0,31.0,10.0,8.0,7.0,21.0,19.0,0,0
1,Abilene Christian,2018-11-23,0,1,Texas Southern,REG (Non-Conf),1,81.0,39.0,30.0,58.0,0.517,6.0,21.0,0.286,24.0,37.0,0.649,0.569,15.0,22.0,0.682,12.0,30.0,42.0,22.0,9.0,7.0,15.0,18.0,11.0,57.0,0.193,4.0,22.0,0.182,7.0,35.0,0.2,0.228,13.0,25.0,0.52,14.0,16.0,30.0,7.0,9.0,0.0,15.0,24.0,0,0
2,Abilene Christian,2018-11-24,0,-1,UTEP,REG (Non-Conf),1,70.0,69.0,24.0,47.0,0.511,14.0,28.0,0.5,10.0,19.0,0.526,0.66,8.0,11.0,0.727,7.0,19.0,26.0,19.0,4.0,2.0,17.0,13.0,31.0,59.0,0.525,4.0,16.0,0.25,27.0,43.0,0.628,0.559,3.0,3.0,1.0,5.0,16.0,21.0,24.0,5.0,2.0,9.0,11.0,0,0
3,Abilene Christian,2018-11-28,0,-1,Tulsa,REG (Non-Conf),-1,63.0,75.0,22.0,49.0,0.449,6.0,19.0,0.316,16.0,30.0,0.533,0.51,13.0,22.0,0.591,10.0,23.0,33.0,14.0,3.0,3.0,22.0,21.0,25.0,63.0,0.397,7.0,21.0,0.333,18.0,42.0,0.429,0.452,18.0,26.0,0.692,12.0,17.0,29.0,15.0,6.0,3.0,7.0,21.0,0,0
4,Abilene Christian,2018-12-08,0,1,Arkansas,REG (Non-Conf),-1,68.0,80.0,24.0,54.0,0.444,5.0,14.0,0.357,19.0,40.0,0.475,0.491,15.0,20.0,0.75,9.0,24.0,33.0,14.0,4.0,2.0,20.0,18.0,28.0,65.0,0.431,10.0,29.0,0.345,18.0,36.0,0.5,0.508,14.0,20.0,0.7,11.0,19.0,30.0,16.0,13.0,4.0,8.0,17.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10761,Youngstown State,2019-02-24,0,-1,Wright State,REG (Conf),-1,65.0,70.0,24.0,57.0,0.421,6.0,26.0,0.231,18.0,31.0,0.581,0.474,11.0,13.0,0.846,7.0,22.0,29.0,12.0,3.0,2.0,12.0,17.0,27.0,68.0,0.397,2.0,14.0,0.143,25.0,54.0,0.463,0.412,14.0,20.0,0.7,19.0,25.0,44.0,6.0,6.0,1.0,5.0,15.0,0,0
10762,Youngstown State,2019-03-02,0,-1,Cleveland State,REG (Conf),1,74.0,61.0,28.0,57.0,0.491,13.0,28.0,0.464,15.0,29.0,0.517,0.605,5.0,9.0,0.556,8.0,29.0,37.0,18.0,3.0,5.0,13.0,19.0,21.0,59.0,0.356,3.0,16.0,0.188,18.0,43.0,0.419,0.381,16.0,22.0,0.727,8.0,23.0,31.0,7.0,9.0,2.0,10.0,13.0,0,0
10763,Youngstown State,2019-03-06,0,1,Milwaukee,CTOURN,1,64.0,58.0,18.0,50.0,0.36,6.0,15.0,0.4,12.0,35.0,0.343,0.42,22.0,28.0,0.786,11.0,23.0,34.0,9.0,5.0,5.0,17.0,9.0,24.0,60.0,0.4,2.0,18.0,0.111,22.0,42.0,0.524,0.417,8.0,14.0,0.571,6.0,16.0,22.0,12.0,9.0,9.0,7.0,25.0,0,0
10764,Youngstown State,2019-03-11,0,-1,Green Bay,CTOURN,-1,53.0,55.0,17.0,52.0,0.327,13.0,32.0,0.406,4.0,20.0,0.2,0.452,6.0,7.0,0.857,5.0,27.0,32.0,14.0,4.0,0.0,13.0,16.0,21.0,55.0,0.382,4.0,16.0,0.25,17.0,39.0,0.436,0.418,9.0,18.0,0.5,10.0,25.0,35.0,18.0,11.0,4.0,8.0,13.0,0,0
10765,Youngstown State,2019-03-21,0,-1,Cincinnati,WNIT,-1,62.0,76.0,24.0,55.0,0.436,5.0,21.0,0.238,19.0,34.0,0.559,0.482,9.0,14.0,0.643,3.0,25.0,28.0,13.0,3.0,2.0,15.0,9.0,29.0,69.0,0.42,5.0,9.0,0.556,24.0,60.0,0.4,0.457,13.0,13.0,1.0,13.0,25.0,38.0,19.0,8.0,3.0,7.0,14.0,0,0

Set up adjusted Score Differential

In [14]:
blowout_threshold = 18  # adjusted score differential will only account up to this score difference

df['Score Differential'] = df['Team Score'] - df['Opponent Score']

df['Adjusted Score Differential'] = df['Score Differential'].abs()

df.loc[df['Adjusted Score Differential'] > blowout_threshold, 'Adjusted Score Differential'] = blowout_threshold

df['Adjusted Score Differential'] = df['Adjusted Score Differential']**(np.log(1.5)/np.log(blowout_threshold))

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential
0,Abilene Christian,2018-11-20,0,-1,New Mexico State,REG (Non-Conf),1,58.0,46.0,18.0,63.0,0.286,5.0,29.0,0.172,13.0,34.0,0.382,0.325,17.0,24.0,0.708,14.0,23.0,37.0,10.0,5.0,2.0,12.0,15.0,16.0,52.0,0.308,4.0,22.0,0.182,12.0,30.0,0.4,0.346,10.0,19.0,0.526,9.0,22.0,31.0,10.0,8.0,7.0,21.0,19.0,0,0,12.0,1.417062
1,Abilene Christian,2018-11-23,0,1,Texas Southern,REG (Non-Conf),1,81.0,39.0,30.0,58.0,0.517,6.0,21.0,0.286,24.0,37.0,0.649,0.569,15.0,22.0,0.682,12.0,30.0,42.0,22.0,9.0,7.0,15.0,18.0,11.0,57.0,0.193,4.0,22.0,0.182,7.0,35.0,0.2,0.228,13.0,25.0,0.52,14.0,16.0,30.0,7.0,9.0,0.0,15.0,24.0,0,0,42.0,1.5
2,Abilene Christian,2018-11-24,0,-1,UTEP,REG (Non-Conf),1,70.0,69.0,24.0,47.0,0.511,14.0,28.0,0.5,10.0,19.0,0.526,0.66,8.0,11.0,0.727,7.0,19.0,26.0,19.0,4.0,2.0,17.0,13.0,31.0,59.0,0.525,4.0,16.0,0.25,27.0,43.0,0.628,0.559,3.0,3.0,1.0,5.0,16.0,21.0,24.0,5.0,2.0,9.0,11.0,0,0,1.0,1.0
3,Abilene Christian,2018-11-28,0,-1,Tulsa,REG (Non-Conf),-1,63.0,75.0,22.0,49.0,0.449,6.0,19.0,0.316,16.0,30.0,0.533,0.51,13.0,22.0,0.591,10.0,23.0,33.0,14.0,3.0,3.0,22.0,21.0,25.0,63.0,0.397,7.0,21.0,0.333,18.0,42.0,0.429,0.452,18.0,26.0,0.692,12.0,17.0,29.0,15.0,6.0,3.0,7.0,21.0,0,0,-12.0,1.417062
4,Abilene Christian,2018-12-08,0,1,Arkansas,REG (Non-Conf),-1,68.0,80.0,24.0,54.0,0.444,5.0,14.0,0.357,19.0,40.0,0.475,0.491,15.0,20.0,0.75,9.0,24.0,33.0,14.0,4.0,2.0,20.0,18.0,28.0,65.0,0.431,10.0,29.0,0.345,18.0,36.0,0.5,0.508,14.0,20.0,0.7,11.0,19.0,30.0,16.0,13.0,4.0,8.0,17.0,0,0,-12.0,1.417062
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10761,Youngstown State,2019-02-24,0,-1,Wright State,REG (Conf),-1,65.0,70.0,24.0,57.0,0.421,6.0,26.0,0.231,18.0,31.0,0.581,0.474,11.0,13.0,0.846,7.0,22.0,29.0,12.0,3.0,2.0,12.0,17.0,27.0,68.0,0.397,2.0,14.0,0.143,25.0,54.0,0.463,0.412,14.0,20.0,0.7,19.0,25.0,44.0,6.0,6.0,1.0,5.0,15.0,0,0,-5.0,1.253292
10762,Youngstown State,2019-03-02,0,-1,Cleveland State,REG (Conf),1,74.0,61.0,28.0,57.0,0.491,13.0,28.0,0.464,15.0,29.0,0.517,0.605,5.0,9.0,0.556,8.0,29.0,37.0,18.0,3.0,5.0,13.0,19.0,21.0,59.0,0.356,3.0,16.0,0.188,18.0,43.0,0.419,0.381,16.0,22.0,0.727,8.0,23.0,31.0,7.0,9.0,2.0,10.0,13.0,0,0,13.0,1.433063
10763,Youngstown State,2019-03-06,0,1,Milwaukee,CTOURN,1,64.0,58.0,18.0,50.0,0.36,6.0,15.0,0.4,12.0,35.0,0.343,0.42,22.0,28.0,0.786,11.0,23.0,34.0,9.0,5.0,5.0,17.0,9.0,24.0,60.0,0.4,2.0,18.0,0.111,22.0,42.0,0.524,0.417,8.0,14.0,0.571,6.0,16.0,22.0,12.0,9.0,9.0,7.0,25.0,0,0,6.0,1.28576
10764,Youngstown State,2019-03-11,0,-1,Green Bay,CTOURN,-1,53.0,55.0,17.0,52.0,0.327,13.0,32.0,0.406,4.0,20.0,0.2,0.452,6.0,7.0,0.857,5.0,27.0,32.0,14.0,4.0,0.0,13.0,16.0,21.0,55.0,0.382,4.0,16.0,0.25,17.0,39.0,0.436,0.418,9.0,18.0,0.5,10.0,25.0,35.0,18.0,11.0,4.0,8.0,13.0,0,0,-2.0,1.10212
10765,Youngstown State,2019-03-21,0,-1,Cincinnati,WNIT,-1,62.0,76.0,24.0,55.0,0.436,5.0,21.0,0.238,19.0,34.0,0.559,0.482,9.0,14.0,0.643,3.0,25.0,28.0,13.0,3.0,2.0,15.0,9.0,29.0,69.0,0.42,5.0,9.0,0.556,24.0,60.0,0.4,0.457,13.0,13.0,1.0,13.0,25.0,38.0,19.0,8.0,3.0,7.0,14.0,0,0,-14.0,1.448039

Get per possession stats

In [15]:
Y = 0.44

df['Possessions'] = (
    df['Team FGA'] - df['Team ORB'] + df['Team TOV'] + Y*df['Team FTA'] +
    df['Opponent FGA'] - df['Opponent ORB'] + df['Opponent TOV'] + Y*df['Opponent FTA']
)/2

df['Team PPP'] = df['Team Score'] / df['Possessions']
df['Opponent PPP'] = df['Opponent Score'] / df['Possessions']
df['Tempo'] = 40*df['Possessions'] / (40 + 5*df['Overtimes Amount'])

# some games are missing stats due to delay/finished recently
df = df.loc[df['Team PPP'].notna(), :].reset_index(drop=True)

df

,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo
0,Abilene Christian,2018-11-20,0,-1,New Mexico State,REG (Non-Conf),1,58.0,46.0,18.0,63.0,0.286,5.0,29.0,0.172,13.0,34.0,0.382,0.325,17.0,24.0,0.708,14.0,23.0,37.0,10.0,5.0,2.0,12.0,15.0,16.0,52.0,0.308,4.0,22.0,0.182,12.0,30.0,0.4,0.346,10.0,19.0,0.526,9.0,22.0,31.0,10.0,8.0,7.0,21.0,19.0,0,0,12.0,1.417062,71.96,0.806003,0.639244,71.96
1,Abilene Christian,2018-11-23,0,1,Texas Southern,REG (Non-Conf),1,81.0,39.0,30.0,58.0,0.517,6.0,21.0,0.286,24.0,37.0,0.649,0.569,15.0,22.0,0.682,12.0,30.0,42.0,22.0,9.0,7.0,15.0,18.0,11.0,57.0,0.193,4.0,22.0,0.182,7.0,35.0,0.2,0.228,13.0,25.0,0.52,14.0,16.0,30.0,7.0,9.0,0.0,15.0,24.0,0,0,42.0,1.5,69.84,1.159794,0.558419,69.84
2,Abilene Christian,2018-11-24,0,-1,UTEP,REG (Non-Conf),1,70.0,69.0,24.0,47.0,0.511,14.0,28.0,0.5,10.0,19.0,0.526,0.66,8.0,11.0,0.727,7.0,19.0,26.0,19.0,4.0,2.0,17.0,13.0,31.0,59.0,0.525,4.0,16.0,0.25,27.0,43.0,0.628,0.559,3.0,3.0,1.0,5.0,16.0,21.0,24.0,5.0,2.0,9.0,11.0,0,0,1.0,1.0,63.08,1.109702,1.093849,63.08
3,Abilene Christian,2018-11-28,0,-1,Tulsa,REG (Non-Conf),-1,63.0,75.0,22.0,49.0,0.449,6.0,19.0,0.316,16.0,30.0,0.533,0.51,13.0,22.0,0.591,10.0,23.0,33.0,14.0,3.0,3.0,22.0,21.0,25.0,63.0,0.397,7.0,21.0,0.333,18.0,42.0,0.429,0.452,18.0,26.0,0.692,12.0,17.0,29.0,15.0,6.0,3.0,7.0,21.0,0,0,-12.0,1.417062,70.06,0.899229,1.070511,70.06
4,Abilene Christian,2018-12-08,0,1,Arkansas,REG (Non-Conf),-1,68.0,80.0,24.0,54.0,0.444,5.0,14.0,0.357,19.0,40.0,0.475,0.491,15.0,20.0,0.75,9.0,24.0,33.0,14.0,4.0,2.0,20.0,18.0,28.0,65.0,0.431,10.0,29.0,0.345,18.0,36.0,0.5,0.508,14.0,20.0,0.7,11.0,19.0,30.0,16.0,13.0,4.0,8.0,17.0,0,0,-12.0,1.417062,72.3,0.940526,1.106501,72.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10761,Youngstown State,2019-02-24,0,-1,Wright State,REG (Conf),-1,65.0,70.0,24.0,57.0,0.421,6.0,26.0,0.231,18.0,31.0,0.581,0.474,11.0,13.0,0.846,7.0,22.0,29.0,12.0,3.0,2.0,12.0,17.0,27.0,68.0,0.397,2.0,14.0,0.143,25.0,54.0,0.463,0.412,14.0,20.0,0.7,19.0,25.0,44.0,6.0,6.0,1.0,5.0,15.0,0,0,-5.0,1.253292,65.26,0.996016,1.072633,65.26
10762,Youngstown State,2019-03-02,0,-1,Cleveland State,REG (Conf),1,74.0,61.0,28.0,57.0,0.491,13.0,28.0,0.464,15.0,29.0,0.517,0.605,5.0,9.0,0.556,8.0,29.0,37.0,18.0,3.0,5.0,13.0,19.0,21.0,59.0,0.356,3.0,16.0,0.188,18.0,43.0,0.419,0.381,16.0,22.0,0.727,8.0,23.0,31.0,7.0,9.0,2.0,10.0,13.0,0,0,13.0,1.433063,68.32,1.083138,0.892857,68.32
10763,Youngstown State,2019-03-06,0,1,Milwaukee,CTOURN,1,64.0,58.0,18.0,50.0,0.36,6.0,15.0,0.4,12.0,35.0,0.343,0.42,22.0,28.0,0.786,11.0,23.0,34.0,9.0,5.0,5.0,17.0,9.0,24.0,60.0,0.4,2.0,18.0,0.111,22.0,42.0,0.524,0.417,8.0,14.0,0.571,6.0,16.0,22.0,12.0,9.0,9.0,7.0,25.0,0,0,6.0,1.28576,67.74,0.944789,0.856215,67.74
10764,Youngstown State,2019-03-11,0,-1,Green Bay,CTOURN,-1,53.0,55.0,17.0,52.0,0.327,13.0,32.0,0.406,4.0,20.0,0.2,0.452,6.0,7.0,0.857,5.0,27.0,32.0,14.0,4.0,0.0,13.0,16.0,21.0,55.0,0.382,4.0,16.0,0.25,17.0,39.0,0.436,0.418,9.0,18.0,0.5,10.0,25.0,35.0,18.0,11.0,4.0,8.0,13.0,0,0,-2.0,1.10212,62.0,0.854839,0.887097,62.0
10765,Youngstown State,2019-03-21,0,-1,Cincinnati,WNIT,-1,62.0,76.0,24.0,55.0,0.436,5.0,21.0,0.238,19.0,34.0,0.559,0.482,9.0,14.0,0.643,3.0,25.0,28.0,13.0,3.0,2.0,15.0,9.0,29.0,69.0,0.42,5.0,9.0,0.556,24.0,60.0,0.4,0.457,13.0,13.0,1.0,13.0,25.0,38.0,19.0,8.0,3.0,7.0,14.0,0,0,-14.0,1.448039,70.94,0.873978,1.071328,70.94

Save

In [16]:
df.to_parquet(f'../data/unprocessed/womens_sports_reference/full_season_sports_reference_{season}.parquet')

'Done'

'Done'