# Get Men's Head-to-Head

Get head-to-head records and records against common opponents.

### Head-to-Head

In [1]:
SEASON = 2025
INCLUDE_CURRENT_SEASON = True

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 100)

df = pd.concat(
    [
        pd.read_parquet(fr'..\data\unprocessed\mens_sports_reference\full_season_sports_reference_{season}.parquet')
        .assign(Season=season)
        for season in range(2012, SEASON + INCLUDE_CURRENT_SEASON)
        if season != 2020  # tournament was cancelled
    ],
    ignore_index=True
)

df.insert(0, 'Season', df.pop('Season'))

df = df.loc[df['NCAA Tournament'] == 0, :].reset_index(drop=True)  # only include games before NCAA Tournament

df

,Season,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo
0,2012,Air Force,2011-11-11,0,1,Army,REG (Non-Conf),1,87,71,29.0,52.0,0.558,3.0,14.0,0.214,26.0,38.0,0.684,0.587,26.0,36.0,0.722,7.0,30.0,37.0,25.0,15.0,1.0,23.0,25.0,23.0,58.0,0.397,6.0,29.0,0.207,17.0,29.0,0.586,0.448,19.0,26.0,0.731,6.0,18.0,24.0,13.0,11.0,0.0,24.0,29.0,0,0,16,1.475419,85.64,1.015880,0.829052,85.640000
1,2012,Air Force,2011-11-12,0,0,Virginia Military Institute,REG (Non-Conf),1,75,65,28.0,56.0,0.500,6.0,22.0,0.273,22.0,34.0,0.647,0.554,13.0,18.0,0.722,11.0,29.0,40.0,20.0,5.0,4.0,14.0,16.0,22.0,56.0,0.393,10.0,30.0,0.333,12.0,26.0,0.462,0.482,11.0,15.0,0.733,6.0,19.0,25.0,11.0,6.0,4.0,14.0,21.0,0,0,10,1.381279,68.76,1.090750,0.945317,68.760000
2,2012,Air Force,2011-11-23,0,1,Colorado,REG (Non-Conf),-1,73,76,25.0,62.0,0.403,5.0,19.0,0.263,20.0,43.0,0.465,0.444,18.0,25.0,0.720,10.0,16.0,26.0,14.0,9.0,4.0,6.0,14.0,29.0,60.0,0.483,10.0,24.0,0.417,19.0,36.0,0.528,0.567,8.0,14.0,0.571,12.0,30.0,42.0,15.0,1.0,4.0,17.0,22.0,1,1,-3,1.166625,70.08,1.041667,1.084475,62.293333
3,2012,Air Force,2011-12-03,0,-1,Drake,REG (Non-Conf),-1,60,62,16.0,41.0,0.390,6.0,15.0,0.400,10.0,26.0,0.385,0.463,22.0,35.0,0.629,4.0,23.0,27.0,6.0,9.0,2.0,15.0,24.0,18.0,45.0,0.400,6.0,20.0,0.300,12.0,25.0,0.480,0.467,20.0,31.0,0.645,5.0,25.0,30.0,8.0,9.0,4.0,13.0,26.0,0,0,-2,1.102120,67.02,0.895255,0.925097,67.020000
4,2012,Air Force,2011-12-07,0,1,Wright State,REG (Non-Conf),1,55,34,19.0,45.0,0.422,9.0,25.0,0.360,10.0,20.0,0.500,0.522,8.0,12.0,0.667,3.0,25.0,28.0,15.0,7.0,4.0,12.0,15.0,9.0,46.0,0.196,2.0,19.0,0.105,7.0,27.0,0.259,0.217,14.0,18.0,0.778,9.0,22.0,31.0,4.0,5.0,5.0,16.0,14.0,0,0,21,1.500000,60.10,0.915141,0.565724,60.100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138699,2025,Youngstown State,2025-02-23,0,1,Green Bay,REG (Conf),1,81,77,27.0,55.0,0.491,6.0,18.0,0.333,21.0,37.0,0.568,0.545,21.0,31.0,0.677,9.0,25.0,34.0,10.0,5.0,5.0,16.0,19.0,27.0,59.0,0.458,9.0,29.0,0.310,18.0,30.0,0.600,0.534,14.0,21.0,0.667,10.0,21.0,31.0,19.0,9.0,1.0,12.0,23.0,0,0,4,1.214668,72.94,1.110502,1.055662,72.940000
138700,2025,Youngstown State,2025-03-01,0,-1,Northern Kentucky,REG (Conf),-1,79,88,26.0,57.0,0.456,14.0,29.0,0.483,12.0,28.0,0.429,0.579,13.0,17.0,0.765,7.0,16.0,23.0,18.0,5.0,1.0,10.0,18.0,30.0,58.0,0.517,9.0,24.0,0.375,21.0,34.0,0.618,0.595,19.0,23.0,0.826,8.0,24.0,32.0,15.0,3.0,4.0,8.0,16.0,0,0,-9,1.361013,67.80,1.165192,1.297935,67.800000
138701,2025,Youngstown State,2025-03-06,0,1,Purdue Fort Wayne,CTOURN,1,72,67,21.0,58.0,0.362,5.0,28.0,0.179,16.0,30.0,0.533,0.405,25.0,31.0,0.806,10.0,34.0,44.0,10.0,6.0,5.0,17.0,20.0,23.0,62.0,0.371,8.0,27.0,0.296,15.0,35.0,0.429,0.435,13.0,20.0,0.650,6.0,23.0,29.0,11.0,9.0,3.0,13.0,23.0,0,0,5,1.253292,78.22,0.920481,0.856558,78.220000
138702,2025,Youngstown State,2025-03-10,0,0,Cleveland State,CTOURN,1,56,54,18.0,50.0,0.360,8.0,25.0,0.320,10.0,25.0,0.400,0.440,12.0,23.0,0.522,12.0,20.0,32.0,11.0,10.0,4.0,11.0,12.0,19.0,46.0,0.413,8.0,12.0,0.667,11.0,34.0,0.324,0.500,8.0,12.0,0.667,6.0,20.0,26.0,12.0,7.0,5.0,15.0,19.0,0,0,2,1.102120,59.70,0.938023,0.904523,59.700000
138703,2025,Youngstown State,2025-03-11,0,0,Robert Morris,CTOURN,-1,78,89,27.0,63.0,0.429,11.0,29.0,0.379,16.0,34.0,0.471,0.516,13.0,17.0,0.765,7.0,25.0,32.0,17.0,5.0,7.0,5.0,21.0,29.0,62.0,0.468,11.0,22.0,0.500,18.0,40.0,0.450,0.556,20.0,28.0,0.714,14.0,26.0,40.0,23.0,2.0,4.0,8.0,16.0,0,0,-11,1.399871,68.40,1.140351,1.301170,68.400000

In [3]:
def rescale_weights(arr, minimum, maximum):
    """
    Rescale the weights array to match desired weights.
    Assumes the data is already transformed where a 1 point win is 1.00, a blowout is 1.50, and a tie is 0.50.
    Ties will be weighted as half the minimum.
    """

    arr_scaled = ((arr - 1.00) / 0.50) * (maximum - minimum) + minimum
    arr_scaled[arr == 0.50] = minimum / 2
    return arr_scaled

# make sure losses have negative adjusted score differential in this file
df['Adjusted Score Differential'] = rescale_weights(df['Adjusted Score Differential'], 0.50, 1.00)*df['Result']

df

,Season,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo
0,2012,Air Force,2011-11-11,0,1,Army,REG (Non-Conf),1,87,71,29.0,52.0,0.558,3.0,14.0,0.214,26.0,38.0,0.684,0.587,26.0,36.0,0.722,7.0,30.0,37.0,25.0,15.0,1.0,23.0,25.0,23.0,58.0,0.397,6.0,29.0,0.207,17.0,29.0,0.586,0.448,19.0,26.0,0.731,6.0,18.0,24.0,13.0,11.0,0.0,24.0,29.0,0,0,16,0.975419,85.64,1.015880,0.829052,85.640000
1,2012,Air Force,2011-11-12,0,0,Virginia Military Institute,REG (Non-Conf),1,75,65,28.0,56.0,0.500,6.0,22.0,0.273,22.0,34.0,0.647,0.554,13.0,18.0,0.722,11.0,29.0,40.0,20.0,5.0,4.0,14.0,16.0,22.0,56.0,0.393,10.0,30.0,0.333,12.0,26.0,0.462,0.482,11.0,15.0,0.733,6.0,19.0,25.0,11.0,6.0,4.0,14.0,21.0,0,0,10,0.881279,68.76,1.090750,0.945317,68.760000
2,2012,Air Force,2011-11-23,0,1,Colorado,REG (Non-Conf),-1,73,76,25.0,62.0,0.403,5.0,19.0,0.263,20.0,43.0,0.465,0.444,18.0,25.0,0.720,10.0,16.0,26.0,14.0,9.0,4.0,6.0,14.0,29.0,60.0,0.483,10.0,24.0,0.417,19.0,36.0,0.528,0.567,8.0,14.0,0.571,12.0,30.0,42.0,15.0,1.0,4.0,17.0,22.0,1,1,-3,-0.666625,70.08,1.041667,1.084475,62.293333
3,2012,Air Force,2011-12-03,0,-1,Drake,REG (Non-Conf),-1,60,62,16.0,41.0,0.390,6.0,15.0,0.400,10.0,26.0,0.385,0.463,22.0,35.0,0.629,4.0,23.0,27.0,6.0,9.0,2.0,15.0,24.0,18.0,45.0,0.400,6.0,20.0,0.300,12.0,25.0,0.480,0.467,20.0,31.0,0.645,5.0,25.0,30.0,8.0,9.0,4.0,13.0,26.0,0,0,-2,-0.602120,67.02,0.895255,0.925097,67.020000
4,2012,Air Force,2011-12-07,0,1,Wright State,REG (Non-Conf),1,55,34,19.0,45.0,0.422,9.0,25.0,0.360,10.0,20.0,0.500,0.522,8.0,12.0,0.667,3.0,25.0,28.0,15.0,7.0,4.0,12.0,15.0,9.0,46.0,0.196,2.0,19.0,0.105,7.0,27.0,0.259,0.217,14.0,18.0,0.778,9.0,22.0,31.0,4.0,5.0,5.0,16.0,14.0,0,0,21,1.000000,60.10,0.915141,0.565724,60.100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138699,2025,Youngstown State,2025-02-23,0,1,Green Bay,REG (Conf),1,81,77,27.0,55.0,0.491,6.0,18.0,0.333,21.0,37.0,0.568,0.545,21.0,31.0,0.677,9.0,25.0,34.0,10.0,5.0,5.0,16.0,19.0,27.0,59.0,0.458,9.0,29.0,0.310,18.0,30.0,0.600,0.534,14.0,21.0,0.667,10.0,21.0,31.0,19.0,9.0,1.0,12.0,23.0,0,0,4,0.714668,72.94,1.110502,1.055662,72.940000
138700,2025,Youngstown State,2025-03-01,0,-1,Northern Kentucky,REG (Conf),-1,79,88,26.0,57.0,0.456,14.0,29.0,0.483,12.0,28.0,0.429,0.579,13.0,17.0,0.765,7.0,16.0,23.0,18.0,5.0,1.0,10.0,18.0,30.0,58.0,0.517,9.0,24.0,0.375,21.0,34.0,0.618,0.595,19.0,23.0,0.826,8.0,24.0,32.0,15.0,3.0,4.0,8.0,16.0,0,0,-9,-0.861013,67.80,1.165192,1.297935,67.800000
138701,2025,Youngstown State,2025-03-06,0,1,Purdue Fort Wayne,CTOURN,1,72,67,21.0,58.0,0.362,5.0,28.0,0.179,16.0,30.0,0.533,0.405,25.0,31.0,0.806,10.0,34.0,44.0,10.0,6.0,5.0,17.0,20.0,23.0,62.0,0.371,8.0,27.0,0.296,15.0,35.0,0.429,0.435,13.0,20.0,0.650,6.0,23.0,29.0,11.0,9.0,3.0,13.0,23.0,0,0,5,0.753292,78.22,0.920481,0.856558,78.220000
138702,2025,Youngstown State,2025-03-10,0,0,Cleveland State,CTOURN,1,56,54,18.0,50.0,0.360,8.0,25.0,0.320,10.0,25.0,0.400,0.440,12.0,23.0,0.522,12.0,20.0,32.0,11.0,10.0,4.0,11.0,12.0,19.0,46.0,0.413,8.0,12.0,0.667,11.0,34.0,0.324,0.500,8.0,12.0,0.667,6.0,20.0,26.0,12.0,7.0,5.0,15.0,19.0,0,0,2,0.602120,59.70,0.938023,0.904523,59.700000
138703,2025,Youngstown State,2025-03-11,0,0,Robert Morris,CTOURN,-1,78,89,27.0,63.0,0.429,11.0,29.0,0.379,16.0,34.0,0.471,0.516,13.0,17.0,0.765,7.0,25.0,32.0,17.0,5.0,7.0,5.0,21.0,29.0,62.0,0.468,11.0,22.0,0.500,18.0,40.0,0.450,0.556,20.0,28.0,0.714,14.0,26.0,40.0,23.0,2.0,4.0,8.0,16.0,0,0,-11,-0.899871,68.40,1.140351,1.301170,68.400000

In [4]:
df_h2h = (
    df
    .groupby(['Season', 'Team', 'Opponent'])
    .agg(
        h2h_sum=('Adjusted Score Differential', 'sum'),
        h2h_count=('Result', 'count')
    )
    .reset_index()
    .rename(columns={'Team': 'Team A', 'Opponent': 'Team B'})
)

# add 1/4 to denominator so that a team that beats opponent multiple times is better accounted for
df_h2h['Head to Head'] = df_h2h['h2h_sum'] / (df_h2h['h2h_count'] + 1/4)

df_h2h

,Season,Team A,Team B,h2h_sum,h2h_count,Head to Head
0,2012,Air Force,Arkansas-Pine Bluff,0.917062,1,0.733650
1,2012,Air Force,Army,0.975419,1,0.780336
2,2012,Air Force,Boise State,0.062251,2,0.027667
3,2012,Air Force,Chicago State,0.948039,1,0.758431
4,2012,Air Force,Colorado,-0.666625,1,-0.533300
...,...,...,...,...,...,...
97563,2025,Youngstown State,Stephen F. Austin,-0.813867,1,-0.651094
97564,2025,Youngstown State,Syracuse,-0.861013,1,-0.688811
97565,2025,Youngstown State,Toledo,0.785760,1,0.628608
97566,2025,Youngstown State,Western Michigan,-0.899871,1,-0.719897
97567,2025,Youngstown State,Wright State,1.483399,2,0.659288

### Common Opponents

In [5]:
df_h2h['h2h_avg'] = df_h2h['h2h_sum']/df_h2h['h2h_count']

df_h2h

,Season,Team A,Team B,h2h_sum,h2h_count,Head to Head,h2h_avg
0,2012,Air Force,Arkansas-Pine Bluff,0.917062,1,0.733650,0.917062
1,2012,Air Force,Army,0.975419,1,0.780336,0.975419
2,2012,Air Force,Boise State,0.062251,2,0.027667,0.031126
3,2012,Air Force,Chicago State,0.948039,1,0.758431,0.948039
4,2012,Air Force,Colorado,-0.666625,1,-0.533300,-0.666625
...,...,...,...,...,...,...,...
97563,2025,Youngstown State,Stephen F. Austin,-0.813867,1,-0.651094,-0.813867
97564,2025,Youngstown State,Syracuse,-0.861013,1,-0.688811,-0.861013
97565,2025,Youngstown State,Toledo,0.785760,1,0.628608,0.785760
97566,2025,Youngstown State,Western Michigan,-0.899871,1,-0.719897,-0.899871
97567,2025,Youngstown State,Wright State,1.483399,2,0.659288,0.741699

In [6]:
def get_opponents_results(season, team):
    data = df_h2h.loc[
        (df_h2h['Season'] == season) & 
        (df_h2h['Team A'] == team), 
        :
    ]
    
    return dict(zip(
        data['Team B'],
        data['h2h_avg']
    ))

In [7]:
from tqdm.autonotebook import tqdm

season_team_opponents = {
    season: {
        team: get_opponents_results(season, team) 
        for team in df_h2h.loc[df_h2h['Season'] == season, 'Team A'].unique()
    } 
    for season in tqdm(df_h2h['Season'].unique())
}

len(season_team_opponents)

C:\Users\mhugh\AppData\Local\Temp\ipykernel_20660\755660832.py:1: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

  0%|          | 0/13 [00:00<?, ?it/s]

13

In [8]:
import numpy as np

def get_difference(season, team_a, team_b):
    team_a_dict = season_team_opponents[season][team_a]
    team_b_dict = season_team_opponents[season][team_b]

    common_keys = team_a_dict.keys() & team_b_dict.keys()

    if len(common_keys) == 0:
        return np.nan, np.nan
    
    commons_opps_results = tuple(team_a_dict[key] - team_b_dict[key] for key in common_keys)

    return np.sum(commons_opps_results), (len(commons_opps_results))

In [9]:
common_opps = [
    (season, team_a, team_b, *get_difference(season, team_a, team_b))
    for season in tqdm(df_h2h['Season'].unique())
    for team_a in df_h2h.loc[df_h2h['Season'] == season, 'Team A'].unique()
    for team_b in df_h2h.loc[df_h2h['Season'] == season, 'Team A'].unique()  # could use Team B but shouldn't matter
    if team_a != team_b
]

common_opps[:5]

  0%|          | 0/13 [00:00<?, ?it/s]

[(2012, 'Air Force', 'Akron', -0.32964524332997414, 2),
 (2012, 'Air Force', 'Alabama', nan, nan),
 (2012, 'Air Force', 'Alabama A&M', 0.9766301676118663, 1),
 (2012, 'Air Force', 'Alabama State', 1.0600316474605287, 1),
 (2012, 'Air Force', 'Albany (NY)', nan, nan)]

In [10]:
df_common_opps = pd.DataFrame(
    common_opps,
    columns=['Season', 'Team A', 'Team B', 'common_opps_sum', 'common_opps_count'],
)

df_common_opps

,Season,Team A,Team B,common_opps_sum,common_opps_count
0,2012,Air Force,Akron,-0.329645,2.0
1,2012,Air Force,Alabama,NaN,NaN
2,2012,Air Force,Alabama A&M,0.976630,1.0
3,2012,Air Force,Alabama State,1.060032,1.0
4,2012,Air Force,Albany (NY),NaN,NaN
...,...,...,...,...,...
1618643,2025,Youngstown State,Wofford,-0.652956,2.0
1618644,2025,Youngstown State,Wright State,4.508683,10.0
1618645,2025,Youngstown State,Wyoming,NaN,NaN
1618646,2025,Youngstown State,Xavier,-0.836976,1.0
1618647,2025,Youngstown State,Yale,NaN,NaN

In [11]:
df_h2h = pd.merge(
    df_h2h.drop(columns=['h2h_avg']),
    df_common_opps,
    how='outer',
    on=['Season', 'Team A', 'Team B'],
)

df_h2h

,Season,Team A,Team B,h2h_sum,h2h_count,Head to Head,common_opps_sum,common_opps_count
0,2012,Air Force,Akron,NaN,NaN,NaN,-0.329645,2.0
1,2012,Air Force,Alabama,NaN,NaN,NaN,NaN,NaN
2,2012,Air Force,Alabama A&M,NaN,NaN,NaN,0.976630,1.0
3,2012,Air Force,Alabama State,NaN,NaN,NaN,1.060032,1.0
4,2012,Air Force,Albany (NY),NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1618643,2025,Youngstown State,Wofford,NaN,NaN,NaN,-0.652956,2.0
1618644,2025,Youngstown State,Wright State,1.483399,2.0,0.659288,4.508683,10.0
1618645,2025,Youngstown State,Wyoming,NaN,NaN,NaN,NaN,NaN
1618646,2025,Youngstown State,Xavier,NaN,NaN,NaN,-0.836976,1.0
1618647,2025,Youngstown State,Yale,NaN,NaN,NaN,NaN,NaN

In [12]:
# add 1/4 to denominator so that a team that beats opponent multiple times is better accounted for
df_h2h['Common Opps'] = df_h2h['common_opps_sum']/(df_h2h['common_opps_count'] + 1/4)

df_h2h

,Season,Team A,Team B,h2h_sum,h2h_count,Head to Head,common_opps_sum,common_opps_count,Common Opps
0,2012,Air Force,Akron,NaN,NaN,NaN,-0.329645,2.0,-0.146509
1,2012,Air Force,Alabama,NaN,NaN,NaN,NaN,NaN,NaN
2,2012,Air Force,Alabama A&M,NaN,NaN,NaN,0.976630,1.0,0.781304
3,2012,Air Force,Alabama State,NaN,NaN,NaN,1.060032,1.0,0.848025
4,2012,Air Force,Albany (NY),NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1618643,2025,Youngstown State,Wofford,NaN,NaN,NaN,-0.652956,2.0,-0.290202
1618644,2025,Youngstown State,Wright State,1.483399,2.0,0.659288,4.508683,10.0,0.439871
1618645,2025,Youngstown State,Wyoming,NaN,NaN,NaN,NaN,NaN,NaN
1618646,2025,Youngstown State,Xavier,NaN,NaN,NaN,-0.836976,1.0,-0.669581
1618647,2025,Youngstown State,Yale,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_h2h.loc[(df_h2h['Season'] == 2024) & df_h2h['Team A'].str.contains('Connecticut'), :]

,Season,Team A,Team B,h2h_sum,h2h_count,Head to Head,common_opps_sum,common_opps_count,Common Opps
1371718,2024,Central Connecticut State,Abilene Christian,NaN,NaN,NaN,-0.345919,1.0,-0.276735
1371719,2024,Central Connecticut State,Air Force,NaN,NaN,NaN,-0.057596,1.0,-0.046077
1371720,2024,Central Connecticut State,Akron,NaN,NaN,NaN,NaN,NaN,NaN
1371721,2024,Central Connecticut State,Alabama,NaN,NaN,NaN,NaN,NaN,NaN
1371722,2024,Central Connecticut State,Alabama A&M,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1377489,2024,Connecticut,Wright State,NaN,NaN,NaN,1.861013,1.0,1.488811
1377490,2024,Connecticut,Wyoming,NaN,NaN,NaN,1.881279,1.0,1.505023
1377491,2024,Connecticut,Xavier,2.753292,3.0,0.847167,5.774493,9.0,0.624270
1377492,2024,Connecticut,Yale,NaN,NaN,NaN,2.142639,2.0,0.952284
1377493,2024,Connecticut,Youngstown State,NaN,NaN,NaN,NaN,NaN,NaN

Remove all the rows without data to reduce the dataframe size

In [14]:
df_h2h = df_h2h.loc[(df_h2h['Head to Head'].notna()) | (df_h2h['Common Opps'].notna()), :].reset_index(drop=True)

df_h2h

,Season,Team A,Team B,h2h_sum,h2h_count,Head to Head,common_opps_sum,common_opps_count,Common Opps
0,2012,Air Force,Akron,NaN,NaN,NaN,-0.329645,2.0,-0.146509
1,2012,Air Force,Alabama A&M,NaN,NaN,NaN,0.976630,1.0,0.781304
2,2012,Air Force,Alabama State,NaN,NaN,NaN,1.060032,1.0,0.848025
3,2012,Air Force,Alcorn State,NaN,NaN,NaN,0.904641,1.0,0.723713
4,2012,Air Force,American,NaN,NaN,NaN,1.323847,2.0,0.588376
...,...,...,...,...,...,...,...,...,...
910375,2025,Youngstown State,Winthrop,NaN,NaN,NaN,-1.889770,2.0,-0.839898
910376,2025,Youngstown State,Wisconsin,NaN,NaN,NaN,-1.690552,3.0,-0.520170
910377,2025,Youngstown State,Wofford,NaN,NaN,NaN,-0.652956,2.0,-0.290202
910378,2025,Youngstown State,Wright State,1.483399,2.0,0.659288,4.508683,10.0,0.439871
910379,2025,Youngstown State,Xavier,NaN,NaN,NaN,-0.836976,1.0,-0.669581

In [15]:
df_h2h.drop(columns=['h2h_sum', 'h2h_count', 'common_opps_sum', 'common_opps_count'], inplace=True)

df_h2h

        Season            Team A         Team B  Head to Head  Common Opps
0         2012         Air Force          Akron           NaN    -0.146509
1         2012         Air Force    Alabama A&M           NaN     0.781304
2         2012         Air Force  Alabama State           NaN     0.848025
3         2012         Air Force   Alcorn State           NaN     0.723713
4         2012         Air Force       American           NaN     0.588376
...        ...               ...            ...           ...          ...
910375    2025  Youngstown State       Winthrop           NaN    -0.839898
910376    2025  Youngstown State      Wisconsin           NaN    -0.520170
910377    2025  Youngstown State        Wofford           NaN    -0.290202
910378    2025  Youngstown State   Wright State      0.659288     0.439871
910379    2025  Youngstown State         Xavier           NaN    -0.669581

[910380 rows x 5 columns]

In [16]:
df_h2h.to_parquet('../data/preprocessed/mens_h2h/h2h.parquet')

'Done'

'Done'