# Get Women's Standard Stats

Get yearly averages for team stats that you would find in a boxscore

In [1]:
SEASON = 2025
INCLUDE_CURRENT_SEASON = False

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 100)

df = pd.concat(
    [
        pd.read_parquet(fr'..\data\unprocessed\womens_sports_reference\full_season_sports_reference_{season}.parquet') 
        .assign(Season=season)
        for season in range(2012, SEASON + INCLUDE_CURRENT_SEASON)
    ], 
    ignore_index=True
)

df.insert(0, 'Season', df.pop('Season'))

# only include games before NCAA tournament
df = df.loc[df['NCAA Tournament'] == 0, :].reset_index(drop=True)

df

,Season,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo
0,2012,Air Force,2011-11-11,0,-1,Lipscomb,REG (Non-Conf),1,68.0,59.0,23.0,63.0,0.365,1.0,4.0,0.250,22.0,59.0,0.373,0.373,21.0,30.0,0.700,15.0,26.0,41.0,11.0,11.0,2.0,16.0,23.0,18.0,54.0,0.333,4.0,12.0,0.333,14.0,42.0,0.333,0.370,19.0,31.0,0.613,13.0,23.0,36.0,10.0,8.0,3.0,23.0,24.0,0,0,9.0,1.361013,77.42,0.878326,0.762077,77.42
1,2012,Air Force,2011-11-13,0,-1,Tennessee-Martin,REG (Non-Conf),-1,60.0,84.0,27.0,64.0,0.422,4.0,8.0,0.500,23.0,56.0,0.411,0.453,2.0,4.0,0.500,12.0,23.0,35.0,17.0,10.0,1.0,27.0,16.0,32.0,69.0,0.464,10.0,30.0,0.333,22.0,39.0,0.564,0.536,10.0,11.0,0.909,9.0,22.0,31.0,15.0,12.0,4.0,18.0,7.0,0,0,-24.0,1.500000,81.80,0.733496,1.026895,81.80
2,2012,Air Force,2011-11-17,0,1,Denver,REG (Non-Conf),-1,52.0,54.0,20.0,60.0,0.333,1.0,8.0,0.125,19.0,52.0,0.365,0.342,11.0,20.0,0.550,14.0,34.0,48.0,15.0,7.0,3.0,21.0,26.0,20.0,57.0,0.351,1.0,10.0,0.100,19.0,47.0,0.404,0.360,13.0,30.0,0.433,10.0,32.0,42.0,16.0,13.0,4.0,20.0,19.0,0,0,-2.0,1.102120,78.00,0.666667,0.692308,78.00
3,2012,Air Force,2011-11-19,0,-1,Texas Southern,REG (Non-Conf),1,64.0,54.0,20.0,51.0,0.392,0.0,2.0,0.000,20.0,49.0,0.408,0.392,24.0,33.0,0.727,8.0,27.0,35.0,13.0,14.0,1.0,21.0,20.0,17.0,57.0,0.298,5.0,18.0,0.278,12.0,39.0,0.308,0.342,15.0,24.0,0.625,15.0,26.0,41.0,13.0,10.0,6.0,30.0,27.0,0,0,10.0,1.381279,80.54,0.794636,0.670474,80.54
4,2012,Air Force,2011-11-21,0,-1,Texas State,REG (Non-Conf),1,77.0,69.0,25.0,61.0,0.410,1.0,6.0,0.167,24.0,55.0,0.436,0.418,26.0,31.0,0.839,16.0,29.0,45.0,10.0,9.0,3.0,19.0,21.0,27.0,67.0,0.403,4.0,21.0,0.190,23.0,46.0,0.500,0.433,11.0,20.0,0.550,13.0,17.0,30.0,10.0,8.0,2.0,14.0,20.0,0,0,8.0,1.338710,77.22,0.997151,0.893551,77.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133249,2024,Youngstown State,2024-02-24,0,-1,Northern Kentucky,REG (Conf),1,68.0,64.0,24.0,57.0,0.421,12.0,23.0,0.522,12.0,34.0,0.353,0.526,8.0,11.0,0.727,8.0,28.0,36.0,12.0,4.0,6.0,13.0,14.0,22.0,61.0,0.361,10.0,23.0,0.435,12.0,38.0,0.316,0.443,10.0,13.0,0.769,8.0,19.0,27.0,13.0,10.0,4.0,8.0,12.0,0,0,4.0,1.214668,66.78,1.018269,0.958371,66.78
133250,2024,Youngstown State,2024-02-27,0,1,Cleveland State,REG (Conf),-1,53.0,56.0,21.0,60.0,0.350,7.0,26.0,0.269,14.0,34.0,0.412,0.408,4.0,4.0,1.000,5.0,29.0,34.0,15.0,10.0,4.0,19.0,20.0,17.0,58.0,0.293,4.0,13.0,0.308,13.0,45.0,0.289,0.328,18.0,22.0,0.818,12.0,31.0,43.0,5.0,7.0,1.0,17.0,11.0,0,0,-3.0,1.166625,74.22,0.714093,0.754514,74.22
133251,2024,Youngstown State,2024-03-02,0,-1,Purdue Fort Wayne,REG (Conf),-1,64.0,73.0,23.0,56.0,0.411,7.0,21.0,0.333,16.0,35.0,0.457,0.473,11.0,12.0,0.917,5.0,24.0,29.0,16.0,10.0,6.0,16.0,15.0,27.0,62.0,0.435,13.0,34.0,0.382,14.0,28.0,0.500,0.540,6.0,9.0,0.667,9.0,26.0,35.0,12.0,7.0,2.0,14.0,15.0,0,0,-9.0,1.361013,71.62,0.893605,1.019268,71.62
133252,2024,Youngstown State,2024-03-05,0,1,IU Indy,REG (Non-Conf),1,73.0,50.0,29.0,63.0,0.460,8.0,16.0,0.500,21.0,47.0,0.447,0.524,7.0,11.0,0.636,7.0,23.0,30.0,20.0,9.0,4.0,12.0,22.0,16.0,48.0,0.333,1.0,12.0,0.083,15.0,36.0,0.417,0.344,17.0,25.0,0.680,6.0,26.0,32.0,12.0,7.0,8.0,18.0,19.0,0,0,23.0,1.500000,71.92,1.015017,0.695217,71.92
133253,2024,Youngstown State,2024-03-07,0,-1,Green Bay,REG (Non-Conf),-1,57.0,94.0,21.0,56.0,0.375,10.0,27.0,0.370,11.0,29.0,0.379,0.464,5.0,13.0,0.385,7.0,13.0,20.0,12.0,6.0,0.0,16.0,14.0,35.0,59.0,0.593,11.0,24.0,0.458,24.0,35.0,0.686,0.686,13.0,14.0,0.929,9.0,25.0,34.0,26.0,8.0,5.0,12.0,12.0,0,0,-37.0,1.500000,69.44,0.820853,1.353687,69.44

Fix columns for this analysis

In [3]:
df['Team Win%'] = (df['Result'] == 1).astype(int)

df['Team EFG%'] = (0.5*df['Team 3P'] + df['Team FG'])/df['Team FGA']
df['Opponent EFG%'] = (0.5*df['Opponent 3P'] + df['Opponent FG'])/df['Opponent FGA']

df['Team TOR'] = df['Team TOV'] / df['Possessions'] * 100
df['Opponent TOR'] = df['Opponent TOV'] / df['Possessions'] * 100

df['Team ORBR'] = df['Team ORB'] / df['Possessions'] * 100

df['Team FTR'] = df['Team FT'] / df['Team FGA'] * 100
df['Opponent FTR'] = df['Opponent FT'] / df['Opponent FGA'] * 100

df

,Season,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo,Team Win%,Team EFG%,Opponent EFG%,Team TOR,Opponent TOR,Team ORBR,Team FTR,Opponent FTR
0,2012,Air Force,2011-11-11,0,-1,Lipscomb,REG (Non-Conf),1,68.0,59.0,23.0,63.0,0.365,1.0,4.0,0.250,22.0,59.0,0.373,0.373,21.0,30.0,0.700,15.0,26.0,41.0,11.0,11.0,2.0,16.0,23.0,18.0,54.0,0.333,4.0,12.0,0.333,14.0,42.0,0.333,0.370,19.0,31.0,0.613,13.0,23.0,36.0,10.0,8.0,3.0,23.0,24.0,0,0,9.0,1.361013,77.42,0.878326,0.762077,77.42,1,0.373016,0.370370,20.666494,29.708086,19.374839,33.333333,35.185185
1,2012,Air Force,2011-11-13,0,-1,Tennessee-Martin,REG (Non-Conf),-1,60.0,84.0,27.0,64.0,0.422,4.0,8.0,0.500,23.0,56.0,0.411,0.453,2.0,4.0,0.500,12.0,23.0,35.0,17.0,10.0,1.0,27.0,16.0,32.0,69.0,0.464,10.0,30.0,0.333,22.0,39.0,0.564,0.536,10.0,11.0,0.909,9.0,22.0,31.0,15.0,12.0,4.0,18.0,7.0,0,0,-24.0,1.500000,81.80,0.733496,1.026895,81.80,0,0.453125,0.536232,33.007335,22.004890,14.669927,3.125000,14.492754
2,2012,Air Force,2011-11-17,0,1,Denver,REG (Non-Conf),-1,52.0,54.0,20.0,60.0,0.333,1.0,8.0,0.125,19.0,52.0,0.365,0.342,11.0,20.0,0.550,14.0,34.0,48.0,15.0,7.0,3.0,21.0,26.0,20.0,57.0,0.351,1.0,10.0,0.100,19.0,47.0,0.404,0.360,13.0,30.0,0.433,10.0,32.0,42.0,16.0,13.0,4.0,20.0,19.0,0,0,-2.0,1.102120,78.00,0.666667,0.692308,78.00,0,0.341667,0.359649,26.923077,25.641026,17.948718,18.333333,22.807018
3,2012,Air Force,2011-11-19,0,-1,Texas Southern,REG (Non-Conf),1,64.0,54.0,20.0,51.0,0.392,0.0,2.0,0.000,20.0,49.0,0.408,0.392,24.0,33.0,0.727,8.0,27.0,35.0,13.0,14.0,1.0,21.0,20.0,17.0,57.0,0.298,5.0,18.0,0.278,12.0,39.0,0.308,0.342,15.0,24.0,0.625,15.0,26.0,41.0,13.0,10.0,6.0,30.0,27.0,0,0,10.0,1.381279,80.54,0.794636,0.670474,80.54,1,0.392157,0.342105,26.074000,37.248572,9.932953,47.058824,26.315789
4,2012,Air Force,2011-11-21,0,-1,Texas State,REG (Non-Conf),1,77.0,69.0,25.0,61.0,0.410,1.0,6.0,0.167,24.0,55.0,0.436,0.418,26.0,31.0,0.839,16.0,29.0,45.0,10.0,9.0,3.0,19.0,21.0,27.0,67.0,0.403,4.0,21.0,0.190,23.0,46.0,0.500,0.433,11.0,20.0,0.550,13.0,17.0,30.0,10.0,8.0,2.0,14.0,20.0,0,0,8.0,1.338710,77.22,0.997151,0.893551,77.22,1,0.418033,0.432836,24.605025,18.130018,20.720021,42.622951,16.417910
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133249,2024,Youngstown State,2024-02-24,0,-1,Northern Kentucky,REG (Conf),1,68.0,64.0,24.0,57.0,0.421,12.0,23.0,0.522,12.0,34.0,0.353,0.526,8.0,11.0,0.727,8.0,28.0,36.0,12.0,4.0,6.0,13.0,14.0,22.0,61.0,0.361,10.0,23.0,0.435,12.0,38.0,0.316,0.443,10.0,13.0,0.769,8.0,19.0,27.0,13.0,10.0,4.0,8.0,12.0,0,0,4.0,1.214668,66.78,1.018269,0.958371,66.78,1,0.526316,0.442623,19.466906,11.979635,11.979635,14.035088,16.393443
133250,2024,Youngstown State,2024-02-27,0,1,Cleveland State,REG (Conf),-1,53.0,56.0,21.0,60.0,0.350,7.0,26.0,0.269,14.0,34.0,0.412,0.408,4.0,4.0,1.000,5.0,29.0,34.0,15.0,10.0,4.0,19.0,20.0,17.0,58.0,0.293,4.0,13.0,0.308,13.0,45.0,0.289,0.328,18.0,22.0,0.818,12.0,31.0,43.0,5.0,7.0,1.0,17.0,11.0,0,0,-3.0,1.166625,74.22,0.714093,0.754514,74.22,0,0.408333,0.327586,25.599569,22.904877,6.736729,6.666667,31.034483
133251,2024,Youngstown State,2024-03-02,0,-1,Purdue Fort Wayne,REG (Conf),-1,64.0,73.0,23.0,56.0,0.411,7.0,21.0,0.333,16.0,35.0,0.457,0.473,11.0,12.0,0.917,5.0,24.0,29.0,16.0,10.0,6.0,16.0,15.0,27.0,62.0,0.435,13.0,34.0,0.382,14.0,28.0,0.500,0.540,6.0,9.0,0.667,9.0,26.0,35.0,12.0,7.0,2.0,14.0,15.0,0,0,-9.0,1.361013,71.62,0.893605,1.019268,71.62,0,0.473214,0.540323,22.340128,19.547612,6.981290,19.642857,9.677419
133252,2024,Youngstown State,2024-03-05,0,1,IU Indy,REG (Non-Conf),1,73.0,50.0,29.0,63.0,0.460,8.0,16.0,0.500,21.0,47.0,0.447,0.524,7.0,11.0,0.636,7.0,23.0,30.0,20.0,9.0,4.0,12.0,22.0,16.0,48.0,0.333,1.0,12.0,0.083,15.0,36.0,0.417,0.344,17.0,25.0,0.680,6.0,26.0,32.0,12.0,7.0,8.0,18.0,19.0,0,0,23.0,1.500000,71.92,1.015017,0.695217,71.92,1,0.523810,0.343750,16.685206,25.027809,9.733037,11.111111,35.416667
133253,2024,Youngstown State,2024-03-07,0,-1,Green Bay,REG (Non-Conf),-1,57.0,94.0,21.0,56.0,0.375,10.0,27.0,0.370,11.0,29.0,0.379,0.464,5.0,13.0,0.385,7.0,13.0,20.0,12.0,6.0,0.0,16.0,14.0,35.0,59.0,0.593,11.0,24.0,0.458,24.0,35.0,0.686,0.686,13.0,14.0,0.929,9.0,25.0,34.0,26.0,8.0,5.0,12.0,12.0,0,0,-37.0,1.500000,69.44,0.820853,1.353687,69.44,0,0.464286,0.686441,23.041475,17.281106,10.080645,8.928571,22.033898

In [4]:
df_stats = (
    df
    .groupby(['Season', 'Team'])
    [['Team Win%', 'Team EFG%', 'Opponent EFG%', 'Team TOR', 'Opponent TOR', 'Team ORBR', 'Team FTR', 'Opponent FTR']]
    .mean()
    .reset_index()
)

df_stats

,Season,Team,Team Win%,Team EFG%,Opponent EFG%,Team TOR,Opponent TOR,Team ORBR,Team FTR,Opponent FTR
0,2012,Air Force,0.206897,0.359092,0.465672,28.432136,24.020646,15.950771,27.764713,26.582950
1,2012,Akron,0.437500,0.479016,0.450917,24.421918,22.137917,13.804245,23.486284,24.877060
2,2012,Alabama,0.387097,0.385596,0.452268,23.786649,26.323043,16.400917,23.213107,22.586530
3,2012,Alabama A&M,0.571429,0.399033,0.398839,22.398825,22.936621,19.312337,28.515040,21.120411
4,2012,Alabama State,0.481481,0.376662,0.392360,28.142944,22.975633,19.676092,27.066845,32.001872
...,...,...,...,...,...,...,...,...,...,...
4548,2024,Wright State,0.516129,0.477860,0.488562,18.043420,19.560289,9.488515,21.044587,21.790551
4549,2024,Wyoming,0.517241,0.507442,0.464675,20.152826,16.741229,9.383333,17.073582,17.922837
4550,2024,Xavier,0.035714,0.420328,0.513675,25.643612,21.237123,8.332792,13.540131,21.670300
4551,2024,Yale,0.296296,0.422138,0.493458,19.933187,19.684487,15.534023,17.563822,25.764921
4552,2024,Youngstown State,0.419355,0.454233,0.445694,22.053763,20.162864,11.022605,16.825523,21.493162

In [5]:
df_stats.drop(columns=['Opponent TOR'], inplace=True)  # low correlation

df_stats

,Season,Team,Team Win%,Team EFG%,Opponent EFG%,Team TOR,Team ORBR,Team FTR,Opponent FTR
0,2012,Air Force,0.206897,0.359092,0.465672,28.432136,15.950771,27.764713,26.582950
1,2012,Akron,0.437500,0.479016,0.450917,24.421918,13.804245,23.486284,24.877060
2,2012,Alabama,0.387097,0.385596,0.452268,23.786649,16.400917,23.213107,22.586530
3,2012,Alabama A&M,0.571429,0.399033,0.398839,22.398825,19.312337,28.515040,21.120411
4,2012,Alabama State,0.481481,0.376662,0.392360,28.142944,19.676092,27.066845,32.001872
...,...,...,...,...,...,...,...,...,...
4548,2024,Wright State,0.516129,0.477860,0.488562,18.043420,9.488515,21.044587,21.790551
4549,2024,Wyoming,0.517241,0.507442,0.464675,20.152826,9.383333,17.073582,17.922837
4550,2024,Xavier,0.035714,0.420328,0.513675,25.643612,8.332792,13.540131,21.670300
4551,2024,Yale,0.296296,0.422138,0.493458,19.933187,15.534023,17.563822,25.764921
4552,2024,Youngstown State,0.419355,0.454233,0.445694,22.053763,11.022605,16.825523,21.493162

In [6]:
df_stats.to_parquet(f'../data/preprocessed/womens_standard_stats/standard_stats.parquet')

'Done'

'Done'