# Get Women's Head-to-Head

Get head-to-head records and records against common opponents.

### Head-to-Head

In [1]:
SEASON = 2025
INCLUDE_CURRENT_SEASON = False

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 100)

df = pd.concat(
    [
        pd.read_parquet(fr'..\data\unprocessed\womens_sports_reference\full_season_sports_reference_{season}.parquet')
        .assign(Season=season)
        for season in range(2012, SEASON + INCLUDE_CURRENT_SEASON)
        if season != 2020  # tournament was cancelled
    ],
    ignore_index=True
)

df.insert(0, 'Season', df.pop('Season'))

df = df.loc[df['NCAA Tournament'] == 0, :].reset_index(drop=True)  # only include games before NCAA Tournament

df

,Season,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo
0,2012,Air Force,2011-11-11,0,-1,Lipscomb,REG (Non-Conf),1,68.0,59.0,23.0,63.0,0.365,1.0,4.0,0.250,22.0,59.0,0.373,0.373,21.0,30.0,0.700,15.0,26.0,41.0,11.0,11.0,2.0,16.0,23.0,18.0,54.0,0.333,4.0,12.0,0.333,14.0,42.0,0.333,0.370,19.0,31.0,0.613,13.0,23.0,36.0,10.0,8.0,3.0,23.0,24.0,0,0,9.0,1.361013,77.42,0.878326,0.762077,77.42
1,2012,Air Force,2011-11-13,0,-1,Tennessee-Martin,REG (Non-Conf),-1,60.0,84.0,27.0,64.0,0.422,4.0,8.0,0.500,23.0,56.0,0.411,0.453,2.0,4.0,0.500,12.0,23.0,35.0,17.0,10.0,1.0,27.0,16.0,32.0,69.0,0.464,10.0,30.0,0.333,22.0,39.0,0.564,0.536,10.0,11.0,0.909,9.0,22.0,31.0,15.0,12.0,4.0,18.0,7.0,0,0,-24.0,1.500000,81.80,0.733496,1.026895,81.80
2,2012,Air Force,2011-11-17,0,1,Denver,REG (Non-Conf),-1,52.0,54.0,20.0,60.0,0.333,1.0,8.0,0.125,19.0,52.0,0.365,0.342,11.0,20.0,0.550,14.0,34.0,48.0,15.0,7.0,3.0,21.0,26.0,20.0,57.0,0.351,1.0,10.0,0.100,19.0,47.0,0.404,0.360,13.0,30.0,0.433,10.0,32.0,42.0,16.0,13.0,4.0,20.0,19.0,0,0,-2.0,1.102120,78.00,0.666667,0.692308,78.00
3,2012,Air Force,2011-11-19,0,-1,Texas Southern,REG (Non-Conf),1,64.0,54.0,20.0,51.0,0.392,0.0,2.0,0.000,20.0,49.0,0.408,0.392,24.0,33.0,0.727,8.0,27.0,35.0,13.0,14.0,1.0,21.0,20.0,17.0,57.0,0.298,5.0,18.0,0.278,12.0,39.0,0.308,0.342,15.0,24.0,0.625,15.0,26.0,41.0,13.0,10.0,6.0,30.0,27.0,0,0,10.0,1.381279,80.54,0.794636,0.670474,80.54
4,2012,Air Force,2011-11-21,0,-1,Texas State,REG (Non-Conf),1,77.0,69.0,25.0,61.0,0.410,1.0,6.0,0.167,24.0,55.0,0.436,0.418,26.0,31.0,0.839,16.0,29.0,45.0,10.0,9.0,3.0,19.0,21.0,27.0,67.0,0.403,4.0,21.0,0.190,23.0,46.0,0.500,0.433,11.0,20.0,0.550,13.0,17.0,30.0,10.0,8.0,2.0,14.0,20.0,0,0,8.0,1.338710,77.22,0.997151,0.893551,77.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122907,2024,Youngstown State,2024-02-24,0,-1,Northern Kentucky,REG (Conf),1,68.0,64.0,24.0,57.0,0.421,12.0,23.0,0.522,12.0,34.0,0.353,0.526,8.0,11.0,0.727,8.0,28.0,36.0,12.0,4.0,6.0,13.0,14.0,22.0,61.0,0.361,10.0,23.0,0.435,12.0,38.0,0.316,0.443,10.0,13.0,0.769,8.0,19.0,27.0,13.0,10.0,4.0,8.0,12.0,0,0,4.0,1.214668,66.78,1.018269,0.958371,66.78
122908,2024,Youngstown State,2024-02-27,0,1,Cleveland State,REG (Conf),-1,53.0,56.0,21.0,60.0,0.350,7.0,26.0,0.269,14.0,34.0,0.412,0.408,4.0,4.0,1.000,5.0,29.0,34.0,15.0,10.0,4.0,19.0,20.0,17.0,58.0,0.293,4.0,13.0,0.308,13.0,45.0,0.289,0.328,18.0,22.0,0.818,12.0,31.0,43.0,5.0,7.0,1.0,17.0,11.0,0,0,-3.0,1.166625,74.22,0.714093,0.754514,74.22
122909,2024,Youngstown State,2024-03-02,0,-1,Purdue Fort Wayne,REG (Conf),-1,64.0,73.0,23.0,56.0,0.411,7.0,21.0,0.333,16.0,35.0,0.457,0.473,11.0,12.0,0.917,5.0,24.0,29.0,16.0,10.0,6.0,16.0,15.0,27.0,62.0,0.435,13.0,34.0,0.382,14.0,28.0,0.500,0.540,6.0,9.0,0.667,9.0,26.0,35.0,12.0,7.0,2.0,14.0,15.0,0,0,-9.0,1.361013,71.62,0.893605,1.019268,71.62
122910,2024,Youngstown State,2024-03-05,0,1,IU Indy,REG (Non-Conf),1,73.0,50.0,29.0,63.0,0.460,8.0,16.0,0.500,21.0,47.0,0.447,0.524,7.0,11.0,0.636,7.0,23.0,30.0,20.0,9.0,4.0,12.0,22.0,16.0,48.0,0.333,1.0,12.0,0.083,15.0,36.0,0.417,0.344,17.0,25.0,0.680,6.0,26.0,32.0,12.0,7.0,8.0,18.0,19.0,0,0,23.0,1.500000,71.92,1.015017,0.695217,71.92
122911,2024,Youngstown State,2024-03-07,0,-1,Green Bay,REG (Non-Conf),-1,57.0,94.0,21.0,56.0,0.375,10.0,27.0,0.370,11.0,29.0,0.379,0.464,5.0,13.0,0.385,7.0,13.0,20.0,12.0,6.0,0.0,16.0,14.0,35.0,59.0,0.593,11.0,24.0,0.458,24.0,35.0,0.686,0.686,13.0,14.0,0.929,9.0,25.0,34.0,26.0,8.0,5.0,12.0,12.0,0,0,-37.0,1.500000,69.44,0.820853,1.353687,69.44

In [3]:
def rescale_weights(arr, minimum, maximum):
    """
    Rescale the weights array to match desired weights.
    Assumes the data is already transformed where a 1 point win is 1.00, a blowout is 1.50, and a tie is 0.50.
    Ties will be weighted as half the minimum.
    """

    arr_scaled = ((arr - 1.00) / 0.50) * (maximum - minimum) + minimum
    arr_scaled[arr == 0.50] = minimum / 2
    return arr_scaled

# make sure losses have negative adjusted score differential in this file
df['Adjusted Score Differential'] = rescale_weights(df['Adjusted Score Differential'], 0.50, 1.00)*df['Result']

df

,Season,Team,Date,NCAA Tournament,Location,Opponent,Type,Result,Team Score,Opponent Score,Team FG,Team FGA,Team FG%,Team 3P,Team 3PA,Team 3P%,Team 2P,Team 2PA,Team 2P%,Team eFG%,Team FT,Team FTA,Team FT%,Team ORB,Team DRB,Team TRB,Team AST,Team STL,Team BLK,Team TOV,Team PF,Opponent FG,Opponent FGA,Opponent FG%,Opponent 3P,Opponent 3PA,Opponent 3P%,Opponent 2P,Opponent 2PA,Opponent 2P%,Opponent eFG%,Opponent FT,Opponent FTA,Opponent FT%,Opponent ORB,Opponent DRB,Opponent TRB,Opponent AST,Opponent STL,Opponent BLK,Opponent TOV,Opponent PF,Overtimes Amount,Overtime,Score Differential,Adjusted Score Differential,Possessions,Team PPP,Opponent PPP,Tempo
0,2012,Air Force,2011-11-11,0,-1,Lipscomb,REG (Non-Conf),1,68.0,59.0,23.0,63.0,0.365,1.0,4.0,0.250,22.0,59.0,0.373,0.373,21.0,30.0,0.700,15.0,26.0,41.0,11.0,11.0,2.0,16.0,23.0,18.0,54.0,0.333,4.0,12.0,0.333,14.0,42.0,0.333,0.370,19.0,31.0,0.613,13.0,23.0,36.0,10.0,8.0,3.0,23.0,24.0,0,0,9.0,0.861013,77.42,0.878326,0.762077,77.42
1,2012,Air Force,2011-11-13,0,-1,Tennessee-Martin,REG (Non-Conf),-1,60.0,84.0,27.0,64.0,0.422,4.0,8.0,0.500,23.0,56.0,0.411,0.453,2.0,4.0,0.500,12.0,23.0,35.0,17.0,10.0,1.0,27.0,16.0,32.0,69.0,0.464,10.0,30.0,0.333,22.0,39.0,0.564,0.536,10.0,11.0,0.909,9.0,22.0,31.0,15.0,12.0,4.0,18.0,7.0,0,0,-24.0,-1.000000,81.80,0.733496,1.026895,81.80
2,2012,Air Force,2011-11-17,0,1,Denver,REG (Non-Conf),-1,52.0,54.0,20.0,60.0,0.333,1.0,8.0,0.125,19.0,52.0,0.365,0.342,11.0,20.0,0.550,14.0,34.0,48.0,15.0,7.0,3.0,21.0,26.0,20.0,57.0,0.351,1.0,10.0,0.100,19.0,47.0,0.404,0.360,13.0,30.0,0.433,10.0,32.0,42.0,16.0,13.0,4.0,20.0,19.0,0,0,-2.0,-0.602120,78.00,0.666667,0.692308,78.00
3,2012,Air Force,2011-11-19,0,-1,Texas Southern,REG (Non-Conf),1,64.0,54.0,20.0,51.0,0.392,0.0,2.0,0.000,20.0,49.0,0.408,0.392,24.0,33.0,0.727,8.0,27.0,35.0,13.0,14.0,1.0,21.0,20.0,17.0,57.0,0.298,5.0,18.0,0.278,12.0,39.0,0.308,0.342,15.0,24.0,0.625,15.0,26.0,41.0,13.0,10.0,6.0,30.0,27.0,0,0,10.0,0.881279,80.54,0.794636,0.670474,80.54
4,2012,Air Force,2011-11-21,0,-1,Texas State,REG (Non-Conf),1,77.0,69.0,25.0,61.0,0.410,1.0,6.0,0.167,24.0,55.0,0.436,0.418,26.0,31.0,0.839,16.0,29.0,45.0,10.0,9.0,3.0,19.0,21.0,27.0,67.0,0.403,4.0,21.0,0.190,23.0,46.0,0.500,0.433,11.0,20.0,0.550,13.0,17.0,30.0,10.0,8.0,2.0,14.0,20.0,0,0,8.0,0.838710,77.22,0.997151,0.893551,77.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122907,2024,Youngstown State,2024-02-24,0,-1,Northern Kentucky,REG (Conf),1,68.0,64.0,24.0,57.0,0.421,12.0,23.0,0.522,12.0,34.0,0.353,0.526,8.0,11.0,0.727,8.0,28.0,36.0,12.0,4.0,6.0,13.0,14.0,22.0,61.0,0.361,10.0,23.0,0.435,12.0,38.0,0.316,0.443,10.0,13.0,0.769,8.0,19.0,27.0,13.0,10.0,4.0,8.0,12.0,0,0,4.0,0.714668,66.78,1.018269,0.958371,66.78
122908,2024,Youngstown State,2024-02-27,0,1,Cleveland State,REG (Conf),-1,53.0,56.0,21.0,60.0,0.350,7.0,26.0,0.269,14.0,34.0,0.412,0.408,4.0,4.0,1.000,5.0,29.0,34.0,15.0,10.0,4.0,19.0,20.0,17.0,58.0,0.293,4.0,13.0,0.308,13.0,45.0,0.289,0.328,18.0,22.0,0.818,12.0,31.0,43.0,5.0,7.0,1.0,17.0,11.0,0,0,-3.0,-0.666625,74.22,0.714093,0.754514,74.22
122909,2024,Youngstown State,2024-03-02,0,-1,Purdue Fort Wayne,REG (Conf),-1,64.0,73.0,23.0,56.0,0.411,7.0,21.0,0.333,16.0,35.0,0.457,0.473,11.0,12.0,0.917,5.0,24.0,29.0,16.0,10.0,6.0,16.0,15.0,27.0,62.0,0.435,13.0,34.0,0.382,14.0,28.0,0.500,0.540,6.0,9.0,0.667,9.0,26.0,35.0,12.0,7.0,2.0,14.0,15.0,0,0,-9.0,-0.861013,71.62,0.893605,1.019268,71.62
122910,2024,Youngstown State,2024-03-05,0,1,IU Indy,REG (Non-Conf),1,73.0,50.0,29.0,63.0,0.460,8.0,16.0,0.500,21.0,47.0,0.447,0.524,7.0,11.0,0.636,7.0,23.0,30.0,20.0,9.0,4.0,12.0,22.0,16.0,48.0,0.333,1.0,12.0,0.083,15.0,36.0,0.417,0.344,17.0,25.0,0.680,6.0,26.0,32.0,12.0,7.0,8.0,18.0,19.0,0,0,23.0,1.000000,71.92,1.015017,0.695217,71.92
122911,2024,Youngstown State,2024-03-07,0,-1,Green Bay,REG (Non-Conf),-1,57.0,94.0,21.0,56.0,0.375,10.0,27.0,0.370,11.0,29.0,0.379,0.464,5.0,13.0,0.385,7.0,13.0,20.0,12.0,6.0,0.0,16.0,14.0,35.0,59.0,0.593,11.0,24.0,0.458,24.0,35.0,0.686,0.686,13.0,14.0,0.929,9.0,25.0,34.0,26.0,8.0,5.0,12.0,12.0,0,0,-37.0,-1.000000,69.44,0.820853,1.353687,69.44

In [4]:
df_h2h = (
    df
    .groupby(['Season', 'Team', 'Opponent'])
    .agg(
        h2h_sum=('Adjusted Score Differential', 'sum'),
        h2h_count=('Result', 'count')
    )
    .reset_index()
    .rename(columns={'Team': 'Team A', 'Opponent': 'Team B'})
)

# add 1/4 to denominator so that a team that beats opponent multiple times is better accounted for
df_h2h['Head to Head'] = df_h2h['h2h_sum'] / (df_h2h['h2h_count'] + 1/4)

df_h2h

,Season,Team A,Team B,h2h_sum,h2h_count,Head to Head
0,2012,Air Force,Alabama,-1.000000,1,-0.800000
1,2012,Air Force,Boise State,-1.785760,2,-0.793671
2,2012,Air Force,Colorado State,-2.000000,2,-0.888889
3,2012,Air Force,Denver,-0.602120,1,-0.481696
4,2012,Air Force,Jackson State,0.933063,1,0.746451
...,...,...,...,...,...,...
87031,2024,Youngstown State,St. Bonaventure,-0.838710,1,-0.670968
87032,2024,Youngstown State,West Virginia,-1.000000,1,-0.800000
87033,2024,Youngstown State,Western Michigan,-0.602120,1,-0.481696
87034,2024,Youngstown State,Wright State,0.051961,2,0.023094
87035,2024,Youngstown State,Xavier,0.948039,1,0.758431

### Common Opponents

In [5]:
df_h2h['h2h_avg'] = df_h2h['h2h_sum']/df_h2h['h2h_count']

df_h2h

,Season,Team A,Team B,h2h_sum,h2h_count,Head to Head,h2h_avg
0,2012,Air Force,Alabama,-1.000000,1,-0.800000,-1.000000
1,2012,Air Force,Boise State,-1.785760,2,-0.793671,-0.892880
2,2012,Air Force,Colorado State,-2.000000,2,-0.888889,-1.000000
3,2012,Air Force,Denver,-0.602120,1,-0.481696,-0.602120
4,2012,Air Force,Jackson State,0.933063,1,0.746451,0.933063
...,...,...,...,...,...,...,...
87031,2024,Youngstown State,St. Bonaventure,-0.838710,1,-0.670968,-0.838710
87032,2024,Youngstown State,West Virginia,-1.000000,1,-0.800000,-1.000000
87033,2024,Youngstown State,Western Michigan,-0.602120,1,-0.481696,-0.602120
87034,2024,Youngstown State,Wright State,0.051961,2,0.023094,0.025980
87035,2024,Youngstown State,Xavier,0.948039,1,0.758431,0.948039

In [6]:
def get_opponents_results(season, team):
    data = df_h2h.loc[
        (df_h2h['Season'] == season) & 
        (df_h2h['Team A'] == team), 
        :
    ]
    
    return dict(zip(
        data['Team B'],
        data['h2h_avg']
    ))

In [7]:
from tqdm.autonotebook import tqdm

season_team_opponents = {
    season: {
        team: get_opponents_results(season, team) 
        for team in df_h2h.loc[df_h2h['Season'] == season, 'Team A'].unique()
    } 
    for season in tqdm(df_h2h['Season'].unique())
}

len(season_team_opponents)

C:\Users\mhugh\AppData\Local\Temp\ipykernel_13644\755660832.py:1: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm

  0%|          | 0/12 [00:00<?, ?it/s]

12

In [8]:
import numpy as np

def get_difference(season, team_a, team_b):
    team_a_dict = season_team_opponents[season][team_a]
    team_b_dict = season_team_opponents[season][team_b]

    common_keys = team_a_dict.keys() & team_b_dict.keys()

    if len(common_keys) == 0:
        return np.nan, np.nan
    
    commons_opps_results = tuple(team_a_dict[key] - team_b_dict[key] for key in common_keys)

    return np.sum(commons_opps_results), (len(commons_opps_results))

In [9]:
common_opps = [
    (season, team_a, team_b, *get_difference(season, team_a, team_b))
    for season in tqdm(df_h2h['Season'].unique())
    for team_a in df_h2h.loc[df_h2h['Season'] == season, 'Team A'].unique()
    for team_b in df_h2h.loc[df_h2h['Season'] == season, 'Team A'].unique()  # could use Team B but shouldn't matter
    if team_a != team_b
]

common_opps[:5]

  0%|          | 0/12 [00:00<?, ?it/s]

[(2012, 'Air Force', 'Akron', nan, nan),
 (2012, 'Air Force', 'Alabama', nan, nan),
 (2012, 'Air Force', 'Alabama A&M', 0.5871746800195029, 3),
 (2012, 'Air Force', 'Alabama State', 0.1716690566331004, 3),
 (2012, 'Air Force', 'Albany (NY)', nan, nan)]

In [10]:
df_common_opps = pd.DataFrame(
    common_opps,
    columns=['Season', 'Team A', 'Team B', 'common_opps_sum', 'common_opps_count'],
)

df_common_opps

,Season,Team A,Team B,common_opps_sum,common_opps_count
0,2012,Air Force,Akron,NaN,NaN
1,2012,Air Force,Alabama,NaN,NaN
2,2012,Air Force,Alabama A&M,0.587175,3.0
3,2012,Air Force,Alabama State,0.171669,3.0
4,2012,Air Force,Albany (NY),NaN,NaN
...,...,...,...,...,...
1467597,2024,Youngstown State,Wofford,NaN,NaN
1467598,2024,Youngstown State,Wright State,-1.772090,10.0
1467599,2024,Youngstown State,Wyoming,-0.855298,1.0
1467600,2024,Youngstown State,Xavier,NaN,NaN
1467601,2024,Youngstown State,Yale,NaN,NaN

In [11]:
df_h2h = pd.merge(
    df_h2h.drop(columns=['h2h_avg']),
    df_common_opps,
    how='outer',
    on=['Season', 'Team A', 'Team B'],
)

df_h2h

,Season,Team A,Team B,h2h_sum,h2h_count,Head to Head,common_opps_sum,common_opps_count
0,2012,Air Force,Akron,NaN,NaN,NaN,NaN,NaN
1,2012,Air Force,Alabama,-1.000000,1.0,-0.800000,NaN,NaN
2,2012,Air Force,Alabama A&M,NaN,NaN,NaN,0.587175,3.0
3,2012,Air Force,Alabama State,NaN,NaN,NaN,0.171669,3.0
4,2012,Air Force,Albany (NY),NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
1467597,2024,Youngstown State,Wofford,NaN,NaN,NaN,NaN,NaN
1467598,2024,Youngstown State,Wright State,0.051961,2.0,0.023094,-1.772090,10.0
1467599,2024,Youngstown State,Wyoming,NaN,NaN,NaN,-0.855298,1.0
1467600,2024,Youngstown State,Xavier,0.948039,1.0,0.758431,NaN,NaN
1467601,2024,Youngstown State,Yale,NaN,NaN,NaN,NaN,NaN

In [12]:
# add 1/4 to denominator so that a team that beats opponent multiple times is better accounted for
df_h2h['Common Opps'] = df_h2h['common_opps_sum']/(df_h2h['common_opps_count'] + 1/4)

df_h2h

,Season,Team A,Team B,h2h_sum,h2h_count,Head to Head,common_opps_sum,common_opps_count,Common Opps
0,2012,Air Force,Akron,NaN,NaN,NaN,NaN,NaN,NaN
1,2012,Air Force,Alabama,-1.000000,1.0,-0.800000,NaN,NaN,NaN
2,2012,Air Force,Alabama A&M,NaN,NaN,NaN,0.587175,3.0,0.180669
3,2012,Air Force,Alabama State,NaN,NaN,NaN,0.171669,3.0,0.052821
4,2012,Air Force,Albany (NY),NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1467597,2024,Youngstown State,Wofford,NaN,NaN,NaN,NaN,NaN,NaN
1467598,2024,Youngstown State,Wright State,0.051961,2.0,0.023094,-1.772090,10.0,-0.172887
1467599,2024,Youngstown State,Wyoming,NaN,NaN,NaN,-0.855298,1.0,-0.684239
1467600,2024,Youngstown State,Xavier,0.948039,1.0,0.758431,NaN,NaN,NaN
1467601,2024,Youngstown State,Yale,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df_h2h.loc[(df_h2h['Season'] == 2024) & df_h2h['Team A'].str.contains('Connecticut'), :]

,Season,Team A,Team B,h2h_sum,h2h_count,Head to Head,common_opps_sum,common_opps_count,Common Opps
1354158,2024,Central Connecticut State,Abilene Christian,NaN,NaN,NaN,NaN,NaN,NaN
1354159,2024,Central Connecticut State,Air Force,NaN,NaN,NaN,NaN,NaN,NaN
1354160,2024,Central Connecticut State,Akron,NaN,NaN,NaN,NaN,NaN,NaN
1354161,2024,Central Connecticut State,Alabama,NaN,NaN,NaN,-0.214240,1.0,-0.171392
1354162,2024,Central Connecticut State,Alabama A&M,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
1359897,2024,Connecticut,Wright State,NaN,NaN,NaN,NaN,NaN,NaN
1359898,2024,Connecticut,Wyoming,NaN,NaN,NaN,1.917062,1.0,1.533650
1359899,2024,Connecticut,Xavier,1.0,1.0,0.8,17.844118,9.0,1.929094
1359900,2024,Connecticut,Yale,NaN,NaN,NaN,3.734353,2.0,1.659713
1359901,2024,Connecticut,Youngstown State,NaN,NaN,NaN,0.051961,1.0,0.041569

Remove all the rows without data to reduce the dataframe size

In [14]:
df_h2h = df_h2h.loc[(df_h2h['Head to Head'].notna()) | (df_h2h['Common Opps'].notna()), :].reset_index(drop=True)

df_h2h

,Season,Team A,Team B,h2h_sum,h2h_count,Head to Head,common_opps_sum,common_opps_count,Common Opps
0,2012,Air Force,Alabama,-1.000000,1.0,-0.800000,NaN,NaN,NaN
1,2012,Air Force,Alabama A&M,NaN,NaN,NaN,0.587175,3.0,0.180669
2,2012,Air Force,Alabama State,NaN,NaN,NaN,0.171669,3.0,0.052821
3,2012,Air Force,Alcorn State,NaN,NaN,NaN,1.179970,3.0,0.363068
4,2012,Air Force,American,NaN,NaN,NaN,-3.255768,2.0,-1.447008
...,...,...,...,...,...,...,...,...,...
739007,2024,Youngstown State,Wichita State,NaN,NaN,NaN,-0.102120,1.0,-0.081696
739008,2024,Youngstown State,Wisconsin,NaN,NaN,NaN,-0.912292,1.0,-0.729834
739009,2024,Youngstown State,Wright State,0.051961,2.0,0.023094,-1.772090,10.0,-0.172887
739010,2024,Youngstown State,Wyoming,NaN,NaN,NaN,-0.855298,1.0,-0.684239
739011,2024,Youngstown State,Xavier,0.948039,1.0,0.758431,NaN,NaN,NaN

In [15]:
df_h2h.drop(columns=['h2h_sum', 'h2h_count', 'common_opps_sum', 'common_opps_count'], inplace=True)

df_h2h

        Season            Team A         Team B  Head to Head  Common Opps
0         2012         Air Force        Alabama     -0.800000          NaN
1         2012         Air Force    Alabama A&M           NaN     0.180669
2         2012         Air Force  Alabama State           NaN     0.052821
3         2012         Air Force   Alcorn State           NaN     0.363068
4         2012         Air Force       American           NaN    -1.447008
...        ...               ...            ...           ...          ...
739007    2024  Youngstown State  Wichita State           NaN    -0.081696
739008    2024  Youngstown State      Wisconsin           NaN    -0.729834
739009    2024  Youngstown State   Wright State      0.023094    -0.172887
739010    2024  Youngstown State        Wyoming           NaN    -0.684239
739011    2024  Youngstown State         Xavier      0.758431          NaN

[739012 rows x 5 columns]

In [19]:
df_h2h.to_parquet('../data/preprocessed/womens_h2h/h2h.parquet')

'Done'

'Done'