# Simulate Men's Tourney

Generated brackets based on model probabilities and public picks.

In [1]:
season = 2025

playin_losers = (  # remove play-in losers from seeding data
    1384,  # St Francis PA
    1291,  # Mt St Mary's
    1361,  # San Diego St
    1400,  # Texas
)

season

2025

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 100)

df_seeds = pd.read_csv(r'..\data\unprocessed\kaggle\MNCAATourneySeeds.csv')

df_seeds = df_seeds.loc[df_seeds['Season'] == season, :].reset_index(drop=True)

df_seeds.insert(2, 'Play In', df_seeds['Seed'].str.endswith(('a', 'b')))
df_seeds.insert(2, 'Region', df_seeds['Seed'].str[0])
df_seeds['Seed'] = df_seeds['Seed'].str.extract('(\d+)').astype(int)

df_seeds = df_seeds.loc[~df_seeds['TeamID'].isin(playin_losers), :].reset_index(drop=True)

df_seeds.insert(1, 'Region Seed', df_seeds['Region'] + df_seeds['Seed'].astype(str).str.zfill(2))

df_seeds

    Season Region Seed  Seed Region  Play In  TeamID
0     2025         W01     1      W    False    1181
1     2025         W02     2      W    False    1104
2     2025         W03     3      W    False    1458
3     2025         W04     4      W    False    1112
4     2025         W05     5      W    False    1332
..     ...         ...   ...    ...      ...     ...
59    2025         Z12    12      Z    False    1161
60    2025         Z13    13      Z    False    1213
61    2025         Z14    14      Z    False    1423
62    2025         Z15    15      Z    False    1303
63    2025         Z16    16      Z    False    1313

[64 rows x 6 columns]

### Simulate Tournament

I think it might make more sense to just go through all 63 matchups as a dictionary, adding future rounds as you go

In [3]:
df_matrix = pd.read_csv(
    fr'../data/simulations/mens/matchup_matrix_{season}.csv',
    index_col='Team A ID',
).rename_axis(index=None)

df_matrix.columns = df_matrix.columns.astype(int)

df_matrix

,1103,1104,1106,1110,1112,1116,1120,1124,1136,1140,1155,1161,1163,1166,1179,1181,1188,1196,1208,1211,1213,1219,1222,1228,1235,1242,1246,1251,1252,1257,1266,1268,1270,1272,1276,1277,1279,1280,1281,1285,1303,1307,1313,1314,1328,1332,1345,1352,1385,1388,1397,1401,1403,1407,1417,1423,1429,1433,1435,1458,1459,1462,1463,1471
1103,NaN,0.218855,0.799502,0.682211,0.130761,0.345421,0.108685,0.200028,0.397114,0.140669,0.138632,0.181955,0.156639,0.152973,0.395766,0.066197,0.695523,0.122202,0.196100,0.090257,0.368122,0.492275,0.069799,0.208546,0.198045,0.115667,0.143089,0.590858,0.658768,0.161206,0.118439,0.097387,0.300348,0.276252,0.171951,0.145708,0.231806,0.193931,0.118082,0.562885,0.651718,0.247957,0.623069,0.139795,0.271491,0.268023,0.175434,0.598475,0.079134,0.136927,0.075853,0.152122,0.097493,0.461942,0.225625,0.647964,0.299588,0.155318,0.170433,0.189577,0.741452,0.278926,0.502084,0.331959
1104,0.773840,NaN,0.895708,0.865300,0.554941,0.791982,0.365387,0.663334,0.914295,0.580909,0.558605,0.881970,0.825739,0.865018,0.894333,0.219921,0.921878,0.253007,0.666295,0.659649,0.893610,0.897161,0.305743,0.592925,0.761049,0.640653,0.739727,0.907130,0.896616,0.606808,0.502564,0.595208,0.899091,0.836064,0.558095,0.635498,0.756574,0.782011,0.778688,0.934768,0.935407,0.801104,0.949688,0.812229,0.891663,0.779390,0.583837,0.949091,0.518280,0.579855,0.471348,0.497814,0.424679,0.894360,0.716078,0.918126,0.924590,0.668307,0.886933,0.550678,0.883818,0.927256,0.885258,0.738776
1106,0.179176,0.090486,NaN,0.595856,0.043280,0.076725,0.065868,0.093101,0.204948,0.075485,0.109470,0.052192,0.084634,0.082508,0.126404,0.046008,0.410219,0.072190,0.049554,0.054667,0.084373,0.249944,0.044407,0.068330,0.062763,0.049950,0.068444,0.110275,0.145294,0.063841,0.044256,0.036046,0.081228,0.060967,0.069433,0.051301,0.086310,0.066260,0.051455,0.264313,0.331485,0.060918,0.262872,0.076097,0.082512,0.073306,0.061388,0.273054,0.060978,0.047509,0.054323,0.061369,0.067799,0.170539,0.099599,0.279555,0.130761,0.045221,0.065361,0.105654,0.404787,0.073142,0.112716,0.052860
1110,0.335018,0.128592,0.328124,NaN,0.050041,0.063869,0.046293,0.058377,0.338637,0.071242,0.049386,0.073047,0.056501,0.078504,0.102785,0.051340,0.464864,0.041666,0.080625,0.052089,0.084680,0.168029,0.032600,0.106275,0.065496,0.059483,0.085912,0.158352,0.224518,0.046732,0.083933,0.037781,0.060326,0.059988,0.105142,0.061328,0.081670,0.065819,0.073693,0.421402,0.356418,0.072665,0.349062,0.056537,0.071239,0.057413,0.057038,0.422335,0.045876,0.044675,0.065898,0.096278,0.099120,0.138584,0.079787,0.200782,0.212515,0.051079,0.077153,0.061218,0.339169,0.061514,0.125009,0.055119
1112,0.849992,0.413901,0.944698,0.940539,NaN,0.804638,0.243786,0.496646,0.868259,0.589636,0.367826,0.748614,0.664762,0.625196,0.862989,0.245570,0.931439,0.409921,0.570094,0.403422,0.873699,0.877436,0.217001,0.597953,0.679849,0.458624,0.521171,0.740392,0.889514,0.685157,0.440955,0.528988,0.847090,0.795267,0.696764,0.354440,0.646363,0.681545,0.453841,0.890609,0.904607,0.593883,0.921405,0.736730,0.751192,0.627955,0.454033,0.910176,0.550072,0.532861,0.290509,0.369040,0.418512,0.937756,0.519803,0.921868,0.608392,0.624988,0.670154,0.660604,0.900149,0.851427,0.819019,0.828993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458,0.780371,0.389194,0.890562,0.944453,0.389597,0.563831,0.176939,0.567463,0.836870,0.399985,0.447483,0.810910,0.556216,0.694846,0.805801,0.131407,0.926998,0.242592,0.339952,0.484925,0.793720,0.790506,0.096336,0.405367,0.563077,0.381417,0.530826,0.720593,0.858295,0.547589,0.332267,0.543858,0.788740,0.719824,0.468229,0.477838,0.648739,0.572130,0.490507,0.896755,0.910793,0.585822,0.906962,0.616691,0.578651,0.555757,0.417935,0.896250,0.457748,0.506062,0.367603,0.415326,0.322913,0.904175,0.580120,0.894545,0.620202,0.415111,0.595268,NaN,0.850984,0.858708,0.855305,0.729458
1459,0.272956,0.101510,0.540001,0.639830,0.086931,0.128706,0.089005,0.119507,0.504115,0.135489,0.073517,0.186350,0.215190,0.223448,0.157788,0.044355,0.653221,0.068643,0.080932,0.099813,0.412377,0.284683,0.050626,0.090666,0.076874,0.045983,0.096886,0.283741,0.385499,0.117186,0.095437,0.062110,0.194085,0.104504,0.092306,0.074613,0.108003,0.101367,0.123171,0.554658,0.595636,0.177843,0.603193,0.181725,0.133931,0.124906,0.119077,0.527786,0.060389,0.084360,0.063781,0.057323,0.077350,0.394463,0.112201,0.524174,0.180315,0.107304,0.176022,0.147421,NaN,0.220605,0.342480,0.164765
1462,0.685447,0.133410,0.907740,0.916149,0.149884,0.349836,0.091992,0.205118,0.815563,0.299824,0.329436,0.493447,0.249896,0.311424,0.471995,0.090629,0.880801,0.178312,0.340013,0.220888,0.687150,0.608330,0.046280,0.280314,0.155957,0.207324,0.200752,0.549784,0.608082,0.343330,0.281993,0.198947,0.402111,0.507391,0.361578,0.155552,0.283928,0.379260,0.358958,0.803022,0.894649,0.526929,0.855455,0.390523,0.458648,0.319246,0.375782,0.858923,0.159585,0.227200,0.113861,0.319123,0.146677,0.771080,0.281556,0.703341,0.452368,0.378758,0.450705,0.184884,0.754865,NaN,0.469931,0.461503
1463,0.471128,0.100979,0.880086,0.844361,0.165307,0.366116,0.058131,0.167326,0.676179,0.176895,0.106133,0.441824,0.280241,0.374251,0.364012,0.056189,0.827635,0.066596,0.288253,0.271551,0.622454,0.373122,0.041701,0.121813,0.140129,0.250599,0.132411,0.649015,0.568499,0.160879,0.153113,0.105345,0.387001,0.507742,0.169434,0.241309,0.147070,0.251887,0.264702,0.769732,0.822047,0.395778,0.880443,0.276609,0.362653,0.289593,0.119515,0.903722,0.086869,0.152187,0.076543,0.131002,0.102046,0.579540,0.315374,0.558016,0.512723,0.185294,0.325309,0.148982,0.701600,0.495724,NaN,0.289520
1471,0.579549,0.292178,0.910689,0.931150,0.200274,0.597937,0.125443,0.410067,0.729523,0.293145,0.310313,0.470809,0.294411,0.350196,0.560018,0.044450,0.909881,0.190463,0.198025,0.193093,0.618368,0.568505,0.100503,0.308215,0.178019,0.212154,0.341902,0.462321,0.612857,0.389416,0.143060,0.076835,0.325967,0.555149,0.345412,0.196658,0.339951,0.433561,0.277511,0.764234,0.739938,0.453552,0.799767,0.385079,0.501736,0.255757,0.252960,0.861895,0.241036,0.342988,0.093686,0.215509,0.189322,0.714060,0.228025,0.702861,0.317242,0.264370,0.400301,0.228276,0.827383,0.521943,0.629880,NaN

In [4]:
id_to_region_seed = dict(zip(df_seeds['TeamID'], df_seeds['Region Seed']))

df_matrix.index = df_matrix.index.map(id_to_region_seed)
df_matrix.columns = df_matrix.columns.map(id_to_region_seed)

df_matrix

,W13,W02,Y16,W16,W04,Z10,Y01,W09,Y15,W06,X05,Z12,Z08,Y09,Z11,W01,X16,Z01,X09,X08,Z13,X13,X01,X06,Y03,Z07,X03,W12,Y14,Y08,Y07,Z04,X12,Z05,Y05,Y02,Y06,W08,Z06,W14,Z15,Y10,Z16,Y11,Z09,W05,X04,W15,Z02,W07,X02,Y04,Z03,X14,X07,Z14,X10,W11,W10,W03,X15,X11,Y13,Y12
W13,NaN,0.218855,0.799502,0.682211,0.130761,0.345421,0.108685,0.200028,0.397114,0.140669,0.138632,0.181955,0.156639,0.152973,0.395766,0.066197,0.695523,0.122202,0.196100,0.090257,0.368122,0.492275,0.069799,0.208546,0.198045,0.115667,0.143089,0.590858,0.658768,0.161206,0.118439,0.097387,0.300348,0.276252,0.171951,0.145708,0.231806,0.193931,0.118082,0.562885,0.651718,0.247957,0.623069,0.139795,0.271491,0.268023,0.175434,0.598475,0.079134,0.136927,0.075853,0.152122,0.097493,0.461942,0.225625,0.647964,0.299588,0.155318,0.170433,0.189577,0.741452,0.278926,0.502084,0.331959
W02,0.773840,NaN,0.895708,0.865300,0.554941,0.791982,0.365387,0.663334,0.914295,0.580909,0.558605,0.881970,0.825739,0.865018,0.894333,0.219921,0.921878,0.253007,0.666295,0.659649,0.893610,0.897161,0.305743,0.592925,0.761049,0.640653,0.739727,0.907130,0.896616,0.606808,0.502564,0.595208,0.899091,0.836064,0.558095,0.635498,0.756574,0.782011,0.778688,0.934768,0.935407,0.801104,0.949688,0.812229,0.891663,0.779390,0.583837,0.949091,0.518280,0.579855,0.471348,0.497814,0.424679,0.894360,0.716078,0.918126,0.924590,0.668307,0.886933,0.550678,0.883818,0.927256,0.885258,0.738776
Y16,0.179176,0.090486,NaN,0.595856,0.043280,0.076725,0.065868,0.093101,0.204948,0.075485,0.109470,0.052192,0.084634,0.082508,0.126404,0.046008,0.410219,0.072190,0.049554,0.054667,0.084373,0.249944,0.044407,0.068330,0.062763,0.049950,0.068444,0.110275,0.145294,0.063841,0.044256,0.036046,0.081228,0.060967,0.069433,0.051301,0.086310,0.066260,0.051455,0.264313,0.331485,0.060918,0.262872,0.076097,0.082512,0.073306,0.061388,0.273054,0.060978,0.047509,0.054323,0.061369,0.067799,0.170539,0.099599,0.279555,0.130761,0.045221,0.065361,0.105654,0.404787,0.073142,0.112716,0.052860
W16,0.335018,0.128592,0.328124,NaN,0.050041,0.063869,0.046293,0.058377,0.338637,0.071242,0.049386,0.073047,0.056501,0.078504,0.102785,0.051340,0.464864,0.041666,0.080625,0.052089,0.084680,0.168029,0.032600,0.106275,0.065496,0.059483,0.085912,0.158352,0.224518,0.046732,0.083933,0.037781,0.060326,0.059988,0.105142,0.061328,0.081670,0.065819,0.073693,0.421402,0.356418,0.072665,0.349062,0.056537,0.071239,0.057413,0.057038,0.422335,0.045876,0.044675,0.065898,0.096278,0.099120,0.138584,0.079787,0.200782,0.212515,0.051079,0.077153,0.061218,0.339169,0.061514,0.125009,0.055119
W04,0.849992,0.413901,0.944698,0.940539,NaN,0.804638,0.243786,0.496646,0.868259,0.589636,0.367826,0.748614,0.664762,0.625196,0.862989,0.245570,0.931439,0.409921,0.570094,0.403422,0.873699,0.877436,0.217001,0.597953,0.679849,0.458624,0.521171,0.740392,0.889514,0.685157,0.440955,0.528988,0.847090,0.795267,0.696764,0.354440,0.646363,0.681545,0.453841,0.890609,0.904607,0.593883,0.921405,0.736730,0.751192,0.627955,0.454033,0.910176,0.550072,0.532861,0.290509,0.369040,0.418512,0.937756,0.519803,0.921868,0.608392,0.624988,0.670154,0.660604,0.900149,0.851427,0.819019,0.828993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
W03,0.780371,0.389194,0.890562,0.944453,0.389597,0.563831,0.176939,0.567463,0.836870,0.399985,0.447483,0.810910,0.556216,0.694846,0.805801,0.131407,0.926998,0.242592,0.339952,0.484925,0.793720,0.790506,0.096336,0.405367,0.563077,0.381417,0.530826,0.720593,0.858295,0.547589,0.332267,0.543858,0.788740,0.719824,0.468229,0.477838,0.648739,0.572130,0.490507,0.896755,0.910793,0.585822,0.906962,0.616691,0.578651,0.555757,0.417935,0.896250,0.457748,0.506062,0.367603,0.415326,0.322913,0.904175,0.580120,0.894545,0.620202,0.415111,0.595268,NaN,0.850984,0.858708,0.855305,0.729458
X15,0.272956,0.101510,0.540001,0.639830,0.086931,0.128706,0.089005,0.119507,0.504115,0.135489,0.073517,0.186350,0.215190,0.223448,0.157788,0.044355,0.653221,0.068643,0.080932,0.099813,0.412377,0.284683,0.050626,0.090666,0.076874,0.045983,0.096886,0.283741,0.385499,0.117186,0.095437,0.062110,0.194085,0.104504,0.092306,0.074613,0.108003,0.101367,0.123171,0.554658,0.595636,0.177843,0.603193,0.181725,0.133931,0.124906,0.119077,0.527786,0.060389,0.084360,0.063781,0.057323,0.077350,0.394463,0.112201,0.524174,0.180315,0.107304,0.176022,0.147421,NaN,0.220605,0.342480,0.164765
X11,0.685447,0.133410,0.907740,0.916149,0.149884,0.349836,0.091992,0.205118,0.815563,0.299824,0.329436,0.493447,0.249896,0.311424,0.471995,0.090629,0.880801,0.178312,0.340013,0.220888,0.687150,0.608330,0.046280,0.280314,0.155957,0.207324,0.200752,0.549784,0.608082,0.343330,0.281993,0.198947,0.402111,0.507391,0.361578,0.155552,0.283928,0.379260,0.358958,0.803022,0.894649,0.526929,0.855455,0.390523,0.458648,0.319246,0.375782,0.858923,0.159585,0.227200,0.113861,0.319123,0.146677,0.771080,0.281556,0.703341,0.452368,0.378758,0.450705,0.184884,0.754865,NaN,0.469931,0.461503
Y13,0.471128,0.100979,0.880086,0.844361,0.165307,0.366116,0.058131,0.167326,0.676179,0.176895,0.106133,0.441824,0.280241,0.374251,0.364012,0.056189,0.827635,0.066596,0.288253,0.271551,0.622454,0.373122,0.041701,0.121813,0.140129,0.250599,0.132411,0.649015,0.568499,0.160879,0.153113,0.105345,0.387001,0.507742,0.169434,0.241309,0.147070,0.251887,0.264702,0.769732,0.822047,0.395778,0.880443,0.276609,0.362653,0.289593,0.119515,0.903722,0.086869,0.152187,0.076543,0.131002,0.102046,0.579540,0.315374,0.558016,0.512723,0.185294,0.325309,0.148982,0.701600,0.495724,NaN,0.289520
Y12,0.579549,0.292178,0.910689,0.931150,0.200274,0.597937,0.125443,0.410067,0.729523,0.293145,0.310313,0.470809,0.294411,0.350196,0.560018,0.044450,0.909881,0.190463,0.198025,0.193093,0.618368,0.568505,0.100503,0.308215,0.178019,0.212154,0.341902,0.462321,0.612857,0.389416,0.143060,0.076835,0.325967,0.555149,0.345412,0.196658,0.339951,0.433561,0.277511,0.764234,0.739938,0.453552,0.799767,0.385079,0.501736,0.255757,0.252960,0.861895,0.241036,0.342988,0.093686,0.215509,0.189322,0.714060,0.228025,0.702861,0.317242,0.264370,0.400301,0.228276,0.827383,0.521943,0.629880,NaN

In [5]:
df_matrix_opposite = 1 - df_matrix  # prob of team losing

df_matrix_opposite

,W13,W02,Y16,W16,W04,Z10,Y01,W09,Y15,W06,X05,Z12,Z08,Y09,Z11,W01,X16,Z01,X09,X08,Z13,X13,X01,X06,Y03,Z07,X03,W12,Y14,Y08,Y07,Z04,X12,Z05,Y05,Y02,Y06,W08,Z06,W14,Z15,Y10,Z16,Y11,Z09,W05,X04,W15,Z02,W07,X02,Y04,Z03,X14,X07,Z14,X10,W11,W10,W03,X15,X11,Y13,Y12
W13,NaN,0.781145,0.200498,0.317789,0.869239,0.654579,0.891315,0.799972,0.602886,0.859331,0.861368,0.818045,0.843361,0.847027,0.604234,0.933803,0.304477,0.877798,0.803900,0.909743,0.631878,0.507725,0.930201,0.791454,0.801955,0.884333,0.856911,0.409142,0.341232,0.838794,0.881561,0.902613,0.699652,0.723748,0.828049,0.854292,0.768194,0.806069,0.881918,0.437115,0.348282,0.752043,0.376931,0.860205,0.728509,0.731977,0.824566,0.401525,0.920866,0.863073,0.924147,0.847878,0.902507,0.538058,0.774375,0.352036,0.700412,0.844682,0.829567,0.810423,0.258548,0.721074,0.497916,0.668041
W02,0.226160,NaN,0.104292,0.134700,0.445059,0.208018,0.634613,0.336666,0.085705,0.419091,0.441395,0.118030,0.174261,0.134982,0.105667,0.780079,0.078122,0.746993,0.333705,0.340351,0.106390,0.102839,0.694257,0.407075,0.238951,0.359347,0.260273,0.092870,0.103384,0.393192,0.497436,0.404792,0.100909,0.163936,0.441905,0.364502,0.243426,0.217989,0.221312,0.065232,0.064593,0.198896,0.050312,0.187771,0.108337,0.220610,0.416163,0.050909,0.481720,0.420145,0.528652,0.502186,0.575321,0.105640,0.283922,0.081874,0.075410,0.331693,0.113067,0.449322,0.116182,0.072744,0.114742,0.261224
Y16,0.820824,0.909514,NaN,0.404144,0.956720,0.923275,0.934132,0.906899,0.795052,0.924515,0.890530,0.947808,0.915366,0.917492,0.873596,0.953992,0.589781,0.927810,0.950446,0.945333,0.915627,0.750056,0.955593,0.931670,0.937237,0.950050,0.931556,0.889725,0.854706,0.936159,0.955744,0.963954,0.918772,0.939033,0.930567,0.948699,0.913690,0.933740,0.948545,0.735687,0.668515,0.939082,0.737128,0.923903,0.917488,0.926694,0.938612,0.726946,0.939022,0.952491,0.945677,0.938631,0.932201,0.829461,0.900401,0.720445,0.869239,0.954779,0.934639,0.894346,0.595213,0.926858,0.887284,0.947140
W16,0.664982,0.871408,0.671876,NaN,0.949959,0.936131,0.953707,0.941623,0.661363,0.928758,0.950614,0.926953,0.943499,0.921496,0.897215,0.948660,0.535136,0.958334,0.919375,0.947911,0.915320,0.831971,0.967400,0.893725,0.934504,0.940517,0.914088,0.841648,0.775482,0.953268,0.916067,0.962219,0.939674,0.940012,0.894858,0.938672,0.918330,0.934181,0.926307,0.578598,0.643582,0.927335,0.650938,0.943463,0.928761,0.942587,0.942962,0.577665,0.954124,0.955325,0.934102,0.903722,0.900880,0.861416,0.920213,0.799218,0.787485,0.948921,0.922847,0.938782,0.660831,0.938486,0.874991,0.944881
W04,0.150008,0.586099,0.055302,0.059461,NaN,0.195362,0.756214,0.503354,0.131741,0.410364,0.632174,0.251386,0.335238,0.374804,0.137011,0.754430,0.068561,0.590079,0.429906,0.596578,0.126301,0.122564,0.782999,0.402047,0.320151,0.541376,0.478829,0.259608,0.110486,0.314843,0.559045,0.471012,0.152910,0.204733,0.303236,0.645560,0.353637,0.318455,0.546159,0.109391,0.095393,0.406117,0.078595,0.263270,0.248808,0.372045,0.545967,0.089824,0.449928,0.467139,0.709491,0.630960,0.581488,0.062244,0.480197,0.078132,0.391608,0.375012,0.329846,0.339396,0.099851,0.148573,0.180981,0.171007
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
W03,0.219629,0.610806,0.109438,0.055547,0.610403,0.436169,0.823061,0.432537,0.163130,0.600015,0.552517,0.189090,0.443784,0.305154,0.194199,0.868593,0.073002,0.757408,0.660048,0.515075,0.206280,0.209494,0.903664,0.594633,0.436923,0.618583,0.469174,0.279407,0.141705,0.452411,0.667733,0.456142,0.211260,0.280176,0.531771,0.522162,0.351261,0.427870,0.509493,0.103245,0.089207,0.414178,0.093038,0.383309,0.421349,0.444243,0.582065,0.103750,0.542252,0.493938,0.632397,0.584674,0.677087,0.095825,0.419880,0.105455,0.379798,0.584889,0.404732,NaN,0.149016,0.141292,0.144695,0.270542
X15,0.727044,0.898490,0.459999,0.360170,0.913069,0.871294,0.910995,0.880493,0.495885,0.864511,0.926483,0.813650,0.784810,0.776552,0.842212,0.955645,0.346779,0.931357,0.919068,0.900187,0.587623,0.715317,0.949374,0.909334,0.923126,0.954017,0.903114,0.716259,0.614501,0.882814,0.904563,0.937890,0.805915,0.895496,0.907694,0.925387,0.891997,0.898633,0.876829,0.445342,0.404364,0.822157,0.396807,0.818275,0.866069,0.875094,0.880923,0.472214,0.939611,0.915640,0.936219,0.942677,0.922650,0.605537,0.887799,0.475826,0.819685,0.892696,0.823978,0.852579,NaN,0.779395,0.657520,0.835235
X11,0.314553,0.866590,0.092260,0.083851,0.850116,0.650164,0.908008,0.794882,0.184437,0.700176,0.670564,0.506553,0.750104,0.688576,0.528005,0.909371,0.119199,0.821688,0.659987,0.779112,0.312850,0.391670,0.953720,0.719686,0.844043,0.792676,0.799248,0.450216,0.391918,0.656670,0.718007,0.801053,0.597889,0.492609,0.638422,0.844448,0.716072,0.620740,0.641042,0.196978,0.105351,0.473071,0.144545,0.609477,0.541352,0.680754,0.624218,0.141077,0.840415,0.772800,0.886139,0.680877,0.853323,0.228920,0.718444,0.296659,0.547632,0.621242,0.549295,0.815116,0.245135,NaN,0.530069,0.538497
Y13,0.528872,0.899021,0.119914,0.155639,0.834693,0.633884,0.941869,0.832674,0.323821,0.823105,0.893867,0.558176,0.719759,0.625749,0.635988,0.943811,0.172365,0.933404,0.711747,0.728449,0.377546,0.626878,0.958299,0.878187,0.859871,0.749401,0.867589,0.350985,0.431501,0.839121,0.846887,0.894655,0.612999,0.492258,0.830566,0.758691,0.852930,0.748113,0.735298,0.230268,0.177953,0.604222,0.119557,0.723391,0.637347,0.710407,0.880485,0.096278,0.913131,0.847813,0.923457,0.868998,0.897954,0.420460,0.684626,0.441984,0.487277,0.814706,0.674691,0.851018,0.298400,0.504276,NaN,0.710480
Y12,0.420451,0.707822,0.089311,0.068850,0.799726,0.402063,0.874557,0.589933,0.270477,0.706855,0.689687,0.529191,0.705589,0.649804,0.439982,0.955550,0.090119,0.809537,0.801975,0.806907,0.381632,0.431495,0.899497,0.691785,0.821981,0.787846,0.658098,0.537679,0.387143,0.610584,0.856940,0.923165,0.674033,0.444851,0.654588,0.803342,0.660049,0.566439,0.722489,0.235766,0.260062,0.546448,0.200233,0.614921,0.498264,0.744243,0.747040,0.138105,0.758964,0.657012,0.906314,0.784491,0.810678,0.285940,0.771975,0.297139,0.682758,0.735630,0.599699,0.771724,0.172617,0.478057,0.370120,NaN

In [6]:
import numpy as np

def simulate_tournament() -> dict:
    """
    Simulate the tournament in Kaggle submission format
    """
    # ROUND 1
    round_1 = {
        f'R1{region}{i}': np.random.choice(
            (f'{region}{i:02d}', f'{region}{17-i:02d}'), 
            p=(
                df_matrix.loc[f'{region}{i:02d}', f'{region}{17-i:02d}'], 
                df_matrix_opposite.loc[f'{region}{i:02d}', f'{region}{17-i:02d}']
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 8, 5, 4, 6, 3, 7, 2)
    }

    # ROUND 2
    round_2 = {
        f'R2{region}{i}': np.random.choice(
            (round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']), 
            p=(
                df_matrix.loc[round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']], 
                df_matrix_opposite.loc[round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 4, 3, 2)
    }

    # ROUND 3
    round_3 = {
        f'R3{region}{i}': np.random.choice(
            (round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']), 
            p=(
                df_matrix.loc[round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']], 
                df_matrix_opposite.loc[round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 2)
    }

    # ROUND 4
    round_4 = {
        f'R4{region}{i}': np.random.choice(
            (round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']), 
            p=(
                df_matrix.loc[round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']], 
                df_matrix_opposite.loc[round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, )
    }

    # ROUND 5
    round_5 = {
        'R5WX': np.random.choice(
            (round_4['R4W1'], round_4['R4X1']),
            p=(
                df_matrix.loc[round_4['R4W1'], round_4['R4X1']],
                df_matrix_opposite.loc[round_4['R4W1'], round_4['R4X1']],
            )
        ),
        'R5YZ': np.random.choice(
            (round_4['R4Y1'], round_4['R4Z1']),
            p=(
                df_matrix.loc[round_4['R4Y1'], round_4['R4Z1']],
                df_matrix_opposite.loc[round_4['R4Y1'], round_4['R4Z1']],
            )
        ),
    }

    # ROUND 6
    round_6 = {
        'R6CH': np.random.choice(
            (round_5['R5WX'], round_5['R5YZ']),
            p=(
                df_matrix.loc[round_5['R5WX'], round_5['R5YZ']],
                df_matrix_opposite.loc[round_5['R5WX'], round_5['R5YZ']],
            )
        ),
    }

    return round_1 | round_2 | round_3 | round_4 | round_5 | round_6  # merge the dictionaries (python >= 3.9)

simulate_tournament()

{'R1W1': 'W01',
 'R1W8': 'W09',
 'R1W5': 'W05',
 'R1W4': 'W04',
 'R1W6': 'W11',
 'R1W3': 'W03',
 'R1W7': 'W07',
 'R1W2': 'W02',
 'R1X1': 'X01',
 'R1X8': 'X09',
 'R1X5': 'X05',
 'R1X4': 'X04',
 'R1X6': 'X06',
 'R1X3': 'X03',
 'R1X7': 'X07',
 'R1X2': 'X02',
 'R1Y1': 'Y01',
 'R1Y8': 'Y09',
 'R1Y5': 'Y05',
 'R1Y4': 'Y04',
 'R1Y6': 'Y06',
 'R1Y3': 'Y03',
 'R1Y7': 'Y07',
 'R1Y2': 'Y02',
 'R1Z1': 'Z01',
 'R1Z8': 'Z08',
 'R1Z5': 'Z12',
 'R1Z4': 'Z04',
 'R1Z6': 'Z11',
 'R1Z3': 'Z03',
 'R1Z7': 'Z07',
 'R1Z2': 'Z02',
 'R2W1': 'W09',
 'R2W4': 'W04',
 'R2W3': 'W11',
 'R2W2': 'W02',
 'R2X1': 'X09',
 'R2X4': 'X05',
 'R2X3': 'X06',
 'R2X2': 'X02',
 'R2Y1': 'Y01',
 'R2Y4': 'Y04',
 'R2Y3': 'Y03',
 'R2Y2': 'Y07',
 'R2Z1': 'Z01',
 'R2Z4': 'Z04',
 'R2Z3': 'Z03',
 'R2Z2': 'Z07',
 'R3W1': 'W04',
 'R3W2': 'W11',
 'R3X1': 'X05',
 'R3X2': 'X02',
 'R3Y1': 'Y04',
 'R3Y2': 'Y03',
 'R3Z1': 'Z01',
 'R3Z2': 'Z03',
 'R4W1': 'W04',
 'R4X1': 'X02',
 'R4Y1': 'Y04',
 'R4Z1': 'Z01',
 'R5WX': 'W04',
 'R5YZ': 'Z01',
 'R6CH': 'Z01'}

In [7]:
from tqdm.autonotebook import trange

np.random.seed(22)

results = tuple(
    simulate_tournament()
    for _ in trange(30_000)  # set back to 30_000
)

len(results)

C:\Users\mhugh\AppData\Local\Temp\ipykernel_6660\1353165705.py:1: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import trange

  0%|          | 0/30000 [00:00<?, ?it/s]

30000

In [8]:
np.random.seed(23)

my_candidates = tuple(
    simulate_tournament()
    for _ in trange(20_000)  # set back to 20_000
)

len(my_candidates)

  0%|          | 0/20000 [00:00<?, ?it/s]

20000

In [9]:
def bracket_to_team_placements(bracket: dict) -> dict:
    """
    Convert bracket to dict of how many games each team won
    """
    round_1 = {
        bracket[f'R1{region}{i}']: 1
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 8, 5, 4, 6, 3, 7, 2)
    }

    round_2 = {
        bracket[f'R2{region}{i}']: 2
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 4, 3, 2)
    }

    round_3 = {
        bracket[f'R3{region}{i}']: 3
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 2)
    }

    round_4 = {
        bracket[f'R4{region}{i}']: 4
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, )
    }

    round_5 = {
        bracket['R5WX']: 5,
        bracket['R5YZ']: 5,
    }

    round_6 = {
        bracket['R6CH']: 6,
    }

    return round_1 | round_2 | round_3 | round_4 | round_5 | round_6  # merge the dictionaries (python >= 3.9)

bracket_to_team_placements(results[0])

{'W01': 4,
 'W09': 1,
 'W05': 1,
 'W13': 2,
 'W06': 2,
 'W03': 1,
 'W07': 3,
 'W02': 1,
 'X01': 6,
 'X09': 1,
 'X05': 1,
 'X04': 2,
 'X11': 1,
 'X03': 3,
 'X07': 1,
 'X02': 2,
 'Y01': 5,
 'Y09': 1,
 'Y05': 1,
 'Y04': 2,
 'Y11': 1,
 'Y03': 3,
 'Y07': 1,
 'Y02': 2,
 'Z01': 2,
 'Z08': 1,
 'Z12': 3,
 'Z04': 1,
 'Z11': 2,
 'Z14': 1,
 'Z10': 1,
 'Z02': 4}

In [10]:
from tqdm.autonotebook import tqdm

team_placements = tuple(bracket_to_team_placements(result) for result in tqdm(results))

len(team_placements)

  0%|          | 0/30000 [00:00<?, ?it/s]

30000

In [11]:
team_all_placements = {
    team: np.array([team_placements_bracket.get(team, 0) for team_placements_bracket in team_placements])
    for team in ((f'{region}{i:02d}') for region in ('W', 'X', 'Y', 'Z') for i in range(1, 17))
}

team_all_placements

{'W01': array([4, 6, 6, ..., 1, 6, 2]),
 'W02': array([1, 3, 2, ..., 2, 3, 4]),
 'W03': array([1, 1, 3, ..., 1, 2, 2]),
 'W04': array([0, 1, 1, ..., 3, 2, 3]),
 'W05': array([1, 0, 2, ..., 1, 1, 0]),
 'W06': array([2, 2, 1, ..., 4, 0, 0]),
 'W07': array([3, 1, 0, ..., 0, 1, 0]),
 'W08': array([0, 0, 0, ..., 0, 1, 0]),
 'W09': array([1, 1, 1, ..., 2, 0, 1]),
 'W10': array([0, 0, 1, ..., 1, 0, 1]),
 'W11': array([0, 0, 0, ..., 0, 1, 1]),
 'W12': array([0, 2, 0, ..., 0, 0, 1]),
 'W13': array([2, 0, 0, ..., 0, 0, 0]),
 'W14': array([0, 0, 0, ..., 0, 0, 0]),
 'W15': array([0, 0, 0, ..., 0, 0, 0]),
 'W16': array([0, 0, 0, ..., 0, 0, 0]),
 'X01': array([6, 2, 2, ..., 3, 2, 1]),
 'X02': array([2, 2, 1, ..., 1, 1, 1]),
 'X03': array([3, 1, 2, ..., 6, 1, 2]),
 'X04': array([2, 3, 3, ..., 0, 4, 1]),
 'X05': array([1, 1, 1, ..., 2, 0, 2]),
 'X06': array([0, 4, 1, ..., 1, 3, 1]),
 'X07': array([1, 1, 0, ..., 2, 2, 0]),
 'X08': array([0, 0, 1, ..., 0, 0, 3]),
 'X09': array([1, 1, 0, ..., 1, 1, 0]),
 'X10': array([0, 0, 4, ..., 0, 0, 5]),
 'X11': array([1, 0, 0, ..., 0, 0, 0]),
 'X12': array([0, 0, 0, ..., 0, 1, 0]),
 'X13': array([0, 0, 0, ..., 1, 0, 0]),
 'X14': array([0, 0, 0, ..., 0, 0, 0]),
 'X15': array([0, 0, 0, ..., 0, 0, 0]),
 'X16': array([0, 0, 0, ..., 0, 0, 0]),
 'Y01': array([5, 2, 3, ..., 4, 5, 2]),
 'Y02': array([2, 1, 4, ..., 2, 1, 0]),
 'Y03': array([3, 2, 2, ..., 1, 3, 1]),
 'Y04': array([2, 1, 2, ..., 1, 1, 4]),
 'Y05': array([1, 4, 1, ..., 2, 0, 1]),
 'Y06': array([0, 1, 0, ..., 0, 0, 3]),
 'Y07': array([1, 3, 1, ..., 1, 0, 2]),
 'Y08': array([0, 0, 0, ..., 0, 0, 0]),
 'Y09': array([1, 1, 1, ..., 1, 1, 1]),
 'Y10': array([0, 0, 0, ..., 0, 2, 0]),
 'Y11': array([1, 0, 1, ..., 3, 1, 0]),
 'Y12': array([0, 0, 0, ..., 0, 2, 0]),
 'Y13': array([0, 0, 0, ..., 0, 0, 0]),
 'Y14': array([0, 0, 0, ..., 0, 0, 0]),
 'Y15': array([0, 0, 0, ..., 0, 0, 1]),
 'Y16': array([0, 0, 0, ..., 0, 0, 0]),
 'Z01': array([2, 2, 2, ..., 5, 0, 1]),
 'Z02': array([4, 2, 5, ..., 3, 1, 1]),
 'Z03': array([0, 5, 1, ..., 2, 2, 3]),
 'Z04': array([1, 3, 3, ..., 2, 2, 6]),
 'Z05': array([0, 1, 1, ..., 1, 0, 0]),
 'Z06': array([0, 0, 2, ..., 0, 0, 0]),
 'Z07': array([0, 0, 1, ..., 1, 4, 2]),
 'Z08': array([1, 1, 1, ..., 1, 3, 2]),
 'Z09': array([0, 0, 0, ..., 0, 0, 0]),
 'Z10': array([1, 1, 0, ..., 0, 0, 0]),
 'Z11': array([2, 1, 0, ..., 1, 1, 1]),
 'Z12': array([3, 0, 0, ..., 0, 1, 1]),
 'Z13': array([0, 0, 0, ..., 0, 0, 0]),
 'Z14': array([1, 0, 0, ..., 0, 0, 0]),
 'Z15': array([0, 0, 0, ..., 0, 0, 0]),
 'Z16': array([0, 0, 0, ..., 0, 1, 0])}

Get probabilities of surviving

In [12]:
team_model_probs = dict(
    (
        t, 
        np.array(tuple(
            (v >= round).mean()
            for round in range(1, 7)
        ))
    )
    for t, v in team_all_placements.items()
)

team_model_probs

{'W01': array([0.9468    , 0.8511    , 0.72116667, 0.6099    , 0.3657    ,
        0.25313333]),
 'W02': array([0.95      , 0.69856667, 0.42743333, 0.1397    , 0.0609    ,
        0.02646667]),
 'W03': array([0.89386667, 0.3627    , 0.17073333, 0.04306667, 0.0122    ,
        0.0039    ]),
 'W04': array([0.85106667, 0.5567    , 0.15293333, 0.08156667, 0.0254    ,
        0.01013333]),
 'W05': array([0.7654    , 0.3218    , 0.04143333, 0.01606667, 0.003     ,
        0.0008    ]),
 'W06': array([0.41546667, 0.2629    , 0.1177    , 0.02396667, 0.00693333,
        0.0017    ]),
 'W07': array([0.4968    , 0.22266667, 0.1105    , 0.02373333, 0.00606667,
        0.00196667]),
 'W08': array([0.31496667, 0.05263333, 0.0264    , 0.0091    , 0.00246667,
        0.00106667]),
 'W09': array([0.68503333, 0.09316667, 0.04933333, 0.01936667, 0.00483333,
        0.00173333]),
 'W10': array([5.03200000e-01, 7.21666667e-02, 3.36333333e-02, 7.40000000e-03,
        9.33333333e-04, 2.33333333e-04]),
 'W11': array([0.58453333, 0.35746667, 0.13763333, 0.02443333, 0.00506667,
        0.00166667]),
 'W12': array([2.34600000e-01, 6.90333333e-02, 4.30000000e-03, 7.00000000e-04,
        1.33333333e-04, 3.33333333e-05]),
 'W13': array([1.48933333e-01, 5.24666667e-02, 4.20000000e-03, 9.00000000e-04,
        6.66666667e-05, 0.00000000e+00]),
 'W14': array([1.06133333e-01, 1.69333333e-02, 1.93333333e-03, 1.00000000e-04,
        3.33333333e-05, 0.00000000e+00]),
 'W15': array([0.05      , 0.0066    , 0.00043333, 0.        , 0.        ,
        0.        ]),
 'W16': array([0.0532    , 0.0031    , 0.00023333, 0.        , 0.        ,
        0.        ]),
 'X01': array([0.96943333, 0.7638    , 0.6348    , 0.4792    , 0.30016667,
        0.21326667]),
 'X02': array([0.94886667, 0.78913333, 0.54953333, 0.2327    , 0.12666667,
        0.06846667]),
 'X03': array([0.81433333, 0.52043333, 0.16206667, 0.0534    , 0.01246667,
        0.0044    ]),
 'X04': array([0.9064    , 0.45803333, 0.15003333, 0.06793333, 0.0195    ,
        0.00743333]),
 'X05': array([0.76166667, 0.428     , 0.0969    , 0.04783333, 0.0137    ,
        0.0049    ]),
 'X06': array([0.73196667, 0.35916667, 0.18746667, 0.04866667, 0.01236667,
        0.00546667]),
 'X07': array([0.66946667, 0.13206667, 0.0648    , 0.01353333, 0.00286667,
        0.0007    ]),
 'X08': array([0.58763333, 0.1921    , 0.08896667, 0.04306667, 0.01586667,
        0.00563333]),
 'X09': array([0.41236667, 0.041     , 0.01813333, 0.0058    , 0.0017    ,
        0.0005    ]),
 'X10': array([3.30533333e-01, 7.21000000e-02, 2.08666667e-02, 3.96666667e-03,
        6.33333333e-04, 6.66666667e-05]),
 'X11': array([2.68033333e-01, 8.05000000e-02, 1.21333333e-02, 1.56666667e-03,
        1.33333333e-04, 3.33333333e-05]),
 'X12': array([2.38333333e-01, 9.26666667e-02, 8.76666667e-03, 1.56666667e-03,
        1.33333333e-04, 0.00000000e+00]),
 'X13': array([0.0936, 0.0213, 0.0022, 0.0003, 0.    , 0.    ]),
 'X14': array([1.85666667e-01, 3.99000000e-02, 2.33333333e-03, 4.00000000e-04,
        3.33333333e-05, 0.00000000e+00]),
 'X15': array([5.11333333e-02, 6.70000000e-03, 8.00000000e-04, 6.66666667e-05,
        3.33333333e-05, 0.00000000e+00]),
 'X16': array([0.03056667, 0.0031    , 0.0002    , 0.        , 0.        ,
        0.        ]),
 'Y01': array([0.93346667, 0.82343333, 0.62133333, 0.4954    , 0.3594    ,
        0.1781    ]),
 'Y02': array([0.92533333, 0.58823333, 0.2981    , 0.10093333, 0.03973333,
        0.01166667]),
 'Y03': array([0.89146667, 0.56213333, 0.33473333, 0.12316667, 0.04576667,
        0.0102    ]),
 'Y04': array([0.86763333, 0.62856667, 0.2238    , 0.11236667, 0.04296667,
        0.01276667]),
 'Y05': array([0.7356    , 0.27383333, 0.05716667, 0.02286667, 0.0071    ,
        0.00143333]),
 'Y06': array([0.47743333, 0.1864    , 0.0797    , 0.0251    , 0.00766667,
        0.00113333]),
 'Y07': array([0.65896667, 0.2282    , 0.10733333, 0.0378    , 0.0141    ,
        0.0038    ]),
 'Y08': array([0.4067    , 0.08036667, 0.04106667, 0.0191    , 0.00693333,
        0.00153333]),
 'Y09': array([0.5933    , 0.09113333, 0.0407    , 0.01476667, 0.00526667,
        0.00096667]),
 'Y10': array([3.41033333e-01, 1.76733333e-01, 6.04666667e-02, 1.28333333e-02,
        2.46666667e-03, 3.33333333e-04]),
 'Y11': array([0.52256667, 0.23486667, 0.11633333, 0.0315    , 0.0087    ,
        0.00176667]),
 'Y12': array([2.64400000e-01, 7.19333333e-02, 1.27000000e-02, 3.63333333e-03,
        8.66666667e-04, 3.33333333e-05]),
 'Y13': array([1.32366667e-01, 2.56666667e-02, 2.73333333e-03, 4.33333333e-04,
        6.66666667e-05, 0.00000000e+00]),
 'Y14': array([1.08533333e-01, 1.66000000e-02, 2.56666667e-03, 6.66666667e-05,
        0.00000000e+00, 0.00000000e+00]),
 'Y15': array([7.46666667e-02, 6.83333333e-03, 7.66666667e-04, 3.33333333e-05,
        0.00000000e+00, 0.00000000e+00]),
 'Y16': array([0.06653333, 0.00506667, 0.0005    , 0.        , 0.        ,
        0.        ]),
 'Z01': array([0.9378    , 0.69386667, 0.5013    , 0.3508    , 0.21226667,
        0.09656667]),
 'Z02': array([0.9544    , 0.7038    , 0.36076667, 0.17683333, 0.07283333,
        0.01636667]),
 'Z03': array([0.94306667, 0.60423333, 0.35733333, 0.14456667, 0.06476667,
        0.023     ]),
 'Z04': array([0.91676667, 0.6773    , 0.26863333, 0.1354    , 0.05206667,
        0.01356667]),
 'Z05': array([5.48266667e-01, 1.29733333e-01, 1.99666667e-02, 4.96666667e-03,
        9.33333333e-04, 1.00000000e-04]),
 'Z06': array([0.60416667, 0.3165    , 0.12723333, 0.0466    , 0.0128    ,
        0.0034    ]),
 'Z07': array([0.64423333, 0.21093333, 0.1067    , 0.03776667, 0.0125    ,
        0.00293333]),
 'Z08': array([0.74386667, 0.25496667, 0.15943333, 0.07916667, 0.02613333,
        0.0063    ]),
 'Z09': array([2.56133333e-01, 4.35666667e-02, 1.72666667e-02, 5.30000000e-03,
        1.30000000e-03, 1.33333333e-04]),
 'Z10': array([3.55766667e-01, 8.28333333e-02, 2.89000000e-02, 6.66666667e-03,
        1.53333333e-03, 1.33333333e-04]),
 'Z11': array([0.39583333, 0.06593333, 0.01756667, 0.00343333, 0.0006    ,
        0.        ]),
 'Z12': array([4.51733333e-01, 1.68766667e-01, 3.06000000e-02, 7.93333333e-03,
        1.13333333e-03, 6.66666667e-05]),
 'Z13': array([8.32333333e-02, 2.42000000e-02, 2.23333333e-03, 2.33333333e-04,
        6.66666667e-05, 0.00000000e+00]),
 'Z14': array([0.05693333, 0.01333333, 0.0011    , 0.0002    , 0.        ,
        0.        ]),
 'Z15': array([4.56000000e-02, 2.43333333e-03, 4.00000000e-04, 6.66666667e-05,
        0.00000000e+00, 0.00000000e+00]),
 'Z16': array([6.22000000e-02, 7.60000000e-03, 5.66666667e-04, 6.66666667e-05,
        3.33333333e-05, 0.00000000e+00])}

In [13]:
region_seed_to_id = dict(zip(df_seeds['Region Seed'], df_seeds['TeamID']))

df_model = pd.DataFrame({
    'Team': team_model_probs.keys()
})

df_model[[f'Round {i}' for i in range(1, 7)]] = np.array(tuple(df_model['Team'].map(team_model_probs)))

df_model.insert(1, 'TeamID', df_model['Team'].map(region_seed_to_id))

df_model.sort_values(by=['Round 6'], ascending=False, inplace=True, ignore_index=True)

df_model.head(10)

  Team  TeamID   Round 1   Round 2   Round 3   Round 4   Round 5   Round 6
0  W01    1181  0.946800  0.851100  0.721167  0.609900  0.365700  0.253133
1  X01    1222  0.969433  0.763800  0.634800  0.479200  0.300167  0.213267
2  Y01    1120  0.933467  0.823433  0.621333  0.495400  0.359400  0.178100
3  Z01    1196  0.937800  0.693867  0.501300  0.350800  0.212267  0.096567
4  X02    1397  0.948867  0.789133  0.549533  0.232700  0.126667  0.068467
5  W02    1104  0.950000  0.698567  0.427433  0.139700  0.060900  0.026467
6  Z03    1403  0.943067  0.604233  0.357333  0.144567  0.064767  0.023000
7  Z02    1385  0.954400  0.703800  0.360767  0.176833  0.072833  0.016367
8  Z04    1268  0.916767  0.677300  0.268633  0.135400  0.052067  0.013567
9  Y04    1401  0.867633  0.628567  0.223800  0.112367  0.042967  0.012767

In [14]:
df_teams = pd.read_csv(r'..\data\unprocessed\kaggle\MTeams.csv')

df_teams

     TeamID        TeamName  FirstD1Season  LastD1Season
0      1101     Abilene Chr           2014          2025
1      1102       Air Force           1985          2025
2      1103           Akron           1985          2025
3      1104         Alabama           1985          2025
4      1105     Alabama A&M           2000          2025
..      ...             ...            ...           ...
375    1476       Stonehill           2023          2025
376    1477  East Texas A&M           2023          2025
377    1478        Le Moyne           2024          2025
378    1479      Mercyhurst           2025          2025
379    1480    West Georgia           2025          2025

[380 rows x 4 columns]

In [15]:
id_to_team = dict(zip(df_teams['TeamID'], df_teams['TeamName']))

df_model.insert(df_model.columns.get_loc('TeamID') + 1, 'Name', df_model['TeamID'].map(id_to_team))

df_model.head(25)

,Team,TeamID,Name,Round 1,Round 2,Round 3,Round 4,Round 5,Round 6
0,W01,1181,Duke,0.946800,0.851100,0.721167,0.609900,0.365700,0.253133
1,X01,1222,Houston,0.969433,0.763800,0.634800,0.479200,0.300167,0.213267
2,Y01,1120,Auburn,0.933467,0.823433,0.621333,0.495400,0.359400,0.178100
3,Z01,1196,Florida,0.937800,0.693867,0.501300,0.350800,0.212267,0.096567
4,X02,1397,Tennessee,0.948867,0.789133,0.549533,0.232700,0.126667,0.068467
5,W02,1104,Alabama,0.950000,0.698567,0.427433,0.139700,0.060900,0.026467
6,Z03,1403,Texas Tech,0.943067,0.604233,0.357333,0.144567,0.064767,0.023000
7,Z02,1385,St John's,0.954400,0.703800,0.360767,0.176833,0.072833,0.016367
8,Z04,1268,Maryland,0.916767,0.677300,0.268633,0.135400,0.052067,0.013567
9,Y04,1401,Texas A&M,0.867633,0.628567,0.223800,0.112367,0.042967,0.012767
10,Y02,1277,Michigan St,0.925333,0.588233,0.298100,0.100933,0.039733,0.011667
11,Y03,1235,Iowa St,0.891467,0.562133,0.334733,0.123167,0.045767,0.010200
12,W04,1112,Arizona,0.851067,0.556700,0.152933,0.081567,0.025400,0.010133
13,X04,1345,Purdue,0.906400,0.458033,0.150033,0.067933,0.019500,0.007433
14,Z08,1163,Connecticut,0.743867,0.254967,0.159433,0.079167,0.026133,0.006300
15,X08,1211,Gonzaga,0.587633,0.192100,0.088967,0.043067,0.015867,0.005633
16,X06,1228,Illinois,0.731967,0.359167,0.187467,0.048667,0.012367,0.005467
17,X05,1155,Clemson,0.761667,0.428000,0.096900,0.047833,0.013700,0.004900
18,X03,1246,Kentucky,0.814333,0.520433,0.162067,0.053400,0.012467,0.004400
19,W03,1458,Wisconsin,0.893867,0.362700,0.170733,0.043067,0.012200,0.003900
20,Y07,1266,Marquette,0.658967,0.228200,0.107333,0.037800,0.014100,0.003800
21,Z06,1281,Missouri,0.604167,0.316500,0.127233,0.046600,0.012800,0.003400
22,Z07,1242,Kansas,0.644233,0.210933,0.106700,0.037767,0.012500,0.002933
23,W07,1388,St Mary's CA,0.496800,0.222667,0.110500,0.023733,0.006067,0.001967
24,Y11,1314,North Carolina,0.522567,0.234867,0.116333,0.031500,0.008700,0.001767

Get public brackets

In [16]:
df_public = pd.read_parquet(f'..\data\preprocessed\mens_yahoo\yahoo_picks_{season}.parquet')

df_public.sort_values(by=['Round 6'], ascending=False, ignore_index=True).head(10)

,Team,TeamID,Region Seed,Seed,Region,Play In,Round 1,Round 2,Round 3,Round 4,Round 5,Round 6
0,Duke,1181,W01,1,W,False,0.9662,0.9153,0.8027,0.6410,0.4936,0.2817
1,Florida,1196,Z01,1,Z,False,0.9638,0.8425,0.7401,0.5465,0.3169,0.1741
2,Auburn,1120,Y01,1,Y,False,0.9810,0.8730,0.7248,0.5181,0.2779,0.1412
3,Houston,1222,X01,1,X,False,0.9567,0.7871,0.6655,0.4420,0.1647,0.0846
4,St. John's,1385,Z02,2,Z,False,0.9390,0.6753,0.4925,0.2019,0.1133,0.0507
5,Michigan St.,1277,Y02,2,Y,False,0.9587,0.7921,0.5870,0.2518,0.1037,0.0436
6,Tennessee,1397,X02,2,X,False,0.9417,0.7791,0.5511,0.2512,0.0826,0.0336
7,Alabama,1104,W02,2,W,False,0.9460,0.7902,0.5595,0.1790,0.0848,0.0332
8,Kentucky,1246,X03,3,X,False,0.9209,0.6374,0.2520,0.1205,0.0446,0.0191
9,Michigan,1276,Y05,5,Y,False,0.7932,0.5036,0.1210,0.0532,0.0239,0.0116

R1X1: (1, 16)
R2X1: (1, 8, 9, 16)
R3X1: (1, 4, 5, 8, 9, 12, 13, 16)
R4X1: (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)

R1X2: (2, 15)
R2X2: (2, 7, 10, 15)
R3X2: (2, 3, 6, 7, 10, 11, 14, 15)

R1X3: (3, 14)
R2X3: (3, 6, 11, 14)

R1X4: (4, 13)
R2X4: (4, 5, 12, 13)

R1X5: (5, 12)

R1X6: (6, 11)

R1X7: (7, 10)

R1X8: (8, 9)

Partition data into possible areas in advance

In [17]:
public_dict = {
    # ROUND 6
    'R6CH': df_public.loc[:, ['Region Seed', 'Region', 'Seed', 'Round 6']].rename(columns={'Round 6': 'P'}).reset_index(drop=True),

    # ROUND 5
    'R5WX': df_public.loc[df_public['Region'].isin(('W', 'X')), ['Region Seed', 'Region', 'Seed', 'Round 5']].rename(columns={'Round 5': 'P'}).reset_index(drop=True),
    'R5YZ': df_public.loc[df_public['Region'].isin(('Y', 'Z')), ['Region Seed', 'Region', 'Seed', 'Round 5']].rename(columns={'Round 5': 'P'}).reset_index(drop=True),
}

# ROUND 4
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R4{region}1'] = df_public.loc[df_public['Region'] == region, ['Region Seed', 'Region', 'Seed', 'Round 4']].rename(columns={'Round 4': 'P'}).reset_index(drop=True)

# ROUND 3
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R3{region}1'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((1, 4, 5, 8, 9, 12, 13, 16))), ['Region Seed', 'Region', 'Seed', 'Round 3']].rename(columns={'Round 3': 'P'}).reset_index(drop=True)
    public_dict[f'R3{region}2'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((2, 3, 6, 7, 10, 11, 14, 15))), ['Region Seed', 'Region', 'Seed', 'Round 3']].rename(columns={'Round 3': 'P'}).reset_index(drop=True)

# ROUND 2
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R2{region}1'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((1, 8, 9, 16))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}2'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((2, 7, 10, 15))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}3'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((3, 6, 11, 14))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}4'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((4, 5, 12, 13))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)

# ROUND 1
for region in ('W', 'X', 'Y', 'Z'):
    for i in range(1, 9):
        public_dict[f'R1{region}{i}'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((i, 17-i))), ['Region Seed', 'Region', 'Seed', 'Round 1']].rename(columns={'Round 1': 'P'}).reset_index(drop=True)

for key, value in public_dict.items():  # make sure probabilities add to 1
    # print(value['P'].sum())

    value['P'] = value['P']/value['P'].sum()
    public_dict[key] = value

    # print(value['P'].sum())
    # print()

public_dict

{'R6CH':    Region Seed Region  Seed         P
 0          Y16      Y    16  0.000500
 1          W16      W    16  0.000400
 2          W13      W    13  0.000600
 3          W02      W     2  0.033207
 4          W04      W     4  0.007502
 ..         ...    ...   ...       ...
 59         W11      W    11  0.000600
 60         W10      W    10  0.000700
 61         W03      W     3  0.010502
 62         X15      X    15  0.000500
 63         Y13      Y    13  0.002100

 [64 rows x 4 columns],
 'R5WX':    Region Seed Region  Seed         P
 0          W16      W    16  0.001001
 1          W13      W    13  0.001101
 2          W02      W     2  0.084885
 3          W04      W     4  0.016216
 4          W06      W     6  0.004304
 5          W09      W     9  0.002703
 6          X05      X     5  0.011111
 7          W01      W     1  0.494094
 8          X09      X     9  0.006406
 9          X08      X     8  0.011211
 10         X13      X    13  0.001001
 11         X01      X     1  0.164865
 12         X06      X     6  0.005506
 13         X03      X     3  0.044645
 14         W12      W    12  0.001101
 15         X12      X    12  0.001001
 16         W08      W     8  0.001301
 17         W14      W    14  0.001001
 18         W05      W     5  0.008909
 19         X04      X     4  0.011712
 20         W15      W    15  0.000901
 21         X16      X    16  0.001101
 22         W07      W     7  0.002503
 23         X11      X    11  0.001301
 24         X02      X     2  0.082683
 25         X14      X    14  0.000901
 26         X07      X     7  0.006406
 27         X10      X    10  0.001101
 28         W11      W    11  0.001401
 29         W10      W    10  0.001602
 30         W03      W     3  0.024825
 31         X15      X    15  0.001201,
 'R5YZ':    Region Seed Region  Seed         P
 0          Y16      Y    16  0.001001
 1          Z10      Z    10  0.002503
 2          Y01      Y     1  0.278262
 3          Y15      Y    15  0.000901
 4          Z12      Z    12  0.001502
 5          Z08      Z     8  0.016021
 6          Y09      Y     9  0.002804
 7          Z11      Z    11  0.002503
 8          Z01      Z     1  0.317313
 9          Z13      Z    13  0.001202
 10         Y03      Y     3  0.022329
 11         Z07      Z     7  0.020126
 12         Y14      Y    14  0.000701
 13         Y08      Y     8  0.004306
 14         Y07      Y     7  0.003805
 15         Z04      Z     4  0.017022
 16         Z05      Z     5  0.006308
 17         Y05      Y     5  0.023931
 18         Y02      Y     2  0.103835
 19         Y06      Y     6  0.006609
 20         Z06      Z     6  0.004306
 21         Z14      Z    14  0.000901
 22         Z15      Z    15  0.001101
 23         Y10      Y    10  0.001302
 24         Z16      Z    16  0.001101
 25         Z09      Z     9  0.002103
 26         Y11      Y    11  0.003304
 27         Z02      Z     2  0.113447
 28         Y04      Y     4  0.009312
 29         Z03      Z     3  0.024732
 30         Y12      Y    12  0.002103
 31         Y13      Y    13  0.003304,
 'R4W1':    Region Seed Region  Seed         P
 0          W16      W    16  0.002227
 1          W13      W    13  0.002430
 2          W02      W     2  0.181229
 3          W04      W     4  0.039891
 4          W06      W     6  0.012352
 5          W09      W     9  0.006783
 6          W01      W     1  0.648982
 7          W12      W    12  0.002531
 8          W08      W     8  0.003240
 9          W14      W    14  0.002329
 10         W05      W     5  0.022173
 11         W15      W    15  0.002227
 12         W07      W     7  0.007188
 13         W11      W    11  0.003139
 14         W10      W    10  0.004252
 15         W03      W     3  0.059026,
 'R4X1':    Region Seed Region  Seed         P
 0          X05      X     5  0.039618
 1          X09      X     9  0.010565
 2          X08      X     8  0.032202
 3          X13      X    13  0.002743
 4          X01      X     1  0.449004
 5          X06      X     6  0.017879
 6          X03      X     3  0.122410
 7          X12      X    12  0.002540
 8          X04      X     4  0.035047
 9          X16      X    16  0.002438
 10         X11      X    11  0.003251
 11         X02      X     2  0.255181
 12         X14      X    14  0.002032
 13         X07      X     7  0.019707
 14         X10      X    10  0.002946
 15         X15      X    15  0.002438,
 'R4Y1':    Region Seed Region  Seed         P
 0          Y16      Y    16  0.002113
 1          Y01      Y     1  0.521280
 2          Y15      Y    15  0.002515
 3          Y09      Y     9  0.007948
 4          Y03      Y     3  0.064493
 5          Y14      Y    14  0.001710
 6          Y08      Y     8  0.020022
 7          Y07      Y     7  0.011671
 8          Y05      Y     5  0.053527
 9          Y02      Y     2  0.253345
 10         Y06      Y     6  0.013080
 11         Y10      Y    10  0.003521
 12         Y11      Y    11  0.006540
 13         Y04      Y     4  0.027568
 14         Y12      Y    12  0.005232
 15         Y13      Y    13  0.005433,
 'R4Z1':    Region Seed Region  Seed         P
 0          Z10      Z    10  0.005765
 1          Z12      Z    12  0.003439
 2          Z08      Z     8  0.030036
 3          Z11      Z    11  0.005967
 4          Z01      Z     1  0.552690
 5          Z13      Z    13  0.002832
 6          Z07      Z     7  0.038026
 7          Z04      Z     4  0.045409
 8          Z05      Z     5  0.017698
 9          Z06      Z     6  0.011529
 10         Z14      Z    14  0.002023
 11         Z15      Z    15  0.002427
 12         Z16      Z    16  0.002225
 13         Z09      Z     9  0.005057
 14         Z02      Z     2  0.204187
 15         Z03      Z     3  0.070692,
 'R3W1':   Region Seed Region  Seed         P
 0         W16      W    16  0.003856
 1         W13      W    13  0.006292
 2         W04      W     4  0.091131
 3         W09      W     9  0.015019
 4         W01      W     1  0.814593
 5         W12      W    12  0.005784
 6         W08      W     8  0.009235
 7         W05      W     5  0.054090,
 'R3W2':   Region Seed Region  Seed         P
 0         W02      W     2  0.569002
 1         W06      W     6  0.114004
 2         W14      W    14  0.005492
 3         W15      W    15  0.005492
 4         W07      W     7  0.037628
 5         W11      W    11  0.015560
 6         W10      W    10  0.020238
 7         W03      W     3  0.232584,
 'R3X1':   Region Seed Region  Seed         P
 0         X05      X     5  0.106350
 1         X09      X     9  0.024629
 2         X08      X     8  0.074496
 3         X13      X    13  0.006106
 4         X01      X     1  0.677285
 5         X12      X    12  0.006819
 6         X04      X     4  0.100041
 7         X16      X    16  0.004274,
 'R3X2':   Region Seed Region  Seed         P
 0         X06      X     6  0.100428
 1         X03      X     3  0.256933
 2         X11      X    11  0.010909
 3         X02      X     2  0.561888
 4         X14      X    14  0.004894
 5         X07      X     7  0.048532
 6         X10      X    10  0.009890
 7         X15      X    15  0.006525,
 'R3Y1':   Region Seed Region  Seed         P
 0         Y16      Y    16  0.003828
 1         Y01      Y     1  0.730056
 2         Y09      Y     9  0.020346
 3         Y08      Y     8  0.037268
 4         Y05      Y     5  0.121878
 5         Y04      Y     4  0.065371
 6         Y12      Y    12  0.011583
 7         Y13      Y    13  0.009670,
 'R3Y2':   Region Seed Region  Seed         P
 0         Y15      Y    15  0.006456
 1         Y03      Y     3  0.224027
 2         Y14      Y    14  0.004640
 3         Y07      Y     7  0.051342
 4         Y02      Y     2  0.592092
 5         Y06      Y     6  0.087250
 6         Y10      Y    10  0.013718
 7         Y11      Y    11  0.020476,
 'R3Z1':   Region Seed Region  Seed         P
 0         Z12      Z    12  0.008515
 1         Z08      Z     8  0.071059
 2         Z01      Z     1  0.750228
 3         Z13      Z    13  0.006994
 4         Z04      Z     4  0.097719
 5         Z05      Z     5  0.048555
 6         Z16      Z    16  0.004055
 7         Z09      Z     9  0.012874,
 'R3Z2':   Region Seed Region  Seed         P
 0         Z10      Z    10  0.023150
 1         Z11      Z    11  0.024876
 2         Z07      Z     7  0.109148
 3         Z06      Z     6  0.087522
 4         Z14      Z    14  0.004975
 5         Z15      Z    15  0.005990
 6         Z02      Z     2  0.500051
 7         Z03      Z     3  0.244289,
 'R2W1':   Region Seed Region  Seed         P
 0         W16      W    16  0.007637
 1         W09      W     9  0.038591
 2         W01      W     1  0.931982
 3         W08      W     8  0.021790,
 'R2W2':   Region Seed Region  Seed         P
 0         W02      W     2  0.806409
 1         W15      W    15  0.012552
 2         W07      W     7  0.124707
 3         W10      W    10  0.056332,
 'R2W3':   Region Seed Region  Seed         P
 0         W06      W     6  0.285174
 1         W14      W    14  0.018085
 2         W11      W    11  0.080924
 3         W03      W     3  0.615817,
 'R2W4':   Region Seed Region  Seed         P
 0         W13      W    13  0.043229
 1         W04      W     4  0.531528
 2         W12      W    12  0.045989
 3         W05      W     5  0.379254,
 'R2X1':   Region Seed Region  Seed         P
 0         X09      X     9  0.055442
 1         X08      X     8  0.132326
 2         X01      X     1  0.803655
 3         X16      X    16  0.008577,
 'R2X2':   Region Seed Region  Seed         P
 0         X02      X     2  0.796300
 1         X07      X     7  0.158115
 2         X10      X    10  0.032502
 3         X15      X    15  0.013083,
 'R2X3':   Region Seed Region  Seed         P
 0         X06      X     6  0.270741
 1         X03      X     3  0.653677
 2         X11      X    11  0.058558
 3         X14      X    14  0.017024,
 'R2X4':   Region Seed Region  Seed         P
 0         X05      X     5  0.497697
 1         X13      X    13  0.040229
 2         X12      X    12  0.052206
 3         X04      X     4  0.409868,
 'R2Y1':   Region Seed Region  Seed         P
 0         Y16      Y    16  0.007067
 1         Y01      Y     1  0.881373
 2         Y09      Y     9  0.046138
 3         Y08      Y     8  0.065422,
 'R2Y2':   Region Seed Region  Seed         P
 0         Y15      Y    15  0.013436
 1         Y07      Y     7  0.147288
 2         Y02      Y     2  0.800182
 3         Y10      Y    10  0.039095,
 'R2Y3':   Region Seed Region  Seed         P
 0         Y03      Y     3  0.645597
 1         Y14      Y    14  0.018364
 2         Y06      Y     6  0.232244
 3         Y11      Y    11  0.103795,
 'R2Y4':   Region Seed Region  Seed         P
 0         Y05      Y     5  0.509562
 1         Y04      Y     4  0.356572
 2         Y12      Y    12  0.083679
 3         Y13      Y    13  0.050187,
 'R2Z1':   Region Seed Region  Seed         P
 0         Z08      Z     8  0.107325
 1         Z01      Z     1  0.857070
 2         Z16      Z    16  0.008240
 3         Z09      Z     9  0.027365,
 'R2Z2':   Region Seed Region  Seed         P
 0         Z10      Z    10  0.063054
 1         Z07      Z     7  0.236121
 2         Z15      Z    15  0.012937
 3         Z02      Z     2  0.687888,
 'R2Z3':   Region Seed Region  Seed         P
 0         Z11      Z    11  0.124413
 1         Z06      Z     6  0.230047
 2         Z14      Z    14  0.018473
 3         Z03      Z     3  0.627067,
 'R2Z4':   Region Seed Region  Seed         P
 0         Z12      Z    12  0.069729
 1         Z13      Z    13  0.046554
 2         Z04      Z     4  0.537825
 3         Z05      Z     5  0.345891,
 'R1W1':   Region Seed Region  Seed        P
 0         W16      W    16  0.01659
 1         W01      W     1  0.98341,
 'R1W2':   Region Seed Region  Seed         P
 0         W02      W     2  0.966984
 1         W15      W    15  0.033016,
 'R1W3':   Region Seed Region  Seed         P
 0         W14      W    14  0.057181
 1         W03      W     3  0.942819,
 'R1W4':   Region Seed Region  Seed        P
 0         W13      W    13  0.12365
 1         W04      W     4  0.87635,
 'R1W5':   Region Seed Region  Seed         P
 0         W12      W    12  0.177361
 1         W05      W     5  0.822639,
 'R1W6':   Region Seed Region  Seed         P
 0         W06      W     6  0.675712
 1         W11      W    11  0.324288,
 'R1W7':   Region Seed Region  Seed         P
 0         W07      W     7  0.570396
 1         W10      W    10  0.429604,
 'R1W8':   Region Seed Region  Seed         P
 0         W09      W     9  0.565172
 1         W08      W     8  0.434828,
 'R1X1':   Region Seed Region  Seed         P
 0         X01      X     1  0.978121
 1         X16      X    16  0.021879,
 'R1X2':   Region Seed Region  Seed         P
 0         X02      X     2  0.965549
 1         X15      X    15  0.034451,
 'R1X3':   Region Seed Region  Seed         P
 0         X03      X     3  0.948795
 1         X14      X    14  0.051205,
 'R1X4':   Region Seed Region  Seed         P
 0         X13      X    13  0.149892
 1         X04      X     4  0.850108,
 'R1X5':   Region Seed Region  Seed         P
 0         X05      X     5  0.851095
 1         X12      X    12  0.148905,
 'R1X6':   Region Seed Region  Seed         P
 0         X06      X     6  0.766819
 1         X11      X    11  0.233181,
 'R1X7':   Region Seed Region  Seed         P
 0         X07      X     7  0.675849
 1         X10      X    10  0.324151,
 'R1X8':   Region Seed Region  Seed         P
 0         X09      X     9  0.285404
 1         X08      X     8  0.714596,
 'R1Y1':   Region Seed Region  Seed         P
 0         Y16      Y    16  0.016245
 1         Y01      Y     1  0.983755,
 'R1Y2':   Region Seed Region  Seed         P
 0         Y15      Y    15  0.032789
 1         Y02      Y     2  0.967211,
 'R1Y3':   Region Seed Region  Seed         P
 0         Y03      Y     3  0.941886
 1         Y14      Y    14  0.058114,
 'R1Y4':   Region Seed Region  Seed         P
 0         Y04      Y     4  0.787666
 1         Y13      Y    13  0.212334,
 'R1Y5':   Region Seed Region  Seed         P
 0         Y05      Y     5  0.804218
 1         Y12      Y    12  0.195782,
 'R1Y6':   Region Seed Region  Seed         P
 0         Y06      Y     6  0.672878
 1         Y11      Y    11  0.327122,
 'R1Y7':   Region Seed Region  Seed         P
 0         Y07      Y     7  0.656814
 1         Y10      Y    10  0.343186,
 'R1Y8':   Region Seed Region  Seed         P
 0         Y09      Y     9  0.446421
 1         Y08      Y     8  0.553579,
 'R1Z1':   Region Seed Region  Seed         P
 0         Z01      Z     1  0.980468
 1         Z16      Z    16  0.019532,
 'R1Z2':   Region Seed Region  Seed         P
 0         Z15      Z    15  0.041152
 1         Z02      Z     2  0.958848,
 'R1Z3':   Region Seed Region  Seed         P
 0         Z14      Z    14  0.061512
 1         Z03      Z     3  0.938488,
 'R1Z4':   Region Seed Region  Seed        P
 0         Z13      Z    13  0.13791
 1         Z04      Z     4  0.86209,
 'R1Z5':   Region Seed Region  Seed         P
 0         Z12      Z    12  0.286052
 1         Z05      Z     5  0.713948,
 'R1Z6':   Region Seed Region  Seed         P
 0         Z11      Z    11  0.394561
 1         Z06      Z     6  0.605439,
 'R1Z7':   Region Seed Region  Seed        P
 0         Z10      Z    10  0.35651
 1         Z07      Z     7  0.64349,
 'R1Z8':   Region Seed Region  Seed         P
 0         Z08      Z     8  0.694073
 1         Z09      Z     9  0.305927}

In [18]:
def fill_in_team(bracket: dict, round_: int, team: str, region: str, seed: int) -> dict:
    """
    Helper for simulate_public
    Fill in previous rounds of bracket for a team that wins in a future round
    """
    for r in range(1, min(round_ + 1, 4)):
        if seed > 2**(4-r):
            seed = 2**(5-r) + 1 - seed
        bracket[f'R{r}{region}{seed}'] = team

    if round_ >= 4:
        bracket[f'R4{region}1'] = team
    if round_ >= 5:
        if region in ('W', 'X'):
            bracket[f'R5WX'] = team
        else:
            bracket[f'R5YZ'] = team
    if round_ == 6:
        bracket[f'R6CH'] = team

    return bracket


def simulate_public():
    """
    Get bracket based on probabilities of winning each round
    """
    bracket = dict()

    # ROUND 6
    for matchup in ('R6CH', ):
        if not bracket.get(matchup):
            df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
            winner = df_matchup.loc[
                np.random.choice(
                    df_matchup.index,
                    p=df_matchup['P'],
                ),
                :
            ]
            bracket = fill_in_team(bracket, 6, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 5
    for matchup in ('R5WX', 'R5YZ'):
        if not bracket.get(matchup):
            df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
            winner = df_matchup.loc[
                np.random.choice(
                    df_matchup.index,
                    p=df_matchup['P'],
                ),
                :
            ]
            bracket = fill_in_team(bracket, 5, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 4
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 2):
            matchup = f'R4{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 4, winner['Region Seed'], winner['Region'], winner['Seed'])



    # ROUND 3
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 3):
            matchup = f'R3{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 3, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 2
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 5):
            matchup = f'R2{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 2, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 1
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 9):
            matchup = f'R1{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 1, winner['Region Seed'], winner['Region'], winner['Seed'])

    return dict(sorted(bracket.items()))

simulate_public()

{'R1W1': 'W01',
 'R1W2': 'W02',
 'R1W3': 'W03',
 'R1W4': 'W04',
 'R1W5': 'W05',
 'R1W6': 'W06',
 'R1W7': 'W10',
 'R1W8': 'W09',
 'R1X1': 'X01',
 'R1X2': 'X02',
 'R1X3': 'X03',
 'R1X4': 'X04',
 'R1X5': 'X12',
 'R1X6': 'X06',
 'R1X7': 'X07',
 'R1X8': 'X08',
 'R1Y1': 'Y01',
 'R1Y2': 'Y02',
 'R1Y3': 'Y03',
 'R1Y4': 'Y04',
 'R1Y5': 'Y05',
 'R1Y6': 'Y06',
 'R1Y7': 'Y07',
 'R1Y8': 'Y08',
 'R1Z1': 'Z01',
 'R1Z2': 'Z02',
 'R1Z3': 'Z03',
 'R1Z4': 'Z04',
 'R1Z5': 'Z05',
 'R1Z6': 'Z11',
 'R1Z7': 'Z10',
 'R1Z8': 'Z09',
 'R2W1': 'W09',
 'R2W2': 'W02',
 'R2W3': 'W03',
 'R2W4': 'W05',
 'R2X1': 'X01',
 'R2X2': 'X02',
 'R2X3': 'X06',
 'R2X4': 'X04',
 'R2Y1': 'Y01',
 'R2Y2': 'Y02',
 'R2Y3': 'Y03',
 'R2Y4': 'Y04',
 'R2Z1': 'Z01',
 'R2Z2': 'Z02',
 'R2Z3': 'Z03',
 'R2Z4': 'Z05',
 'R3W1': 'W09',
 'R3W2': 'W03',
 'R3X1': 'X01',
 'R3X2': 'X02',
 'R3Y1': 'Y01',
 'R3Y2': 'Y02',
 'R3Z1': 'Z01',
 'R3Z2': 'Z03',
 'R4W1': 'W09',
 'R4X1': 'X02',
 'R4Y1': 'Y01',
 'R4Z1': 'Z01',
 'R5WX': 'W09',
 'R5YZ': 'Z01',
 'R6CH': 'Z01'}

In [19]:
np.random.seed(24)

public_brackets = tuple(simulate_public() for _ in trange(20_000))  # set back to 20_000

len(public_brackets)

  0%|          | 0/20000 [00:00<?, ?it/s]

20000

In [ ]:
np.random.seed(25)

public_candidates = tuple(simulate_public() for _ in trange(20_000))  # set back to 20_000

len(public_candidates)

  0%|          | 0/2000 [00:00<?, ?it/s]

2000

In [21]:
simulation_data = {
    'results': results,
    'candidates': my_candidates + public_candidates,
    'public': public_brackets,
}

len(simulation_data)

3

In [22]:
import pickle

with open(f'../data/simulations/mens/mens_simulation_{season}.pkl', 'wb') as f:
    pickle.dump(simulation_data, f)

'Done'

'Done'