# Simulate Men's Tourney

Generated brackets based on model probabilities and public picks.

In [1]:
season = 2024

playin_losers = (  # remove play-in losers from seeding data
    1224,  # Howard
    1438,  # Virginia
    1286,  # Montana St
    1129,  # Boise St
)

season

2024

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 100)

df_seeds = pd.read_csv(r'..\data\unprocessed\kaggle\MNCAATourneySeeds.csv')

df_seeds = df_seeds.loc[df_seeds['Season'] == season, :].reset_index(drop=True)

df_seeds.insert(2, 'Play In', df_seeds['Seed'].str.endswith(('a', 'b')))
df_seeds.insert(2, 'Region', df_seeds['Seed'].str[0])
df_seeds['Seed'] = df_seeds['Seed'].str.extract('(\d+)').astype(int)

df_seeds = df_seeds.loc[~df_seeds['TeamID'].isin(playin_losers), :].reset_index(drop=True)

df_seeds.insert(1, 'Region Seed', df_seeds['Region'] + df_seeds['Seed'].astype(str).str.zfill(2))

df_seeds

    Season Region Seed  Seed Region  Play In  TeamID
0     2024         W01     1      W    False    1163
1     2024         W02     2      W    False    1235
2     2024         W03     3      W    False    1228
3     2024         W04     4      W    False    1120
4     2024         W05     5      W    False    1361
..     ...         ...   ...    ...      ...     ...
59    2024         Z12    12      Z    False    1241
60    2024         Z13    13      Z    False    1436
61    2024         Z14    14      Z    False    1324
62    2024         Z15    15      Z    False    1443
63    2024         Z16    16      Z    False    1255

[64 rows x 6 columns]

### Simulate Tournament

I think it might make more sense to just go through all 63 matchups as a dictionary, adding future rounds as you go

In [3]:
df_matrix = pd.read_csv(
    fr'../data/simulations/mens/matchup_matrix_{season}.csv',
    index_col='Team A ID',
).rename_axis(index=None)

df_matrix.columns = df_matrix.columns.astype(int)

df_matrix

,1103,1104,1112,1120,1124,1140,1155,1158,1159,1160,1161,1163,1166,1173,1179,1181,1182,1194,1196,1211,1212,1213,1222,1228,1235,1241,1242,1246,1253,1255,1266,1270,1277,1280,1287,1301,1304,1305,1307,1314,1321,1324,1332,1345,1355,1359,1361,1376,1388,1389,1391,1395,1397,1400,1401,1403,1412,1429,1436,1443,1447,1450,1458,1463
1103,NaN,0.091424,0.100999,0.049055,0.131083,0.155765,0.157105,0.367367,0.560826,0.250313,0.225430,0.034348,0.106627,0.222755,0.281165,0.106767,0.312563,0.233548,0.209328,0.103026,0.730086,0.286865,0.038950,0.145166,0.104024,0.310438,0.104804,0.121994,0.535948,0.704541,0.093873,0.338311,0.109939,0.171521,0.399835,0.205099,0.225470,0.198172,0.193089,0.073454,0.255970,0.519174,0.248627,0.059206,0.592316,0.430386,0.085425,0.234464,0.135958,0.557775,0.670341,0.179640,0.063735,0.137210,0.229399,0.168736,0.419211,0.303317,0.441591,0.543127,0.786664,0.163285,0.222902,0.306252
1104,0.887449,NaN,0.495728,0.446144,0.446509,0.629222,0.734520,0.844120,0.816294,0.698888,0.663397,0.213377,0.484626,0.662964,0.728947,0.465467,0.819684,0.733430,0.670293,0.370357,0.902744,0.796515,0.290977,0.499721,0.630285,0.781615,0.477631,0.528642,0.870246,0.902599,0.557683,0.802345,0.615933,0.674149,0.836165,0.776244,0.650679,0.773625,0.654538,0.514926,0.705286,0.895274,0.728910,0.324404,0.910130,0.845026,0.548337,0.759642,0.495212,0.884772,0.899043,0.691232,0.523457,0.581930,0.638315,0.611653,0.843289,0.747786,0.840188,0.878728,0.892666,0.690447,0.621297,0.802720
1112,0.920101,0.512363,NaN,0.582447,0.569483,0.693065,0.695271,0.848028,0.888044,0.704243,0.764256,0.277244,0.489642,0.742488,0.812140,0.626449,0.848107,0.679434,0.731327,0.434969,0.944352,0.837338,0.263829,0.560484,0.564288,0.816304,0.691762,0.631711,0.939420,0.925273,0.638145,0.787844,0.629192,0.720149,0.888539,0.811626,0.790048,0.844721,0.730414,0.522722,0.740460,0.908033,0.739081,0.516795,0.910863,0.853979,0.559995,0.840035,0.639849,0.858673,0.907419,0.715965,0.567121,0.669379,0.772259,0.688352,0.762712,0.792121,0.858367,0.894852,0.917132,0.715442,0.762986,0.864187
1120,0.942205,0.542500,0.517429,NaN,0.587811,0.718672,0.727100,0.875870,0.943376,0.752414,0.789643,0.341665,0.510303,0.760715,0.840927,0.522076,0.881595,0.802651,0.770356,0.510027,0.945687,0.877556,0.285309,0.664446,0.640003,0.872160,0.661159,0.600889,0.923330,0.953046,0.555464,0.870865,0.709740,0.783636,0.901448,0.832055,0.802074,0.847943,0.822159,0.463446,0.751709,0.905288,0.751350,0.363941,0.939845,0.899116,0.735807,0.782864,0.602511,0.940083,0.935136,0.794294,0.514761,0.681920,0.819617,0.734574,0.882190,0.824634,0.878228,0.943663,0.935917,0.807095,0.736274,0.761602
1124,0.841726,0.574906,0.447245,0.403862,NaN,0.664542,0.652738,0.766535,0.882888,0.677107,0.677627,0.257938,0.449187,0.579388,0.820853,0.362534,0.780075,0.671490,0.565665,0.450448,0.899802,0.627877,0.231932,0.444465,0.512421,0.738477,0.555774,0.449446,0.834585,0.909486,0.473802,0.765529,0.557811,0.651269,0.840664,0.634145,0.612767,0.669080,0.631254,0.422350,0.607154,0.886073,0.695656,0.308807,0.862892,0.781507,0.532749,0.645180,0.471677,0.869053,0.866036,0.626406,0.506122,0.573884,0.559854,0.647553,0.817842,0.725458,0.744863,0.815890,0.892299,0.637932,0.619721,0.805674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1443,0.419586,0.103249,0.087278,0.049238,0.158699,0.115367,0.192579,0.309076,0.480313,0.174399,0.177746,0.032347,0.067406,0.152848,0.235006,0.105894,0.390444,0.198300,0.130172,0.127512,0.743769,0.238720,0.034079,0.110393,0.091894,0.287335,0.074378,0.116196,0.566913,0.495737,0.090055,0.420332,0.083192,0.199054,0.496692,0.308922,0.132460,0.170303,0.113852,0.096708,0.211048,0.618824,0.208622,0.061947,0.503129,0.318194,0.096513,0.199685,0.099107,0.505639,0.502262,0.156872,0.055535,0.116944,0.219871,0.125013,0.330125,0.175393,0.388348,NaN,0.750524,0.189614,0.172138,0.337303
1447,0.166219,0.082837,0.068291,0.059187,0.095867,0.113150,0.115598,0.127085,0.251783,0.109558,0.142693,0.053728,0.057043,0.106317,0.169324,0.066829,0.170455,0.183493,0.110814,0.075015,0.482774,0.083759,0.044236,0.091673,0.060788,0.149452,0.102564,0.078585,0.257305,0.287470,0.071013,0.172332,0.063142,0.106295,0.156098,0.081862,0.133964,0.093775,0.124412,0.075896,0.076510,0.232560,0.127961,0.074548,0.244428,0.166526,0.081708,0.091295,0.060552,0.357979,0.289863,0.078705,0.063113,0.083834,0.087767,0.093000,0.172413,0.124052,0.130279,0.200522,NaN,0.074421,0.098597,0.121238
1450,0.821738,0.279463,0.301227,0.206493,0.370281,0.416059,0.510134,0.721663,0.812141,0.493483,0.474908,0.101741,0.303784,0.464022,0.613380,0.332911,0.734335,0.469986,0.456356,0.277716,0.908947,0.591999,0.077311,0.365014,0.255929,0.651908,0.291892,0.280063,0.892435,0.879024,0.342631,0.704620,0.380600,0.472642,0.793208,0.520002,0.429016,0.570473,0.457216,0.332050,0.460941,0.849120,0.502870,0.184703,0.817759,0.674070,0.356195,0.531814,0.342666,0.788367,0.823596,0.350547,0.203666,0.420798,0.484377,0.479857,0.586690,0.623516,0.730905,0.766662,0.921917,NaN,0.485620,0.727767
1458,0.745849,0.332230,0.248009,0.264960,0.361514,0.469460,0.592091,0.657507,0.799037,0.674044,0.523663,0.108573,0.386947,0.574645,0.688989,0.358187,0.674025,0.505485,0.459247,0.273914,0.838972,0.720606,0.223340,0.344008,0.436396,0.650464,0.425354,0.471220,0.820097,0.892238,0.320395,0.623928,0.430540,0.486640,0.751351,0.552259,0.650247,0.652778,0.522340,0.379182,0.554066,0.789228,0.597115,0.147704,0.817159,0.721556,0.504445,0.513457,0.460713,0.811086,0.819829,0.438159,0.293966,0.420424,0.577941,0.499452,0.745979,0.611103,0.655988,0.772663,0.875152,0.496112,NaN,0.685292
1463,0.684611,0.176217,0.173866,0.224280,0.196599,0.285921,0.290856,0.530361,0.614144,0.408078,0.366985,0.068330,0.151038,0.280046,0.463036,0.224724,0.585212,0.345894,0.293159,0.193841,0.855225,0.442482,0.101167,0.203790,0.126593,0.426446,0.182744,0.247325,0.779754,0.841050,0.127735,0.457979,0.215513,0.457786,0.605951,0.373083,0.330854,0.270046,0.412230,0.224919,0.384308,0.617403,0.527058,0.075098,0.638464,0.583941,0.196960,0.392041,0.171528,0.800107,0.733358,0.446735,0.154328,0.170805,0.335195,0.240069,0.579015,0.360977,0.602281,0.726730,0.866658,0.276589,0.314117,NaN

In [4]:
id_to_region_seed = dict(zip(df_seeds['TeamID'], df_seeds['Region Seed']))

df_matrix.index = df_matrix.index.map(id_to_region_seed)
df_matrix.columns = df_matrix.columns.map(id_to_region_seed)

df_matrix

,Y14,X04,X02,W04,X03,W06,X06,X13,X14,Z10,Y10,W01,Y03,X07,W10,Z04,W11,W08,Z07,Y05,Y16,X12,Z01,W03,W02,Z12,Y04,Z03,X15,Z16,Z02,Y12,X09,X08,W14,Z11,Z08,X10,X11,X01,W09,Z14,Y11,Y01,W15,Y13,W05,Y06,X05,Y15,W16,Y09,Y02,Y07,Z09,Z06,W12,Y08,Z13,Z15,X16,W07,Z05,W13
Y14,NaN,0.091424,0.100999,0.049055,0.131083,0.155765,0.157105,0.367367,0.560826,0.250313,0.225430,0.034348,0.106627,0.222755,0.281165,0.106767,0.312563,0.233548,0.209328,0.103026,0.730086,0.286865,0.038950,0.145166,0.104024,0.310438,0.104804,0.121994,0.535948,0.704541,0.093873,0.338311,0.109939,0.171521,0.399835,0.205099,0.225470,0.198172,0.193089,0.073454,0.255970,0.519174,0.248627,0.059206,0.592316,0.430386,0.085425,0.234464,0.135958,0.557775,0.670341,0.179640,0.063735,0.137210,0.229399,0.168736,0.419211,0.303317,0.441591,0.543127,0.786664,0.163285,0.222902,0.306252
X04,0.887449,NaN,0.495728,0.446144,0.446509,0.629222,0.734520,0.844120,0.816294,0.698888,0.663397,0.213377,0.484626,0.662964,0.728947,0.465467,0.819684,0.733430,0.670293,0.370357,0.902744,0.796515,0.290977,0.499721,0.630285,0.781615,0.477631,0.528642,0.870246,0.902599,0.557683,0.802345,0.615933,0.674149,0.836165,0.776244,0.650679,0.773625,0.654538,0.514926,0.705286,0.895274,0.728910,0.324404,0.910130,0.845026,0.548337,0.759642,0.495212,0.884772,0.899043,0.691232,0.523457,0.581930,0.638315,0.611653,0.843289,0.747786,0.840188,0.878728,0.892666,0.690447,0.621297,0.802720
X02,0.920101,0.512363,NaN,0.582447,0.569483,0.693065,0.695271,0.848028,0.888044,0.704243,0.764256,0.277244,0.489642,0.742488,0.812140,0.626449,0.848107,0.679434,0.731327,0.434969,0.944352,0.837338,0.263829,0.560484,0.564288,0.816304,0.691762,0.631711,0.939420,0.925273,0.638145,0.787844,0.629192,0.720149,0.888539,0.811626,0.790048,0.844721,0.730414,0.522722,0.740460,0.908033,0.739081,0.516795,0.910863,0.853979,0.559995,0.840035,0.639849,0.858673,0.907419,0.715965,0.567121,0.669379,0.772259,0.688352,0.762712,0.792121,0.858367,0.894852,0.917132,0.715442,0.762986,0.864187
W04,0.942205,0.542500,0.517429,NaN,0.587811,0.718672,0.727100,0.875870,0.943376,0.752414,0.789643,0.341665,0.510303,0.760715,0.840927,0.522076,0.881595,0.802651,0.770356,0.510027,0.945687,0.877556,0.285309,0.664446,0.640003,0.872160,0.661159,0.600889,0.923330,0.953046,0.555464,0.870865,0.709740,0.783636,0.901448,0.832055,0.802074,0.847943,0.822159,0.463446,0.751709,0.905288,0.751350,0.363941,0.939845,0.899116,0.735807,0.782864,0.602511,0.940083,0.935136,0.794294,0.514761,0.681920,0.819617,0.734574,0.882190,0.824634,0.878228,0.943663,0.935917,0.807095,0.736274,0.761602
X03,0.841726,0.574906,0.447245,0.403862,NaN,0.664542,0.652738,0.766535,0.882888,0.677107,0.677627,0.257938,0.449187,0.579388,0.820853,0.362534,0.780075,0.671490,0.565665,0.450448,0.899802,0.627877,0.231932,0.444465,0.512421,0.738477,0.555774,0.449446,0.834585,0.909486,0.473802,0.765529,0.557811,0.651269,0.840664,0.634145,0.612767,0.669080,0.631254,0.422350,0.607154,0.886073,0.695656,0.308807,0.862892,0.781507,0.532749,0.645180,0.471677,0.869053,0.866036,0.626406,0.506122,0.573884,0.559854,0.647553,0.817842,0.725458,0.744863,0.815890,0.892299,0.637932,0.619721,0.805674
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Z15,0.419586,0.103249,0.087278,0.049238,0.158699,0.115367,0.192579,0.309076,0.480313,0.174399,0.177746,0.032347,0.067406,0.152848,0.235006,0.105894,0.390444,0.198300,0.130172,0.127512,0.743769,0.238720,0.034079,0.110393,0.091894,0.287335,0.074378,0.116196,0.566913,0.495737,0.090055,0.420332,0.083192,0.199054,0.496692,0.308922,0.132460,0.170303,0.113852,0.096708,0.211048,0.618824,0.208622,0.061947,0.503129,0.318194,0.096513,0.199685,0.099107,0.505639,0.502262,0.156872,0.055535,0.116944,0.219871,0.125013,0.330125,0.175393,0.388348,NaN,0.750524,0.189614,0.172138,0.337303
X16,0.166219,0.082837,0.068291,0.059187,0.095867,0.113150,0.115598,0.127085,0.251783,0.109558,0.142693,0.053728,0.057043,0.106317,0.169324,0.066829,0.170455,0.183493,0.110814,0.075015,0.482774,0.083759,0.044236,0.091673,0.060788,0.149452,0.102564,0.078585,0.257305,0.287470,0.071013,0.172332,0.063142,0.106295,0.156098,0.081862,0.133964,0.093775,0.124412,0.075896,0.076510,0.232560,0.127961,0.074548,0.244428,0.166526,0.081708,0.091295,0.060552,0.357979,0.289863,0.078705,0.063113,0.083834,0.087767,0.093000,0.172413,0.124052,0.130279,0.200522,NaN,0.074421,0.098597,0.121238
W07,0.821738,0.279463,0.301227,0.206493,0.370281,0.416059,0.510134,0.721663,0.812141,0.493483,0.474908,0.101741,0.303784,0.464022,0.613380,0.332911,0.734335,0.469986,0.456356,0.277716,0.908947,0.591999,0.077311,0.365014,0.255929,0.651908,0.291892,0.280063,0.892435,0.879024,0.342631,0.704620,0.380600,0.472642,0.793208,0.520002,0.429016,0.570473,0.457216,0.332050,0.460941,0.849120,0.502870,0.184703,0.817759,0.674070,0.356195,0.531814,0.342666,0.788367,0.823596,0.350547,0.203666,0.420798,0.484377,0.479857,0.586690,0.623516,0.730905,0.766662,0.921917,NaN,0.485620,0.727767
Z05,0.745849,0.332230,0.248009,0.264960,0.361514,0.469460,0.592091,0.657507,0.799037,0.674044,0.523663,0.108573,0.386947,0.574645,0.688989,0.358187,0.674025,0.505485,0.459247,0.273914,0.838972,0.720606,0.223340,0.344008,0.436396,0.650464,0.425354,0.471220,0.820097,0.892238,0.320395,0.623928,0.430540,0.486640,0.751351,0.552259,0.650247,0.652778,0.522340,0.379182,0.554066,0.789228,0.597115,0.147704,0.817159,0.721556,0.504445,0.513457,0.460713,0.811086,0.819829,0.438159,0.293966,0.420424,0.577941,0.499452,0.745979,0.611103,0.655988,0.772663,0.875152,0.496112,NaN,0.685292
W13,0.684611,0.176217,0.173866,0.224280,0.196599,0.285921,0.290856,0.530361,0.614144,0.408078,0.366985,0.068330,0.151038,0.280046,0.463036,0.224724,0.585212,0.345894,0.293159,0.193841,0.855225,0.442482,0.101167,0.203790,0.126593,0.426446,0.182744,0.247325,0.779754,0.841050,0.127735,0.457979,0.215513,0.457786,0.605951,0.373083,0.330854,0.270046,0.412230,0.224919,0.384308,0.617403,0.527058,0.075098,0.638464,0.583941,0.196960,0.392041,0.171528,0.800107,0.733358,0.446735,0.154328,0.170805,0.335195,0.240069,0.579015,0.360977,0.602281,0.726730,0.866658,0.276589,0.314117,NaN

In [5]:
df_matrix_opposite = 1 - df_matrix  # prob of team losing

df_matrix_opposite

,Y14,X04,X02,W04,X03,W06,X06,X13,X14,Z10,Y10,W01,Y03,X07,W10,Z04,W11,W08,Z07,Y05,Y16,X12,Z01,W03,W02,Z12,Y04,Z03,X15,Z16,Z02,Y12,X09,X08,W14,Z11,Z08,X10,X11,X01,W09,Z14,Y11,Y01,W15,Y13,W05,Y06,X05,Y15,W16,Y09,Y02,Y07,Z09,Z06,W12,Y08,Z13,Z15,X16,W07,Z05,W13
Y14,NaN,0.908576,0.899001,0.950945,0.868917,0.844235,0.842895,0.632633,0.439174,0.749687,0.774570,0.965652,0.893373,0.777245,0.718835,0.893233,0.687437,0.766452,0.790672,0.896974,0.269914,0.713135,0.961050,0.854834,0.895976,0.689562,0.895196,0.878006,0.464052,0.295459,0.906127,0.661689,0.890061,0.828479,0.600165,0.794901,0.774530,0.801828,0.806911,0.926546,0.744030,0.480826,0.751373,0.940794,0.407684,0.569614,0.914575,0.765536,0.864042,0.442225,0.329659,0.820360,0.936265,0.862790,0.770601,0.831264,0.580789,0.696683,0.558409,0.456873,0.213336,0.836715,0.777098,0.693748
X04,0.112551,NaN,0.504272,0.553856,0.553491,0.370778,0.265480,0.155880,0.183706,0.301112,0.336603,0.786623,0.515374,0.337036,0.271053,0.534533,0.180316,0.266570,0.329707,0.629643,0.097256,0.203485,0.709023,0.500279,0.369715,0.218385,0.522369,0.471358,0.129754,0.097401,0.442317,0.197655,0.384067,0.325851,0.163835,0.223756,0.349321,0.226375,0.345462,0.485074,0.294714,0.104726,0.271090,0.675596,0.089870,0.154974,0.451663,0.240358,0.504788,0.115228,0.100957,0.308768,0.476543,0.418070,0.361685,0.388347,0.156711,0.252214,0.159812,0.121272,0.107334,0.309553,0.378703,0.197280
X02,0.079899,0.487637,NaN,0.417553,0.430517,0.306935,0.304729,0.151972,0.111956,0.295757,0.235744,0.722756,0.510358,0.257512,0.187860,0.373551,0.151893,0.320566,0.268673,0.565031,0.055648,0.162662,0.736171,0.439516,0.435712,0.183696,0.308238,0.368289,0.060580,0.074727,0.361855,0.212156,0.370808,0.279851,0.111461,0.188374,0.209952,0.155279,0.269586,0.477278,0.259540,0.091967,0.260919,0.483205,0.089137,0.146021,0.440005,0.159965,0.360151,0.141327,0.092581,0.284035,0.432879,0.330621,0.227741,0.311648,0.237288,0.207879,0.141633,0.105148,0.082868,0.284558,0.237014,0.135813
W04,0.057795,0.457500,0.482571,NaN,0.412189,0.281328,0.272900,0.124130,0.056624,0.247586,0.210357,0.658335,0.489697,0.239285,0.159073,0.477924,0.118405,0.197349,0.229644,0.489973,0.054313,0.122444,0.714691,0.335554,0.359997,0.127840,0.338841,0.399111,0.076670,0.046954,0.444536,0.129135,0.290260,0.216364,0.098552,0.167945,0.197926,0.152057,0.177841,0.536554,0.248291,0.094712,0.248650,0.636059,0.060155,0.100884,0.264193,0.217136,0.397489,0.059917,0.064864,0.205706,0.485239,0.318080,0.180383,0.265426,0.117810,0.175366,0.121772,0.056337,0.064083,0.192905,0.263726,0.238398
X03,0.158274,0.425094,0.552755,0.596138,NaN,0.335458,0.347262,0.233465,0.117112,0.322893,0.322373,0.742062,0.550813,0.420612,0.179147,0.637466,0.219925,0.328510,0.434335,0.549552,0.100198,0.372123,0.768068,0.555535,0.487579,0.261523,0.444226,0.550554,0.165415,0.090514,0.526198,0.234471,0.442189,0.348731,0.159336,0.365855,0.387233,0.330920,0.368746,0.577650,0.392846,0.113927,0.304344,0.691193,0.137108,0.218493,0.467251,0.354820,0.528323,0.130947,0.133964,0.373594,0.493878,0.426116,0.440146,0.352447,0.182158,0.274542,0.255137,0.184110,0.107701,0.362068,0.380279,0.194326
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Z15,0.580414,0.896751,0.912722,0.950762,0.841301,0.884633,0.807421,0.690924,0.519687,0.825601,0.822254,0.967653,0.932594,0.847152,0.764994,0.894106,0.609556,0.801700,0.869828,0.872488,0.256231,0.761280,0.965921,0.889607,0.908106,0.712665,0.925622,0.883804,0.433087,0.504263,0.909945,0.579668,0.916808,0.800946,0.503308,0.691078,0.867540,0.829697,0.886148,0.903292,0.788952,0.381176,0.791378,0.938053,0.496871,0.681806,0.903487,0.800315,0.900893,0.494361,0.497738,0.843128,0.944465,0.883056,0.780129,0.874987,0.669875,0.824607,0.611652,NaN,0.249476,0.810386,0.827862,0.662697
X16,0.833781,0.917163,0.931709,0.940813,0.904133,0.886850,0.884402,0.872915,0.748217,0.890442,0.857307,0.946272,0.942957,0.893683,0.830676,0.933171,0.829545,0.816507,0.889186,0.924985,0.517226,0.916241,0.955764,0.908327,0.939212,0.850548,0.897436,0.921415,0.742695,0.712530,0.928987,0.827668,0.936858,0.893705,0.843902,0.918138,0.866036,0.906225,0.875588,0.924104,0.923490,0.767440,0.872039,0.925452,0.755572,0.833474,0.918292,0.908705,0.939448,0.642021,0.710137,0.921295,0.936887,0.916166,0.912233,0.907000,0.827587,0.875948,0.869721,0.799478,NaN,0.925579,0.901403,0.878762
W07,0.178262,0.720537,0.698773,0.793507,0.629719,0.583941,0.489866,0.278337,0.187859,0.506517,0.525092,0.898259,0.696216,0.535978,0.386620,0.667089,0.265665,0.530014,0.543644,0.722284,0.091053,0.408001,0.922689,0.634986,0.744071,0.348092,0.708108,0.719937,0.107565,0.120976,0.657369,0.295380,0.619400,0.527358,0.206792,0.479998,0.570984,0.429527,0.542784,0.667950,0.539059,0.150880,0.497130,0.815297,0.182241,0.325930,0.643805,0.468186,0.657334,0.211633,0.176404,0.649453,0.796334,0.579202,0.515623,0.520143,0.413310,0.376484,0.269095,0.233338,0.078083,NaN,0.514380,0.272233
Z05,0.254151,0.667770,0.751991,0.735040,0.638486,0.530540,0.407909,0.342493,0.200963,0.325956,0.476337,0.891427,0.613053,0.425355,0.311011,0.641813,0.325975,0.494515,0.540753,0.726086,0.161028,0.279394,0.776660,0.655992,0.563604,0.349536,0.574646,0.528780,0.179903,0.107762,0.679605,0.376072,0.569460,0.513360,0.248649,0.447741,0.349753,0.347222,0.477660,0.620818,0.445934,0.210772,0.402885,0.852296,0.182841,0.278444,0.495555,0.486543,0.539287,0.188914,0.180171,0.561841,0.706034,0.579576,0.422059,0.500548,0.254021,0.388897,0.344012,0.227337,0.124848,0.503888,NaN,0.314708
W13,0.315389,0.823783,0.826134,0.775720,0.803401,0.714079,0.709144,0.469639,0.385856,0.591922,0.633015,0.931670,0.848962,0.719954,0.536964,0.775276,0.414788,0.654106,0.706841,0.806159,0.144775,0.557518,0.898833,0.796210,0.873407,0.573554,0.817256,0.752675,0.220246,0.158950,0.872265,0.542021,0.784487,0.542214,0.394049,0.626917,0.669146,0.729954,0.587770,0.775081,0.615692,0.382597,0.472942,0.924902,0.361536,0.416059,0.803040,0.607959,0.828472,0.199893,0.266642,0.553265,0.845672,0.829195,0.664805,0.759931,0.420985,0.639023,0.397719,0.273270,0.133342,0.723411,0.685883,NaN

In [6]:
import numpy as np

def simulate_tournament() -> dict:
    """
    Simulate the tournament in Kaggle submission format
    """
    # ROUND 1
    round_1 = {
        f'R1{region}{i}': np.random.choice(
            (f'{region}{i:02d}', f'{region}{17-i:02d}'), 
            p=(
                df_matrix.loc[f'{region}{i:02d}', f'{region}{17-i:02d}'], 
                df_matrix_opposite.loc[f'{region}{i:02d}', f'{region}{17-i:02d}']
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 8, 5, 4, 6, 3, 7, 2)
    }

    # ROUND 2
    round_2 = {
        f'R2{region}{i}': np.random.choice(
            (round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']), 
            p=(
                df_matrix.loc[round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']], 
                df_matrix_opposite.loc[round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 4, 3, 2)
    }

    # ROUND 3
    round_3 = {
        f'R3{region}{i}': np.random.choice(
            (round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']), 
            p=(
                df_matrix.loc[round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']], 
                df_matrix_opposite.loc[round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 2)
    }

    # ROUND 4
    round_4 = {
        f'R4{region}{i}': np.random.choice(
            (round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']), 
            p=(
                df_matrix.loc[round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']], 
                df_matrix_opposite.loc[round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, )
    }

    # ROUND 5
    round_5 = {
        'R5WX': np.random.choice(
            (round_4['R4W1'], round_4['R4X1']),
            p=(
                df_matrix.loc[round_4['R4W1'], round_4['R4X1']],
                df_matrix_opposite.loc[round_4['R4W1'], round_4['R4X1']],
            )
        ),
        'R5YZ': np.random.choice(
            (round_4['R4Y1'], round_4['R4Z1']),
            p=(
                df_matrix.loc[round_4['R4Y1'], round_4['R4Z1']],
                df_matrix_opposite.loc[round_4['R4Y1'], round_4['R4Z1']],
            )
        ),
    }

    # ROUND 6
    round_6 = {
        'R6CH': np.random.choice(
            (round_5['R5WX'], round_5['R5YZ']),
            p=(
                df_matrix.loc[round_5['R5WX'], round_5['R5YZ']],
                df_matrix_opposite.loc[round_5['R5WX'], round_5['R5YZ']],
            )
        ),
    }

    return round_1 | round_2 | round_3 | round_4 | round_5 | round_6  # merge the dictionaries (python >= 3.9)

simulate_tournament()

{'R1W1': 'W01',
 'R1W8': 'W09',
 'R1W5': 'W12',
 'R1W4': 'W04',
 'R1W6': 'W06',
 'R1W3': 'W03',
 'R1W7': 'W07',
 'R1W2': 'W02',
 'R1X1': 'X01',
 'R1X8': 'X08',
 'R1X5': 'X12',
 'R1X4': 'X04',
 'R1X6': 'X11',
 'R1X3': 'X03',
 'R1X7': 'X07',
 'R1X2': 'X02',
 'R1Y1': 'Y01',
 'R1Y8': 'Y09',
 'R1Y5': 'Y12',
 'R1Y4': 'Y04',
 'R1Y6': 'Y11',
 'R1Y3': 'Y03',
 'R1Y7': 'Y07',
 'R1Y2': 'Y02',
 'R1Z1': 'Z01',
 'R1Z8': 'Z09',
 'R1Z5': 'Z05',
 'R1Z4': 'Z04',
 'R1Z6': 'Z06',
 'R1Z3': 'Z03',
 'R1Z7': 'Z07',
 'R1Z2': 'Z02',
 'R2W1': 'W01',
 'R2W4': 'W04',
 'R2W3': 'W06',
 'R2W2': 'W07',
 'R2X1': 'X01',
 'R2X4': 'X04',
 'R2X3': 'X03',
 'R2X2': 'X02',
 'R2Y1': 'Y09',
 'R2Y4': 'Y04',
 'R2Y3': 'Y03',
 'R2Y2': 'Y07',
 'R2Z1': 'Z01',
 'R2Z4': 'Z04',
 'R2Z3': 'Z06',
 'R2Z2': 'Z02',
 'R3W1': 'W04',
 'R3W2': 'W06',
 'R3X1': 'X04',
 'R3X2': 'X03',
 'R3Y1': 'Y09',
 'R3Y2': 'Y03',
 'R3Z1': 'Z01',
 'R3Z2': 'Z02',
 'R4W1': 'W04',
 'R4X1': 'X04',
 'R4Y1': 'Y03',
 'R4Z1': 'Z01',
 'R5WX': 'X04',
 'R5YZ': 'Z01',
 'R6CH': 'X04'}

In [7]:
from tqdm.autonotebook import trange

np.random.seed(22)

results = tuple(
    simulate_tournament()
    for _ in trange(3_000)  # set back to 30_000
)

len(results)

C:\Users\mhugh\AppData\Local\Temp\ipykernel_12096\4113097100.py:1: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import trange

  0%|          | 0/3000 [00:00<?, ?it/s]

3000

In [8]:
np.random.seed(23)

my_candidates = tuple(
    simulate_tournament()
    for _ in trange(2_000)  # set back to 20_000
)

len(my_candidates)

  0%|          | 0/2000 [00:00<?, ?it/s]

2000

In [9]:
def bracket_to_team_placements(bracket: dict) -> dict:
    """
    Convert bracket to dict of how many games each team won
    """
    round_1 = {
        bracket[f'R1{region}{i}']: 1
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 8, 5, 4, 6, 3, 7, 2)
    }

    round_2 = {
        bracket[f'R2{region}{i}']: 2
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 4, 3, 2)
    }

    round_3 = {
        bracket[f'R3{region}{i}']: 3
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 2)
    }

    round_4 = {
        bracket[f'R4{region}{i}']: 4
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, )
    }

    round_5 = {
        bracket['R5WX']: 5,
        bracket['R5YZ']: 5,
    }

    round_6 = {
        bracket['R6CH']: 6,
    }

    return round_1 | round_2 | round_3 | round_4 | round_5 | round_6  # merge the dictionaries (python >= 3.9)

bracket_to_team_placements(results[0])

{'W01': 4,
 'W08': 1,
 'W05': 1,
 'W13': 2,
 'W06': 3,
 'W03': 1,
 'W07': 2,
 'W02': 1,
 'X01': 6,
 'X09': 1,
 'X05': 1,
 'X04': 2,
 'X11': 1,
 'X03': 3,
 'X07': 1,
 'X02': 2,
 'Y01': 5,
 'Y09': 1,
 'Y05': 1,
 'Y04': 2,
 'Y11': 1,
 'Y03': 2,
 'Y07': 1,
 'Y02': 3,
 'Z01': 2,
 'Z09': 1,
 'Z12': 1,
 'Z04': 4,
 'Z11': 3,
 'Z14': 1,
 'Z10': 1,
 'Z02': 2}

In [10]:
from tqdm.autonotebook import tqdm

team_placements = tuple(bracket_to_team_placements(result) for result in tqdm(results))

len(team_placements)

  0%|          | 0/3000 [00:00<?, ?it/s]

3000

In [11]:
team_all_placements = {
    team: np.array([team_placements_bracket.get(team, 0) for team_placements_bracket in team_placements])
    for team in ((f'{region}{i:02d}') for region in ('W', 'X', 'Y', 'Z') for i in range(1, 17))
}

team_all_placements

{'W01': array([4, 6, 6, ..., 6, 4, 5]),
 'W02': array([1, 3, 0, ..., 3, 1, 3]),
 'W03': array([1, 0, 3, ..., 1, 2, 2]),
 'W04': array([0, 2, 1, ..., 2, 2, 1]),
 'W05': array([1, 0, 2, ..., 0, 0, 0]),
 'W06': array([3, 2, 1, ..., 2, 1, 1]),
 'W07': array([2, 1, 0, ..., 0, 3, 0]),
 'W08': array([1, 0, 0, ..., 0, 1, 0]),
 'W09': array([0, 1, 1, ..., 1, 0, 1]),
 'W10': array([0, 0, 2, ..., 1, 0, 1]),
 'W11': array([0, 0, 0, ..., 0, 0, 0]),
 'W12': array([0, 1, 0, ..., 1, 1, 2]),
 'W13': array([2, 0, 0, ..., 0, 0, 0]),
 'W14': array([0, 1, 0, ..., 0, 0, 0]),
 'W15': array([0, 0, 1, ..., 0, 0, 0]),
 'W16': array([0, 0, 0, ..., 0, 0, 0]),
 'X01': array([6, 0, 2, ..., 3, 5, 2]),
 'X02': array([2, 2, 1, ..., 1, 3, 1]),
 'X03': array([3, 1, 2, ..., 4, 1, 3]),
 'X04': array([2, 4, 4, ..., 1, 2, 0]),
 'X05': array([1, 1, 1, ..., 2, 1, 4]),
 'X06': array([0, 3, 1, ..., 1, 0, 1]),
 'X07': array([1, 1, 0, ..., 2, 1, 2]),
 'X08': array([0, 0, 1, ..., 0, 0, 0]),
 'X09': array([1, 2, 0, ..., 1, 1, 1]),
 'X10': array([0, 0, 3, ..., 0, 0, 0]),
 'X11': array([1, 0, 0, ..., 0, 2, 0]),
 'X12': array([0, 0, 0, ..., 0, 0, 0]),
 'X13': array([0, 0, 0, ..., 0, 0, 1]),
 'X14': array([0, 0, 0, ..., 0, 0, 0]),
 'X15': array([0, 0, 0, ..., 0, 0, 0]),
 'X16': array([0, 1, 0, ..., 0, 0, 0]),
 'Y01': array([5, 2, 3, ..., 4, 2, 3]),
 'Y02': array([3, 1, 4, ..., 0, 1, 4]),
 'Y03': array([2, 2, 2, ..., 3, 4, 1]),
 'Y04': array([2, 1, 2, ..., 2, 3, 0]),
 'Y05': array([1, 4, 1, ..., 1, 0, 1]),
 'Y06': array([0, 1, 0, ..., 0, 0, 2]),
 'Y07': array([1, 3, 1, ..., 2, 2, 0]),
 'Y08': array([0, 0, 0, ..., 1, 1, 0]),
 'Y09': array([1, 1, 1, ..., 0, 0, 1]),
 'Y10': array([0, 0, 0, ..., 0, 0, 1]),
 'Y11': array([1, 0, 1, ..., 1, 1, 0]),
 'Y12': array([0, 0, 0, ..., 0, 1, 0]),
 'Y13': array([0, 0, 0, ..., 0, 0, 2]),
 'Y14': array([0, 0, 0, ..., 0, 0, 0]),
 'Y15': array([0, 0, 0, ..., 1, 0, 0]),
 'Y16': array([0, 0, 0, ..., 0, 0, 0]),
 'Z01': array([2, 3, 2, ..., 5, 6, 1]),
 'Z02': array([2, 5, 0, ..., 2, 0, 3]),
 'Z03': array([0, 1, 1, ..., 1, 1, 1]),
 'Z04': array([4, 1, 3, ..., 2, 2, 2]),
 'Z05': array([0, 2, 1, ..., 0, 1, 1]),
 'Z06': array([0, 0, 2, ..., 3, 0, 2]),
 'Z07': array([0, 0, 5, ..., 1, 3, 0]),
 'Z08': array([0, 0, 1, ..., 0, 1, 0]),
 'Z09': array([1, 1, 0, ..., 1, 0, 6]),
 'Z10': array([1, 1, 0, ..., 0, 0, 1]),
 'Z11': array([3, 2, 0, ..., 0, 2, 0]),
 'Z12': array([1, 0, 0, ..., 1, 0, 0]),
 'Z13': array([0, 0, 0, ..., 0, 0, 0]),
 'Z14': array([1, 0, 0, ..., 0, 0, 0]),
 'Z15': array([0, 0, 1, ..., 0, 1, 0]),
 'Z16': array([0, 0, 0, ..., 0, 0, 0])}

Get probabilities of surviving

In [12]:
team_model_probs = dict(
    (
        t, 
        np.array(tuple(
            (v >= round).mean()
            for round in range(1, 7)
        ))
    )
    for t, v in team_all_placements.items()
)

team_model_probs

{'W01': array([0.963     , 0.85      , 0.649     , 0.50966667, 0.39433333,
        0.27333333]),
 'W02': array([0.914     , 0.67933333, 0.413     , 0.13433333, 0.06733333,
        0.02366667]),
 'W03': array([0.854     , 0.59033333, 0.32233333, 0.09866667, 0.05233333,
        0.02033333]),
 'W04': array([0.74833333, 0.576     , 0.22066667, 0.149     , 0.08266667,
        0.035     ]),
 'W05': array([0.793     , 0.312     , 0.07366667, 0.038     , 0.01533333,
        0.00266667]),
 'W06': array([0.57366667, 0.27466667, 0.11433333, 0.02466667, 0.009     ,
        0.004     ]),
 'W07': array([5.96333333e-01, 1.80333333e-01, 7.10000000e-02, 1.23333333e-02,
        3.66666667e-03, 3.33333333e-04]),
 'W08': array([0.55233333, 0.097     , 0.02733333, 0.01133333, 0.00333333,
        0.00066667]),
 'W09': array([4.47666667e-01, 4.63333333e-02, 1.63333333e-02, 5.33333333e-03,
        2.33333333e-03, 3.33333333e-04]),
 'W10': array([0.40366667, 0.11966667, 0.04533333, 0.00933333, 0.00233333,
        0.00066667]),
 'W11': array([0.42633333, 0.09866667, 0.024     , 0.00366667, 0.00066667,
        0.        ]),
 'W12': array([0.207     , 0.04333333, 0.006     , 0.002     , 0.00066667,
        0.        ]),
 'W13': array([0.25166667, 0.06866667, 0.00633333, 0.00066667, 0.        ,
        0.        ]),
 'W14': array([0.146     , 0.03633333, 0.00666667, 0.00033333, 0.        ,
        0.        ]),
 'W15': array([0.086     , 0.02066667, 0.00333333, 0.00066667, 0.        ,
        0.        ]),
 'W16': array([0.037     , 0.00666667, 0.00066667, 0.        , 0.        ,
        0.        ]),
 'X01': array([0.908     , 0.618     , 0.335     , 0.19333333, 0.07033333,
        0.027     ]),
 'X02': array([0.935     , 0.727     , 0.46833333, 0.255     , 0.107     ,
        0.04666667]),
 'X03': array([0.87966667, 0.566     , 0.26733333, 0.135     , 0.05666667,
        0.024     ]),
 'X04': array([0.85633333, 0.50866667, 0.28333333, 0.15566667, 0.06033333,
        0.023     ]),
 'X05': array([0.612     , 0.34433333, 0.19633333, 0.08733333, 0.027     ,
        0.00833333]),
 'X06': array([0.61033333, 0.24366667, 0.08733333, 0.03466667, 0.01033333,
        0.00333333]),
 'X07': array([5.71000000e-01, 1.73666667e-01, 7.90000000e-02, 3.03333333e-02,
        5.33333333e-03, 3.33333333e-04]),
 'X08': array([3.88666667e-01, 1.31333333e-01, 4.16666667e-02, 1.36666667e-02,
        1.33333333e-03, 3.33333333e-04]),
 'X09': array([0.61133333, 0.24433333, 0.09966667, 0.04366667, 0.014     ,
        0.00433333]),
 'X10': array([0.429     , 0.08866667, 0.037     , 0.01333333, 0.00333333,
        0.00066667]),
 'X11': array([0.38966667, 0.168     , 0.056     , 0.02533333, 0.00833333,
        0.00166667]),
 'X12': array([0.388     , 0.109     , 0.032     , 0.01033333, 0.002     ,
        0.00066667]),
 'X13': array([0.14366667, 0.038     , 0.011     , 0.00133333, 0.        ,
        0.        ]),
 'X14': array([0.12033333, 0.02233333, 0.00233333, 0.00033333, 0.        ,
        0.        ]),
 'X15': array([0.065     , 0.01066667, 0.00266667, 0.00066667, 0.        ,
        0.        ]),
 'X16': array([0.092     , 0.00633333, 0.001     , 0.        , 0.        ,
        0.        ]),
 'Y01': array([0.95133333, 0.77      , 0.55033333, 0.369     , 0.21033333,
        0.101     ]),
 'Y02': array([0.929     , 0.65966667, 0.427     , 0.20533333, 0.086     ,
        0.03066667]),
 'Y03': array([0.87433333, 0.67333333, 0.345     , 0.17133333, 0.082     ,
        0.03433333]),
 'Y04': array([0.74566667, 0.35833333, 0.122     , 0.043     , 0.01166667,
        0.005     ]),
 'Y05': array([0.82033333, 0.52466667, 0.21366667, 0.10566667, 0.04133333,
        0.01633333]),
 'Y06': array([4.49666667e-01, 1.24333333e-01, 3.90000000e-02, 8.66666667e-03,
        1.00000000e-03, 3.33333333e-04]),
 'Y07': array([0.70866667, 0.24233333, 0.11533333, 0.042     , 0.00933333,
        0.003     ]),
 'Y08': array([5.51000000e-01, 1.44666667e-01, 5.66666667e-02, 1.96666667e-02,
        4.00000000e-03, 3.33333333e-04]),
 'Y09': array([4.49000000e-01, 7.96666667e-02, 3.26666667e-02, 1.20000000e-02,
        2.33333333e-03, 3.33333333e-04]),
 'Y10': array([0.29133333, 0.08766667, 0.03033333, 0.00766667, 0.001     ,
        0.00033333]),
 'Y11': array([5.50333333e-01, 1.70000000e-01, 3.90000000e-02, 9.33333333e-03,
        1.66666667e-03, 3.33333333e-04]),
 'Y12': array([0.17966667, 0.05833333, 0.011     , 0.003     , 0.00033333,
        0.        ]),
 'Y13': array([0.25433333, 0.05866667, 0.013     , 0.00233333, 0.00033333,
        0.00033333]),
 'Y14': array([0.12566667, 0.03233333, 0.00433333, 0.001     , 0.00033333,
        0.        ]),
 'Y15': array([0.071     , 0.01033333, 0.        , 0.        , 0.        ,
        0.        ]),
 'Y16': array([0.04866667, 0.00566667, 0.00066667, 0.        , 0.        ,
        0.        ]),
 'Z01': array([0.96166667, 0.87933333, 0.659     , 0.54266667, 0.367     ,
        0.243     ]),
 'Z02': array([0.88733333, 0.66733333, 0.42      , 0.13966667, 0.063     ,
        0.02666667]),
 'Z03': array([0.81566667, 0.49266667, 0.25466667, 0.07266667, 0.03133333,
        0.01133333]),
 'Z04': array([0.892     , 0.63666667, 0.226     , 0.131     , 0.059     ,
        0.02      ]),
 'Z05': array([0.65666667, 0.262     , 0.06333333, 0.02666667, 0.00633333,
        0.00133333]),
 'Z06': array([0.562     , 0.286     , 0.11466667, 0.02766667, 0.007     ,
        0.00166667]),
 'Z07': array([0.478     , 0.14066667, 0.05766667, 0.017     , 0.00366667,
        0.00066667]),
 'Z08': array([5.12666667e-01, 5.66666667e-02, 1.63333333e-02, 5.33333333e-03,
        3.33333333e-04, 0.00000000e+00]),
 'Z09': array([0.48733333, 0.06      , 0.02466667, 0.01      , 0.003     ,
        0.001     ]),
 'Z10': array([5.22000000e-01, 1.73666667e-01, 6.76666667e-02, 1.30000000e-02,
        4.00000000e-03, 3.33333333e-04]),
 'Z11': array([0.438     , 0.18466667, 0.07866667, 0.01066667, 0.00266667,
        0.        ]),
 'Z12': array([3.43333333e-01, 5.96666667e-02, 5.66666667e-03, 2.00000000e-03,
        6.66666667e-04, 3.33333333e-04]),
 'Z13': array([0.108     , 0.04166667, 0.00433333, 0.001     , 0.00033333,
        0.        ]),
 'Z14': array([0.18433333, 0.03666667, 0.004     , 0.00033333, 0.        ,
        0.        ]),
 'Z15': array([0.11266667, 0.01833333, 0.00266667, 0.00033333, 0.        ,
        0.        ]),
 'Z16': array([0.03833333, 0.004     , 0.00066667, 0.        , 0.        ,
        0.        ])}

In [13]:
region_seed_to_id = dict(zip(df_seeds['Region Seed'], df_seeds['TeamID']))

df_model = pd.DataFrame({
    'Team': team_model_probs.keys()
})

df_model[[f'Round {i}' for i in range(1, 7)]] = np.array(tuple(df_model['Team'].map(team_model_probs)))

df_model.insert(1, 'TeamID', df_model['Team'].map(region_seed_to_id))

df_model.sort_values(by=['Round 6'], ascending=False, inplace=True, ignore_index=True)

df_model.head(10)

  Team  TeamID   Round 1   Round 2   Round 3   Round 4   Round 5   Round 6
0  W01    1163  0.963000  0.850000  0.649000  0.509667  0.394333  0.273333
1  Z01    1222  0.961667  0.879333  0.659000  0.542667  0.367000  0.243000
2  Y01    1345  0.951333  0.770000  0.550333  0.369000  0.210333  0.101000
3  X02    1112  0.935000  0.727000  0.468333  0.255000  0.107000  0.046667
4  W04    1120  0.748333  0.576000  0.220667  0.149000  0.082667  0.035000
5  Y03    1166  0.874333  0.673333  0.345000  0.171333  0.082000  0.034333
6  Y02    1397  0.929000  0.659667  0.427000  0.205333  0.086000  0.030667
7  X01    1314  0.908000  0.618000  0.335000  0.193333  0.070333  0.027000
8  Z02    1266  0.887333  0.667333  0.420000  0.139667  0.063000  0.026667
9  X03    1124  0.879667  0.566000  0.267333  0.135000  0.056667  0.024000

In [14]:
df_teams = pd.read_csv(r'..\data\unprocessed\kaggle\MTeams.csv')

df_teams

     TeamID        TeamName  FirstD1Season  LastD1Season
0      1101     Abilene Chr           2014          2025
1      1102       Air Force           1985          2025
2      1103           Akron           1985          2025
3      1104         Alabama           1985          2025
4      1105     Alabama A&M           2000          2025
..      ...             ...            ...           ...
375    1476       Stonehill           2023          2025
376    1477  East Texas A&M           2023          2025
377    1478        Le Moyne           2024          2025
378    1479      Mercyhurst           2025          2025
379    1480    West Georgia           2025          2025

[380 rows x 4 columns]

In [15]:
id_to_team = dict(zip(df_teams['TeamID'], df_teams['TeamName']))

df_model.insert(df_model.columns.get_loc('TeamID') + 1, 'Name', df_model['TeamID'].map(id_to_team))

df_model.head(25)

,Team,TeamID,Name,Round 1,Round 2,Round 3,Round 4,Round 5,Round 6
0,W01,1163,Connecticut,0.963000,0.850000,0.649000,0.509667,0.394333,0.273333
1,Z01,1222,Houston,0.961667,0.879333,0.659000,0.542667,0.367000,0.243000
2,Y01,1345,Purdue,0.951333,0.770000,0.550333,0.369000,0.210333,0.101000
3,X02,1112,Arizona,0.935000,0.727000,0.468333,0.255000,0.107000,0.046667
4,W04,1120,Auburn,0.748333,0.576000,0.220667,0.149000,0.082667,0.035000
5,Y03,1166,Creighton,0.874333,0.673333,0.345000,0.171333,0.082000,0.034333
6,Y02,1397,Tennessee,0.929000,0.659667,0.427000,0.205333,0.086000,0.030667
7,X01,1314,North Carolina,0.908000,0.618000,0.335000,0.193333,0.070333,0.027000
8,Z02,1266,Marquette,0.887333,0.667333,0.420000,0.139667,0.063000,0.026667
9,X03,1124,Baylor,0.879667,0.566000,0.267333,0.135000,0.056667,0.024000
10,W02,1235,Iowa St,0.914000,0.679333,0.413000,0.134333,0.067333,0.023667
11,X04,1104,Alabama,0.856333,0.508667,0.283333,0.155667,0.060333,0.023000
12,W03,1228,Illinois,0.854000,0.590333,0.322333,0.098667,0.052333,0.020333
13,Z04,1181,Duke,0.892000,0.636667,0.226000,0.131000,0.059000,0.020000
14,Y05,1211,Gonzaga,0.820333,0.524667,0.213667,0.105667,0.041333,0.016333
15,Z03,1246,Kentucky,0.815667,0.492667,0.254667,0.072667,0.031333,0.011333
16,X05,1388,St Mary's CA,0.612000,0.344333,0.196333,0.087333,0.027000,0.008333
17,Y04,1242,Kansas,0.745667,0.358333,0.122000,0.043000,0.011667,0.005000
18,X09,1277,Michigan St,0.611333,0.244333,0.099667,0.043667,0.014000,0.004333
19,W06,1140,BYU,0.573667,0.274667,0.114333,0.024667,0.009000,0.004000
20,X06,1155,Clemson,0.610333,0.243667,0.087333,0.034667,0.010333,0.003333
21,Y07,1400,Texas,0.708667,0.242333,0.115333,0.042000,0.009333,0.003000
22,W05,1361,San Diego St,0.793000,0.312000,0.073667,0.038000,0.015333,0.002667
23,Z06,1403,Texas Tech,0.562000,0.286000,0.114667,0.027667,0.007000,0.001667
24,X11,1307,New Mexico,0.389667,0.168000,0.056000,0.025333,0.008333,0.001667

Get public brackets

In [16]:
df_public = pd.read_parquet(f'..\data\preprocessed\mens_yahoo\yahoo_picks_{season}.parquet')

df_public.sort_values(by=['Round 6'], ascending=False, ignore_index=True).head(10)

,Team,TeamID,Region Seed,Seed,Region,Play In,Round 1,Round 2,Round 3,Round 4,Round 5,Round 6
0,Connecticut,1163,W01,1,W,False,0.9841,0.9359,0.8022,0.6620,0.5027,0.3492
1,Houston,1222,Z01,1,Z,False,0.9701,0.8569,0.6625,0.4540,0.2998,0.1210
2,Purdue,1345,Y01,1,Y,False,0.9708,0.8807,0.6377,0.4254,0.2164,0.1022
3,N. Carolina,1314,X01,1,X,False,0.9755,0.8621,0.7116,0.4436,0.1615,0.0927
4,Arizona,1112,X02,2,X,False,0.9519,0.8492,0.5984,0.3025,0.1005,0.0478
5,Kentucky,1246,Z03,3,Z,False,0.9467,0.7358,0.4828,0.2201,0.1093,0.0406
6,Tennessee,1397,Y02,2,Y,False,0.9433,0.7816,0.5202,0.2226,0.0999,0.0348
7,Iowa St.,1235,W02,2,W,False,0.9549,0.8105,0.4960,0.1215,0.0647,0.0302
8,Marquette,1266,Z02,2,Z,False,0.9354,0.7310,0.3368,0.1338,0.0579,0.0196
9,Kansas,1242,Y04,4,Y,False,0.8319,0.4478,0.1593,0.0837,0.0394,0.0183

R1X1: (1, 16)
R2X1: (1, 8, 9, 16)
R3X1: (1, 4, 5, 8, 9, 12, 13, 16)
R4X1: (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)

R1X2: (2, 15)
R2X2: (2, 7, 10, 15)
R3X2: (2, 3, 6, 7, 10, 11, 14, 15)

R1X3: (3, 14)
R2X3: (3, 6, 11, 14)

R1X4: (4, 13)
R2X4: (4, 5, 12, 13)

R1X5: (5, 12)

R1X6: (6, 11)

R1X7: (7, 10)

R1X8: (8, 9)

Partition data into possible areas in advance

In [17]:
public_dict = {
    # ROUND 6
    'R6CH': df_public.loc[:, ['Region Seed', 'Region', 'Seed', 'Round 6']].rename(columns={'Round 6': 'P'}).reset_index(drop=True),

    # ROUND 5
    'R5WX': df_public.loc[df_public['Region'].isin(('W', 'X')), ['Region Seed', 'Region', 'Seed', 'Round 5']].rename(columns={'Round 5': 'P'}).reset_index(drop=True),
    'R5YZ': df_public.loc[df_public['Region'].isin(('Y', 'Z')), ['Region Seed', 'Region', 'Seed', 'Round 5']].rename(columns={'Round 5': 'P'}).reset_index(drop=True),
}

# ROUND 4
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R4{region}1'] = df_public.loc[df_public['Region'] == region, ['Region Seed', 'Region', 'Seed', 'Round 4']].rename(columns={'Round 4': 'P'}).reset_index(drop=True)

# ROUND 3
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R3{region}1'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((1, 4, 5, 8, 9, 12, 13, 16))), ['Region Seed', 'Region', 'Seed', 'Round 3']].rename(columns={'Round 3': 'P'}).reset_index(drop=True)
    public_dict[f'R3{region}2'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((2, 3, 6, 7, 10, 11, 14, 15))), ['Region Seed', 'Region', 'Seed', 'Round 3']].rename(columns={'Round 3': 'P'}).reset_index(drop=True)

# ROUND 2
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R2{region}1'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((1, 8, 9, 16))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}2'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((2, 7, 10, 15))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}3'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((3, 6, 11, 14))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}4'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((4, 5, 12, 13))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)

# ROUND 1
for region in ('W', 'X', 'Y', 'Z'):
    for i in range(1, 9):
        public_dict[f'R1{region}{i}'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((i, 17-i))), ['Region Seed', 'Region', 'Seed', 'Round 1']].rename(columns={'Round 1': 'P'}).reset_index(drop=True)

for key, value in public_dict.items():  # make sure probabilities add to 1
    # print(value['P'].sum())

    value['P'] = value['P']/value['P'].sum()
    public_dict[key] = value

    # print(value['P'].sum())
    # print()

public_dict

{'R6CH':    Region Seed Region  Seed         P
 0          Y14      Y    14  0.000400
 1          X04      X     4  0.005499
 2          X02      X     2  0.047790
 3          W04      W     4  0.017297
 4          Z10      Z    10  0.000500
 ..         ...    ...   ...       ...
 59         Z15      Z    15  0.000300
 60         X16      X    16  0.000600
 61         W07      W     7  0.001000
 62         Z05      Z     5  0.004799
 63         W13      W    13  0.001600

 [64 rows x 4 columns],
 'R5WX':    Region Seed Region  Seed         P
 0          X04      X     4  0.014104
 1          X02      X     2  0.100530
 2          W04      W     4  0.036411
 3          W06      W     6  0.003301
 4          X03      X     3  0.028909
 5          X13      X    13  0.000800
 6          X06      X     6  0.004801
 7          X14      X    14  0.000800
 8          W01      W     1  0.502851
 9          X07      X     7  0.001701
 10         W10      W    10  0.001600
 11         W11      W    11  0.000900
 12         W08      W     8  0.002001
 13         X12      X    12  0.001100
 14         W03      W     3  0.038612
 15         W02      W     2  0.064719
 16         X15      X    15  0.001100
 17         X09      X     9  0.006402
 18         X08      X     8  0.001400
 19         W14      W    14  0.000800
 20         X01      X     1  0.161548
 21         X10      X    10  0.001100
 22         X11      X    11  0.001801
 23         W09      W     9  0.001701
 24         W15      W    15  0.000800
 25         W05      W     5  0.006202
 26         X05      X     5  0.006102
 27         W16      W    16  0.001000
 28         W12      W    12  0.001000
 29         X16      X    16  0.001300
 30         W07      W     7  0.002101
 31         W13      W    13  0.002501,
 'R5YZ':    Region Seed Region  Seed         P
 0          Y14      Y    14  0.000901
 1          Z10      Z    10  0.001601
 2          Y10      Y    10  0.001001
 3          Y03      Y     3  0.043535
 4          Z04      Z     4  0.039331
 5          Z07      Z     7  0.006405
 6          Y05      Y     5  0.026421
 7          Z01      Z     1  0.300040
 8          Z12      Z    12  0.002302
 9          Y04      Y     4  0.039432
 10         Z03      Z     3  0.109388
 11         Z16      Z    16  0.001101
 12         Y16      Y    16  0.000701
 13         Z02      Z     2  0.057946
 14         Y12      Y    12  0.001501
 15         Z11      Z    11  0.006205
 16         Z08      Z     8  0.003002
 17         Z14      Z    14  0.000801
 18         Y11      Y    11  0.004003
 19         Y01      Y     1  0.216573
 20         Y13      Y    13  0.001001
 21         Y06      Y     6  0.004003
 22         Y15      Y    15  0.001101
 23         Y09      Y     9  0.001801
 24         Y02      Y     2  0.099980
 25         Y07      Y     7  0.009207
 26         Z09      Z     9  0.002602
 27         Z06      Z     6  0.003803
 28         Y08      Y     8  0.001501
 29         Z13      Z    13  0.000801
 30         Z15      Z    15  0.000701
 31         Z05      Z     5  0.011309,
 'R4W1':    Region Seed Region  Seed         P
 0          W04      W     4  0.073254
 1          W06      W     6  0.015032
 2          W01      W     1  0.663393
 3          W10      W    10  0.003908
 4          W11      W    11  0.002205
 5          W08      W     8  0.004910
 6          W03      W     3  0.079667
 7          W02      W     2  0.121756
 8          W14      W    14  0.001804
 9          W09      W     9  0.004209
 10         W15      W    15  0.001704
 11         W05      W     5  0.014931
 12         W16      W    16  0.001904
 13         W12      W    12  0.002405
 14         W07      W     7  0.005111
 15         W13      W    13  0.003808,
 'R4X1':    Region Seed Region  Seed         P
 0          X04      X     4  0.052245
 1          X02      X     2  0.304510
 2          X03      X     3  0.105798
 3          X13      X    13  0.001913
 4          X06      X     6  0.013892
 5          X14      X    14  0.003423
 6          X07      X     7  0.005637
 7          X12      X    12  0.003523
 8          X15      X    15  0.002416
 9          X09      X     9  0.015905
 10         X08      X     8  0.005033
 11         X01      X     1  0.446547
 12         X10      X    10  0.004027
 13         X11      X    11  0.007952
 14         X05      X     5  0.024059
 15         X16      X    16  0.003121,
 'R4Y1':    Region Seed Region  Seed         P
 0          Y14      Y    14  0.001916
 1          Y10      Y    10  0.003731
 2          Y03      Y     3  0.128076
 3          Y05      Y     5  0.062727
 4          Y04      Y     4  0.084409
 5          Y16      Y    16  0.001815
 6          Y12      Y    12  0.004538
 7          Y11      Y    11  0.010690
 8          Y01      Y     1  0.429004
 9          Y13      Y    13  0.002521
 10         Y06      Y     6  0.011597
 11         Y15      Y    15  0.002420
 12         Y09      Y     9  0.005042
 13         Y02      Y     2  0.224486
 14         Y07      Y     7  0.022892
 15         Y08      Y     8  0.004135,
 'R4Z1':    Region Seed Region  Seed         P
 0          Z10      Z    10  0.002421
 1          Z04      Z     4  0.082501
 2          Z07      Z     7  0.016541
 3          Z01      Z     1  0.457892
 4          Z12      Z    12  0.005547
 5          Z03      Z     3  0.221987
 6          Z16      Z    16  0.002118
 7          Z02      Z     2  0.134947
 8          Z11      Z    11  0.014019
 9          Z08      Z     8  0.006959
 10         Z14      Z    14  0.001916
 11         Z09      Z     9  0.006858
 12         Z06      Z     6  0.010893
 13         Z13      Z    13  0.002017
 14         Z15      Z    15  0.001815
 15         Z05      Z     5  0.031568,
 'R3W1':   Region Seed Region  Seed         P
 0         W04      W     4  0.121941
 1         W01      W     1  0.804452
 2         W08      W     8  0.010630
 3         W09      W     9  0.010529
 4         W05      W     5  0.036602
 5         W16      W    16  0.003309
 6         W12      W    12  0.005616
 7         W13      W    13  0.006919,
 'R3W2':   Region Seed Region  Seed         P
 0         W06      W     6  0.076228
 1         W10      W    10  0.022898
 2         W11      W    11  0.009039
 3         W03      W     3  0.356533
 4         W02      W     2  0.498142
 5         W14      W    14  0.006428
 6         W15      W    15  0.005423
 7         W07      W     7  0.025309,
 'R3X1':   Region Seed Region  Seed         P
 0         X04      X     4  0.136455
 1         X13      X    13  0.005136
 2         X12      X    12  0.010272
 3         X09      X     9  0.040685
 4         X08      X     8  0.015509
 5         X01      X     1  0.716616
 6         X05      X     5  0.069688
 7         X16      X    16  0.005639,
 'R3X2':   Region Seed Region  Seed         P
 0         X02      X     2  0.604017
 1         X03      X     3  0.259110
 2         X06      X     6  0.053800
 3         X14      X    14  0.006965
 4         X07      X     7  0.021096
 5         X15      X    15  0.006359
 6         X10      X    10  0.016756
 7         X11      X    11  0.031897,
 'R3Y1':   Region Seed Region  Seed         P
 0         Y05      Y     5  0.135550
 1         Y04      Y     4  0.161023
 2         Y16      Y    16  0.003336
 3         Y12      Y    12  0.015971
 4         Y01      Y     1  0.644597
 5         Y13      Y    13  0.006570
 6         Y09      Y     9  0.018397
 7         Y08      Y     8  0.014556,
 'R3Y2':   Region Seed Region  Seed         P
 0         Y14      Y    14  0.004938
 1         Y10      Y    10  0.010983
 2         Y03      Y     3  0.297158
 3         Y11      Y    11  0.037686
 4         Y06      Y     6  0.043833
 5         Y15      Y    15  0.006852
 6         Y02      Y     2  0.524184
 7         Y07      Y     7  0.074365,
 'R3Z1':   Region Seed Region  Seed         P
 0         Z04      Z     4  0.190073
 1         Z01      Z     1  0.668382
 2         Z12      Z    12  0.015738
 3         Z16      Z    16  0.003834
 4         Z08      Z     8  0.018866
 5         Z09      Z     9  0.020884
 6         Z13      Z    13  0.004944
 7         Z05      Z     5  0.077280,
 'R3Z2':   Region Seed Region  Seed         P
 0         Z10      Z    10  0.007780
 1         Z07      Z     7  0.061534
 2         Z03      Z     3  0.487825
 3         Z02      Z     2  0.340305
 4         Z11      Z    11  0.042437
 5         Z14      Z    14  0.004850
 6         Z06      Z     6  0.050419
 7         Z15      Z    15  0.004850,
 'R2W1':   Region Seed Region  Seed         P
 0         W01      W     1  0.939093
 1         W08      W     8  0.024483
 2         W09      W     9  0.029801
 3         W16      W    16  0.006623,
 'R2W2':   Region Seed Region  Seed         P
 0         W10      W    10  0.082755
 1         W02      W     2  0.814982
 2         W15      W    15  0.014681
 3         W07      W     7  0.087582,
 'R2W3':   Region Seed Region  Seed         P
 0         W06      W     6  0.218244
 1         W11      W    11  0.039626
 2         W03      W     3  0.714774
 3         W14      W    14  0.027356,
 'R2W4':   Region Seed Region  Seed         P
 0         W04      W     4  0.650407
 1         W05      W     5  0.274565
 2         W12      W    12  0.038218
 3         W13      W    13  0.036810,
 'R2X1':   Region Seed Region  Seed         P
 0         X09      X     9  0.083618
 1         X08      X     8  0.038036
 2         X01      X     1  0.867478
 3         X16      X    16  0.010867,
 'R2X2':   Region Seed Region  Seed         P
 0         X02      X     2  0.858298
 1         X07      X     7  0.068324
 2         X15      X    15  0.016374
 3         X10      X    10  0.057004,
 'R2X3':   Region Seed Region  Seed         P
 0         X03      X     3  0.664172
 1         X06      X     6  0.154461
 2         X14      X    14  0.020129
 3         X11      X    11  0.161238,
 'R2X4':   Region Seed Region  Seed         P
 0         X04      X     4  0.563784
 1         X13      X    13  0.030046
 2         X12      X    12  0.077289
 3         X05      X     5  0.328882,
 'R2Y1':   Region Seed Region  Seed         P
 0         Y16      Y    16  0.006783
 1         Y01      Y     1  0.891668
 2         Y09      Y     9  0.062063
 3         Y08      Y     8  0.039486,
 'R2Y2':   Region Seed Region  Seed         P
 0         Y10      Y    10  0.038392
 1         Y15      Y    15  0.017497
 2         Y02      Y     2  0.781444
 3         Y07      Y     7  0.162667,
 'R2Y3':   Region Seed Region  Seed         P
 0         Y14      Y    14  0.018033
 1         Y03      Y     3  0.682200
 2         Y11      Y    11  0.151758
 3         Y06      Y     6  0.148009,
 'R2Y4':   Region Seed Region  Seed         P
 0         Y05      Y     5  0.421133
 1         Y04      Y     4  0.453652
 2         Y12      Y    12  0.094519
 3         Y13      Y    13  0.030696,
 'R2Z1':   Region Seed Region  Seed         P
 0         Z01      Z     1  0.865468
 1         Z16      Z    16  0.008383
 2         Z08      Z     8  0.063024
 3         Z09      Z     9  0.063125,
 'R2Z2':   Region Seed Region  Seed         P
 0         Z10      Z    10  0.034626
 1         Z07      Z     7  0.203199
 2         Z02      Z     2  0.740103
 3         Z15      Z    15  0.022071,
 'R2Z3':   Region Seed Region  Seed         P
 0         Z03      Z     3  0.744059
 1         Z11      Z    11  0.113358
 2         Z14      Z    14  0.014056
 3         Z06      Z     6  0.128527,
 'R2Z4':   Region Seed Region  Seed        P
 0         Z04      Z     4  0.60637
 1         Z12      Z    12  0.10546
 2         Z13      Z    13  0.01911
 3         Z05      Z     5  0.26906,
 'R1W1':   Region Seed Region  Seed         P
 0         W01      W     1  0.984986
 1         W16      W    16  0.015014,
 'R1W2':   Region Seed Region  Seed         P
 0         W02      W     2  0.959602
 1         W15      W    15  0.040398,
 'R1W3':   Region Seed Region  Seed         P
 0         W03      W     3  0.928068
 1         W14      W    14  0.071932,
 'R1W4':   Region Seed Region  Seed         P
 0         W04      W     4  0.906869
 1         W13      W    13  0.093131,
 'R1W5':   Region Seed Region  Seed         P
 0         W05      W     5  0.788737
 1         W12      W    12  0.211263,
 'R1W6':   Region Seed Region  Seed         P
 0         W06      W     6  0.757609
 1         W11      W    11  0.242391,
 'R1W7':   Region Seed Region  Seed         P
 0         W10      W    10  0.570132
 1         W07      W     7  0.429868,
 'R1W8':   Region Seed Region  Seed         P
 0         W08      W     8  0.557917
 1         W09      W     9  0.442083,
 'R1X1':   Region Seed Region  Seed         P
 0         X01      X     1  0.975793
 1         X16      X    16  0.024207,
 'R1X2':   Region Seed Region  Seed         P
 0         X02      X     2  0.962487
 1         X15      X    15  0.037513,
 'R1X3':   Region Seed Region  Seed         P
 0         X03      X     3  0.935373
 1         X14      X    14  0.064627,
 'R1X4':   Region Seed Region  Seed         P
 0         X04      X     4  0.882752
 1         X13      X    13  0.117248,
 'R1X5':   Region Seed Region  Seed         P
 0         X12      X    12  0.259278
 1         X05      X     5  0.740722,
 'R1X6':   Region Seed Region  Seed         P
 0         X06      X     6  0.521907
 1         X11      X    11  0.478093,
 'R1X7':   Region Seed Region  Seed         P
 0         X07      X     7  0.450365
 1         X10      X    10  0.549635,
 'R1X8':   Region Seed Region  Seed         P
 0         X09      X     9  0.649062
 1         X08      X     8  0.350938,
 'R1Y1':   Region Seed Region  Seed         P
 0         Y16      Y    16  0.017508
 1         Y01      Y     1  0.982492,
 'R1Y2':   Region Seed Region  Seed         P
 0         Y15      Y    15  0.043791
 1         Y02      Y     2  0.956209,
 'R1Y3':   Region Seed Region  Seed         P
 0         Y14      Y    14  0.072698
 1         Y03      Y     3  0.927302,
 'R1Y4':   Region Seed Region  Seed        P
 0         Y04      Y     4  0.84474
 1         Y13      Y    13  0.15526,
 'R1Y5':   Region Seed Region  Seed         P
 0         Y05      Y     5  0.807657
 1         Y12      Y    12  0.192343,
 'R1Y6':   Region Seed Region  Seed         P
 0         Y11      Y    11  0.483421
 1         Y06      Y     6  0.516579,
 'R1Y7':   Region Seed Region  Seed         P
 0         Y10      Y    10  0.180373
 1         Y07      Y     7  0.819627,
 'R1Y8':   Region Seed Region  Seed         P
 0         Y09      Y     9  0.581502
 1         Y08      Y     8  0.418498,
 'R1Z1':   Region Seed Region  Seed         P
 0         Z01      Z     1  0.978713
 1         Z16      Z    16  0.021287,
 'R1Z2':   Region Seed Region  Seed         P
 0         Z02      Z     2  0.946091
 1         Z15      Z    15  0.053909,
 'R1Z3':   Region Seed Region  Seed         P
 0         Z03      Z     3  0.958101
 1         Z14      Z    14  0.041899,
 'R1Z4':   Region Seed Region  Seed         P
 0         Z04      Z     4  0.922571
 1         Z13      Z    13  0.077429,
 'R1Z5':   Region Seed Region  Seed         P
 0         Z12      Z    12  0.328706
 1         Z05      Z     5  0.671294,
 'R1Z6':   Region Seed Region  Seed         P
 0         Z11      Z    11  0.441773
 1         Z06      Z     6  0.558227,
 'R1Z7':   Region Seed Region  Seed         P
 0         Z10      Z    10  0.233625
 1         Z07      Z     7  0.766375,
 'R1Z8':   Region Seed Region  Seed         P
 0         Z08      Z     8  0.502079
 1         Z09      Z     9  0.497921}

In [18]:
def fill_in_team(bracket: dict, round_: int, team: str, region: str, seed: int) -> dict:
    """
    Helper for simulate_public
    Fill in previous rounds of bracket for a team that wins in a future round
    """
    for r in range(1, min(round_ + 1, 4)):
        if seed > 2**(4-r):
            seed = 2**(5-r) + 1 - seed
        bracket[f'R{r}{region}{seed}'] = team

    if round_ >= 4:
        bracket[f'R4{region}1'] = team
    if round_ >= 5:
        if region in ('W', 'X'):
            bracket[f'R5WX'] = team
        else:
            bracket[f'R5YZ'] = team
    if round_ == 6:
        bracket[f'R6CH'] = team

    return bracket


def simulate_public():
    """
    Get bracket based on probabilities of winning each round
    """
    bracket = dict()

    # ROUND 6
    for matchup in ('R6CH', ):
        if not bracket.get(matchup):
            df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
            winner = df_matchup.loc[
                np.random.choice(
                    df_matchup.index,
                    p=df_matchup['P'],
                ),
                :
            ]
            bracket = fill_in_team(bracket, 6, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 5
    for matchup in ('R5WX', 'R5YZ'):
        if not bracket.get(matchup):
            df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
            winner = df_matchup.loc[
                np.random.choice(
                    df_matchup.index,
                    p=df_matchup['P'],
                ),
                :
            ]
            bracket = fill_in_team(bracket, 5, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 4
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 2):
            matchup = f'R4{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 4, winner['Region Seed'], winner['Region'], winner['Seed'])



    # ROUND 3
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 3):
            matchup = f'R3{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 3, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 2
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 5):
            matchup = f'R2{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 2, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 1
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 9):
            matchup = f'R1{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 1, winner['Region Seed'], winner['Region'], winner['Seed'])

    return dict(sorted(bracket.items()))

simulate_public()

{'R1W1': 'W01',
 'R1W2': 'W02',
 'R1W3': 'W03',
 'R1W4': 'W04',
 'R1W5': 'W05',
 'R1W6': 'W11',
 'R1W7': 'W07',
 'R1W8': 'W09',
 'R1X1': 'X01',
 'R1X2': 'X02',
 'R1X3': 'X03',
 'R1X4': 'X04',
 'R1X5': 'X05',
 'R1X6': 'X06',
 'R1X7': 'X10',
 'R1X8': 'X09',
 'R1Y1': 'Y01',
 'R1Y2': 'Y02',
 'R1Y3': 'Y03',
 'R1Y4': 'Y04',
 'R1Y5': 'Y05',
 'R1Y6': 'Y11',
 'R1Y7': 'Y07',
 'R1Y8': 'Y09',
 'R1Z1': 'Z01',
 'R1Z2': 'Z02',
 'R1Z3': 'Z03',
 'R1Z4': 'Z04',
 'R1Z5': 'Z05',
 'R1Z6': 'Z06',
 'R1Z7': 'Z07',
 'R1Z8': 'Z08',
 'R2W1': 'W01',
 'R2W2': 'W02',
 'R2W3': 'W03',
 'R2W4': 'W04',
 'R2X1': 'X01',
 'R2X2': 'X02',
 'R2X3': 'X03',
 'R2X4': 'X04',
 'R2Y1': 'Y01',
 'R2Y2': 'Y02',
 'R2Y3': 'Y03',
 'R2Y4': 'Y05',
 'R2Z1': 'Z01',
 'R2Z2': 'Z02',
 'R2Z3': 'Z03',
 'R2Z4': 'Z04',
 'R3W1': 'W01',
 'R3W2': 'W03',
 'R3X1': 'X01',
 'R3X2': 'X02',
 'R3Y1': 'Y01',
 'R3Y2': 'Y02',
 'R3Z1': 'Z04',
 'R3Z2': 'Z02',
 'R4W1': 'W01',
 'R4X1': 'X01',
 'R4Y1': 'Y02',
 'R4Z1': 'Z02',
 'R5WX': 'W01',
 'R5YZ': 'Z02',
 'R6CH': 'W01'}

In [19]:
np.random.seed(24)

public_brackets = tuple(simulate_public() for _ in trange(2_000))  # set back to 20_000

len(public_brackets)

  0%|          | 0/2000 [00:00<?, ?it/s]

2000

In [20]:
np.random.seed(25)

public_candidates = tuple(simulate_public() for _ in trange(2_000))  # set back to 20_000

len(public_candidates)

  0%|          | 0/2000 [00:00<?, ?it/s]

2000

In [21]:
simulation_data = {
    'results': results,
    'candidates': my_candidates + public_candidates,
    'public': public_brackets,
}

len(simulation_data)

3

In [22]:
import pickle

with open(f'../data/simulations/mens/mens_simulation_{season}.pkl', 'wb') as f:
    pickle.dump(simulation_data, f)

'Done'

'Done'