# Simulate Men's Tourney

Generated brackets based on model probabilities and public picks.

In [1]:
import json

with open(f'../data/meta/mens/metadata.json', "r") as file:
    json_data = json.load(file)

SEASON = json_data['SEASON']
playin_losers = json_data['season_data'][str(SEASON)]['playin_losers']

SEASON, playin_losers

(2025, [1384, 1291, 1361, 1400])

### Load Data

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 100)

df_seeds = pd.read_csv(r'..\data\unprocessed\kaggle\MNCAATourneySeeds.csv')

df_seeds = df_seeds.loc[df_seeds['Season'] == SEASON, :].reset_index(drop=True)

df_seeds.insert(2, 'Play In', df_seeds['Seed'].str.endswith(('a', 'b')))
df_seeds.insert(2, 'Region', df_seeds['Seed'].str[0])
df_seeds['Seed'] = df_seeds['Seed'].str.extract('(\d+)').astype(int)

df_seeds = df_seeds.loc[~df_seeds['TeamID'].isin(playin_losers), :].reset_index(drop=True)

df_seeds.insert(1, 'Region Seed', df_seeds['Region'] + df_seeds['Seed'].astype(str).str.zfill(2))

df_seeds

    Season Region Seed  Seed Region  Play In  TeamID
0     2025         W01     1      W    False    1181
1     2025         W02     2      W    False    1104
2     2025         W03     3      W    False    1458
3     2025         W04     4      W    False    1112
4     2025         W05     5      W    False    1332
..     ...         ...   ...    ...      ...     ...
59    2025         Z12    12      Z    False    1161
60    2025         Z13    13      Z    False    1213
61    2025         Z14    14      Z    False    1423
62    2025         Z15    15      Z    False    1303
63    2025         Z16    16      Z    False    1313

[64 rows x 6 columns]

In [3]:
df_matrix = pd.read_csv(
    fr'../data/simulations/mens/matchup_matrix_{SEASON}.csv',
    index_col='Team A ID',
).rename_axis(index=None)

df_matrix.columns = df_matrix.columns.astype(int)

df_matrix

,1103,1104,1106,1110,1112,1116,1120,1124,1136,1140,1155,1161,1163,1166,1179,1181,1188,1196,1208,1211,1213,1219,1222,1228,1235,1242,1246,1251,1252,1257,1266,1268,1270,1272,1276,1277,1279,1280,1281,1285,1303,1307,1313,1314,1328,1332,1345,1352,1385,1388,1397,1401,1403,1407,1417,1423,1429,1433,1435,1458,1459,1462,1463,1471
1103,NaN,0.218855,0.814330,0.747846,0.130761,0.378076,0.108685,0.227940,0.400273,0.162867,0.141767,0.217477,0.182613,0.152973,0.433833,0.068494,0.708379,0.122202,0.206690,0.093120,0.385600,0.492275,0.069799,0.212648,0.198045,0.119670,0.161474,0.590858,0.661924,0.161206,0.118439,0.097387,0.300348,0.276252,0.171951,0.154397,0.243739,0.200797,0.127840,0.587032,0.656595,0.283579,0.623069,0.152199,0.271491,0.268023,0.184938,0.598475,0.120288,0.141557,0.075853,0.162088,0.106496,0.461942,0.225625,0.652260,0.384147,0.186827,0.286238,0.200268,0.754994,0.340162,0.511514,0.375963
1104,0.773840,NaN,0.895708,0.873932,0.554941,0.791982,0.365387,0.663334,0.920285,0.567786,0.567572,0.871512,0.819175,0.865018,0.887773,0.219921,0.921878,0.253007,0.666295,0.659649,0.915527,0.897161,0.305743,0.592925,0.761049,0.640653,0.739727,0.900529,0.896616,0.606808,0.509090,0.595208,0.899091,0.836064,0.558095,0.635498,0.761060,0.782011,0.778688,0.934768,0.935407,0.801104,0.949688,0.765542,0.891663,0.779390,0.583837,0.949091,0.518280,0.579855,0.471348,0.497814,0.448000,0.894360,0.716078,0.918126,0.926590,0.663348,0.886933,0.535712,0.883818,0.920449,0.881328,0.727097
1106,0.162046,0.090486,NaN,0.601517,0.043280,0.076725,0.074367,0.070406,0.187017,0.075485,0.117125,0.054602,0.099082,0.085230,0.126404,0.042574,0.423595,0.073230,0.051730,0.054667,0.110506,0.229729,0.045400,0.078741,0.073297,0.052883,0.068444,0.110275,0.148377,0.068074,0.041425,0.039706,0.078537,0.060967,0.074181,0.055188,0.083331,0.071666,0.058588,0.361113,0.331485,0.060918,0.271723,0.081803,0.081441,0.073306,0.056867,0.316398,0.056785,0.046170,0.066434,0.064029,0.067799,0.168806,0.103732,0.291040,0.137233,0.044921,0.062529,0.102626,0.404787,0.075956,0.128954,0.052860
1110,0.250457,0.120929,0.318411,NaN,0.050041,0.064909,0.047914,0.059204,0.411813,0.071242,0.057674,0.075373,0.061219,0.078504,0.103918,0.040944,0.464864,0.041666,0.080625,0.052089,0.084680,0.162147,0.033339,0.119439,0.067295,0.058435,0.082228,0.212605,0.255123,0.056002,0.083024,0.037071,0.069659,0.059988,0.093531,0.061328,0.080230,0.061903,0.065160,0.426689,0.352620,0.072665,0.345300,0.062826,0.072896,0.057413,0.063061,0.399764,0.044992,0.042264,0.068014,0.088811,0.068316,0.108859,0.082905,0.200782,0.184222,0.061313,0.076997,0.074019,0.430693,0.065576,0.125009,0.046498
1112,0.845163,0.411177,0.938787,0.939241,NaN,0.804638,0.235308,0.496646,0.868259,0.571583,0.372627,0.748614,0.664762,0.625196,0.855499,0.245570,0.931439,0.409921,0.570094,0.403422,0.861654,0.877436,0.217001,0.597953,0.679849,0.458624,0.521171,0.702235,0.885786,0.685157,0.430736,0.528988,0.847090,0.795267,0.696764,0.354440,0.646363,0.681545,0.453841,0.882985,0.904607,0.670231,0.918894,0.709664,0.751192,0.627955,0.454033,0.910176,0.550072,0.532861,0.290509,0.364034,0.418512,0.932662,0.519803,0.916217,0.717572,0.624988,0.662555,0.660604,0.893110,0.798711,0.813411,0.828993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458,0.757623,0.413574,0.889539,0.933357,0.389597,0.563831,0.176939,0.567463,0.836870,0.399985,0.452579,0.810910,0.556216,0.694846,0.805801,0.131407,0.926998,0.242592,0.339952,0.484925,0.782435,0.774019,0.096336,0.405367,0.563077,0.381417,0.530826,0.713493,0.843486,0.547589,0.332267,0.543858,0.785996,0.719824,0.468229,0.477838,0.648739,0.572130,0.490507,0.896755,0.910793,0.585822,0.904038,0.616691,0.578651,0.555757,0.417935,0.896250,0.461686,0.506062,0.367603,0.415326,0.358168,0.894365,0.574859,0.894545,0.620202,0.415111,0.583795,NaN,0.850984,0.858708,0.841387,0.799863
1459,0.272956,0.101510,0.547588,0.528198,0.091922,0.146276,0.079652,0.119507,0.501316,0.135489,0.090872,0.199105,0.215190,0.251583,0.157788,0.044355,0.646531,0.068643,0.080932,0.105458,0.412377,0.284683,0.050626,0.101919,0.087757,0.051895,0.094116,0.277525,0.385499,0.117829,0.108639,0.071064,0.173251,0.114310,0.092306,0.071578,0.112218,0.113552,0.123171,0.541519,0.588619,0.201917,0.603193,0.188011,0.149379,0.139481,0.119077,0.527786,0.060389,0.075455,0.063781,0.057323,0.081840,0.394463,0.116754,0.501964,0.205338,0.107304,0.197933,0.149534,NaN,0.221858,0.342480,0.164765
1462,0.569405,0.140659,0.904838,0.907942,0.195364,0.241946,0.094090,0.182640,0.758426,0.298410,0.339912,0.493447,0.249896,0.313914,0.487645,0.090629,0.889758,0.173381,0.340013,0.225959,0.664067,0.608330,0.046280,0.297295,0.156302,0.239978,0.244218,0.522518,0.607509,0.371278,0.278436,0.254177,0.486399,0.502750,0.383349,0.155088,0.312732,0.331275,0.353071,0.800781,0.885380,0.526929,0.845408,0.395440,0.487979,0.308802,0.370761,0.853762,0.156979,0.253123,0.112221,0.312737,0.157286,0.740356,0.299698,0.693922,0.481838,0.355941,0.587384,0.184884,0.754399,NaN,0.459031,0.455029
1463,0.461253,0.100979,0.880086,0.865859,0.165307,0.399069,0.058131,0.186442,0.682140,0.196282,0.110636,0.492603,0.295695,0.374251,0.378080,0.056189,0.827635,0.066596,0.309762,0.271551,0.622454,0.373122,0.041701,0.121813,0.140129,0.285415,0.150271,0.669877,0.568499,0.160879,0.153113,0.105345,0.381411,0.507742,0.163516,0.266095,0.265765,0.251887,0.264702,0.769732,0.822047,0.395778,0.880443,0.251568,0.362653,0.320103,0.122771,0.903722,0.099859,0.152187,0.076543,0.142008,0.105634,0.570884,0.317759,0.558016,0.519332,0.230466,0.336416,0.157830,0.701600,0.514695,NaN,0.326607
1471,0.555359,0.305501,0.909835,0.946314,0.203331,0.597937,0.125443,0.410067,0.715982,0.220306,0.317155,0.470809,0.294411,0.324562,0.544692,0.046039,0.906588,0.171735,0.198025,0.193093,0.618368,0.542414,0.104884,0.308215,0.178019,0.212154,0.282062,0.456567,0.591377,0.422143,0.143060,0.095654,0.259297,0.555149,0.380459,0.196658,0.339951,0.433561,0.277511,0.764234,0.720566,0.453552,0.786815,0.362625,0.501736,0.271155,0.252960,0.861895,0.241036,0.342988,0.099635,0.242221,0.193222,0.714060,0.228025,0.702861,0.317242,0.264370,0.400301,0.168321,0.827383,0.529455,0.597729,NaN

In [4]:
id_to_region_seed = dict(zip(df_seeds['TeamID'], df_seeds['Region Seed']))

df_matrix.index = df_matrix.index.map(id_to_region_seed)
df_matrix.columns = df_matrix.columns.map(id_to_region_seed)

df_matrix

,W13,W02,Y16,W16,W04,Z10,Y01,W09,Y15,W06,X05,Z12,Z08,Y09,Z11,W01,X16,Z01,X09,X08,Z13,X13,X01,X06,Y03,Z07,X03,W12,Y14,Y08,Y07,Z04,X12,Z05,Y05,Y02,Y06,W08,Z06,W14,Z15,Y10,Z16,Y11,Z09,W05,X04,W15,Z02,W07,X02,Y04,Z03,X14,X07,Z14,X10,W11,W10,W03,X15,X11,Y13,Y12
W13,NaN,0.218855,0.814330,0.747846,0.130761,0.378076,0.108685,0.227940,0.400273,0.162867,0.141767,0.217477,0.182613,0.152973,0.433833,0.068494,0.708379,0.122202,0.206690,0.093120,0.385600,0.492275,0.069799,0.212648,0.198045,0.119670,0.161474,0.590858,0.661924,0.161206,0.118439,0.097387,0.300348,0.276252,0.171951,0.154397,0.243739,0.200797,0.127840,0.587032,0.656595,0.283579,0.623069,0.152199,0.271491,0.268023,0.184938,0.598475,0.120288,0.141557,0.075853,0.162088,0.106496,0.461942,0.225625,0.652260,0.384147,0.186827,0.286238,0.200268,0.754994,0.340162,0.511514,0.375963
W02,0.773840,NaN,0.895708,0.873932,0.554941,0.791982,0.365387,0.663334,0.920285,0.567786,0.567572,0.871512,0.819175,0.865018,0.887773,0.219921,0.921878,0.253007,0.666295,0.659649,0.915527,0.897161,0.305743,0.592925,0.761049,0.640653,0.739727,0.900529,0.896616,0.606808,0.509090,0.595208,0.899091,0.836064,0.558095,0.635498,0.761060,0.782011,0.778688,0.934768,0.935407,0.801104,0.949688,0.765542,0.891663,0.779390,0.583837,0.949091,0.518280,0.579855,0.471348,0.497814,0.448000,0.894360,0.716078,0.918126,0.926590,0.663348,0.886933,0.535712,0.883818,0.920449,0.881328,0.727097
Y16,0.162046,0.090486,NaN,0.601517,0.043280,0.076725,0.074367,0.070406,0.187017,0.075485,0.117125,0.054602,0.099082,0.085230,0.126404,0.042574,0.423595,0.073230,0.051730,0.054667,0.110506,0.229729,0.045400,0.078741,0.073297,0.052883,0.068444,0.110275,0.148377,0.068074,0.041425,0.039706,0.078537,0.060967,0.074181,0.055188,0.083331,0.071666,0.058588,0.361113,0.331485,0.060918,0.271723,0.081803,0.081441,0.073306,0.056867,0.316398,0.056785,0.046170,0.066434,0.064029,0.067799,0.168806,0.103732,0.291040,0.137233,0.044921,0.062529,0.102626,0.404787,0.075956,0.128954,0.052860
W16,0.250457,0.120929,0.318411,NaN,0.050041,0.064909,0.047914,0.059204,0.411813,0.071242,0.057674,0.075373,0.061219,0.078504,0.103918,0.040944,0.464864,0.041666,0.080625,0.052089,0.084680,0.162147,0.033339,0.119439,0.067295,0.058435,0.082228,0.212605,0.255123,0.056002,0.083024,0.037071,0.069659,0.059988,0.093531,0.061328,0.080230,0.061903,0.065160,0.426689,0.352620,0.072665,0.345300,0.062826,0.072896,0.057413,0.063061,0.399764,0.044992,0.042264,0.068014,0.088811,0.068316,0.108859,0.082905,0.200782,0.184222,0.061313,0.076997,0.074019,0.430693,0.065576,0.125009,0.046498
W04,0.845163,0.411177,0.938787,0.939241,NaN,0.804638,0.235308,0.496646,0.868259,0.571583,0.372627,0.748614,0.664762,0.625196,0.855499,0.245570,0.931439,0.409921,0.570094,0.403422,0.861654,0.877436,0.217001,0.597953,0.679849,0.458624,0.521171,0.702235,0.885786,0.685157,0.430736,0.528988,0.847090,0.795267,0.696764,0.354440,0.646363,0.681545,0.453841,0.882985,0.904607,0.670231,0.918894,0.709664,0.751192,0.627955,0.454033,0.910176,0.550072,0.532861,0.290509,0.364034,0.418512,0.932662,0.519803,0.916217,0.717572,0.624988,0.662555,0.660604,0.893110,0.798711,0.813411,0.828993
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
W03,0.757623,0.413574,0.889539,0.933357,0.389597,0.563831,0.176939,0.567463,0.836870,0.399985,0.452579,0.810910,0.556216,0.694846,0.805801,0.131407,0.926998,0.242592,0.339952,0.484925,0.782435,0.774019,0.096336,0.405367,0.563077,0.381417,0.530826,0.713493,0.843486,0.547589,0.332267,0.543858,0.785996,0.719824,0.468229,0.477838,0.648739,0.572130,0.490507,0.896755,0.910793,0.585822,0.904038,0.616691,0.578651,0.555757,0.417935,0.896250,0.461686,0.506062,0.367603,0.415326,0.358168,0.894365,0.574859,0.894545,0.620202,0.415111,0.583795,NaN,0.850984,0.858708,0.841387,0.799863
X15,0.272956,0.101510,0.547588,0.528198,0.091922,0.146276,0.079652,0.119507,0.501316,0.135489,0.090872,0.199105,0.215190,0.251583,0.157788,0.044355,0.646531,0.068643,0.080932,0.105458,0.412377,0.284683,0.050626,0.101919,0.087757,0.051895,0.094116,0.277525,0.385499,0.117829,0.108639,0.071064,0.173251,0.114310,0.092306,0.071578,0.112218,0.113552,0.123171,0.541519,0.588619,0.201917,0.603193,0.188011,0.149379,0.139481,0.119077,0.527786,0.060389,0.075455,0.063781,0.057323,0.081840,0.394463,0.116754,0.501964,0.205338,0.107304,0.197933,0.149534,NaN,0.221858,0.342480,0.164765
X11,0.569405,0.140659,0.904838,0.907942,0.195364,0.241946,0.094090,0.182640,0.758426,0.298410,0.339912,0.493447,0.249896,0.313914,0.487645,0.090629,0.889758,0.173381,0.340013,0.225959,0.664067,0.608330,0.046280,0.297295,0.156302,0.239978,0.244218,0.522518,0.607509,0.371278,0.278436,0.254177,0.486399,0.502750,0.383349,0.155088,0.312732,0.331275,0.353071,0.800781,0.885380,0.526929,0.845408,0.395440,0.487979,0.308802,0.370761,0.853762,0.156979,0.253123,0.112221,0.312737,0.157286,0.740356,0.299698,0.693922,0.481838,0.355941,0.587384,0.184884,0.754399,NaN,0.459031,0.455029
Y13,0.461253,0.100979,0.880086,0.865859,0.165307,0.399069,0.058131,0.186442,0.682140,0.196282,0.110636,0.492603,0.295695,0.374251,0.378080,0.056189,0.827635,0.066596,0.309762,0.271551,0.622454,0.373122,0.041701,0.121813,0.140129,0.285415,0.150271,0.669877,0.568499,0.160879,0.153113,0.105345,0.381411,0.507742,0.163516,0.266095,0.265765,0.251887,0.264702,0.769732,0.822047,0.395778,0.880443,0.251568,0.362653,0.320103,0.122771,0.903722,0.099859,0.152187,0.076543,0.142008,0.105634,0.570884,0.317759,0.558016,0.519332,0.230466,0.336416,0.157830,0.701600,0.514695,NaN,0.326607
Y12,0.555359,0.305501,0.909835,0.946314,0.203331,0.597937,0.125443,0.410067,0.715982,0.220306,0.317155,0.470809,0.294411,0.324562,0.544692,0.046039,0.906588,0.171735,0.198025,0.193093,0.618368,0.542414,0.104884,0.308215,0.178019,0.212154,0.282062,0.456567,0.591377,0.422143,0.143060,0.095654,0.259297,0.555149,0.380459,0.196658,0.339951,0.433561,0.277511,0.764234,0.720566,0.453552,0.786815,0.362625,0.501736,0.271155,0.252960,0.861895,0.241036,0.342988,0.099635,0.242221,0.193222,0.714060,0.228025,0.702861,0.317242,0.264370,0.400301,0.168321,0.827383,0.529455,0.597729,NaN

Make transposition of matrix equivalent so ordering of teams doesn't matter

In [5]:
assert ((df_matrix.columns == df_matrix.index).all()), "Index does not align with columns"

df_matrix = (df_matrix + 1-df_matrix.transpose())/2

df_matrix

,W13,W02,Y16,W16,W04,Z10,Y01,W09,Y15,W06,X05,Z12,Z08,Y09,Z11,W01,X16,Z01,X09,X08,Z13,X13,X01,X06,Y03,Z07,X03,W12,Y14,Y08,Y07,Z04,X12,Z05,Y05,Y02,Y06,W08,Z06,W14,Z15,Y10,Z16,Y11,Z09,W05,X04,W15,Z02,W07,X02,Y04,Z03,X14,X07,Z14,X10,W11,W10,W03,X15,X11,Y13,Y12
W13,NaN,0.222507,0.826142,0.748695,0.142799,0.390865,0.115890,0.238431,0.386453,0.171492,0.149696,0.232147,0.170188,0.158325,0.426422,0.062239,0.707896,0.128433,0.179665,0.098988,0.389489,0.521725,0.072511,0.217761,0.242706,0.115092,0.206677,0.587382,0.656707,0.188224,0.115194,0.101460,0.275875,0.289201,0.183462,0.153675,0.244079,0.222480,0.127335,0.558153,0.650661,0.307972,0.612788,0.152502,0.318318,0.267634,0.194281,0.642325,0.116635,0.158654,0.072658,0.163330,0.114647,0.500734,0.232593,0.660310,0.440302,0.189491,0.262729,0.221323,0.741019,0.385378,0.525130,0.410302
W02,0.777493,NaN,0.902611,0.876502,0.571882,0.782107,0.341945,0.697309,0.918751,0.585617,0.577564,0.855312,0.807938,0.855677,0.876972,0.206579,0.928005,0.263931,0.661522,0.673538,0.922403,0.895409,0.304107,0.593367,0.752124,0.643449,0.708573,0.883657,0.890957,0.655804,0.538531,0.609020,0.900685,0.825181,0.583978,0.620221,0.751859,0.783757,0.771528,0.931714,0.930573,0.805523,0.948622,0.776448,0.881240,0.761413,0.594821,0.931470,0.519245,0.618943,0.473200,0.477860,0.440162,0.888965,0.695276,0.918823,0.918331,0.695990,0.894059,0.561069,0.891154,0.889895,0.890175,0.710798
Y16,0.173858,0.097389,NaN,0.641553,0.052246,0.079010,0.073592,0.065482,0.203011,0.075966,0.103624,0.069284,0.109722,0.082367,0.144793,0.051043,0.398221,0.085962,0.064667,0.059600,0.116845,0.234099,0.046089,0.081506,0.077133,0.052549,0.082206,0.141913,0.166650,0.073095,0.045666,0.041232,0.094397,0.070593,0.080418,0.063164,0.087151,0.068788,0.066209,0.397399,0.356159,0.070026,0.302778,0.085858,0.095094,0.072630,0.061295,0.331593,0.060430,0.050022,0.074539,0.065243,0.075942,0.190535,0.091410,0.334480,0.141046,0.055938,0.060302,0.106543,0.428600,0.085559,0.124434,0.071512
W16,0.251305,0.123498,0.358447,NaN,0.055400,0.074806,0.054619,0.054246,0.417809,0.079722,0.061530,0.074724,0.058572,0.078965,0.131617,0.046539,0.460075,0.049523,0.100182,0.057127,0.102344,0.178160,0.037596,0.113682,0.071027,0.063007,0.095994,0.220085,0.270386,0.054786,0.085183,0.043882,0.079656,0.074983,0.103450,0.070059,0.090960,0.065707,0.076380,0.448710,0.411892,0.082011,0.379304,0.069160,0.091505,0.060799,0.059752,0.433649,0.047879,0.047165,0.072695,0.094256,0.065836,0.149691,0.079432,0.235863,0.232457,0.068997,0.084414,0.070331,0.451248,0.078817,0.129575,0.050092
W04,0.857201,0.428118,0.947754,0.944600,NaN,0.788592,0.237579,0.517198,0.875362,0.550110,0.426414,0.771276,0.654985,0.633698,0.856952,0.237206,0.933476,0.411862,0.547878,0.398577,0.866689,0.861876,0.256175,0.591871,0.639995,0.455948,0.531829,0.714606,0.885165,0.679290,0.443361,0.522313,0.854161,0.797361,0.698935,0.350717,0.637778,0.646702,0.417021,0.883266,0.897609,0.638520,0.918299,0.699878,0.746441,0.622846,0.442974,0.918673,0.526520,0.512108,0.303159,0.378904,0.405353,0.915136,0.556842,0.916785,0.735594,0.579728,0.619621,0.635503,0.900594,0.801673,0.824052,0.812831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
W03,0.778677,0.438931,0.893457,0.929669,0.364497,0.600641,0.178923,0.580244,0.842811,0.391555,0.442128,0.787173,0.560738,0.681046,0.831493,0.151944,0.929246,0.247842,0.366232,0.476331,0.811777,0.776060,0.099138,0.396727,0.529529,0.373956,0.523331,0.720788,0.832196,0.534046,0.326446,0.493915,0.786213,0.730704,0.449427,0.474883,0.621371,0.588641,0.498399,0.896300,0.920168,0.589062,0.912400,0.602074,0.620009,0.553454,0.395548,0.892747,0.420074,0.512023,0.351721,0.403325,0.361319,0.890538,0.495234,0.897832,0.591912,0.431519,0.581846,NaN,0.850725,0.836912,0.841779,0.815771
X15,0.258981,0.108846,0.571400,0.548752,0.099406,0.146698,0.083343,0.116161,0.491689,0.144054,0.098437,0.196658,0.195797,0.235379,0.187898,0.045030,0.662531,0.075532,0.092528,0.111362,0.413382,0.262848,0.044026,0.106710,0.091356,0.051460,0.098292,0.271598,0.396081,0.127341,0.104061,0.077365,0.208178,0.146132,0.091105,0.083602,0.107346,0.115808,0.135357,0.570667,0.596288,0.212748,0.587085,0.181126,0.147802,0.137078,0.114990,0.534094,0.054953,0.085157,0.058622,0.061162,0.083544,0.399596,0.101320,0.494262,0.213616,0.114121,0.200276,0.149275,NaN,0.233729,0.320440,0.168691
X11,0.614622,0.110105,0.914441,0.921183,0.198327,0.233117,0.087767,0.191791,0.785012,0.301218,0.364346,0.430623,0.242696,0.311109,0.475756,0.085177,0.897290,0.178921,0.350917,0.225248,0.722510,0.582830,0.053361,0.284831,0.148796,0.242030,0.250760,0.525949,0.561779,0.405739,0.286933,0.296098,0.506855,0.555521,0.394667,0.159400,0.296946,0.312478,0.382317,0.795905,0.882102,0.574732,0.850374,0.423198,0.471672,0.291065,0.353979,0.849568,0.153919,0.262091,0.109428,0.308979,0.173238,0.746440,0.277175,0.703731,0.471952,0.369417,0.624617,0.163088,0.766271,NaN,0.472168,0.462787
Y13,0.474870,0.109825,0.875566,0.870425,0.175948,0.388571,0.065903,0.179523,0.686609,0.206842,0.108177,0.517494,0.250606,0.366974,0.400285,0.059140,0.812476,0.071261,0.286627,0.262717,0.647587,0.359070,0.045231,0.108138,0.132059,0.254190,0.154982,0.671071,0.608490,0.157212,0.169601,0.094810,0.396164,0.490150,0.167163,0.254435,0.277721,0.248498,0.257848,0.765497,0.836094,0.437337,0.879255,0.265334,0.413622,0.311040,0.109701,0.885921,0.095420,0.154988,0.074387,0.149060,0.115262,0.587703,0.291829,0.595603,0.533526,0.240569,0.348946,0.158221,0.679560,0.527832,NaN,0.364439
Y12,0.589698,0.289202,0.928488,0.949908,0.187169,0.596893,0.130729,0.418857,0.732450,0.228518,0.340641,0.451499,0.327916,0.332694,0.579250,0.045339,0.911414,0.188101,0.238009,0.189585,0.644823,0.557133,0.096053,0.297291,0.199586,0.217309,0.285784,0.436452,0.600793,0.398109,0.166181,0.106088,0.273919,0.554936,0.332816,0.181658,0.390132,0.449797,0.307603,0.717137,0.739514,0.466596,0.770346,0.351354,0.525736,0.282010,0.280691,0.871895,0.225518,0.306807,0.105839,0.234545,0.188086,0.716171,0.258437,0.719003,0.364444,0.285093,0.387250,0.184229,0.831309,0.537213,0.635561,NaN

In [6]:
df_matrix_opposite = 1 - df_matrix  # prob of team losing

df_matrix_opposite

,W13,W02,Y16,W16,W04,Z10,Y01,W09,Y15,W06,X05,Z12,Z08,Y09,Z11,W01,X16,Z01,X09,X08,Z13,X13,X01,X06,Y03,Z07,X03,W12,Y14,Y08,Y07,Z04,X12,Z05,Y05,Y02,Y06,W08,Z06,W14,Z15,Y10,Z16,Y11,Z09,W05,X04,W15,Z02,W07,X02,Y04,Z03,X14,X07,Z14,X10,W11,W10,W03,X15,X11,Y13,Y12
W13,NaN,0.777493,0.173858,0.251305,0.857201,0.609135,0.884110,0.761569,0.613547,0.828508,0.850304,0.767853,0.829812,0.841675,0.573578,0.937761,0.292104,0.871567,0.820335,0.901012,0.610511,0.478275,0.927489,0.782239,0.757294,0.884908,0.793323,0.412618,0.343293,0.811776,0.884806,0.898540,0.724125,0.710799,0.816538,0.846325,0.755921,0.777520,0.872665,0.441847,0.349339,0.692028,0.387212,0.847498,0.681682,0.732366,0.805719,0.357675,0.883365,0.841346,0.927342,0.836670,0.885353,0.499266,0.767407,0.339690,0.559698,0.810509,0.737271,0.778677,0.258981,0.614622,0.474870,0.589698
W02,0.222507,NaN,0.097389,0.123498,0.428118,0.217893,0.658055,0.302691,0.081249,0.414383,0.422436,0.144688,0.192062,0.144323,0.123028,0.793421,0.071995,0.736069,0.338478,0.326462,0.077597,0.104591,0.695893,0.406633,0.247876,0.356551,0.291427,0.116343,0.109043,0.344196,0.461469,0.390980,0.099315,0.174819,0.416022,0.379779,0.248141,0.216243,0.228472,0.068286,0.069427,0.194477,0.051378,0.223552,0.118760,0.238587,0.405179,0.068530,0.480755,0.381057,0.526800,0.522140,0.559838,0.111035,0.304724,0.081177,0.081669,0.304010,0.105941,0.438931,0.108846,0.110105,0.109825,0.289202
Y16,0.826142,0.902611,NaN,0.358447,0.947754,0.920990,0.926408,0.934518,0.796989,0.924034,0.896376,0.930716,0.890278,0.917633,0.855207,0.948957,0.601779,0.914038,0.935333,0.940400,0.883155,0.765901,0.953911,0.918494,0.922867,0.947451,0.917794,0.858087,0.833350,0.926905,0.954334,0.958768,0.905603,0.929407,0.919582,0.936836,0.912849,0.931212,0.933791,0.602601,0.643841,0.929974,0.697222,0.914142,0.904906,0.927370,0.938705,0.668407,0.939570,0.949978,0.925461,0.934757,0.924058,0.809465,0.908590,0.665520,0.858954,0.944062,0.939698,0.893457,0.571400,0.914441,0.875566,0.928488
W16,0.748695,0.876502,0.641553,NaN,0.944600,0.925194,0.945381,0.945754,0.582191,0.920278,0.938470,0.925276,0.941428,0.921035,0.868383,0.953461,0.539925,0.950477,0.899818,0.942873,0.897656,0.821840,0.962404,0.886318,0.928973,0.936993,0.904006,0.779915,0.729614,0.945214,0.914817,0.956118,0.920344,0.925017,0.896550,0.929941,0.909040,0.934293,0.923620,0.551290,0.588108,0.917989,0.620696,0.930840,0.908495,0.939201,0.940248,0.566351,0.952121,0.952835,0.927305,0.905744,0.934164,0.850309,0.920568,0.764137,0.767543,0.931003,0.915586,0.929669,0.548752,0.921183,0.870425,0.949908
W04,0.142799,0.571882,0.052246,0.055400,NaN,0.211408,0.762421,0.482802,0.124638,0.449890,0.573586,0.228724,0.345015,0.366302,0.143048,0.762794,0.066524,0.588138,0.452122,0.601423,0.133311,0.138124,0.743825,0.408129,0.360005,0.544052,0.468171,0.285394,0.114835,0.320710,0.556639,0.477687,0.145839,0.202639,0.301065,0.649283,0.362222,0.353298,0.582979,0.116734,0.102391,0.361480,0.081701,0.300122,0.253559,0.377154,0.557026,0.081327,0.473480,0.487892,0.696841,0.621096,0.594647,0.084864,0.443158,0.083215,0.264406,0.420272,0.380379,0.364497,0.099406,0.198327,0.175948,0.187169
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
W03,0.221323,0.561069,0.106543,0.070331,0.635503,0.399359,0.821077,0.419756,0.157189,0.608445,0.557872,0.212827,0.439262,0.318954,0.168507,0.848056,0.070754,0.752158,0.633768,0.523669,0.188223,0.223940,0.900862,0.603273,0.470471,0.626044,0.476669,0.279212,0.167804,0.465954,0.673554,0.506085,0.213787,0.269296,0.550573,0.525117,0.378629,0.411359,0.501601,0.103700,0.079832,0.410938,0.087600,0.397926,0.379991,0.446546,0.604452,0.107253,0.579926,0.487977,0.648279,0.596675,0.638681,0.109462,0.504766,0.102168,0.408088,0.568481,0.418154,NaN,0.149275,0.163088,0.158221,0.184229
X15,0.741019,0.891154,0.428600,0.451248,0.900594,0.853302,0.916657,0.883839,0.508311,0.855946,0.901563,0.803342,0.804203,0.764621,0.812102,0.954970,0.337469,0.924468,0.907472,0.888638,0.586618,0.737152,0.955974,0.893290,0.908644,0.948540,0.901708,0.728402,0.603919,0.872659,0.895939,0.922635,0.791822,0.853868,0.908895,0.916398,0.892654,0.884192,0.864643,0.429333,0.403712,0.787252,0.412915,0.818874,0.852198,0.862922,0.885010,0.465906,0.945047,0.914843,0.941378,0.938838,0.916456,0.600404,0.898680,0.505738,0.786384,0.885879,0.799724,0.850725,NaN,0.766271,0.679560,0.831309
X11,0.385378,0.889895,0.085559,0.078817,0.801673,0.766883,0.912233,0.808209,0.214988,0.698782,0.635654,0.569377,0.757304,0.688891,0.524244,0.914823,0.102710,0.821079,0.649083,0.774752,0.277490,0.417170,0.946639,0.715169,0.851204,0.757970,0.749240,0.474051,0.438221,0.594261,0.713067,0.703902,0.493145,0.444479,0.605333,0.840600,0.703054,0.687522,0.617683,0.204095,0.117898,0.425268,0.149626,0.576802,0.528328,0.708935,0.646021,0.150432,0.846081,0.737909,0.890572,0.691021,0.826762,0.253560,0.722825,0.296269,0.528048,0.630583,0.375383,0.836912,0.233729,NaN,0.527832,0.537213
Y13,0.525130,0.890175,0.124434,0.129575,0.824052,0.611429,0.934097,0.820477,0.313391,0.793158,0.891823,0.482506,0.749394,0.633026,0.599715,0.940860,0.187524,0.928739,0.713373,0.737283,0.352413,0.640930,0.954769,0.891862,0.867941,0.745810,0.845018,0.328929,0.391510,0.842788,0.830399,0.905190,0.603836,0.509850,0.832837,0.745565,0.722279,0.751502,0.742152,0.234503,0.163906,0.562663,0.120745,0.734666,0.586378,0.688960,0.890299,0.114079,0.904580,0.845012,0.925613,0.850940,0.884738,0.412297,0.708171,0.404397,0.466474,0.759431,0.651054,0.841779,0.320440,0.472168,NaN,0.635561
Y12,0.410302,0.710798,0.071512,0.050092,0.812831,0.403107,0.869271,0.581143,0.267550,0.771482,0.659359,0.548501,0.672084,0.667306,0.420750,0.954661,0.088586,0.811899,0.761991,0.810415,0.355177,0.442867,0.903947,0.702709,0.800414,0.782691,0.714216,0.563548,0.399207,0.601891,0.833819,0.893912,0.726081,0.445064,0.667184,0.818342,0.609868,0.550203,0.692397,0.282863,0.260486,0.533404,0.229654,0.648646,0.474264,0.717990,0.719309,0.128105,0.774482,0.693193,0.894161,0.765455,0.811914,0.283829,0.741563,0.280997,0.635556,0.714907,0.612750,0.815771,0.168691,0.462787,0.364439,NaN

### Simulate Tournament

In [7]:
import numpy as np

def simulate_tournament() -> dict:
    """
    Simulate the tournament in Kaggle submission format
    """
    # ROUND 1
    round_1 = {
        f'R1{region}{i}': np.random.choice(
            (f'{region}{i:02d}', f'{region}{17-i:02d}'), 
            p=(
                df_matrix.loc[f'{region}{i:02d}', f'{region}{17-i:02d}'], 
                df_matrix_opposite.loc[f'{region}{i:02d}', f'{region}{17-i:02d}']
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 8, 5, 4, 6, 3, 7, 2)
    }

    # ROUND 2
    round_2 = {
        f'R2{region}{i}': np.random.choice(
            (round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']), 
            p=(
                df_matrix.loc[round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']], 
                df_matrix_opposite.loc[round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 4, 3, 2)
    }

    # ROUND 3
    round_3 = {
        f'R3{region}{i}': np.random.choice(
            (round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']), 
            p=(
                df_matrix.loc[round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']], 
                df_matrix_opposite.loc[round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 2)
    }

    # ROUND 4
    round_4 = {
        f'R4{region}{i}': np.random.choice(
            (round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']), 
            p=(
                df_matrix.loc[round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']], 
                df_matrix_opposite.loc[round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, )
    }

    # ROUND 5
    round_5 = {
        'R5WX': np.random.choice(
            (round_4['R4W1'], round_4['R4X1']),
            p=(
                df_matrix.loc[round_4['R4W1'], round_4['R4X1']],
                df_matrix_opposite.loc[round_4['R4W1'], round_4['R4X1']],
            )
        ),
        'R5YZ': np.random.choice(
            (round_4['R4Y1'], round_4['R4Z1']),
            p=(
                df_matrix.loc[round_4['R4Y1'], round_4['R4Z1']],
                df_matrix_opposite.loc[round_4['R4Y1'], round_4['R4Z1']],
            )
        ),
    }

    # ROUND 6
    round_6 = {
        'R6CH': np.random.choice(
            (round_5['R5WX'], round_5['R5YZ']),
            p=(
                df_matrix.loc[round_5['R5WX'], round_5['R5YZ']],
                df_matrix_opposite.loc[round_5['R5WX'], round_5['R5YZ']],
            )
        ),
    }

    return round_1 | round_2 | round_3 | round_4 | round_5 | round_6  # merge the dictionaries (python >= 3.9)

simulate_tournament()

{'R1W1': 'W01',
 'R1W8': 'W08',
 'R1W5': 'W12',
 'R1W4': 'W04',
 'R1W6': 'W11',
 'R1W3': 'W03',
 'R1W7': 'W07',
 'R1W2': 'W15',
 'R1X1': 'X01',
 'R1X8': 'X09',
 'R1X5': 'X12',
 'R1X4': 'X04',
 'R1X6': 'X06',
 'R1X3': 'X03',
 'R1X7': 'X07',
 'R1X2': 'X15',
 'R1Y1': 'Y01',
 'R1Y8': 'Y08',
 'R1Y5': 'Y12',
 'R1Y4': 'Y04',
 'R1Y6': 'Y11',
 'R1Y3': 'Y03',
 'R1Y7': 'Y07',
 'R1Y2': 'Y02',
 'R1Z1': 'Z01',
 'R1Z8': 'Z08',
 'R1Z5': 'Z05',
 'R1Z4': 'Z04',
 'R1Z6': 'Z06',
 'R1Z3': 'Z03',
 'R1Z7': 'Z07',
 'R1Z2': 'Z02',
 'R2W1': 'W01',
 'R2W4': 'W04',
 'R2W3': 'W03',
 'R2W2': 'W07',
 'R2X1': 'X01',
 'R2X4': 'X04',
 'R2X3': 'X03',
 'R2X2': 'X07',
 'R2Y1': 'Y01',
 'R2Y4': 'Y04',
 'R2Y3': 'Y03',
 'R2Y2': 'Y02',
 'R2Z1': 'Z08',
 'R2Z4': 'Z04',
 'R2Z3': 'Z03',
 'R2Z2': 'Z02',
 'R3W1': 'W01',
 'R3W2': 'W07',
 'R3X1': 'X01',
 'R3X2': 'X03',
 'R3Y1': 'Y04',
 'R3Y2': 'Y02',
 'R3Z1': 'Z04',
 'R3Z2': 'Z02',
 'R4W1': 'W01',
 'R4X1': 'X01',
 'R4Y1': 'Y02',
 'R4Z1': 'Z02',
 'R5WX': 'W01',
 'R5YZ': 'Z02',
 'R6CH': 'W01'}

In [ ]:
from tqdm.autonotebook import trange

np.random.seed(22)

results = tuple(
    simulate_tournament()
    for _ in trange(30_000)  # set back to 30_000
)

len(results)

C:\Users\mhugh\AppData\Local\Temp\ipykernel_2348\4113097100.py:1: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import trange

  0%|          | 0/3000 [00:00<?, ?it/s]

3000

In [ ]:
np.random.seed(23)

my_candidates = tuple(
    simulate_tournament()
    for _ in trange(20_000)  # set back to 20_000
)

len(my_candidates)

  0%|          | 0/2000 [00:00<?, ?it/s]

2000

In [10]:
def bracket_to_team_placements(bracket: dict) -> dict:
    """
    Convert bracket to dict of how many games each team won
    """
    round_1 = {
        bracket[f'R1{region}{i}']: 1
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 8, 5, 4, 6, 3, 7, 2)
    }

    round_2 = {
        bracket[f'R2{region}{i}']: 2
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 4, 3, 2)
    }

    round_3 = {
        bracket[f'R3{region}{i}']: 3
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 2)
    }

    round_4 = {
        bracket[f'R4{region}{i}']: 4
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, )
    }

    round_5 = {
        bracket['R5WX']: 5,
        bracket['R5YZ']: 5,
    }

    round_6 = {
        bracket['R6CH']: 6,
    }

    return round_1 | round_2 | round_3 | round_4 | round_5 | round_6  # merge the dictionaries (python >= 3.9)

bracket_to_team_placements(results[0])

{'W01': 4,
 'W09': 1,
 'W05': 1,
 'W13': 2,
 'W06': 2,
 'W03': 1,
 'W07': 3,
 'W02': 1,
 'X01': 6,
 'X09': 1,
 'X05': 1,
 'X04': 2,
 'X11': 1,
 'X03': 3,
 'X07': 1,
 'X02': 2,
 'Y01': 5,
 'Y09': 1,
 'Y12': 1,
 'Y04': 2,
 'Y11': 1,
 'Y03': 3,
 'Y07': 1,
 'Y02': 2,
 'Z01': 2,
 'Z08': 1,
 'Z12': 3,
 'Z04': 1,
 'Z11': 2,
 'Z14': 1,
 'Z10': 1,
 'Z02': 4}

In [11]:
from tqdm.autonotebook import tqdm

team_placements = tuple(bracket_to_team_placements(result) for result in tqdm(results))

len(team_placements)

  0%|          | 0/3000 [00:00<?, ?it/s]

3000

In [12]:
team_all_placements = {
    team: np.array([team_placements_bracket.get(team, 0) for team_placements_bracket in team_placements])
    for team in ((f'{region}{i:02d}') for region in ('W', 'X', 'Y', 'Z') for i in range(1, 17))
}

team_all_placements

{'W01': array([4, 6, 6, ..., 6, 4, 5]),
 'W02': array([1, 3, 2, ..., 3, 1, 3]),
 'W03': array([1, 1, 3, ..., 1, 1, 2]),
 'W04': array([0, 1, 1, ..., 2, 1, 1]),
 'W05': array([1, 0, 2, ..., 0, 0, 0]),
 'W06': array([2, 2, 1, ..., 2, 0, 0]),
 'W07': array([3, 1, 0, ..., 0, 3, 0]),
 'W08': array([0, 0, 0, ..., 0, 1, 0]),
 'W09': array([1, 1, 1, ..., 1, 0, 1]),
 'W10': array([0, 0, 1, ..., 1, 0, 1]),
 'W11': array([0, 0, 0, ..., 0, 2, 1]),
 'W12': array([0, 2, 0, ..., 1, 2, 2]),
 'W13': array([2, 0, 0, ..., 0, 0, 0]),
 'W14': array([0, 0, 0, ..., 0, 0, 0]),
 'W15': array([0, 0, 0, ..., 0, 0, 0]),
 'W16': array([0, 0, 0, ..., 0, 0, 0]),
 'X01': array([6, 2, 2, ..., 3, 6, 4]),
 'X02': array([2, 2, 1, ..., 1, 3, 3]),
 'X03': array([3, 1, 2, ..., 4, 1, 2]),
 'X04': array([2, 3, 4, ..., 1, 2, 0]),
 'X05': array([1, 1, 1, ..., 2, 1, 2]),
 'X06': array([0, 4, 1, ..., 1, 0, 1]),
 'X07': array([1, 1, 0, ..., 2, 1, 1]),
 'X08': array([0, 0, 1, ..., 0, 0, 0]),
 'X09': array([1, 1, 0, ..., 1, 1, 1]),
 'X10': array([0, 0, 3, ..., 0, 0, 0]),
 'X11': array([1, 0, 0, ..., 0, 2, 0]),
 'X12': array([0, 0, 0, ..., 0, 0, 0]),
 'X13': array([0, 0, 0, ..., 0, 0, 1]),
 'X14': array([0, 0, 0, ..., 0, 0, 0]),
 'X15': array([0, 0, 0, ..., 0, 0, 0]),
 'X16': array([0, 0, 0, ..., 0, 0, 0]),
 'Y01': array([5, 2, 3, ..., 4, 2, 3]),
 'Y02': array([2, 1, 4, ..., 0, 1, 4]),
 'Y03': array([3, 2, 2, ..., 3, 1, 1]),
 'Y04': array([2, 1, 2, ..., 2, 3, 2]),
 'Y05': array([0, 4, 1, ..., 0, 0, 1]),
 'Y06': array([0, 1, 0, ..., 0, 0, 2]),
 'Y07': array([1, 3, 1, ..., 2, 2, 0]),
 'Y08': array([0, 0, 0, ..., 1, 0, 0]),
 'Y09': array([1, 1, 1, ..., 0, 1, 1]),
 'Y10': array([0, 0, 0, ..., 0, 0, 1]),
 'Y11': array([1, 0, 1, ..., 1, 4, 0]),
 'Y12': array([1, 0, 0, ..., 1, 1, 0]),
 'Y13': array([0, 0, 0, ..., 0, 0, 0]),
 'Y14': array([0, 0, 0, ..., 0, 0, 0]),
 'Y15': array([0, 0, 0, ..., 1, 0, 0]),
 'Y16': array([0, 0, 0, ..., 0, 0, 0]),
 'Z01': array([2, 2, 2, ..., 5, 5, 1]),
 'Z02': array([4, 2, 5, ..., 2, 0, 3]),
 'Z03': array([0, 5, 1, ..., 1, 1, 1]),
 'Z04': array([1, 3, 3, ..., 2, 2, 2]),
 'Z05': array([0, 1, 1, ..., 0, 0, 1]),
 'Z06': array([0, 0, 2, ..., 3, 0, 2]),
 'Z07': array([0, 0, 1, ..., 1, 3, 0]),
 'Z08': array([1, 1, 1, ..., 0, 1, 6]),
 'Z09': array([0, 0, 0, ..., 1, 0, 0]),
 'Z10': array([1, 1, 0, ..., 0, 0, 1]),
 'Z11': array([2, 1, 0, ..., 0, 2, 0]),
 'Z12': array([3, 0, 0, ..., 1, 1, 0]),
 'Z13': array([0, 0, 0, ..., 0, 0, 0]),
 'Z14': array([1, 0, 0, ..., 0, 0, 0]),
 'Z15': array([0, 0, 0, ..., 0, 1, 0]),
 'Z16': array([0, 0, 0, ..., 0, 0, 0])}

Get probabilities of surviving

In [13]:
team_model_probs = dict(
    (
        t, 
        np.array(tuple(
            (v >= round).mean()
            for round in range(1, 7)
        ))
    )
    for t, v in team_all_placements.items()
)

team_model_probs

{'W01': array([0.95866667, 0.858     , 0.73      , 0.61266667, 0.36433333,
        0.254     ]),
 'W02': array([0.93333333, 0.712     , 0.44366667, 0.14233333, 0.054     ,
        0.02133333]),
 'W03': array([0.89366667, 0.35633333, 0.166     , 0.03866667, 0.01266667,
        0.00466667]),
 'W04': array([0.84233333, 0.545     , 0.14733333, 0.077     , 0.026     ,
        0.01066667]),
 'W05': array([0.76766667, 0.327     , 0.038     , 0.01733333, 0.00366667,
        0.001     ]),
 'W06': array([0.45333333, 0.29866667, 0.13033333, 0.02733333, 0.00933333,
        0.00433333]),
 'W07': array([0.49966667, 0.205     , 0.108     , 0.02533333, 0.00633333,
        0.001     ]),
 'W08': array([0.32166667, 0.05266667, 0.02566667, 0.01033333, 0.00166667,
        0.00033333]),
 'W09': array([0.67833333, 0.087     , 0.04933333, 0.02      , 0.00733333,
        0.00266667]),
 'W10': array([5.00333333e-01, 7.33333333e-02, 3.36666667e-02, 7.66666667e-03,
        1.00000000e-03, 3.33333333e-04]),
 'W11': array([0.54666667, 0.32833333, 0.114     , 0.01933333, 0.005     ,
        0.00066667]),
 'W12': array([0.23233333, 0.075     , 0.006     , 0.002     , 0.00033333,
        0.        ]),
 'W13': array([0.15766667, 0.053     , 0.00333333, 0.        , 0.        ,
        0.        ]),
 'W14': array([0.10633333, 0.01666667, 0.00266667, 0.        , 0.        ,
        0.        ]),
 'W15': array([0.06666667, 0.00966667, 0.00166667, 0.        , 0.        ,
        0.        ]),
 'W16': array([0.04133333, 0.00233333, 0.00033333, 0.        , 0.        ,
        0.        ]),
 'X01': array([0.97033333, 0.767     , 0.64666667, 0.49733333, 0.31      ,
        0.22233333]),
 'X02': array([0.93633333, 0.76      , 0.51566667, 0.21866667, 0.12133333,
        0.06466667]),
 'X03': array([0.8       , 0.48633333, 0.161     , 0.04766667, 0.01033333,
        0.00466667]),
 'X04': array([0.91433333, 0.45166667, 0.141     , 0.062     , 0.019     ,
        0.006     ]),
 'X05': array([0.75833333, 0.42966667, 0.1       , 0.04666667, 0.01233333,
        0.00466667]),
 'X06': array([0.702     , 0.35266667, 0.204     , 0.054     , 0.01166667,
        0.00566667]),
 'X07': array([0.634     , 0.143     , 0.06733333, 0.015     , 0.00233333,
        0.00066667]),
 'X08': array([0.58333333, 0.19833333, 0.09133333, 0.04433333, 0.017     ,
        0.006     ]),
 'X09': array([0.41666667, 0.031     , 0.011     , 0.005     , 0.00233333,
        0.001     ]),
 'X10': array([3.66000000e-01, 8.76666667e-02, 3.06666667e-02, 6.00000000e-03,
        1.33333333e-03, 3.33333333e-04]),
 'X11': array([0.298     , 0.11033333, 0.01666667, 0.00166667, 0.        ,
        0.        ]),
 'X12': array([0.24166667, 0.09933333, 0.00766667, 0.00133333, 0.00066667,
        0.        ]),
 'X13': array([0.08566667, 0.01933333, 0.002     , 0.        , 0.        ,
        0.        ]),
 'X14': array([0.2       , 0.05066667, 0.00333333, 0.00033333, 0.        ,
        0.        ]),
 'X15': array([0.06366667, 0.00933333, 0.00133333, 0.        , 0.        ,
        0.        ]),
 'X16': array([0.02966667, 0.00366667, 0.00033333, 0.        , 0.        ,
        0.        ]),
 'Y01': array([0.92466667, 0.79433333, 0.60866667, 0.48933333, 0.34533333,
        0.173     ]),
 'Y02': array([0.93466667, 0.59      , 0.283     , 0.10266667, 0.04266667,
        0.00933333]),
 'Y03': array([0.88833333, 0.514     , 0.32566667, 0.11733333, 0.045     ,
        0.00833333]),
 'Y04': array([0.834     , 0.57166667, 0.206     , 0.09366667, 0.038     ,
        0.00966667]),
 'Y05': array([0.65333333, 0.27933333, 0.059     , 0.026     , 0.00733333,
        0.002     ]),
 'Y06': array([0.51466667, 0.22633333, 0.10033333, 0.03333333, 0.00866667,
        0.00133333]),
 'Y07': array([0.644     , 0.208     , 0.098     , 0.037     , 0.011     ,
        0.00333333]),
 'Y08': array([0.42666667, 0.10566667, 0.057     , 0.027     , 0.011     ,
        0.00133333]),
 'Y09': array([0.57333333, 0.09366667, 0.04433333, 0.01666667, 0.00666667,
        0.00066667]),
 'Y10': array([0.356     , 0.19466667, 0.05633333, 0.01133333, 0.00233333,
        0.        ]),
 'Y11': array([0.48533333, 0.242     , 0.134     , 0.04166667, 0.01233333,
        0.00266667]),
 'Y12': array([0.34666667, 0.114     , 0.02066667, 0.003     , 0.001     ,
        0.        ]),
 'Y13': array([0.166     , 0.035     , 0.00333333, 0.00066667, 0.        ,
        0.        ]),
 'Y14': array([0.11166667, 0.01766667, 0.00266667, 0.        , 0.        ,
        0.        ]),
 'Y15': array([0.06533333, 0.00733333, 0.        , 0.        , 0.        ,
        0.        ]),
 'Y16': array([0.07533333, 0.00633333, 0.001     , 0.00033333, 0.        ,
        0.        ]),
 'Z01': array([0.94666667, 0.69433333, 0.502     , 0.35333333, 0.21933333,
        0.10533333]),
 'Z02': array([0.95333333, 0.71      , 0.35966667, 0.18733333, 0.08066667,
        0.02133333]),
 'Z03': array([0.94333333, 0.57466667, 0.348     , 0.12633333, 0.057     ,
        0.022     ]),
 'Z04': array([0.92066667, 0.68766667, 0.26133333, 0.13166667, 0.04633333,
        0.01066667]),
 'Z05': array([5.71000000e-01, 1.35000000e-01, 1.76666667e-02, 4.33333333e-03,
        3.33333333e-04, 0.00000000e+00]),
 'Z06': array([0.63733333, 0.35333333, 0.13966667, 0.05633333, 0.01566667,
        0.00366667]),
 'Z07': array([0.64566667, 0.195     , 0.098     , 0.032     , 0.01066667,
        0.00166667]),
 'Z08': array([0.741     , 0.255     , 0.16966667, 0.08166667, 0.031     ,
        0.00633333]),
 'Z09': array([0.259     , 0.045     , 0.01666667, 0.00566667, 0.00133333,
        0.00033333]),
 'Z10': array([0.35433333, 0.09366667, 0.03133333, 0.00966667, 0.00333333,
        0.        ]),
 'Z11': array([0.36266667, 0.05933333, 0.02166667, 0.00366667, 0.00133333,
        0.        ]),
 'Z12': array([0.429     , 0.153     , 0.02966667, 0.008     , 0.00166667,
        0.        ]),
 'Z13': array([0.07933333, 0.02433333, 0.00266667, 0.        , 0.        ,
        0.        ]),
 'Z14': array([0.05666667, 0.01266667, 0.00066667, 0.        , 0.        ,
        0.        ]),
 'Z15': array([0.04666667, 0.00133333, 0.001     , 0.        , 0.        ,
        0.        ]),
 'Z16': array([0.05333333, 0.00566667, 0.00033333, 0.        , 0.        ,
        0.        ])}

In [14]:
region_seed_to_id = dict(zip(df_seeds['Region Seed'], df_seeds['TeamID']))

df_model = pd.DataFrame({
    'Team': team_model_probs.keys()
})

df_model[[f'Round {i}' for i in range(1, 7)]] = np.array(tuple(df_model['Team'].map(team_model_probs)))

df_model.insert(1, 'TeamID', df_model['Team'].map(region_seed_to_id))

df_model.sort_values(by=['Round 6'], ascending=False, inplace=True, ignore_index=True)

df_model.head(10)

  Team  TeamID   Round 1   Round 2   Round 3   Round 4   Round 5   Round 6
0  W01    1181  0.958667  0.858000  0.730000  0.612667  0.364333  0.254000
1  X01    1222  0.970333  0.767000  0.646667  0.497333  0.310000  0.222333
2  Y01    1120  0.924667  0.794333  0.608667  0.489333  0.345333  0.173000
3  Z01    1196  0.946667  0.694333  0.502000  0.353333  0.219333  0.105333
4  X02    1397  0.936333  0.760000  0.515667  0.218667  0.121333  0.064667
5  Z03    1403  0.943333  0.574667  0.348000  0.126333  0.057000  0.022000
6  Z02    1385  0.953333  0.710000  0.359667  0.187333  0.080667  0.021333
7  W02    1104  0.933333  0.712000  0.443667  0.142333  0.054000  0.021333
8  W04    1112  0.842333  0.545000  0.147333  0.077000  0.026000  0.010667
9  Z04    1268  0.920667  0.687667  0.261333  0.131667  0.046333  0.010667

In [15]:
df_teams = pd.read_csv(r'..\data\unprocessed\kaggle\MTeams.csv')

df_teams

     TeamID        TeamName  FirstD1Season  LastD1Season
0      1101     Abilene Chr           2014          2025
1      1102       Air Force           1985          2025
2      1103           Akron           1985          2025
3      1104         Alabama           1985          2025
4      1105     Alabama A&M           2000          2025
..      ...             ...            ...           ...
375    1476       Stonehill           2023          2025
376    1477  East Texas A&M           2023          2025
377    1478        Le Moyne           2024          2025
378    1479      Mercyhurst           2025          2025
379    1480    West Georgia           2025          2025

[380 rows x 4 columns]

In [16]:
id_to_team = dict(zip(df_teams['TeamID'], df_teams['TeamName']))

df_model.insert(df_model.columns.get_loc('TeamID') + 1, 'Name', df_model['TeamID'].map(id_to_team))

df_model.head(25)

,Team,TeamID,Name,Round 1,Round 2,Round 3,Round 4,Round 5,Round 6
0,W01,1181,Duke,0.958667,0.858000,0.730000,0.612667,0.364333,0.254000
1,X01,1222,Houston,0.970333,0.767000,0.646667,0.497333,0.310000,0.222333
2,Y01,1120,Auburn,0.924667,0.794333,0.608667,0.489333,0.345333,0.173000
3,Z01,1196,Florida,0.946667,0.694333,0.502000,0.353333,0.219333,0.105333
4,X02,1397,Tennessee,0.936333,0.760000,0.515667,0.218667,0.121333,0.064667
5,Z03,1403,Texas Tech,0.943333,0.574667,0.348000,0.126333,0.057000,0.022000
6,Z02,1385,St John's,0.953333,0.710000,0.359667,0.187333,0.080667,0.021333
7,W02,1104,Alabama,0.933333,0.712000,0.443667,0.142333,0.054000,0.021333
8,W04,1112,Arizona,0.842333,0.545000,0.147333,0.077000,0.026000,0.010667
9,Z04,1268,Maryland,0.920667,0.687667,0.261333,0.131667,0.046333,0.010667
10,Y04,1401,Texas A&M,0.834000,0.571667,0.206000,0.093667,0.038000,0.009667
11,Y02,1277,Michigan St,0.934667,0.590000,0.283000,0.102667,0.042667,0.009333
12,Y03,1235,Iowa St,0.888333,0.514000,0.325667,0.117333,0.045000,0.008333
13,Z08,1163,Connecticut,0.741000,0.255000,0.169667,0.081667,0.031000,0.006333
14,X04,1345,Purdue,0.914333,0.451667,0.141000,0.062000,0.019000,0.006000
15,X08,1211,Gonzaga,0.583333,0.198333,0.091333,0.044333,0.017000,0.006000
16,X06,1228,Illinois,0.702000,0.352667,0.204000,0.054000,0.011667,0.005667
17,W03,1458,Wisconsin,0.893667,0.356333,0.166000,0.038667,0.012667,0.004667
18,X03,1246,Kentucky,0.800000,0.486333,0.161000,0.047667,0.010333,0.004667
19,X05,1155,Clemson,0.758333,0.429667,0.100000,0.046667,0.012333,0.004667
20,W06,1140,BYU,0.453333,0.298667,0.130333,0.027333,0.009333,0.004333
21,Z06,1281,Missouri,0.637333,0.353333,0.139667,0.056333,0.015667,0.003667
22,Y07,1266,Marquette,0.644000,0.208000,0.098000,0.037000,0.011000,0.003333
23,Y11,1314,North Carolina,0.485333,0.242000,0.134000,0.041667,0.012333,0.002667
24,W09,1124,Baylor,0.678333,0.087000,0.049333,0.020000,0.007333,0.002667

Get public brackets

In [17]:
df_public = pd.read_parquet(f'..\data\preprocessed\mens_yahoo\yahoo_picks_{SEASON}.parquet')

df_public.sort_values(by=['Round 6'], ascending=False, ignore_index=True).head(10)

,TeamID,Team,Region Seed,Seed,Region,Play In,Round 1,Round 2,Round 3,Round 4,Round 5,Round 6
0,1181,Duke,W01,1,W,False,0.9824,0.9384,0.8302,0.6701,0.5118,0.3098
1,1196,Florida,Z01,1,Z,False,0.9796,0.8744,0.7791,0.5926,0.4047,0.2116
2,1120,Auburn,Y01,1,Y,False,0.9829,0.8852,0.7440,0.5176,0.2264,0.1059
3,1222,Houston,X01,1,X,False,0.9769,0.8084,0.6905,0.4673,0.1732,0.0888
4,1385,St. John's,Z02,2,Z,False,0.9591,0.7382,0.5379,0.1900,0.1058,0.0466
5,1277,Michigan St.,Y02,2,Y,False,0.9690,0.8458,0.6387,0.2754,0.1015,0.0416
6,1397,Tennessee,X02,2,X,False,0.9642,0.8374,0.6155,0.2608,0.0820,0.0321
7,1104,Alabama,W02,2,W,False,0.9672,0.8488,0.6167,0.1756,0.0818,0.0304
8,1246,Kentucky,X03,3,X,False,0.9440,0.6825,0.2419,0.1090,0.0379,0.0154
9,1458,Wisconsin,W03,3,W,False,0.9398,0.6532,0.2310,0.0552,0.0232,0.0098

R1X1: (1, 16)
R2X1: (1, 8, 9, 16)
R3X1: (1, 4, 5, 8, 9, 12, 13, 16)
R4X1: (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)

R1X2: (2, 15)
R2X2: (2, 7, 10, 15)
R3X2: (2, 3, 6, 7, 10, 11, 14, 15)

R1X3: (3, 14)
R2X3: (3, 6, 11, 14)

R1X4: (4, 13)
R2X4: (4, 5, 12, 13)

R1X5: (5, 12)

R1X6: (6, 11)

R1X7: (7, 10)

R1X8: (8, 9)

Partition data into possible areas in advance

In [18]:
public_dict = {
    # ROUND 6
    'R6CH': df_public.loc[:, ['Region Seed', 'Region', 'Seed', 'Round 6']].rename(columns={'Round 6': 'P'}).reset_index(drop=True),

    # ROUND 5
    'R5WX': df_public.loc[df_public['Region'].isin(('W', 'X')), ['Region Seed', 'Region', 'Seed', 'Round 5']].rename(columns={'Round 5': 'P'}).reset_index(drop=True),
    'R5YZ': df_public.loc[df_public['Region'].isin(('Y', 'Z')), ['Region Seed', 'Region', 'Seed', 'Round 5']].rename(columns={'Round 5': 'P'}).reset_index(drop=True),
}

# ROUND 4
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R4{region}1'] = df_public.loc[df_public['Region'] == region, ['Region Seed', 'Region', 'Seed', 'Round 4']].rename(columns={'Round 4': 'P'}).reset_index(drop=True)

# ROUND 3
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R3{region}1'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((1, 4, 5, 8, 9, 12, 13, 16))), ['Region Seed', 'Region', 'Seed', 'Round 3']].rename(columns={'Round 3': 'P'}).reset_index(drop=True)
    public_dict[f'R3{region}2'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((2, 3, 6, 7, 10, 11, 14, 15))), ['Region Seed', 'Region', 'Seed', 'Round 3']].rename(columns={'Round 3': 'P'}).reset_index(drop=True)

# ROUND 2
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R2{region}1'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((1, 8, 9, 16))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}2'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((2, 7, 10, 15))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}3'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((3, 6, 11, 14))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}4'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((4, 5, 12, 13))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)

# ROUND 1
for region in ('W', 'X', 'Y', 'Z'):
    for i in range(1, 9):
        public_dict[f'R1{region}{i}'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((i, 17-i))), ['Region Seed', 'Region', 'Seed', 'Round 1']].rename(columns={'Round 1': 'P'}).reset_index(drop=True)

for key, value in public_dict.items():  # make sure probabilities add to 1
    # print(value['P'].sum())

    value['P'] = value['P']/value['P'].sum()
    public_dict[key] = value

    # print(value['P'].sum())
    # print()

public_dict

{'R6CH':    Region Seed Region  Seed         P
 0          W13      W    13  0.000399
 1          W02      W     2  0.030345
 2          Y16      Y    16  0.000599
 3          W04      W     4  0.006688
 4          Z10      Z    10  0.000898
 ..         ...    ...   ...       ...
 59         W03      W     3  0.009782
 60         X15      X    15  0.000399
 61         X11      X    11  0.000799
 62         Y13      Y    13  0.001697
 63         Y12      Y    12  0.000898

 [64 rows x 4 columns],
 'R5WX':    Region Seed Region  Seed         P
 0          W13      W    13  0.000799
 1          W02      W     2  0.081726
 2          W04      W     4  0.015086
 3          W09      W     9  0.002198
 4          W06      W     6  0.003297
 5          X05      X     5  0.010191
 6          W01      W     1  0.511340
 7          X16      X    16  0.000899
 8          X09      X     9  0.005495
 9          X08      X     8  0.009991
 10         X13      X    13  0.000699
 11         X01      X     1  0.173044
 12         X06      X     6  0.004696
 13         X03      X     3  0.037866
 14         W12      W    12  0.000899
 15         X12      X    12  0.000799
 16         W08      W     8  0.000999
 17         W14      W    14  0.000699
 18         W16      W    16  0.001299
 19         W05      W     5  0.007593
 20         X04      X     4  0.010391
 21         W15      W    15  0.000599
 22         W07      W     7  0.001998
 23         X02      X     2  0.081926
 24         X14      X    14  0.000699
 25         X07      X     7  0.005495
 26         X10      X    10  0.000899
 27         W11      W    11  0.001099
 28         W10      W    10  0.001299
 29         W03      W     3  0.023179
 30         X15      X    15  0.000999
 31         X11      X    11  0.001798,
 'R5YZ':    Region Seed Region  Seed         P
 0          Y16      Y    16  0.001398
 1          Z10      Z    10  0.001897
 2          Y01      Y     1  0.226038
 3          Y15      Y    15  0.000699
 4          Z12      Z    12  0.001098
 5          Z08      Z     8  0.012879
 6          Y09      Y     9  0.002296
 7          Z11      Z    11  0.001897
 8          Z01      Z     1  0.404054
 9          Z13      Z    13  0.000899
 10         Y03      Y     3  0.019069
 11         Z07      Z     7  0.016573
 12         Y14      Y    14  0.000599
 13         Y08      Y     8  0.003694
 14         Y07      Y     7  0.003195
 15         Z04      Z     4  0.015775
 16         Z05      Z     5  0.004992
 17         Y05      Y     5  0.018670
 18         Y02      Y     2  0.101338
 19         Y06      Y     6  0.005491
 20         Z06      Z     6  0.003195
 21         Z15      Z    15  0.000799
 22         Y10      Y    10  0.000998
 23         Z16      Z    16  0.000799
 24         Y11      Y    11  0.006589
 25         Z09      Z     9  0.001697
 26         Z02      Z     2  0.105631
 27         Y04      Y     4  0.008187
 28         Z03      Z     3  0.024261
 29         Z14      Z    14  0.000699
 30         Y13      Y    13  0.002796
 31         Y12      Y    12  0.001797,
 'R4W1':    Region Seed Region  Seed         P
 0          W13      W    13  0.001904
 1          W02      W     2  0.175987
 2          W04      W     4  0.037883
 3          W09      W     9  0.005813
 4          W06      W     6  0.009721
 5          W01      W     1  0.671577
 6          W12      W    12  0.002105
 7          W08      W     8  0.002706
 8          W14      W    14  0.001704
 9          W16      W    16  0.002906
 10         W05      W     5  0.018541
 11         W15      W    15  0.001704
 12         W07      W     7  0.005913
 13         W11      W    11  0.002806
 14         W10      W    10  0.003407
 15         W03      W     3  0.055322,
 'R4X1':    Region Seed Region  Seed         P
 0          X05      X     5  0.038003
 1          X16      X    16  0.001905
 2          X09      X     9  0.009526
 3          X08      X     8  0.031786
 4          X13      X    13  0.002005
 5          X01      X     1  0.468565
 6          X06      X     6  0.015743
 7          X03      X     3  0.109295
 8          X12      X    12  0.002106
 9          X04      X     4  0.031786
 10         X02      X     2  0.261506
 11         X14      X    14  0.001604
 12         X07      X     7  0.017447
 13         X10      X    10  0.002306
 14         X15      X    15  0.002005
 15         X11      X    11  0.004412,
 'R4Y1':    Region Seed Region  Seed         P
 0          Y16      Y    16  0.002892
 1          Y01      Y     1  0.516103
 2          Y15      Y    15  0.001795
 3          Y09      Y     9  0.006681
 4          Y03      Y     3  0.059527
 5          Y14      Y    14  0.001496
 6          Y08      Y     8  0.015156
 7          Y07      Y     7  0.009772
 8          Y05      Y     5  0.045069
 9          Y02      Y     2  0.274604
 10         Y06      Y     6  0.011267
 11         Y10      Y    10  0.002991
 12         Y11      Y    11  0.017948
 13         Y04      Y     4  0.025526
 14         Y13      Y    13  0.004686
 15         Y12      Y    12  0.004487,
 'R4Z1':    Region Seed Region  Seed         P
 0          Z10      Z    10  0.004715
 1          Z12      Z    12  0.002809
 2          Z08      Z     8  0.024679
 3          Z11      Z    11  0.004715
 4          Z01      Z     1  0.594502
 5          Z13      Z    13  0.002207
 6          Z07      Z     7  0.031100
 7          Z04      Z     4  0.042737
 8          Z05      Z     5  0.013844
 9          Z06      Z     6  0.008929
 10         Z15      Z    15  0.001906
 11         Z16      Z    16  0.001906
 12         Z09      Z     9  0.004213
 13         Z02      Z     2  0.190610
 14         Z03      Z     3  0.069422
 15         Z14      Z    14  0.001705,
 'R3W1':   Region Seed Region  Seed         P
 0         W13      W    13  0.004707
 1         W04      W     4  0.086930
 2         W09      W     9  0.013320
 3         W01      W     1  0.831447
 4         W12      W    12  0.005008
 5         W08      W     8  0.007211
 6         W16      W    16  0.005108
 7         W05      W     5  0.046269,
 'R3W2':   Region Seed Region  Seed         P
 0         W02      W     2  0.619115
 1         W06      W     6  0.073286
 2         W14      W    14  0.004718
 3         W15      W    15  0.004718
 4         W07      W     7  0.033029
 5         W11      W    11  0.016063
 6         W10      W    10  0.017167
 7         W03      W     3  0.231904,
 'R3X1':   Region Seed Region  Seed         P
 0         X05      X     5  0.103144
 1         X16      X    16  0.003515
 2         X09      X     9  0.021894
 3         X08      X     8  0.075826
 4         X13      X    13  0.004921
 5         X01      X     1  0.693482
 6         X12      X    12  0.005624
 7         X04      X     4  0.091594,
 'R3X2':   Region Seed Region  Seed         P
 0         X06      X     6  0.064755
 1         X03      X     3  0.241731
 2         X02      X     2  0.615069
 3         X14      X    14  0.004097
 4         X07      X     7  0.045668
 5         X10      X    10  0.007994
 6         X15      X    15  0.005296
 7         X11      X    11  0.015389,
 'R3Y1':   Region Seed Region  Seed         P
 0         Y16      Y    16  0.005098
 1         Y01      Y     1  0.743777
 2         Y09      Y     9  0.017895
 3         Y08      Y     8  0.037389
 4         Y05      Y     5  0.112566
 5         Y04      Y     4  0.063681
 6         Y13      Y    13  0.008797
 7         Y12      Y    12  0.010797,
 'R3Y2':   Region Seed Region  Seed         P
 0         Y15      Y    15  0.005151
 1         Y03      Y     3  0.204260
 2         Y14      Y    14  0.003962
 3         Y07      Y     7  0.042694
 4         Y02      Y     2  0.632689
 5         Y06      Y     6  0.047746
 6         Y10      Y    10  0.011392
 7         Y11      Y    11  0.052105,
 'R3Z1':   Region Seed Region  Seed         P
 0         Z12      Z    12  0.007325
 1         Z08      Z     8  0.059803
 2         Z01      Z     1  0.781758
 3         Z13      Z    13  0.005418
 4         Z04      Z     4  0.093819
 5         Z05      Z     5  0.037929
 6         Z16      Z    16  0.003412
 7         Z09      Z     9  0.010536,
 'R3Z2':   Region Seed Region  Seed         P
 0         Z10      Z    10  0.019671
 1         Z11      Z    11  0.021377
 2         Z07      Z     7  0.095544
 3         Z06      Z     6  0.049077
 4         Z15      Z    15  0.005018
 5         Z02      Z     2  0.539843
 6         Z03      Z     3  0.265054
 7         Z14      Z    14  0.004416,
 'R2W1':   Region Seed Region  Seed       P
 0         W09      W     9  0.0338
 1         W01      W     1  0.9384
 2         W08      W     8  0.0179
 3         W16      W    16  0.0099,
 'R2W2':   Region Seed Region  Seed         P
 0         W02      W     2  0.852294
 1         W15      W    15  0.010443
 2         W07      W     7  0.088664
 3         W10      W    10  0.048599,
 'R2W3':   Region Seed Region  Seed         P
 0         W06      W     6  0.239932
 1         W14      W    14  0.016772
 2         W11      W    11  0.087275
 3         W03      W     3  0.656021,
 'R2W4':   Region Seed Region  Seed         P
 0         W13      W    13  0.034448
 1         W04      W     4  0.589736
 2         W12      W    12  0.041579
 3         W05      W     5  0.334237,
 'R2X1':   Region Seed Region  Seed         P
 0         X16      X    16  0.006731
 1         X09      X     9  0.049628
 2         X08      X     8  0.131505
 3         X01      X     1  0.812136,
 'R2X2':   Region Seed Region  Seed         P
 0         X02      X     2  0.841354
 1         X07      X     7  0.120165
 2         X10      X    10  0.027429
 3         X15      X    15  0.011052,
 'R2X3':   Region Seed Region  Seed         P
 0         X06      X     6  0.233337
 1         X03      X     3  0.664104
 2         X14      X    14  0.014498
 3         X11      X    11  0.088061,
 'R2X4':   Region Seed Region  Seed         P
 0         X05      X     5  0.518693
 1         X13      X    13  0.033769
 2         X12      X    12  0.049548
 3         X04      X     4  0.397990,
 'R2Y1':   Region Seed Region  Seed         P
 0         Y16      Y    16  0.010183
 1         Y01      Y     1  0.883698
 2         Y09      Y     9  0.041030
 3         Y08      Y     8  0.065089,
 'R2Y2':   Region Seed Region  Seed         P
 0         Y15      Y    15  0.011416
 1         Y07      Y     7  0.106449
 2         Y02      Y     2  0.846986
 3         Y10      Y    10  0.035149,
 'R2Y3':   Region Seed Region  Seed         P
 0         Y03      Y     3  0.607481
 1         Y14      Y    14  0.015246
 2         Y06      Y     6  0.162311
 3         Y11      Y    11  0.214962,
 'R2Y4':   Region Seed Region  Seed         P
 0         Y05      Y     5  0.498698
 1         Y04      Y     4  0.350661
 2         Y13      Y    13  0.052684
 3         Y12      Y    12  0.097957,
 'R2Z1':   Region Seed Region  Seed         P
 0         Z08      Z     8  0.092834
 1         Z01      Z     1  0.877559
 2         Z16      Z    16  0.006825
 3         Z09      Z     9  0.022782,
 'R2Z2':   Region Seed Region  Seed         P
 0         Z10      Z    10  0.058015
 1         Z07      Z     7  0.189802
 2         Z15      Z    15  0.011242
 3         Z02      Z     2  0.740941,
 'R2Z3':   Region Seed Region  Seed         P
 0         Z11      Z    11  0.114960
 1         Z06      Z     6  0.176807
 2         Z03      Z     3  0.691968
 3         Z14      Z    14  0.016265,
 'R2Z4':   Region Seed Region  Seed         P
 0         Z12      Z    12  0.080337
 1         Z13      Z    13  0.038361
 2         Z04      Z     4  0.599518
 3         Z05      Z     5  0.281783,
 'R1W1':   Region Seed Region  Seed         P
 0         W01      W     1  0.977999
 1         W16      W    16  0.022001,
 'R1W2':   Region Seed Region  Seed         P
 0         W02      W     2  0.971377
 1         W15      W    15  0.028623,
 'R1W3':   Region Seed Region  Seed         P
 0         W14      W    14  0.055857
 1         W03      W     3  0.944143,
 'R1W4':   Region Seed Region  Seed         P
 0         W13      W    13  0.110318
 1         W04      W     4  0.889682,
 'R1W5':   Region Seed Region  Seed         P
 0         W12      W    12  0.177771
 1         W05      W     5  0.822229,
 'R1W6':   Region Seed Region  Seed        P
 0         W06      W     6  0.64519
 1         W11      W    11  0.35481,
 'R1W7':   Region Seed Region  Seed         P
 0         W07      W     7  0.583777
 1         W10      W    10  0.416223,
 'R1W8':   Region Seed Region  Seed         P
 0         W09      W     9  0.622776
 1         W08      W     8  0.377224,
 'R1X1':   Region Seed Region  Seed         P
 0         X16      X    16  0.018388
 1         X01      X     1  0.981612,
 'R1X2':   Region Seed Region  Seed         P
 0         X02      X     2  0.969143
 1         X15      X    15  0.030857,
 'R1X3':   Region Seed Region  Seed         P
 0         X03      X     3  0.949316
 1         X14      X    14  0.050684,
 'R1X4':   Region Seed Region  Seed         P
 0         X13      X    13  0.155486
 1         X04      X     4  0.844514,
 'R1X5':   Region Seed Region  Seed         P
 0         X05      X     5  0.852344
 1         X12      X    12  0.147656,
 'R1X6':   Region Seed Region  Seed         P
 0         X06      X     6  0.670827
 1         X11      X    11  0.329173,
 'R1X7':   Region Seed Region  Seed         P
 0         X07      X     7  0.687192
 1         X10      X    10  0.312808,
 'R1X8':   Region Seed Region  Seed         P
 0         X09      X     9  0.264709
 1         X08      X     8  0.735291,
 'R1Y1':   Region Seed Region  Seed         P
 0         Y16      Y    16  0.023836
 1         Y01      Y     1  0.976164,
 'R1Y2':   Region Seed Region  Seed         P
 0         Y15      Y    15  0.029836
 1         Y02      Y     2  0.970164,
 'R1Y3':   Region Seed Region  Seed       P
 0         Y03      Y     3  0.9374
 1         Y14      Y    14  0.0626,
 'R1Y4':   Region Seed Region  Seed         P
 0         Y04      Y     4  0.764123
 1         Y13      Y    13  0.235877,
 'R1Y5':   Region Seed Region  Seed         P
 0         Y05      Y     5  0.770255
 1         Y12      Y    12  0.229745,
 'R1Y6':   Region Seed Region  Seed        P
 0         Y06      Y     6  0.47743
 1         Y11      Y    11  0.52257,
 'R1Y7':   Region Seed Region  Seed         P
 0         Y07      Y     7  0.650967
 1         Y10      Y    10  0.349033,
 'R1Y8':   Region Seed Region  Seed         P
 0         Y09      Y     9  0.436843
 1         Y08      Y     8  0.563157,
 'R1Z1':   Region Seed Region  Seed         P
 0         Z01      Z     1  0.983238
 1         Z16      Z    16  0.016762,
 'R1Z2':   Region Seed Region  Seed         P
 0         Z15      Z    15  0.036855
 1         Z02      Z     2  0.963145,
 'R1Z3':   Region Seed Region  Seed         P
 0         Z03      Z     3  0.943434
 1         Z14      Z    14  0.056566,
 'R1Z4':   Region Seed Region  Seed         P
 0         Z13      Z    13  0.123681
 1         Z04      Z     4  0.876319,
 'R1Z5':   Region Seed Region  Seed        P
 0         Z12      Z    12  0.33953
 1         Z05      Z     5  0.66047,
 'R1Z6':   Region Seed Region  Seed         P
 0         Z11      Z    11  0.417789
 1         Z06      Z     6  0.582211,
 'R1Z7':   Region Seed Region  Seed        P
 0         Z10      Z    10  0.34794
 1         Z07      Z     7  0.65206,
 'R1Z8':   Region Seed Region  Seed         P
 0         Z08      Z     8  0.719654
 1         Z09      Z     9  0.280346}

In [19]:
def fill_in_team(bracket: dict, round_: int, team: str, region: str, seed: int) -> dict:
    """
    Helper for simulate_public
    Fill in previous rounds of bracket for a team that wins in a future round
    """
    for r in range(1, min(round_ + 1, 4)):
        if seed > 2**(4-r):
            seed = 2**(5-r) + 1 - seed
        bracket[f'R{r}{region}{seed}'] = team

    if round_ >= 4:
        bracket[f'R4{region}1'] = team
    if round_ >= 5:
        if region in ('W', 'X'):
            bracket[f'R5WX'] = team
        else:
            bracket[f'R5YZ'] = team
    if round_ == 6:
        bracket[f'R6CH'] = team

    return bracket


def simulate_public():
    """
    Get bracket based on probabilities of winning each round
    """
    bracket = dict()

    # ROUND 6
    for matchup in ('R6CH', ):
        if not bracket.get(matchup):
            df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
            winner = df_matchup.loc[
                np.random.choice(
                    df_matchup.index,
                    p=df_matchup['P'],
                ),
                :
            ]
            bracket = fill_in_team(bracket, 6, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 5
    for matchup in ('R5WX', 'R5YZ'):
        if not bracket.get(matchup):
            df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
            winner = df_matchup.loc[
                np.random.choice(
                    df_matchup.index,
                    p=df_matchup['P'],
                ),
                :
            ]
            bracket = fill_in_team(bracket, 5, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 4
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 2):
            matchup = f'R4{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 4, winner['Region Seed'], winner['Region'], winner['Seed'])



    # ROUND 3
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 3):
            matchup = f'R3{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 3, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 2
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 5):
            matchup = f'R2{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 2, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 1
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 9):
            matchup = f'R1{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 1, winner['Region Seed'], winner['Region'], winner['Seed'])

    return dict(sorted(bracket.items()))

simulate_public()

{'R1W1': 'W01',
 'R1W2': 'W02',
 'R1W3': 'W03',
 'R1W4': 'W04',
 'R1W5': 'W12',
 'R1W6': 'W11',
 'R1W7': 'W10',
 'R1W8': 'W08',
 'R1X1': 'X01',
 'R1X2': 'X02',
 'R1X3': 'X03',
 'R1X4': 'X04',
 'R1X5': 'X05',
 'R1X6': 'X06',
 'R1X7': 'X07',
 'R1X8': 'X08',
 'R1Y1': 'Y01',
 'R1Y2': 'Y02',
 'R1Y3': 'Y03',
 'R1Y4': 'Y04',
 'R1Y5': 'Y05',
 'R1Y6': 'Y06',
 'R1Y7': 'Y07',
 'R1Y8': 'Y09',
 'R1Z1': 'Z01',
 'R1Z2': 'Z02',
 'R1Z3': 'Z03',
 'R1Z4': 'Z04',
 'R1Z5': 'Z05',
 'R1Z6': 'Z06',
 'R1Z7': 'Z07',
 'R1Z8': 'Z08',
 'R2W1': 'W01',
 'R2W2': 'W02',
 'R2W3': 'W03',
 'R2W4': 'W04',
 'R2X1': 'X01',
 'R2X2': 'X02',
 'R2X3': 'X03',
 'R2X4': 'X05',
 'R2Y1': 'Y01',
 'R2Y2': 'Y02',
 'R2Y3': 'Y03',
 'R2Y4': 'Y05',
 'R2Z1': 'Z01',
 'R2Z2': 'Z02',
 'R2Z3': 'Z06',
 'R2Z4': 'Z05',
 'R3W1': 'W01',
 'R3W2': 'W02',
 'R3X1': 'X01',
 'R3X2': 'X03',
 'R3Y1': 'Y01',
 'R3Y2': 'Y02',
 'R3Z1': 'Z01',
 'R3Z2': 'Z06',
 'R4W1': 'W01',
 'R4X1': 'X03',
 'R4Y1': 'Y02',
 'R4Z1': 'Z01',
 'R5WX': 'W01',
 'R5YZ': 'Z01',
 'R6CH': 'W01'}

In [ ]:
np.random.seed(24)

public = tuple(simulate_public() for _ in trange(20_000))  # set back to 20_000

len(public)

  0%|          | 0/2000 [00:00<?, ?it/s]

2000

In [ ]:
np.random.seed(25)

# used as candidate brackets in the simulations as opposed to competition
public_candidates = tuple(simulate_public() for _ in trange(20_000))  # set back to 20_000

len(public_candidates)

  0%|          | 0/2000 [00:00<?, ?it/s]

2000

### Save

Use both brackets generated from my probabilties as well as public probabilities as candidates

In [ ]:
candidates = my_candidates + public_candidates

len(candidates)

4000

Convert to custom bracket class

In [24]:
from bracket import Bracket

result_brackets = [
    Bracket(picks=r, classification='result')
    for r in results
]

candidate_brackets = [
    Bracket(picks=c, classification='candidate')
    for c in candidates
]

public_brackets = [
    Bracket(picks=p, classification='public')
    for p in public
]

len(result_brackets), len(candidate_brackets), len(public_brackets)

(3000, 4000, 2000)

In [25]:
simulation_data = {
    'result_brackets': result_brackets,
    'candidate_brackets': candidate_brackets,
    'public_brackets': public_brackets,
}

len(simulation_data)

3

In [26]:
import pickle

with open(f'../data/simulations/mens/mens_simulation_{SEASON}.pkl', 'wb') as f:
    pickle.dump(simulation_data, f)

'Done'

'Done'