# Simulate Women's Tourney

Generated brackets based on model probabilities and public picks.

In [1]:
season = 2024

playin_losers = (  # remove play-in losers from seeding data
    3357,  # Sacred Heart
    3162,  # Columbia
    3120,  # Auburn
    3221,  # Holy Cross
)

season

2024

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 100)

df_seeds = pd.read_csv(r'..\data\unprocessed\kaggle\WNCAATourneySeeds.csv')

df_seeds = df_seeds.loc[df_seeds['Season'] == season, :].reset_index(drop=True)

df_seeds.insert(2, 'Play In', df_seeds['Seed'].str.endswith(('a', 'b')))
df_seeds.insert(2, 'Region', df_seeds['Seed'].str[0])
df_seeds['Seed'] = df_seeds['Seed'].str.extract('(\d+)').astype(int)

df_seeds = df_seeds.loc[~df_seeds['TeamID'].isin(playin_losers), :].reset_index(drop=True)

df_seeds.insert(1, 'Region Seed', df_seeds['Region'] + df_seeds['Seed'].astype(str).str.zfill(2))

df_seeds

    Season Region Seed  Seed Region  Play In  TeamID
0     2024         W01     1      W    False    3376
1     2024         W02     2      W    False    3323
2     2024         W03     3      W    False    3333
3     2024         W04     4      W    False    3231
4     2024         W05     5      W    False    3328
..     ...         ...   ...    ...      ...     ...
59    2024         Z12    12      Z     True    3435
60    2024         Z13    13      Z    False    3267
61    2024         Z14    14      Z    False    3238
62    2024         Z15    15      Z    False    3263
63    2024         Z16    16      Z    False    3394

[64 rows x 6 columns]

### Simulate Tournament

I think it might make more sense to just go through all 63 matchups as a dictionary, adding future rounds as you go

In [3]:
df_matrix = pd.read_csv(
    fr'../data/simulations/womens/matchup_matrix_{season}.csv',
    index_col='Team A ID',
).rename_axis(index=None)

df_matrix.columns = df_matrix.columns.astype(int)

df_matrix

,3104,3112,3124,3151,3160,3163,3166,3179,3180,3181,3186,3193,3195,3199,3211,3231,3234,3235,3238,3242,3243,3245,3257,3261,3263,3266,3267,3268,3276,3277,3279,3292,3301,3304,3313,3314,3323,3326,3328,3333,3339,3342,3343,3349,3350,3355,3376,3390,3393,3394,3397,3400,3401,3404,3414,3417,3424,3425,3428,3435,3439,3452,3453,3465
3104,NaN,0.532997,0.249733,0.911312,0.287490,0.060767,0.263217,0.757277,0.939226,0.339851,0.843883,0.769793,0.755994,0.713223,0.159887,0.199885,0.129346,0.323671,0.901078,0.556624,0.328798,0.912412,0.427827,0.126153,0.906912,0.720253,0.875179,0.305022,0.592935,0.298313,0.258396,0.650989,0.250148,0.363112,0.913919,0.701439,0.189810,0.227775,0.417078,0.247650,0.904595,0.945322,0.271104,0.910248,0.687948,0.725120,0.044177,0.086894,0.411898,0.935744,0.192831,0.096851,0.787665,0.945322,0.901803,0.095206,0.400177,0.114796,0.251800,0.806672,0.237100,0.286561,0.632046,0.909813
3112,0.480005,NaN,0.189306,0.898269,0.209489,0.060374,0.340888,0.732107,0.938253,0.424383,0.886452,0.783818,0.587739,0.534685,0.148066,0.232907,0.171487,0.294280,0.897776,0.564971,0.390246,0.905568,0.219911,0.188280,0.904404,0.676189,0.838644,0.309033,0.701832,0.390467,0.326349,0.614654,0.178955,0.381232,0.900449,0.642775,0.225943,0.168489,0.356969,0.177679,0.911950,0.939226,0.290089,0.905390,0.696587,0.693748,0.053877,0.097138,0.622267,0.936615,0.273165,0.056927,0.666493,0.945322,0.904336,0.059718,0.356105,0.173255,0.478563,0.772999,0.220346,0.323573,0.679878,0.887245
3124,0.748752,0.803946,NaN,0.937486,0.548478,0.208890,0.607361,0.833349,0.947569,0.685611,0.937773,0.852589,0.829175,0.823742,0.439406,0.297466,0.330532,0.449882,0.941533,0.609436,0.427169,0.947569,0.575627,0.380014,0.941533,0.839137,0.906775,0.692016,0.819544,0.643562,0.778328,0.795038,0.325023,0.743341,0.941708,0.803509,0.440911,0.373830,0.571296,0.532993,0.945322,0.947569,0.644335,0.947569,0.754775,0.834375,0.104429,0.208680,0.756305,0.947569,0.645220,0.211807,0.830868,0.947569,0.938335,0.287360,0.688819,0.429310,0.652405,0.820050,0.471147,0.760014,0.863159,0.937486
3151,0.082206,0.094270,0.056459,NaN,0.061657,0.053877,0.071359,0.190050,0.529344,0.065247,0.344508,0.151159,0.165485,0.094919,0.064937,0.060211,0.054683,0.100120,0.315344,0.100694,0.056251,0.590250,0.066844,0.053877,0.579655,0.103103,0.164650,0.093328,0.174084,0.079225,0.082647,0.144620,0.056459,0.111986,0.694115,0.094406,0.053877,0.056459,0.070057,0.056459,0.378566,0.919002,0.076514,0.346016,0.080298,0.173390,0.053877,0.056459,0.097231,0.770115,0.082769,0.053877,0.179794,0.828771,0.558375,0.056251,0.160360,0.053877,0.061657,0.190954,0.063989,0.062691,0.174638,0.413474
3160,0.728141,0.800520,0.431396,0.935743,NaN,0.179666,0.548692,0.856991,0.941708,0.654539,0.933405,0.836665,0.860307,0.772893,0.281971,0.319561,0.214886,0.705190,0.933405,0.764086,0.694905,0.941405,0.464705,0.437306,0.933566,0.777216,0.880960,0.552544,0.765931,0.629560,0.718388,0.845459,0.275151,0.703314,0.941405,0.763888,0.365402,0.285737,0.713073,0.481539,0.934423,0.945976,0.626299,0.932137,0.794507,0.859738,0.079313,0.361716,0.768334,0.941533,0.575595,0.178928,0.830583,0.947569,0.930024,0.136005,0.806238,0.198768,0.487155,0.836120,0.393977,0.659902,0.876468,0.935899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3435,0.155184,0.220001,0.162151,0.792756,0.151203,0.057468,0.235429,0.446588,0.903269,0.219190,0.750618,0.788828,0.272283,0.224193,0.201882,0.197371,0.089477,0.372586,0.761656,0.263710,0.154109,0.885941,0.200270,0.096008,0.877987,0.284474,0.619029,0.225570,0.264431,0.235325,0.121804,0.273877,0.104532,0.230050,0.887861,0.235213,0.066831,0.135847,0.249267,0.075928,0.829524,0.937329,0.196449,0.884709,0.321448,0.489528,0.046742,0.058325,0.232032,0.904378,0.137124,0.057468,0.460447,0.945391,0.864020,0.054415,0.244869,0.087396,0.229814,NaN,0.203627,0.208077,0.282095,0.867973
3439,0.760563,0.777355,0.515315,0.934547,0.606480,0.186752,0.731288,0.793408,0.947569,0.444084,0.908704,0.862091,0.796219,0.597322,0.274440,0.309955,0.150022,0.742367,0.941708,0.848133,0.615180,0.935912,0.723930,0.150047,0.941405,0.796219,0.905307,0.683985,0.794700,0.602358,0.745284,0.777355,0.589023,0.760563,0.939211,0.862293,0.258652,0.384140,0.724351,0.476549,0.933910,0.947569,0.725284,0.944732,0.825269,0.793343,0.077218,0.178174,0.847395,0.938574,0.718142,0.199574,0.778472,0.947569,0.938574,0.228867,0.713993,0.478989,0.457353,0.789956,NaN,0.615790,0.898809,0.934706
3452,0.724247,0.663148,0.207255,0.933803,0.327675,0.128689,0.492384,0.769254,0.929638,0.631183,0.925866,0.838602,0.749545,0.781616,0.221476,0.260292,0.217496,0.350410,0.927915,0.807847,0.255884,0.937590,0.415270,0.215147,0.930024,0.782581,0.893541,0.496931,0.680939,0.532079,0.724300,0.689912,0.251665,0.645680,0.938168,0.660146,0.199843,0.242545,0.796775,0.295155,0.931876,0.938806,0.494181,0.928165,0.752220,0.781275,0.085288,0.190198,0.739125,0.939013,0.478569,0.121928,0.781391,0.945322,0.938110,0.187047,0.573253,0.219911,0.287323,0.790677,0.388004,NaN,0.809369,0.933595
3453,0.333773,0.253427,0.128993,0.818421,0.121319,0.060374,0.270530,0.549035,0.847536,0.246831,0.783842,0.678693,0.445852,0.295741,0.101764,0.092530,0.073179,0.156114,0.769280,0.351320,0.190838,0.772608,0.103496,0.082576,0.765852,0.485440,0.725684,0.146630,0.344080,0.224576,0.361663,0.342941,0.134140,0.276563,0.785619,0.250391,0.069734,0.085079,0.203897,0.098051,0.804381,0.934918,0.143024,0.789496,0.686260,0.522169,0.053877,0.075214,0.439335,0.862681,0.119329,0.061085,0.501948,0.934546,0.830473,0.077670,0.233066,0.094726,0.119001,0.700160,0.088205,0.190080,NaN,0.802325
3465,0.083554,0.100242,0.060597,0.457379,0.061657,0.057468,0.068364,0.092562,0.705739,0.065247,0.442264,0.148859,0.090221,0.094611,0.063989,0.060211,0.053877,0.082186,0.387070,0.100628,0.059991,0.325787,0.061657,0.053877,0.448577,0.105556,0.234723,0.110196,0.104056,0.079550,0.083879,0.079632,0.056459,0.061657,0.550186,0.094245,0.053877,0.060211,0.061657,0.062200,0.645275,0.925799,0.077427,0.360957,0.121232,0.090221,0.053877,0.056459,0.095054,0.751537,0.061657,0.053877,0.096540,0.895431,0.488949,0.056812,0.087572,0.053877,0.061657,0.126918,0.066094,0.064859,0.199573,NaN

In [4]:
id_to_region_seed = dict(zip(df_seeds['TeamID'], df_seeds['Region Seed']))

df_matrix.index = df_matrix.index.map(id_to_region_seed)
df_matrix.columns = df_matrix.columns.map(id_to_region_seed)

df_matrix

,X08,Z11,Z05,X14,Y05,Z03,Y07,Y12,X16,Z07,W14,W13,W12,X09,X04,W04,Y01,X07,Z14,Z08,Y04,W15,Y06,Y03,Z15,W10,Z13,X10,Z09,W09,W07,Y11,X03,W06,X15,W08,W02,Z02,W05,W03,Y13,W16,Y09,Y14,Z10,X12,W01,X02,Z06,Z16,X06,X01,W11,Y16,X13,Y02,Y10,Z01,X05,Z12,Z04,Y08,X11,Y15
X08,NaN,0.532997,0.249733,0.911312,0.287490,0.060767,0.263217,0.757277,0.939226,0.339851,0.843883,0.769793,0.755994,0.713223,0.159887,0.199885,0.129346,0.323671,0.901078,0.556624,0.328798,0.912412,0.427827,0.126153,0.906912,0.720253,0.875179,0.305022,0.592935,0.298313,0.258396,0.650989,0.250148,0.363112,0.913919,0.701439,0.189810,0.227775,0.417078,0.247650,0.904595,0.945322,0.271104,0.910248,0.687948,0.725120,0.044177,0.086894,0.411898,0.935744,0.192831,0.096851,0.787665,0.945322,0.901803,0.095206,0.400177,0.114796,0.251800,0.806672,0.237100,0.286561,0.632046,0.909813
Z11,0.480005,NaN,0.189306,0.898269,0.209489,0.060374,0.340888,0.732107,0.938253,0.424383,0.886452,0.783818,0.587739,0.534685,0.148066,0.232907,0.171487,0.294280,0.897776,0.564971,0.390246,0.905568,0.219911,0.188280,0.904404,0.676189,0.838644,0.309033,0.701832,0.390467,0.326349,0.614654,0.178955,0.381232,0.900449,0.642775,0.225943,0.168489,0.356969,0.177679,0.911950,0.939226,0.290089,0.905390,0.696587,0.693748,0.053877,0.097138,0.622267,0.936615,0.273165,0.056927,0.666493,0.945322,0.904336,0.059718,0.356105,0.173255,0.478563,0.772999,0.220346,0.323573,0.679878,0.887245
Z05,0.748752,0.803946,NaN,0.937486,0.548478,0.208890,0.607361,0.833349,0.947569,0.685611,0.937773,0.852589,0.829175,0.823742,0.439406,0.297466,0.330532,0.449882,0.941533,0.609436,0.427169,0.947569,0.575627,0.380014,0.941533,0.839137,0.906775,0.692016,0.819544,0.643562,0.778328,0.795038,0.325023,0.743341,0.941708,0.803509,0.440911,0.373830,0.571296,0.532993,0.945322,0.947569,0.644335,0.947569,0.754775,0.834375,0.104429,0.208680,0.756305,0.947569,0.645220,0.211807,0.830868,0.947569,0.938335,0.287360,0.688819,0.429310,0.652405,0.820050,0.471147,0.760014,0.863159,0.937486
X14,0.082206,0.094270,0.056459,NaN,0.061657,0.053877,0.071359,0.190050,0.529344,0.065247,0.344508,0.151159,0.165485,0.094919,0.064937,0.060211,0.054683,0.100120,0.315344,0.100694,0.056251,0.590250,0.066844,0.053877,0.579655,0.103103,0.164650,0.093328,0.174084,0.079225,0.082647,0.144620,0.056459,0.111986,0.694115,0.094406,0.053877,0.056459,0.070057,0.056459,0.378566,0.919002,0.076514,0.346016,0.080298,0.173390,0.053877,0.056459,0.097231,0.770115,0.082769,0.053877,0.179794,0.828771,0.558375,0.056251,0.160360,0.053877,0.061657,0.190954,0.063989,0.062691,0.174638,0.413474
Y05,0.728141,0.800520,0.431396,0.935743,NaN,0.179666,0.548692,0.856991,0.941708,0.654539,0.933405,0.836665,0.860307,0.772893,0.281971,0.319561,0.214886,0.705190,0.933405,0.764086,0.694905,0.941405,0.464705,0.437306,0.933566,0.777216,0.880960,0.552544,0.765931,0.629560,0.718388,0.845459,0.275151,0.703314,0.941405,0.763888,0.365402,0.285737,0.713073,0.481539,0.934423,0.945976,0.626299,0.932137,0.794507,0.859738,0.079313,0.361716,0.768334,0.941533,0.575595,0.178928,0.830583,0.947569,0.930024,0.136005,0.806238,0.198768,0.487155,0.836120,0.393977,0.659902,0.876468,0.935899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Z12,0.155184,0.220001,0.162151,0.792756,0.151203,0.057468,0.235429,0.446588,0.903269,0.219190,0.750618,0.788828,0.272283,0.224193,0.201882,0.197371,0.089477,0.372586,0.761656,0.263710,0.154109,0.885941,0.200270,0.096008,0.877987,0.284474,0.619029,0.225570,0.264431,0.235325,0.121804,0.273877,0.104532,0.230050,0.887861,0.235213,0.066831,0.135847,0.249267,0.075928,0.829524,0.937329,0.196449,0.884709,0.321448,0.489528,0.046742,0.058325,0.232032,0.904378,0.137124,0.057468,0.460447,0.945391,0.864020,0.054415,0.244869,0.087396,0.229814,NaN,0.203627,0.208077,0.282095,0.867973
Z04,0.760563,0.777355,0.515315,0.934547,0.606480,0.186752,0.731288,0.793408,0.947569,0.444084,0.908704,0.862091,0.796219,0.597322,0.274440,0.309955,0.150022,0.742367,0.941708,0.848133,0.615180,0.935912,0.723930,0.150047,0.941405,0.796219,0.905307,0.683985,0.794700,0.602358,0.745284,0.777355,0.589023,0.760563,0.939211,0.862293,0.258652,0.384140,0.724351,0.476549,0.933910,0.947569,0.725284,0.944732,0.825269,0.793343,0.077218,0.178174,0.847395,0.938574,0.718142,0.199574,0.778472,0.947569,0.938574,0.228867,0.713993,0.478989,0.457353,0.789956,NaN,0.615790,0.898809,0.934706
Y08,0.724247,0.663148,0.207255,0.933803,0.327675,0.128689,0.492384,0.769254,0.929638,0.631183,0.925866,0.838602,0.749545,0.781616,0.221476,0.260292,0.217496,0.350410,0.927915,0.807847,0.255884,0.937590,0.415270,0.215147,0.930024,0.782581,0.893541,0.496931,0.680939,0.532079,0.724300,0.689912,0.251665,0.645680,0.938168,0.660146,0.199843,0.242545,0.796775,0.295155,0.931876,0.938806,0.494181,0.928165,0.752220,0.781275,0.085288,0.190198,0.739125,0.939013,0.478569,0.121928,0.781391,0.945322,0.938110,0.187047,0.573253,0.219911,0.287323,0.790677,0.388004,NaN,0.809369,0.933595
X11,0.333773,0.253427,0.128993,0.818421,0.121319,0.060374,0.270530,0.549035,0.847536,0.246831,0.783842,0.678693,0.445852,0.295741,0.101764,0.092530,0.073179,0.156114,0.769280,0.351320,0.190838,0.772608,0.103496,0.082576,0.765852,0.485440,0.725684,0.146630,0.344080,0.224576,0.361663,0.342941,0.134140,0.276563,0.785619,0.250391,0.069734,0.085079,0.203897,0.098051,0.804381,0.934918,0.143024,0.789496,0.686260,0.522169,0.053877,0.075214,0.439335,0.862681,0.119329,0.061085,0.501948,0.934546,0.830473,0.077670,0.233066,0.094726,0.119001,0.700160,0.088205,0.190080,NaN,0.802325
Y15,0.083554,0.100242,0.060597,0.457379,0.061657,0.057468,0.068364,0.092562,0.705739,0.065247,0.442264,0.148859,0.090221,0.094611,0.063989,0.060211,0.053877,0.082186,0.387070,0.100628,0.059991,0.325787,0.061657,0.053877,0.448577,0.105556,0.234723,0.110196,0.104056,0.079550,0.083879,0.079632,0.056459,0.061657,0.550186,0.094245,0.053877,0.060211,0.061657,0.062200,0.645275,0.925799,0.077427,0.360957,0.121232,0.090221,0.053877,0.056459,0.095054,0.751537,0.061657,0.053877,0.096540,0.895431,0.488949,0.056812,0.087572,0.053877,0.061657,0.126918,0.066094,0.064859,0.199573,NaN

In [5]:
df_matrix_opposite = 1 - df_matrix  # prob of team losing

df_matrix_opposite

,X08,Z11,Z05,X14,Y05,Z03,Y07,Y12,X16,Z07,W14,W13,W12,X09,X04,W04,Y01,X07,Z14,Z08,Y04,W15,Y06,Y03,Z15,W10,Z13,X10,Z09,W09,W07,Y11,X03,W06,X15,W08,W02,Z02,W05,W03,Y13,W16,Y09,Y14,Z10,X12,W01,X02,Z06,Z16,X06,X01,W11,Y16,X13,Y02,Y10,Z01,X05,Z12,Z04,Y08,X11,Y15
X08,NaN,0.467003,0.750267,0.088688,0.712510,0.939233,0.736783,0.242723,0.060774,0.660149,0.156117,0.230207,0.244006,0.286777,0.840113,0.800115,0.870654,0.676329,0.098922,0.443376,0.671202,0.087588,0.572173,0.873847,0.093088,0.279747,0.124821,0.694978,0.407065,0.701687,0.741604,0.349011,0.749852,0.636888,0.086081,0.298561,0.810190,0.772225,0.582922,0.752350,0.095405,0.054678,0.728896,0.089752,0.312052,0.274880,0.955823,0.913106,0.588102,0.064256,0.807169,0.903149,0.212335,0.054678,0.098197,0.904794,0.599823,0.885204,0.748200,0.193328,0.762900,0.713439,0.367954,0.090187
Z11,0.519995,NaN,0.810694,0.101731,0.790511,0.939626,0.659112,0.267893,0.061747,0.575617,0.113548,0.216182,0.412261,0.465315,0.851934,0.767093,0.828513,0.705720,0.102224,0.435029,0.609754,0.094432,0.780089,0.811720,0.095596,0.323811,0.161356,0.690967,0.298168,0.609533,0.673651,0.385346,0.821045,0.618768,0.099551,0.357225,0.774057,0.831511,0.643031,0.822321,0.088050,0.060774,0.709911,0.094610,0.303413,0.306252,0.946123,0.902862,0.377733,0.063385,0.726835,0.943073,0.333507,0.054678,0.095664,0.940282,0.643895,0.826745,0.521437,0.227001,0.779654,0.676427,0.320122,0.112755
Z05,0.251248,0.196054,NaN,0.062514,0.451522,0.791110,0.392639,0.166651,0.052431,0.314389,0.062227,0.147411,0.170825,0.176258,0.560594,0.702534,0.669468,0.550118,0.058467,0.390564,0.572831,0.052431,0.424373,0.619986,0.058467,0.160863,0.093225,0.307984,0.180456,0.356438,0.221672,0.204962,0.674977,0.256659,0.058292,0.196491,0.559089,0.626170,0.428704,0.467007,0.054678,0.052431,0.355665,0.052431,0.245225,0.165625,0.895571,0.791320,0.243695,0.052431,0.354780,0.788193,0.169132,0.052431,0.061665,0.712640,0.311181,0.570690,0.347595,0.179950,0.528853,0.239986,0.136841,0.062514
X14,0.917794,0.905730,0.943541,NaN,0.938343,0.946123,0.928641,0.809950,0.470656,0.934753,0.655492,0.848841,0.834515,0.905081,0.935063,0.939789,0.945317,0.899880,0.684656,0.899306,0.943749,0.409750,0.933156,0.946123,0.420345,0.896897,0.835350,0.906672,0.825916,0.920775,0.917353,0.855380,0.943541,0.888014,0.305885,0.905594,0.946123,0.943541,0.929943,0.943541,0.621434,0.080998,0.923486,0.653984,0.919702,0.826610,0.946123,0.943541,0.902769,0.229885,0.917231,0.946123,0.820206,0.171229,0.441625,0.943749,0.839640,0.946123,0.938343,0.809046,0.936011,0.937309,0.825362,0.586526
Y05,0.271859,0.199480,0.568604,0.064257,NaN,0.820334,0.451308,0.143009,0.058292,0.345461,0.066595,0.163335,0.139693,0.227107,0.718029,0.680439,0.785114,0.294810,0.066595,0.235914,0.305095,0.058595,0.535295,0.562694,0.066434,0.222784,0.119040,0.447456,0.234069,0.370440,0.281612,0.154541,0.724849,0.296686,0.058595,0.236112,0.634598,0.714263,0.286927,0.518461,0.065577,0.054024,0.373701,0.067863,0.205493,0.140262,0.920687,0.638284,0.231666,0.058467,0.424405,0.821072,0.169417,0.052431,0.069976,0.863995,0.193762,0.801232,0.512845,0.163880,0.606023,0.340098,0.123532,0.064101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Z12,0.844816,0.779999,0.837849,0.207244,0.848797,0.942532,0.764571,0.553412,0.096731,0.780810,0.249382,0.211172,0.727717,0.775807,0.798118,0.802629,0.910523,0.627414,0.238344,0.736290,0.845891,0.114059,0.799730,0.903992,0.122013,0.715526,0.380971,0.774430,0.735569,0.764675,0.878196,0.726123,0.895468,0.769950,0.112139,0.764787,0.933169,0.864153,0.750733,0.924072,0.170476,0.062671,0.803551,0.115291,0.678552,0.510472,0.953258,0.941675,0.767968,0.095622,0.862876,0.942532,0.539553,0.054609,0.135980,0.945585,0.755131,0.912604,0.770186,NaN,0.796373,0.791923,0.717905,0.132027
Z04,0.239437,0.222645,0.484685,0.065453,0.393520,0.813248,0.268712,0.206592,0.052431,0.555916,0.091296,0.137909,0.203781,0.402678,0.725560,0.690045,0.849978,0.257633,0.058292,0.151867,0.384820,0.064088,0.276070,0.849953,0.058595,0.203781,0.094693,0.316015,0.205300,0.397642,0.254716,0.222645,0.410977,0.239437,0.060789,0.137707,0.741348,0.615860,0.275649,0.523451,0.066090,0.052431,0.274716,0.055268,0.174731,0.206657,0.922782,0.821826,0.152605,0.061426,0.281858,0.800426,0.221528,0.052431,0.061426,0.771133,0.286007,0.521011,0.542647,0.210044,NaN,0.384210,0.101191,0.065294
Y08,0.275753,0.336852,0.792745,0.066197,0.672325,0.871311,0.507616,0.230746,0.070362,0.368817,0.074134,0.161398,0.250455,0.218384,0.778524,0.739708,0.782504,0.649590,0.072085,0.192153,0.744116,0.062410,0.584730,0.784853,0.069976,0.217419,0.106459,0.503069,0.319061,0.467921,0.275700,0.310088,0.748335,0.354320,0.061832,0.339854,0.800157,0.757455,0.203225,0.704845,0.068124,0.061194,0.505819,0.071835,0.247780,0.218725,0.914712,0.809802,0.260875,0.060987,0.521431,0.878072,0.218609,0.054678,0.061890,0.812953,0.426747,0.780089,0.712677,0.209323,0.611996,NaN,0.190631,0.066405
X11,0.666227,0.746573,0.871007,0.181579,0.878681,0.939626,0.729470,0.450965,0.152464,0.753169,0.216158,0.321307,0.554148,0.704259,0.898236,0.907470,0.926821,0.843886,0.230720,0.648680,0.809162,0.227392,0.896504,0.917424,0.234148,0.514560,0.274316,0.853370,0.655920,0.775424,0.638337,0.657059,0.865860,0.723437,0.214381,0.749609,0.930266,0.914921,0.796103,0.901949,0.195619,0.065082,0.856976,0.210504,0.313740,0.477831,0.946123,0.924786,0.560665,0.137319,0.880671,0.938915,0.498052,0.065454,0.169527,0.922330,0.766934,0.905274,0.880999,0.299840,0.911795,0.809920,NaN,0.197675
Y15,0.916446,0.899758,0.939403,0.542621,0.938343,0.942532,0.931636,0.907438,0.294261,0.934753,0.557736,0.851141,0.909779,0.905389,0.936011,0.939789,0.946123,0.917814,0.612930,0.899372,0.940009,0.674213,0.938343,0.946123,0.551423,0.894444,0.765277,0.889804,0.895944,0.920450,0.916121,0.920368,0.943541,0.938343,0.449814,0.905755,0.946123,0.939789,0.938343,0.937800,0.354725,0.074201,0.922573,0.639043,0.878768,0.909779,0.946123,0.943541,0.904946,0.248463,0.938343,0.946123,0.903460,0.104569,0.511051,0.943188,0.912428,0.946123,0.938343,0.873082,0.933906,0.935141,0.800427,NaN

In [6]:
import numpy as np

def simulate_tournament() -> dict:
    """
    Simulate the tournament in Kaggle submission format
    """
    # ROUND 1
    round_1 = {
        f'R1{region}{i}': np.random.choice(
            (f'{region}{i:02d}', f'{region}{17-i:02d}'), 
            p=(
                df_matrix.loc[f'{region}{i:02d}', f'{region}{17-i:02d}'], 
                df_matrix_opposite.loc[f'{region}{i:02d}', f'{region}{17-i:02d}']
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 8, 5, 4, 6, 3, 7, 2)
    }

    # ROUND 2
    round_2 = {
        f'R2{region}{i}': np.random.choice(
            (round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']), 
            p=(
                df_matrix.loc[round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']], 
                df_matrix_opposite.loc[round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 4, 3, 2)
    }

    # ROUND 3
    round_3 = {
        f'R3{region}{i}': np.random.choice(
            (round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']), 
            p=(
                df_matrix.loc[round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']], 
                df_matrix_opposite.loc[round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 2)
    }

    # ROUND 4
    round_4 = {
        f'R4{region}{i}': np.random.choice(
            (round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']), 
            p=(
                df_matrix.loc[round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']], 
                df_matrix_opposite.loc[round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, )
    }

    # ROUND 5
    round_5 = {
        'R5WX': np.random.choice(
            (round_4['R4W1'], round_4['R4X1']),
            p=(
                df_matrix.loc[round_4['R4W1'], round_4['R4X1']],
                df_matrix_opposite.loc[round_4['R4W1'], round_4['R4X1']],
            )
        ),
        'R5YZ': np.random.choice(
            (round_4['R4Y1'], round_4['R4Z1']),
            p=(
                df_matrix.loc[round_4['R4Y1'], round_4['R4Z1']],
                df_matrix_opposite.loc[round_4['R4Y1'], round_4['R4Z1']],
            )
        ),
    }

    # ROUND 6
    round_6 = {
        'R6CH': np.random.choice(
            (round_5['R5WX'], round_5['R5YZ']),
            p=(
                df_matrix.loc[round_5['R5WX'], round_5['R5YZ']],
                df_matrix_opposite.loc[round_5['R5WX'], round_5['R5YZ']],
            )
        ),
    }

    return round_1 | round_2 | round_3 | round_4 | round_5 | round_6  # merge the dictionaries (python >= 3.9)

simulate_tournament()

{'R1W1': 'W01',
 'R1W8': 'W09',
 'R1W5': 'W12',
 'R1W4': 'W04',
 'R1W6': 'W06',
 'R1W3': 'W03',
 'R1W7': 'W10',
 'R1W2': 'W02',
 'R1X1': 'X16',
 'R1X8': 'X09',
 'R1X5': 'X05',
 'R1X4': 'X04',
 'R1X6': 'X06',
 'R1X3': 'X03',
 'R1X7': 'X07',
 'R1X2': 'X02',
 'R1Y1': 'Y01',
 'R1Y8': 'Y08',
 'R1Y5': 'Y05',
 'R1Y4': 'Y04',
 'R1Y6': 'Y06',
 'R1Y3': 'Y03',
 'R1Y7': 'Y10',
 'R1Y2': 'Y02',
 'R1Z1': 'Z01',
 'R1Z8': 'Z08',
 'R1Z5': 'Z05',
 'R1Z4': 'Z04',
 'R1Z6': 'Z11',
 'R1Z3': 'Z03',
 'R1Z7': 'Z07',
 'R1Z2': 'Z02',
 'R2W1': 'W01',
 'R2W4': 'W04',
 'R2W3': 'W03',
 'R2W2': 'W02',
 'R2X1': 'X09',
 'R2X4': 'X04',
 'R2X3': 'X03',
 'R2X2': 'X02',
 'R2Y1': 'Y01',
 'R2Y4': 'Y04',
 'R2Y3': 'Y06',
 'R2Y2': 'Y02',
 'R2Z1': 'Z01',
 'R2Z4': 'Z04',
 'R2Z3': 'Z11',
 'R2Z2': 'Z07',
 'R3W1': 'W01',
 'R3W2': 'W03',
 'R3X1': 'X04',
 'R3X2': 'X02',
 'R3Y1': 'Y01',
 'R3Y2': 'Y06',
 'R3Z1': 'Z01',
 'R3Z2': 'Z07',
 'R4W1': 'W01',
 'R4X1': 'X04',
 'R4Y1': 'Y01',
 'R4Z1': 'Z01',
 'R5WX': 'W01',
 'R5YZ': 'Y01',
 'R6CH': 'W01'}

In [7]:
from tqdm.autonotebook import trange

np.random.seed(22)

results = tuple(
    simulate_tournament()
    for _ in trange(3_000)  # set back to 30_000
)

len(results)

C:\Users\mhugh\AppData\Local\Temp\ipykernel_4132\4113097100.py:1: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import trange

  0%|          | 0/3000 [00:00<?, ?it/s]

3000

In [8]:
np.random.seed(23)

my_candidates = tuple(
    simulate_tournament()
    for _ in trange(2_000)  # set back to 20_000
)

len(my_candidates)

  0%|          | 0/2000 [00:00<?, ?it/s]

2000

In [9]:
def bracket_to_team_placements(bracket: dict) -> dict:
    """
    Convert bracket to dict of how many games each team won
    """
    round_1 = {
        bracket[f'R1{region}{i}']: 1
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 8, 5, 4, 6, 3, 7, 2)
    }

    round_2 = {
        bracket[f'R2{region}{i}']: 2
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 4, 3, 2)
    }

    round_3 = {
        bracket[f'R3{region}{i}']: 3
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 2)
    }

    round_4 = {
        bracket[f'R4{region}{i}']: 4
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, )
    }

    round_5 = {
        bracket['R5WX']: 5,
        bracket['R5YZ']: 5,
    }

    round_6 = {
        bracket['R6CH']: 6,
    }

    return round_1 | round_2 | round_3 | round_4 | round_5 | round_6  # merge the dictionaries (python >= 3.9)

bracket_to_team_placements(results[0])

{'W01': 4,
 'W09': 1,
 'W05': 2,
 'W13': 1,
 'W06': 2,
 'W03': 1,
 'W07': 1,
 'W02': 3,
 'X01': 6,
 'X09': 1,
 'X05': 1,
 'X04': 2,
 'X06': 1,
 'X03': 3,
 'X07': 1,
 'X02': 2,
 'Y01': 5,
 'Y09': 1,
 'Y05': 1,
 'Y04': 2,
 'Y11': 1,
 'Y03': 2,
 'Y07': 1,
 'Y02': 3,
 'Z01': 2,
 'Z08': 1,
 'Z05': 4,
 'Z04': 1,
 'Z11': 2,
 'Z14': 1,
 'Z07': 1,
 'Z02': 3}

In [10]:
from tqdm.autonotebook import tqdm

team_placements = tuple(bracket_to_team_placements(result) for result in tqdm(results))

len(team_placements)

  0%|          | 0/3000 [00:00<?, ?it/s]

3000

In [11]:
team_all_placements = {
    team: np.array([team_placements_bracket.get(team, 0) for team_placements_bracket in team_placements])
    for team in ((f'{region}{i:02d}') for region in ('W', 'X', 'Y', 'Z') for i in range(1, 17))
}

team_all_placements

{'W01': array([4, 6, 6, ..., 6, 6, 6]),
 'W02': array([3, 3, 2, ..., 3, 3, 3]),
 'W03': array([1, 1, 3, ..., 1, 2, 2]),
 'W04': array([0, 1, 1, ..., 2, 1, 1]),
 'W05': array([2, 0, 2, ..., 0, 0, 0]),
 'W06': array([2, 2, 1, ..., 2, 1, 1]),
 'W07': array([1, 1, 1, ..., 0, 1, 0]),
 'W08': array([0, 0, 0, ..., 0, 1, 0]),
 'W09': array([1, 1, 1, ..., 1, 0, 1]),
 'W10': array([0, 0, 0, ..., 1, 0, 1]),
 'W11': array([0, 0, 0, ..., 0, 0, 0]),
 'W12': array([0, 2, 0, ..., 1, 2, 2]),
 'W13': array([1, 0, 0, ..., 0, 0, 0]),
 'W14': array([0, 0, 0, ..., 0, 0, 0]),
 'W15': array([0, 0, 0, ..., 0, 0, 0]),
 'W16': array([0, 0, 0, ..., 0, 0, 0]),
 'X01': array([6, 0, 2, ..., 4, 4, 4]),
 'X02': array([2, 4, 1, ..., 1, 3, 3]),
 'X03': array([3, 1, 2, ..., 3, 1, 2]),
 'X04': array([2, 3, 3, ..., 1, 2, 1]),
 'X05': array([1, 1, 1, ..., 2, 1, 2]),
 'X06': array([1, 2, 1, ..., 1, 0, 1]),
 'X07': array([1, 1, 0, ..., 2, 1, 1]),
 'X08': array([0, 0, 1, ..., 0, 0, 0]),
 'X09': array([1, 2, 0, ..., 1, 1, 1]),
 'X10': array([0, 0, 4, ..., 0, 0, 0]),
 'X11': array([0, 0, 0, ..., 0, 2, 0]),
 'X12': array([0, 0, 0, ..., 0, 0, 0]),
 'X13': array([0, 0, 0, ..., 0, 0, 0]),
 'X14': array([0, 0, 0, ..., 0, 0, 0]),
 'X15': array([0, 0, 0, ..., 0, 0, 0]),
 'X16': array([0, 1, 0, ..., 0, 0, 0]),
 'Y01': array([5, 2, 3, ..., 4, 2, 3]),
 'Y02': array([3, 1, 4, ..., 2, 1, 4]),
 'Y03': array([2, 3, 2, ..., 3, 5, 1]),
 'Y04': array([2, 1, 1, ..., 2, 3, 2]),
 'Y05': array([1, 4, 2, ..., 1, 0, 1]),
 'Y06': array([0, 1, 0, ..., 1, 0, 2]),
 'Y07': array([1, 2, 1, ..., 1, 2, 0]),
 'Y08': array([0, 0, 0, ..., 1, 1, 0]),
 'Y09': array([1, 1, 1, ..., 0, 0, 1]),
 'Y10': array([0, 0, 0, ..., 0, 0, 1]),
 'Y11': array([1, 0, 1, ..., 0, 1, 0]),
 'Y12': array([0, 0, 0, ..., 0, 1, 0]),
 'Y13': array([0, 0, 0, ..., 0, 0, 0]),
 'Y14': array([0, 0, 0, ..., 0, 0, 0]),
 'Y15': array([0, 0, 0, ..., 0, 0, 0]),
 'Y16': array([0, 0, 0, ..., 0, 0, 0]),
 'Z01': array([2, 2, 2, ..., 5, 4, 1]),
 'Z02': array([3, 2, 2, ..., 2, 0, 2]),
 'Z03': array([0, 5, 5, ..., 3, 1, 3]),
 'Z04': array([1, 1, 3, ..., 2, 2, 5]),
 'Z05': array([4, 3, 1, ..., 0, 1, 1]),
 'Z06': array([0, 0, 0, ..., 0, 0, 0]),
 'Z07': array([1, 0, 1, ..., 1, 3, 1]),
 'Z08': array([1, 0, 1, ..., 0, 1, 0]),
 'Z09': array([0, 1, 0, ..., 1, 0, 2]),
 'Z10': array([0, 1, 0, ..., 0, 0, 0]),
 'Z11': array([2, 1, 1, ..., 1, 2, 1]),
 'Z12': array([0, 0, 0, ..., 1, 0, 0]),
 'Z13': array([0, 0, 0, ..., 0, 0, 0]),
 'Z14': array([1, 0, 0, ..., 0, 0, 0]),
 'Z15': array([0, 0, 0, ..., 0, 1, 0]),
 'Z16': array([0, 0, 0, ..., 0, 0, 0])}

Get probabilities of surviving

In [12]:
team_model_probs = dict(
    (
        t, 
        np.array(tuple(
            (v >= round).mean()
            for round in range(1, 7)
        ))
    )
    for t, v in team_all_placements.items()
)

team_model_probs

{'W01': array([0.96      , 0.90033333, 0.83566667, 0.782     , 0.68766667,
        0.62433333]),
 'W02': array([0.94566667, 0.81866667, 0.564     , 0.08233333, 0.02633333,
        0.00833333]),
 'W03': array([0.929     , 0.73833333, 0.338     , 0.05033333, 0.01033333,
        0.00166667]),
 'W04': array([0.84333333, 0.65233333, 0.09866667, 0.05366667, 0.01266667,
        0.00433333]),
 'W05': array([7.35666667e-01, 2.30666667e-01, 1.93333333e-02, 8.00000000e-03,
        2.33333333e-03, 3.33333333e-04]),
 'W06': array([7.05000000e-01, 1.94666667e-01, 4.03333333e-02, 2.66666667e-03,
        6.66666667e-04, 0.00000000e+00]),
 'W07': array([0.734     , 0.13633333, 0.039     , 0.003     , 0.        ,
        0.        ]),
 'W08': array([3.84666667e-01, 3.36666667e-02, 1.30000000e-02, 5.00000000e-03,
        6.66666667e-04, 3.33333333e-04]),
 'W09': array([0.61533333, 0.06266667, 0.02266667, 0.00933333, 0.00133333,
        0.        ]),
 'W10': array([0.266, 0.039, 0.009, 0.001, 0.   , 0.   ]),
 'W11': array([0.295     , 0.056     , 0.00866667, 0.00066667, 0.00033333,
        0.        ]),
 'W12': array([0.26433333, 0.089     , 0.009     , 0.002     , 0.00033333,
        0.        ]),
 'W13': array([0.15666667, 0.028     , 0.00133333, 0.        , 0.        ,
        0.        ]),
 'W14': array([0.071     , 0.011     , 0.00033333, 0.        , 0.        ,
        0.        ]),
 'W15': array([0.05433333, 0.006     , 0.00066667, 0.        , 0.        ,
        0.        ]),
 'W16': array([0.04      , 0.00333333, 0.00033333, 0.        , 0.        ,
        0.        ]),
 'X01': array([0.947     , 0.88033333, 0.66666667, 0.39666667, 0.10766667,
        0.06433333]),
 'X02': array([0.93633333, 0.778     , 0.62166667, 0.37433333, 0.10533333,
        0.051     ]),
 'X03': array([0.94      , 0.62466667, 0.20466667, 0.05933333, 0.01166667,
        0.00533333]),
 'X04': array([0.93633333, 0.65466667, 0.226     , 0.108     , 0.02366667,
        0.00666667]),
 'X05': array([0.87266667, 0.31133333, 0.08133333, 0.02266667, 0.00433333,
        0.00133333]),
 'X06': array([8.75666667e-01, 3.46000000e-01, 9.30000000e-02, 2.03333333e-02,
        2.00000000e-03, 6.66666667e-04]),
 'X07': array([0.55133333, 0.11666667, 0.043     , 0.00633333, 0.001     ,
        0.        ]),
 'X08': array([0.71433333, 0.08466667, 0.01633333, 0.002     , 0.        ,
        0.        ]),
 'X09': array([0.28566667, 0.032     , 0.007     , 0.00066667, 0.        ,
        0.        ]),
 'X10': array([0.44866667, 0.09966667, 0.034     , 0.00966667, 0.00166667,
        0.        ]),
 'X11': array([0.12433333, 0.02533333, 0.00266667, 0.        , 0.        ,
        0.        ]),
 'X12': array([0.12733333, 0.02733333, 0.002     , 0.        , 0.        ,
        0.        ]),
 'X13': array([0.06366667, 0.00666667, 0.00033333, 0.        , 0.        ,
        0.        ]),
 'X14': array([0.06      , 0.004     , 0.00033333, 0.        , 0.        ,
        0.        ]),
 'X15': array([0.06366667, 0.00566667, 0.00066667, 0.        , 0.        ,
        0.        ]),
 'X16': array([0.053     , 0.003     , 0.00033333, 0.        , 0.        ,
        0.        ]),
 'Y01': array([0.94266667, 0.72533333, 0.58533333, 0.42833333, 0.216     ,
        0.05766667]),
 'Y02': array([0.94766667, 0.79733333, 0.452     , 0.23166667, 0.11066667,
        0.024     ]),
 'Y03': array([0.94066667, 0.716     , 0.40933333, 0.18966667, 0.07466667,
        0.01233333]),
 'Y04': array([9.28333333e-01, 3.50000000e-01, 1.15333333e-01, 2.66666667e-02,
        5.00000000e-03, 6.66666667e-04]),
 'Y05': array([0.84866667, 0.616     , 0.18866667, 0.05433333, 0.01566667,
        0.00166667]),
 'Y06': array([7.42333333e-01, 2.36666667e-01, 8.33333333e-02, 3.06666667e-02,
        7.33333333e-03, 6.66666667e-04]),
 'Y07': array([6.62000000e-01, 1.55000000e-01, 4.23333333e-02, 1.43333333e-02,
        1.66666667e-03, 3.33333333e-04]),
 'Y08': array([0.495     , 0.137     , 0.047     , 0.01233333, 0.003     ,
        0.        ]),
 'Y09': array([5.05000000e-01, 1.33666667e-01, 6.13333333e-02, 9.66666667e-03,
        3.33333333e-03, 3.33333333e-04]),
 'Y10': array([0.338     , 0.04366667, 0.00866667, 0.00166667, 0.00066667,
        0.        ]),
 'Y11': array([0.25766667, 0.04233333, 0.004     , 0.00033333, 0.        ,
        0.        ]),
 'Y12': array([0.15133333, 0.026     , 0.002     , 0.00033333, 0.        ,
        0.        ]),
 'Y13': array([0.07166667, 0.008     , 0.        , 0.        , 0.        ,
        0.        ]),
 'Y14': array([0.05933333, 0.005     , 0.00033333, 0.        , 0.        ,
        0.        ]),
 'Y15': array([0.05233333, 0.004     , 0.        , 0.        , 0.        ,
        0.        ]),
 'Y16': array([0.05733333, 0.004     , 0.00033333, 0.        , 0.        ,
        0.        ]),
 'Z01': array([0.93933333, 0.773     , 0.436     , 0.14266667, 0.059     ,
        0.01133333]),
 'Z02': array([0.941     , 0.69833333, 0.18933333, 0.09766667, 0.028     ,
        0.005     ]),
 'Z03': array([0.93833333, 0.87533333, 0.72633333, 0.586     , 0.42233333,
        0.10933333]),
 'Z04': array([0.90666667, 0.51766667, 0.28966667, 0.07733333, 0.019     ,
        0.00366667]),
 'Z05': array([0.81466667, 0.424     , 0.20566667, 0.06066667, 0.02366667,
        0.00333333]),
 'Z06': array([0.32466667, 0.047     , 0.009     , 0.00233333, 0.00066667,
        0.00033333]),
 'Z07': array([0.82766667, 0.25833333, 0.04633333, 0.01833333, 0.00566667,
        0.        ]),
 'Z08': array([6.31333333e-01, 1.43000000e-01, 3.93333333e-02, 5.33333333e-03,
        2.33333333e-03, 3.33333333e-04]),
 'Z09': array([0.36866667, 0.08      , 0.02133333, 0.00266667, 0.        ,
        0.        ]),
 'Z10': array([0.17233333, 0.04133333, 0.005     , 0.00033333, 0.        ,
        0.        ]),
 'Z11': array([6.75333333e-01, 7.23333333e-02, 2.30000000e-02, 5.00000000e-03,
        1.00000000e-03, 3.33333333e-04]),
 'Z12': array([0.18533333, 0.04533333, 0.00566667, 0.00166667, 0.00033333,
        0.        ]),
 'Z13': array([0.09333333, 0.013     , 0.002     , 0.        , 0.        ,
        0.        ]),
 'Z14': array([0.06166667, 0.00533333, 0.00033333, 0.        , 0.        ,
        0.        ]),
 'Z15': array([0.059     , 0.002     , 0.00066667, 0.        , 0.        ,
        0.        ]),
 'Z16': array([0.06066667, 0.004     , 0.00033333, 0.        , 0.        ,
        0.        ])}

In [13]:
region_seed_to_id = dict(zip(df_seeds['Region Seed'], df_seeds['TeamID']))

df_model = pd.DataFrame({
    'Team': team_model_probs.keys()
})

df_model[[f'Round {i}' for i in range(1, 7)]] = np.array(tuple(df_model['Team'].map(team_model_probs)))

df_model.insert(1, 'TeamID', df_model['Team'].map(region_seed_to_id))

df_model.sort_values(by=['Round 6'], ascending=False, inplace=True, ignore_index=True)

df_model.head(10)

  Team  TeamID   Round 1   Round 2   Round 3   Round 4   Round 5   Round 6
0  W01    3376  0.960000  0.900333  0.835667  0.782000  0.687667  0.624333
1  Z03    3163  0.938333  0.875333  0.726333  0.586000  0.422333  0.109333
2  X01    3400  0.947000  0.880333  0.666667  0.396667  0.107667  0.064333
3  Y01    3234  0.942667  0.725333  0.585333  0.428333  0.216000  0.057667
4  X02    3390  0.936333  0.778000  0.621667  0.374333  0.105333  0.051000
5  Y02    3417  0.947667  0.797333  0.452000  0.231667  0.110667  0.024000
6  Y03    3261  0.940667  0.716000  0.409333  0.189667  0.074667  0.012333
7  Z01    3425  0.939333  0.773000  0.436000  0.142667  0.059000  0.011333
8  W02    3323  0.945667  0.818667  0.564000  0.082333  0.026333  0.008333
9  X04    3211  0.936333  0.654667  0.226000  0.108000  0.023667  0.006667

In [17]:
df_teams = pd.read_csv(r'..\data\unprocessed\kaggle\WTeams.csv')

df_teams

     TeamID        TeamName
0      3101     Abilene Chr
1      3102       Air Force
2      3103           Akron
3      3104         Alabama
4      3105     Alabama A&M
..      ...             ...
373    3476       Stonehill
374    3477  East Texas A&M
375    3478        Le Moyne
376    3479      Mercyhurst
377    3480    West Georgia

[378 rows x 2 columns]

In [18]:
id_to_team = dict(zip(df_teams['TeamID'], df_teams['TeamName']))

df_model.insert(df_model.columns.get_loc('TeamID') + 1, 'Name', df_model['TeamID'].map(id_to_team))

df_model.head(25)

,Team,TeamID,Name,Round 1,Round 2,Round 3,Round 4,Round 5,Round 6
0,W01,3376,South Carolina,0.960000,0.900333,0.835667,0.782000,0.687667,0.624333
1,Z03,3163,Connecticut,0.938333,0.875333,0.726333,0.586000,0.422333,0.109333
2,X01,3400,Texas,0.947000,0.880333,0.666667,0.396667,0.107667,0.064333
3,Y01,3234,Iowa,0.942667,0.725333,0.585333,0.428333,0.216000,0.057667
4,X02,3390,Stanford,0.936333,0.778000,0.621667,0.374333,0.105333,0.051000
5,Y02,3417,UCLA,0.947667,0.797333,0.452000,0.231667,0.110667,0.024000
6,Y03,3261,LSU,0.940667,0.716000,0.409333,0.189667,0.074667,0.012333
7,Z01,3425,USC,0.939333,0.773000,0.436000,0.142667,0.059000,0.011333
8,W02,3323,Notre Dame,0.945667,0.818667,0.564000,0.082333,0.026333,0.008333
9,X04,3211,Gonzaga,0.936333,0.654667,0.226000,0.108000,0.023667,0.006667
10,X03,3301,NC State,0.940000,0.624667,0.204667,0.059333,0.011667,0.005333
11,Z02,3326,Ohio St,0.941000,0.698333,0.189333,0.097667,0.028000,0.005000
12,W04,3231,Indiana,0.843333,0.652333,0.098667,0.053667,0.012667,0.004333
13,Z04,3439,Virginia Tech,0.906667,0.517667,0.289667,0.077333,0.019000,0.003667
14,Z05,3124,Baylor,0.814667,0.424000,0.205667,0.060667,0.023667,0.003333
15,W03,3333,Oregon St,0.929000,0.738333,0.338000,0.050333,0.010333,0.001667
16,Y05,3160,Colorado,0.848667,0.616000,0.188667,0.054333,0.015667,0.001667
17,X05,3428,Utah,0.872667,0.311333,0.081333,0.022667,0.004333,0.001333
18,X06,3397,Tennessee,0.875667,0.346000,0.093000,0.020333,0.002000,0.000667
19,Y04,3243,Kansas St,0.928333,0.350000,0.115333,0.026667,0.005000,0.000667
20,Y06,3257,Louisville,0.742333,0.236667,0.083333,0.030667,0.007333,0.000667
21,Z08,3242,Kansas,0.631333,0.143000,0.039333,0.005333,0.002333,0.000333
22,Z11,3112,Arizona,0.675333,0.072333,0.023000,0.005000,0.001000,0.000333
23,Z06,3393,Syracuse,0.324667,0.047000,0.009000,0.002333,0.000667,0.000333
24,Y09,3343,Princeton,0.505000,0.133667,0.061333,0.009667,0.003333,0.000333

Get public brackets

In [19]:
df_public = pd.read_parquet(f'..\data\preprocessed\womens_yahoo\yahoo_picks_{season}.parquet')

df_public.sort_values(by=['Round 6'], ascending=False, ignore_index=True).head(10)

,Team,TeamID,Region Seed,Seed,Region,Play In,Round 1,Round 2,Round 3,Round 4,Round 5,Round 6
0,South Carolina,3376,W01,1,W,False,0.9831,0.9065,0.8529,0.7587,0.6604,0.3973
1,Iowa,3234,Y01,1,Y,False,0.9798,0.9446,0.8873,0.6741,0.5607,0.3168
2,Connecticut,3163,Z03,3,Z,False,0.9551,0.8523,0.5694,0.3260,0.0954,0.0429
3,LSU,3261,Y03,3,Y,False,0.9508,0.8264,0.5578,0.1615,0.1055,0.0374
4,USC,3425,Z01,1,Z,False,0.9674,0.8767,0.7212,0.3971,0.0898,0.0303
5,Stanford,3390,X02,2,X,False,0.9600,0.8362,0.6441,0.4151,0.0755,0.0247
6,Texas,3400,X01,1,X,False,0.9715,0.9040,0.7498,0.3337,0.0699,0.0240
7,Notre Dame,3323,W02,2,W,False,0.9585,0.8683,0.6675,0.1171,0.0580,0.0188
8,Ohio St.,3326,Z02,2,Z,False,0.9560,0.7998,0.3240,0.1506,0.0402,0.0177
9,UCLA,3417,Y02,2,Y,False,0.9638,0.8594,0.3344,0.0879,0.0416,0.0169

R1X1: (1, 16)
R2X1: (1, 8, 9, 16)
R3X1: (1, 4, 5, 8, 9, 12, 13, 16)
R4X1: (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)

R1X2: (2, 15)
R2X2: (2, 7, 10, 15)
R3X2: (2, 3, 6, 7, 10, 11, 14, 15)

R1X3: (3, 14)
R2X3: (3, 6, 11, 14)

R1X4: (4, 13)
R2X4: (4, 5, 12, 13)

R1X5: (5, 12)

R1X6: (6, 11)

R1X7: (7, 10)

R1X8: (8, 9)

Partition data into possible areas in advance

In [20]:
public_dict = {
    # ROUND 6
    'R6CH': df_public.loc[:, ['Region Seed', 'Region', 'Seed', 'Round 6']].rename(columns={'Round 6': 'P'}).reset_index(drop=True),

    # ROUND 5
    'R5WX': df_public.loc[df_public['Region'].isin(('W', 'X')), ['Region Seed', 'Region', 'Seed', 'Round 5']].rename(columns={'Round 5': 'P'}).reset_index(drop=True),
    'R5YZ': df_public.loc[df_public['Region'].isin(('Y', 'Z')), ['Region Seed', 'Region', 'Seed', 'Round 5']].rename(columns={'Round 5': 'P'}).reset_index(drop=True),
}

# ROUND 4
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R4{region}1'] = df_public.loc[df_public['Region'] == region, ['Region Seed', 'Region', 'Seed', 'Round 4']].rename(columns={'Round 4': 'P'}).reset_index(drop=True)

# ROUND 3
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R3{region}1'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((1, 4, 5, 8, 9, 12, 13, 16))), ['Region Seed', 'Region', 'Seed', 'Round 3']].rename(columns={'Round 3': 'P'}).reset_index(drop=True)
    public_dict[f'R3{region}2'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((2, 3, 6, 7, 10, 11, 14, 15))), ['Region Seed', 'Region', 'Seed', 'Round 3']].rename(columns={'Round 3': 'P'}).reset_index(drop=True)

# ROUND 2
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R2{region}1'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((1, 8, 9, 16))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}2'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((2, 7, 10, 15))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}3'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((3, 6, 11, 14))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}4'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((4, 5, 12, 13))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)

# ROUND 1
for region in ('W', 'X', 'Y', 'Z'):
    for i in range(1, 9):
        public_dict[f'R1{region}{i}'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((i, 17-i))), ['Region Seed', 'Region', 'Seed', 'Round 1']].rename(columns={'Round 1': 'P'}).reset_index(drop=True)

for key, value in public_dict.items():  # make sure probabilities add to 1
    # print(value['P'].sum())

    value['P'] = value['P']/value['P'].sum()
    public_dict[key] = value

    # print(value['P'].sum())
    # print()

public_dict

{'R6CH':    Region Seed Region  Seed         P
 0          Z11      Z    11  0.000500
 1          X08      X     8  0.000999
 2          Z05      Z     5  0.002198
 3          Y15      Y    15  0.000400
 4          X14      X    14  0.000600
 ..         ...    ...   ...       ...
 59         Z01      Z     1  0.030279
 60         X05      X     5  0.001499
 61         Z12      Z    12  0.000799
 62         Z04      Z     4  0.003398
 63         Y08      Y     8  0.001099

 [64 rows x 4 columns],
 'R5WX':    Region Seed Region  Seed         P
 0          X08      X     8  0.002301
 1          X14      X    14  0.001101
 2          X16      X    16  0.001301
 3          W14      W    14  0.000900
 4          W13      W    13  0.001101
 5          W12      W    12  0.001201
 6          X09      X     9  0.006903
 7          X04      X     4  0.017809
 8          X11      X    11  0.001401
 9          W04      W     4  0.012906
 10         X07      X     7  0.006603
 11         W15      W    15  0.000900
 12         W10      W    10  0.001801
 13         X10      X    10  0.002901
 14         W09      W     9  0.003502
 15         W07      W     7  0.001801
 16         W08      W     8  0.004602
 17         X03      X     3  0.014707
 18         W06      W     6  0.005403
 19         X15      X    15  0.000800
 20         W02      W     2  0.058029
 21         W05      W     5  0.004502
 22         W03      W     3  0.014107
 23         W16      W    16  0.001401
 24         X12      X    12  0.001201
 25         W01      W     1  0.660730
 26         X02      X     2  0.075538
 27         X06      X     6  0.017709
 28         X01      X     1  0.069935
 29         W11      W    11  0.001801
 30         X13      X    13  0.001201
 31         X05      X     5  0.003902,
 'R5YZ':    Region Seed Region  Seed         P
 0          Z11      Z    11  0.001100
 1          Z05      Z     5  0.006703
 2          Y15      Y    15  0.000800
 3          Y05      Y     5  0.004602
 4          Z03      Z     3  0.095438
 5          Y07      Y     7  0.001901
 6          Y12      Y    12  0.001200
 7          Z07      Z     7  0.004602
 8          Y16      Y    16  0.000900
 9          Y01      Y     1  0.560924
 10         Z14      Z    14  0.000800
 11         Z08      Z     8  0.002201
 12         Y04      Y     4  0.005702
 13         Y03      Y     3  0.105542
 14         Y06      Y     6  0.003301
 15         Z15      Z    15  0.001200
 16         Z13      Z    13  0.001100
 17         Z09      Z     9  0.003902
 18         Y11      Y    11  0.001100
 19         Z02      Z     2  0.040216
 20         Y13      Y    13  0.001000
 21         Y09      Y     9  0.005102
 22         Y14      Y    14  0.001100
 23         Z10      Z    10  0.001200
 24         Z06      Z     6  0.004002
 25         Z16      Z    16  0.001200
 26         Y02      Y     2  0.041617
 27         Y10      Y    10  0.001801
 28         Z01      Z     1  0.089836
 29         Z12      Z    12  0.001401
 30         Z04      Z     4  0.006503
 31         Y08      Y     8  0.002001,
 'R4W1':    Region Seed Region  Seed       P
 0          W14      W    14  0.0023
 1          W13      W    13  0.0024
 2          W12      W    12  0.0026
 3          W04      W     4  0.0289
 4          W15      W    15  0.0021
 5          W10      W    10  0.0044
 6          W09      W     9  0.0071
 7          W07      W     7  0.0042
 8          W08      W     8  0.0095
 9          W06      W     6  0.0109
 10         W02      W     2  0.1171
 11         W05      W     5  0.0112
 12         W03      W     3  0.0310
 13         W16      W    16  0.0032
 14         W01      W     1  0.7587
 15         W11      W    11  0.0044,
 'R4X1':    Region Seed Region  Seed         P
 0          X08      X     8  0.005823
 1          X14      X    14  0.002711
 2          X16      X    16  0.002711
 3          X09      X     9  0.011647
 4          X04      X     4  0.055522
 5          X11      X    11  0.003414
 6          X07      X     7  0.018976
 7          X10      X    10  0.007329
 8          X03      X     3  0.070482
 9          X15      X    15  0.002309
 10         X12      X    12  0.002811
 11         X02      X     2  0.416767
 12         X06      X     6  0.047088
 13         X01      X     1  0.335040
 14         X13      X    13  0.002811
 15         X05      X     5  0.014558,
 'R4Y1':    Region Seed Region  Seed         P
 0          Y15      Y    15  0.001906
 1          Y05      Y     5  0.009833
 2          Y07      Y     7  0.004616
 3          Y12      Y    12  0.002810
 4          Y16      Y    16  0.002007
 5          Y01      Y     1  0.676400
 6          Y04      Y     4  0.013145
 7          Y03      Y     3  0.162051
 8          Y06      Y     6  0.007526
 9          Y11      Y    11  0.011740
 10         Y13      Y    13  0.002208
 11         Y09      Y     9  0.007526
 12         Y14      Y    14  0.002308
 13         Y02      Y     2  0.088200
 14         Y10      Y    10  0.003612
 15         Y08      Y     8  0.004114,
 'R4Z1':    Region Seed Region  Seed         P
 0          Z11      Z    11  0.002710
 1          Z05      Z     5  0.030613
 2          Z03      Z     3  0.327211
 3          Z07      Z     7  0.017264
 4          Z14      Z    14  0.002108
 5          Z08      Z     8  0.007026
 6          Z15      Z    15  0.002610
 7          Z13      Z    13  0.004818
 8          Z09      Z     9  0.011442
 9          Z02      Z     2  0.151159
 10         Z10      Z    10  0.003011
 11         Z06      Z     6  0.012546
 12         Z16      Z    16  0.002710
 13         Z01      Z     1  0.398575
 14         Z12      Z    12  0.003312
 15         Z04      Z     4  0.022885,
 'R3W1':   Region Seed Region  Seed         P
 0         W13      W    13  0.005495
 1         W12      W    12  0.005694
 2         W04      W     4  0.054446
 3         W09      W     9  0.014885
 4         W08      W     8  0.033666
 5         W05      W     5  0.027972
 6         W16      W    16  0.005794
 7         W01      W     1  0.852048,
 'R3W2':   Region Seed Region  Seed         P
 0         W14      W    14  0.006511
 1         W15      W    15  0.005610
 2         W10      W    10  0.017530
 3         W07      W     7  0.029049
 4         W06      W     6  0.073124
 5         W02      W     2  0.668637
 6         W03      W     3  0.182009
 7         W11      W    11  0.017530,
 'R3X1':   Region Seed Region  Seed         P
 0         X08      X     8  0.015159
 1         X16      X    16  0.005220
 2         X09      X     9  0.022889
 3         X04      X     4  0.134324
 4         X12      X    12  0.006927
 5         X01      X     1  0.752736
 6         X13      X    13  0.007027
 7         X05      X     5  0.055717,
 'R3X2':   Region Seed Region  Seed         P
 0         X14      X    14  0.007129
 1         X11      X    11  0.009037
 2         X07      X     7  0.043277
 3         X10      X    10  0.023798
 4         X03      X     3  0.161161
 5         X15      X    15  0.005322
 6         X02      X     2  0.646752
 7         X06      X     6  0.103524,
 'R3Y1':   Region Seed Region  Seed         P
 0         Y05      Y     5  0.030394
 1         Y12      Y    12  0.006721
 2         Y16      Y    16  0.003912
 3         Y01      Y     1  0.890059
 4         Y04      Y     4  0.041328
 5         Y13      Y    13  0.004915
 6         Y09      Y     9  0.012840
 7         Y08      Y     8  0.009830,
 'R3Y2':   Region Seed Region  Seed         P
 0         Y15      Y    15  0.004918
 1         Y07      Y     7  0.019071
 2         Y03      Y     3  0.559872
 3         Y06      Y     6  0.041453
 4         Y11      Y    11  0.017164
 5         Y14      Y    14  0.010439
 6         Y02      Y     2  0.335642
 7         Y10      Y    10  0.011442,
 'R3Z1':   Region Seed Region  Seed         P
 0         Z05      Z     5  0.128030
 1         Z08      Z     8  0.018433
 2         Z13      Z    13  0.010619
 3         Z09      Z     9  0.038369
 4         Z16      Z    16  0.005209
 5         Z01      Z     1  0.722501
 6         Z12      Z    12  0.007614
 7         Z04      Z     4  0.069225,
 'R3Z2':   Region Seed Region  Seed         P
 0         Z11      Z    11  0.006632
 1         Z03      Z     3  0.572146
 2         Z07      Z     7  0.038384
 3         Z14      Z    14  0.005024
 4         Z15      Z    15  0.005928
 5         Z02      Z     2  0.325563
 6         Z10      Z    10  0.007436
 7         Z06      Z     6  0.038887,
 'R2W1':   Region Seed Region  Seed         P
 0         W09      W     9  0.035778
 1         W08      W     8  0.049432
 2         W16      W    16  0.011361
 3         W01      W     1  0.903428,
 'R2W2':   Region Seed Region  Seed         P
 0         W15      W    15  0.013018
 1         W10      W    10  0.050871
 2         W07      W     7  0.066593
 3         W02      W     2  0.869517,
 'R2W3':   Region Seed Region  Seed         P
 0         W14      W    14  0.018726
 1         W06      W     6  0.229722
 2         W03      W     3  0.656519
 3         W11      W    11  0.095033,
 'R2W4':   Region Seed Region  Seed         P
 0         W13      W    13  0.031983
 1         W12      W    12  0.036094
 2         W04      W     4  0.597854
 3         W05      W     5  0.334069,
 'R2X1':   Region Seed Region  Seed         P
 0         X08      X     8  0.035241
 1         X16      X    16  0.011044
 2         X09      X     9  0.046084
 3         X01      X     1  0.907631,
 'R2X2':   Region Seed Region  Seed         P
 0         X07      X     7  0.094870
 1         X10      X    10  0.053709
 2         X15      X    15  0.011947
 3         X02      X     2  0.839474,
 'R2X3':   Region Seed Region  Seed         P
 0         X14      X    14  0.022691
 1         X11      X    11  0.036546
 2         X03      X     3  0.617671
 3         X06      X     6  0.323092,
 'R2X4':   Region Seed Region  Seed         P
 0         X04      X     4  0.621711
 1         X12      X    12  0.030528
 2         X13      X    13  0.028721
 3         X05      X     5  0.319040,
 'R2Y1':   Region Seed Region  Seed         P
 0         Y16      Y    16  0.007826
 1         Y01      Y     1  0.947728
 2         Y09      Y     9  0.023778
 3         Y08      Y     8  0.020668,
 'R2Y2':   Region Seed Region  Seed         P
 0         Y15      Y    15  0.013651
 1         Y07      Y     7  0.075078
 2         Y02      Y     2  0.862592
 3         Y10      Y    10  0.048680,
 'R2Y3':   Region Seed Region  Seed         P
 0         Y03      Y     3  0.829386
 1         Y06      Y     6  0.120434
 2         Y11      Y    11  0.029707
 3         Y14      Y    14  0.020474,
 'R2Y4':   Region Seed Region  Seed         P
 0         Y05      Y     5  0.338491
 1         Y12      Y    12  0.066914
 2         Y04      Y     4  0.568371
 3         Y13      Y    13  0.026223,
 'R2Z1':   Region Seed Region  Seed         P
 0         Z08      Z     8  0.039582
 1         Z09      Z     9  0.068716
 2         Z16      Z    16  0.010950
 3         Z01      Z     1  0.880751,
 'R2Z2':   Region Seed Region  Seed         P
 0         Z07      Z     7  0.154140
 1         Z15      Z    15  0.014168
 2         Z02      Z     2  0.803658
 3         Z10      Z    10  0.028035,
 'R2Z3':   Region Seed Region  Seed         P
 0         Z11      Z    11  0.018288
 1         Z03      Z     3  0.856411
 2         Z14      Z    14  0.013264
 3         Z06      Z     6  0.112038,
 'R2Z4':   Region Seed Region  Seed         P
 0         Z05      Z     5  0.574958
 1         Z13      Z    13  0.034964
 2         Z12      Z    12  0.024704
 3         Z04      Z     4  0.365375,
 'R1W1':   Region Seed Region  Seed         P
 0         W16      W    16  0.026441
 1         W01      W     1  0.973559,
 'R1W2':   Region Seed Region  Seed         P
 0         W15      W    15  0.039964
 1         W02      W     2  0.960036,
 'R1W3':   Region Seed Region  Seed         P
 0         W14      W    14  0.056012
 1         W03      W     3  0.943988,
 'R1W4':   Region Seed Region  Seed         P
 0         W13      W    13  0.102595
 1         W04      W     4  0.897405,
 'R1W5':   Region Seed Region  Seed         P
 0         W12      W    12  0.139565
 1         W05      W     5  0.860435,
 'R1W6':   Region Seed Region  Seed         P
 0         W06      W     6  0.721287
 1         W11      W    11  0.278713,
 'R1W7':   Region Seed Region  Seed         P
 0         W10      W    10  0.450035
 1         W07      W     7  0.549965,
 'R1W8':   Region Seed Region  Seed         P
 0         W09      W     9  0.394167
 1         W08      W     8  0.605833,
 'R1X1':   Region Seed Region  Seed       P
 0         X16      X    16  0.0245
 1         X01      X     1  0.9755,
 'R1X2':   Region Seed Region  Seed        P
 0         X15      X    15  0.03566
 1         X02      X     2  0.96434,
 'R1X3':   Region Seed Region  Seed         P
 0         X14      X    14  0.073252
 1         X03      X     3  0.926748,
 'R1X4':   Region Seed Region  Seed         P
 0         X04      X     4  0.922621
 1         X13      X    13  0.077379,
 'R1X5':   Region Seed Region  Seed         P
 0         X12      X    12  0.146734
 1         X05      X     5  0.853266,
 'R1X6':   Region Seed Region  Seed         P
 0         X11      X    11  0.161592
 1         X06      X     6  0.838408,
 'R1X7':   Region Seed Region  Seed         P
 0         X07      X     7  0.621508
 1         X10      X    10  0.378492,
 'R1X8':   Region Seed Region  Seed        P
 0         X08      X     8  0.51382
 1         X09      X     9  0.48618,
 'R1Y1':   Region Seed Region  Seed         P
 0         Y16      Y    16  0.016759
 1         Y01      Y     1  0.983241,
 'R1Y2':   Region Seed Region  Seed         P
 0         Y15      Y    15  0.032135
 1         Y02      Y     2  0.967865,
 'R1Y3':   Region Seed Region  Seed         P
 0         Y03      Y     3  0.954714
 1         Y14      Y    14  0.045286,
 'R1Y4':   Region Seed Region  Seed        P
 0         Y04      Y     4  0.91742
 1         Y13      Y    13  0.08258,
 'R1Y5':   Region Seed Region  Seed         P
 0         Y05      Y     5  0.805505
 1         Y12      Y    12  0.194495,
 'R1Y6':   Region Seed Region  Seed         P
 0         Y06      Y     6  0.845242
 1         Y11      Y    11  0.154758,
 'R1Y7':   Region Seed Region  Seed         P
 0         Y07      Y     7  0.644221
 1         Y10      Y    10  0.355779,
 'R1Y8':   Region Seed Region  Seed         P
 0         Y09      Y     9  0.425543
 1         Y08      Y     8  0.574457,
 'R1Z1':   Region Seed Region  Seed         P
 0         Z16      Z    16  0.027739
 1         Z01      Z     1  0.972261,
 'R1Z2':   Region Seed Region  Seed        P
 0         Z15      Z    15  0.03881
 1         Z02      Z     2  0.96119,
 'R1Z3':   Region Seed Region  Seed         P
 0         Z03      Z     3  0.960286
 1         Z14      Z    14  0.039714,
 'R1Z4':   Region Seed Region  Seed         P
 0         Z13      Z    13  0.124321
 1         Z04      Z     4  0.875679,
 'R1Z5':   Region Seed Region  Seed         P
 0         Z05      Z     5  0.919051
 1         Z12      Z    12  0.080949,
 'R1Z6':   Region Seed Region  Seed         P
 0         Z11      Z    11  0.153366
 1         Z06      Z     6  0.846634,
 'R1Z7':   Region Seed Region  Seed         P
 0         Z07      Z     7  0.794064
 1         Z10      Z    10  0.205936,
 'R1Z8':   Region Seed Region  Seed         P
 0         Z08      Z     8  0.501308
 1         Z09      Z     9  0.498692}

In [21]:
def fill_in_team(bracket: dict, round_: int, team: str, region: str, seed: int) -> dict:
    """
    Helper for simulate_public
    Fill in previous rounds of bracket for a team that wins in a future round
    """
    for r in range(1, min(round_ + 1, 4)):
        if seed > 2**(4-r):
            seed = 2**(5-r) + 1 - seed
        bracket[f'R{r}{region}{seed}'] = team

    if round_ >= 4:
        bracket[f'R4{region}1'] = team
    if round_ >= 5:
        if region in ('W', 'X'):
            bracket[f'R5WX'] = team
        else:
            bracket[f'R5YZ'] = team
    if round_ == 6:
        bracket[f'R6CH'] = team

    return bracket


def simulate_public():
    """
    Get bracket based on probabilities of winning each round
    """
    bracket = dict()

    # ROUND 6
    for matchup in ('R6CH', ):
        if not bracket.get(matchup):
            df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
            winner = df_matchup.loc[
                np.random.choice(
                    df_matchup.index,
                    p=df_matchup['P'],
                ),
                :
            ]
            bracket = fill_in_team(bracket, 6, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 5
    for matchup in ('R5WX', 'R5YZ'):
        if not bracket.get(matchup):
            df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
            winner = df_matchup.loc[
                np.random.choice(
                    df_matchup.index,
                    p=df_matchup['P'],
                ),
                :
            ]
            bracket = fill_in_team(bracket, 5, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 4
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 2):
            matchup = f'R4{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 4, winner['Region Seed'], winner['Region'], winner['Seed'])



    # ROUND 3
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 3):
            matchup = f'R3{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 3, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 2
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 5):
            matchup = f'R2{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 2, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 1
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 9):
            matchup = f'R1{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 1, winner['Region Seed'], winner['Region'], winner['Seed'])

    return dict(sorted(bracket.items()))

simulate_public()

{'R1W1': 'W01',
 'R1W2': 'W02',
 'R1W3': 'W03',
 'R1W4': 'W04',
 'R1W5': 'W12',
 'R1W6': 'W11',
 'R1W7': 'W07',
 'R1W8': 'W08',
 'R1X1': 'X01',
 'R1X2': 'X02',
 'R1X3': 'X03',
 'R1X4': 'X04',
 'R1X5': 'X05',
 'R1X6': 'X06',
 'R1X7': 'X10',
 'R1X8': 'X09',
 'R1Y1': 'Y01',
 'R1Y2': 'Y02',
 'R1Y3': 'Y03',
 'R1Y4': 'Y04',
 'R1Y5': 'Y05',
 'R1Y6': 'Y06',
 'R1Y7': 'Y07',
 'R1Y8': 'Y09',
 'R1Z1': 'Z01',
 'R1Z2': 'Z02',
 'R1Z3': 'Z03',
 'R1Z4': 'Z04',
 'R1Z5': 'Z05',
 'R1Z6': 'Z06',
 'R1Z7': 'Z10',
 'R1Z8': 'Z08',
 'R2W1': 'W01',
 'R2W2': 'W02',
 'R2W3': 'W03',
 'R2W4': 'W04',
 'R2X1': 'X01',
 'R2X2': 'X02',
 'R2X3': 'X03',
 'R2X4': 'X04',
 'R2Y1': 'Y01',
 'R2Y2': 'Y02',
 'R2Y3': 'Y03',
 'R2Y4': 'Y05',
 'R2Z1': 'Z01',
 'R2Z2': 'Z02',
 'R2Z3': 'Z03',
 'R2Z4': 'Z04',
 'R3W1': 'W01',
 'R3W2': 'W02',
 'R3X1': 'X01',
 'R3X2': 'X02',
 'R3Y1': 'Y01',
 'R3Y2': 'Y03',
 'R3Z1': 'Z01',
 'R3Z2': 'Z03',
 'R4W1': 'W01',
 'R4X1': 'X02',
 'R4Y1': 'Y01',
 'R4Z1': 'Z01',
 'R5WX': 'W01',
 'R5YZ': 'Y01',
 'R6CH': 'Y01'}

In [22]:
np.random.seed(24)

public_brackets = tuple(simulate_public() for _ in trange(2_000))  # set back to 20_000

len(public_brackets)

  0%|          | 0/2000 [00:00<?, ?it/s]

2000

In [23]:
np.random.seed(25)

public_candidates = tuple(simulate_public() for _ in trange(2_000))  # set back to 20_000

len(public_candidates)

  0%|          | 0/2000 [00:00<?, ?it/s]

2000

In [24]:
simulation_data = {
    'results': results,
    'candidates': my_candidates + public_candidates,
    'public': public_brackets,
}

len(simulation_data)

3

In [25]:
import pickle

with open(f'../data/simulations/mens/womens_simulation_{season}.pkl', 'wb') as f:
    pickle.dump(simulation_data, f)

'Done'

'Done'