# Simulate Women's Tourney

Generated brackets based on model probabilities and public picks.

In [1]:
season = 2025

playin_losers = (  # remove play-in losers from seeding data
    3343,  # Princeton
    3380,  # Southern Univ
    3456,  # William & Mary
    3162,  # Columbia
)

season

2025

In [2]:
import pandas as pd

pd.set_option('display.max_columns', 100)

df_seeds = pd.read_csv(r'..\data\unprocessed\kaggle\WNCAATourneySeeds.csv')

df_seeds = df_seeds.loc[df_seeds['Season'] == season, :].reset_index(drop=True)

df_seeds.insert(2, 'Play In', df_seeds['Seed'].str.endswith(('a', 'b')))
df_seeds.insert(2, 'Region', df_seeds['Seed'].str[0])
df_seeds['Seed'] = df_seeds['Seed'].str.extract('(\d+)').astype(int)

df_seeds = df_seeds.loc[~df_seeds['TeamID'].isin(playin_losers), :].reset_index(drop=True)

df_seeds.insert(1, 'Region Seed', df_seeds['Region'] + df_seeds['Seed'].astype(str).str.zfill(2))

df_seeds

    Season Region Seed  Seed Region  Play In  TeamID
0     2025         W01     1      W    False    3376
1     2025         W02     2      W    False    3181
2     2025         W03     3      W    False    3314
3     2025         W04     4      W    False    3268
4     2025         W05     5      W    False    3104
..     ...         ...   ...    ...      ...     ...
59    2025         Z12    12      Z    False    3193
60    2025         Z13    13      Z    False    3251
61    2025         Z14    14      Z    False    3195
62    2025         Z15    15      Z    False    3117
63    2025         Z16    16      Z    False    3422

[64 rows x 6 columns]

### Simulate Tournament

I think it might make more sense to just go through all 63 matchups as a dictionary, adding future rounds as you go

In [3]:
df_matrix = pd.read_csv(
    fr'../data/simulations/womens/matchup_matrix_{season}.csv',
    index_col='Team A ID',
).rename_axis(index=None)

df_matrix.columns = df_matrix.columns.astype(int)

df_matrix

,3104,3117,3123,3124,3143,3163,3166,3181,3192,3193,3195,3199,3206,3210,3213,3217,3219,3228,3231,3234,3235,3243,3246,3250,3251,3257,3261,3268,3276,3277,3279,3280,3286,3293,3301,3304,3313,3314,3323,3326,3328,3329,3332,3333,3350,3355,3361,3372,3376,3378,3395,3397,3399,3400,3417,3422,3425,3428,3435,3436,3449,3452,3453,3471
3104,NaN,0.954425,0.862467,0.372033,0.541847,0.087864,0.652267,0.342667,0.954425,0.835100,0.884582,0.640815,0.874335,0.753463,0.750500,0.768107,0.954425,0.764072,0.581044,0.550366,0.570316,0.287321,0.455343,0.952046,0.928469,0.641058,0.443561,0.497065,0.734790,0.829342,0.600898,0.856105,0.875358,0.921048,0.409789,0.684127,0.950864,0.724483,0.247309,0.595001,0.252251,0.739176,0.766506,0.942274,0.845440,0.744695,0.952046,0.947817,0.077059,0.921624,0.416816,0.185871,0.952046,0.081202,0.140245,0.952046,0.139300,0.742769,0.374175,0.952477,0.758456,0.367937,0.921361,0.954425
3117,0.046241,NaN,0.136014,0.046241,0.074816,0.046241,0.061890,0.046241,0.676768,0.138150,0.123514,0.048721,0.141297,0.067108,0.138150,0.080245,0.717240,0.066815,0.079564,0.046241,0.066054,0.046241,0.046672,0.301205,0.151207,0.065794,0.046241,0.046428,0.046241,0.061645,0.046241,0.066586,0.256361,0.259487,0.046241,0.080969,0.159623,0.046241,0.046241,0.046241,0.046241,0.061645,0.082139,0.389568,0.075024,0.118245,0.292961,0.263546,0.046241,0.136279,0.046241,0.048721,0.341281,0.046241,0.046241,0.476526,0.046241,0.065671,0.065774,0.292612,0.080969,0.046241,0.132868,0.714069
3123,0.140053,0.859297,NaN,0.127437,0.245238,0.046241,0.236148,0.046241,0.862661,0.413658,0.305752,0.244499,0.363310,0.264219,0.339524,0.270448,0.875467,0.263888,0.220087,0.175675,0.236148,0.129318,0.242248,0.825866,0.559752,0.221183,0.048721,0.203733,0.224457,0.221495,0.117810,0.264219,0.319590,0.316750,0.086836,0.261089,0.669545,0.105485,0.048721,0.130390,0.056356,0.245238,0.274833,0.654809,0.244614,0.141442,0.768335,0.586236,0.046241,0.448056,0.052144,0.136411,0.781152,0.046241,0.046241,0.859962,0.049795,0.257495,0.263305,0.823036,0.263761,0.117262,0.336277,0.874217
3124,0.620468,0.954425,0.878050,NaN,0.785477,0.142686,0.653449,0.364951,0.954425,0.876843,0.901825,0.706472,0.876109,0.742643,0.841218,0.789013,0.954425,0.803046,0.530797,0.735331,0.801006,0.643303,0.742140,0.952477,0.952477,0.763242,0.323683,0.647489,0.685385,0.750671,0.449941,0.797942,0.910697,0.841170,0.550215,0.691038,0.952477,0.749827,0.249880,0.704612,0.490489,0.607890,0.600344,0.950395,0.783243,0.766673,0.954425,0.954425,0.125606,0.934422,0.327459,0.373152,0.954425,0.142249,0.084966,0.954425,0.216817,0.798224,0.671117,0.954425,0.761857,0.703876,0.928378,0.954425
3143,0.392624,0.931992,0.747924,0.209767,NaN,0.059661,0.277877,0.130213,0.939002,0.738938,0.552610,0.499918,0.721801,0.526839,0.731626,0.704961,0.939002,0.315131,0.369112,0.225528,0.326007,0.253563,0.252194,0.861248,0.748786,0.174561,0.206469,0.241574,0.232640,0.153332,0.211973,0.315919,0.750656,0.646526,0.293978,0.444458,0.751396,0.169515,0.075503,0.218345,0.211883,0.371675,0.535098,0.895003,0.516256,0.476825,0.858663,0.855659,0.059661,0.654836,0.122023,0.249753,0.919149,0.059661,0.108926,0.925169,0.116708,0.265431,0.264312,0.859605,0.452633,0.209198,0.728901,0.939002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3436,0.048721,0.703111,0.175389,0.046241,0.135181,0.046241,0.113782,0.046241,0.720350,0.160107,0.197958,0.056581,0.200513,0.126121,0.169358,0.146780,0.725169,0.136932,0.122464,0.053509,0.123311,0.048721,0.047002,0.674722,0.299534,0.121718,0.046241,0.082585,0.053509,0.065671,0.048721,0.123463,0.309202,0.260307,0.046241,0.128394,0.370151,0.053509,0.046241,0.046241,0.046241,0.113282,0.127838,0.522304,0.126667,0.118245,0.668074,0.313668,0.046241,0.259239,0.050826,0.048721,0.690069,0.046241,0.046241,0.695864,0.046241,0.122249,0.075277,NaN,0.124316,0.046241,0.290932,0.723277
3449,0.241788,0.925705,0.730424,0.235022,0.551163,0.046241,0.262592,0.145750,0.933700,0.727115,0.631275,0.263086,0.704048,0.286992,0.728625,0.491296,0.938749,0.597604,0.195834,0.168433,0.232795,0.234771,0.346601,0.846087,0.732509,0.331790,0.078254,0.135114,0.147651,0.198662,0.241788,0.378827,0.716938,0.619130,0.082508,0.530031,0.730937,0.370902,0.072391,0.166628,0.141771,0.383084,0.765445,0.802535,0.444726,0.598180,0.866635,0.795640,0.046241,0.746858,0.117771,0.211276,0.870477,0.046241,0.039786,0.925705,0.043813,0.148126,0.256680,0.870120,NaN,0.320912,0.732214,0.938749
3452,0.626232,0.954425,0.885726,0.296301,0.785878,0.134175,0.641953,0.259982,0.954425,0.873438,0.861602,0.651408,0.786673,0.677624,0.886454,0.770716,0.964307,0.765904,0.639332,0.562549,0.784305,0.737586,0.740639,0.952046,0.935548,0.653482,0.446750,0.518085,0.651629,0.743747,0.556107,0.785928,0.928183,0.827114,0.459250,0.657187,0.886808,0.742396,0.212247,0.631458,0.536661,0.857212,0.773386,0.935797,0.757962,0.757526,0.941059,0.930178,0.129538,0.906001,0.287749,0.495815,0.952477,0.088975,0.155285,0.954425,0.165395,0.800215,0.611286,0.954425,0.674219,NaN,0.929090,0.954425
3453,0.087572,0.862197,0.654304,0.077713,0.274891,0.046241,0.082453,0.050826,0.807995,0.511468,0.403821,0.245238,0.457574,0.277670,0.551266,0.281680,0.874217,0.265632,0.227443,0.122564,0.225045,0.049464,0.145897,0.711360,0.668902,0.127432,0.048721,0.126630,0.179936,0.140334,0.071893,0.265255,0.539189,0.414244,0.086215,0.263761,0.805583,0.090172,0.048721,0.124801,0.062448,0.269423,0.284024,0.614846,0.245238,0.168747,0.716493,0.692824,0.046241,0.677916,0.052460,0.079544,0.724073,0.046241,0.046241,0.744939,0.050826,0.262384,0.217658,0.709112,0.263888,0.073161,NaN,0.871965
3471,0.046241,0.280063,0.123695,0.046241,0.061742,0.046241,0.061890,0.046241,0.489789,0.138150,0.123514,0.046428,0.072110,0.065931,0.138150,0.061812,0.594321,0.061742,0.061645,0.046241,0.061890,0.046241,0.046241,0.254125,0.138669,0.046428,0.046241,0.046428,0.046241,0.046241,0.046241,0.065671,0.138509,0.117966,0.046241,0.061890,0.138313,0.046241,0.046241,0.046241,0.046241,0.046241,0.066187,0.147506,0.061987,0.064465,0.154835,0.176066,0.046241,0.123514,0.046241,0.046241,0.198428,0.046241,0.046241,0.280063,0.046241,0.061645,0.046428,0.272731,0.061890,0.046241,0.128792,NaN

In [4]:
id_to_region_seed = dict(zip(df_seeds['TeamID'], df_seeds['Region Seed']))

df_matrix.index = df_matrix.index.map(id_to_region_seed)
df_matrix.columns = df_matrix.columns.map(id_to_region_seed)

df_matrix

,W05,Z15,Y12,Y04,Z08,Z02,X09,W02,X15,Z12,Z14,Y06,Y11,Y09,Y13,Y10,X16,X08,W09,Z06,X11,Z05,Z04,W15,Z13,X07,Y03,W04,X06,Y07,Y05,Z09,X13,Z11,Y02,X10,W13,W03,X03,X04,Z03,Z07,W10,W14,Y08,Z10,Y14,X14,W01,X12,X02,X05,W16,X01,Y01,Z16,Z01,W08,W07,Y15,W11,W06,W12,Y16
W05,NaN,0.954425,0.862467,0.372033,0.541847,0.087864,0.652267,0.342667,0.954425,0.835100,0.884582,0.640815,0.874335,0.753463,0.750500,0.768107,0.954425,0.764072,0.581044,0.550366,0.570316,0.287321,0.455343,0.952046,0.928469,0.641058,0.443561,0.497065,0.734790,0.829342,0.600898,0.856105,0.875358,0.921048,0.409789,0.684127,0.950864,0.724483,0.247309,0.595001,0.252251,0.739176,0.766506,0.942274,0.845440,0.744695,0.952046,0.947817,0.077059,0.921624,0.416816,0.185871,0.952046,0.081202,0.140245,0.952046,0.139300,0.742769,0.374175,0.952477,0.758456,0.367937,0.921361,0.954425
Z15,0.046241,NaN,0.136014,0.046241,0.074816,0.046241,0.061890,0.046241,0.676768,0.138150,0.123514,0.048721,0.141297,0.067108,0.138150,0.080245,0.717240,0.066815,0.079564,0.046241,0.066054,0.046241,0.046672,0.301205,0.151207,0.065794,0.046241,0.046428,0.046241,0.061645,0.046241,0.066586,0.256361,0.259487,0.046241,0.080969,0.159623,0.046241,0.046241,0.046241,0.046241,0.061645,0.082139,0.389568,0.075024,0.118245,0.292961,0.263546,0.046241,0.136279,0.046241,0.048721,0.341281,0.046241,0.046241,0.476526,0.046241,0.065671,0.065774,0.292612,0.080969,0.046241,0.132868,0.714069
Y12,0.140053,0.859297,NaN,0.127437,0.245238,0.046241,0.236148,0.046241,0.862661,0.413658,0.305752,0.244499,0.363310,0.264219,0.339524,0.270448,0.875467,0.263888,0.220087,0.175675,0.236148,0.129318,0.242248,0.825866,0.559752,0.221183,0.048721,0.203733,0.224457,0.221495,0.117810,0.264219,0.319590,0.316750,0.086836,0.261089,0.669545,0.105485,0.048721,0.130390,0.056356,0.245238,0.274833,0.654809,0.244614,0.141442,0.768335,0.586236,0.046241,0.448056,0.052144,0.136411,0.781152,0.046241,0.046241,0.859962,0.049795,0.257495,0.263305,0.823036,0.263761,0.117262,0.336277,0.874217
Y04,0.620468,0.954425,0.878050,NaN,0.785477,0.142686,0.653449,0.364951,0.954425,0.876843,0.901825,0.706472,0.876109,0.742643,0.841218,0.789013,0.954425,0.803046,0.530797,0.735331,0.801006,0.643303,0.742140,0.952477,0.952477,0.763242,0.323683,0.647489,0.685385,0.750671,0.449941,0.797942,0.910697,0.841170,0.550215,0.691038,0.952477,0.749827,0.249880,0.704612,0.490489,0.607890,0.600344,0.950395,0.783243,0.766673,0.954425,0.954425,0.125606,0.934422,0.327459,0.373152,0.954425,0.142249,0.084966,0.954425,0.216817,0.798224,0.671117,0.954425,0.761857,0.703876,0.928378,0.954425
Z08,0.392624,0.931992,0.747924,0.209767,NaN,0.059661,0.277877,0.130213,0.939002,0.738938,0.552610,0.499918,0.721801,0.526839,0.731626,0.704961,0.939002,0.315131,0.369112,0.225528,0.326007,0.253563,0.252194,0.861248,0.748786,0.174561,0.206469,0.241574,0.232640,0.153332,0.211973,0.315919,0.750656,0.646526,0.293978,0.444458,0.751396,0.169515,0.075503,0.218345,0.211883,0.371675,0.535098,0.895003,0.516256,0.476825,0.858663,0.855659,0.059661,0.654836,0.122023,0.249753,0.919149,0.059661,0.108926,0.925169,0.116708,0.265431,0.264312,0.859605,0.452633,0.209198,0.728901,0.939002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Y15,0.048721,0.703111,0.175389,0.046241,0.135181,0.046241,0.113782,0.046241,0.720350,0.160107,0.197958,0.056581,0.200513,0.126121,0.169358,0.146780,0.725169,0.136932,0.122464,0.053509,0.123311,0.048721,0.047002,0.674722,0.299534,0.121718,0.046241,0.082585,0.053509,0.065671,0.048721,0.123463,0.309202,0.260307,0.046241,0.128394,0.370151,0.053509,0.046241,0.046241,0.046241,0.113282,0.127838,0.522304,0.126667,0.118245,0.668074,0.313668,0.046241,0.259239,0.050826,0.048721,0.690069,0.046241,0.046241,0.695864,0.046241,0.122249,0.075277,NaN,0.124316,0.046241,0.290932,0.723277
W11,0.241788,0.925705,0.730424,0.235022,0.551163,0.046241,0.262592,0.145750,0.933700,0.727115,0.631275,0.263086,0.704048,0.286992,0.728625,0.491296,0.938749,0.597604,0.195834,0.168433,0.232795,0.234771,0.346601,0.846087,0.732509,0.331790,0.078254,0.135114,0.147651,0.198662,0.241788,0.378827,0.716938,0.619130,0.082508,0.530031,0.730937,0.370902,0.072391,0.166628,0.141771,0.383084,0.765445,0.802535,0.444726,0.598180,0.866635,0.795640,0.046241,0.746858,0.117771,0.211276,0.870477,0.046241,0.039786,0.925705,0.043813,0.148126,0.256680,0.870120,NaN,0.320912,0.732214,0.938749
W06,0.626232,0.954425,0.885726,0.296301,0.785878,0.134175,0.641953,0.259982,0.954425,0.873438,0.861602,0.651408,0.786673,0.677624,0.886454,0.770716,0.964307,0.765904,0.639332,0.562549,0.784305,0.737586,0.740639,0.952046,0.935548,0.653482,0.446750,0.518085,0.651629,0.743747,0.556107,0.785928,0.928183,0.827114,0.459250,0.657187,0.886808,0.742396,0.212247,0.631458,0.536661,0.857212,0.773386,0.935797,0.757962,0.757526,0.941059,0.930178,0.129538,0.906001,0.287749,0.495815,0.952477,0.088975,0.155285,0.954425,0.165395,0.800215,0.611286,0.954425,0.674219,NaN,0.929090,0.954425
W12,0.087572,0.862197,0.654304,0.077713,0.274891,0.046241,0.082453,0.050826,0.807995,0.511468,0.403821,0.245238,0.457574,0.277670,0.551266,0.281680,0.874217,0.265632,0.227443,0.122564,0.225045,0.049464,0.145897,0.711360,0.668902,0.127432,0.048721,0.126630,0.179936,0.140334,0.071893,0.265255,0.539189,0.414244,0.086215,0.263761,0.805583,0.090172,0.048721,0.124801,0.062448,0.269423,0.284024,0.614846,0.245238,0.168747,0.716493,0.692824,0.046241,0.677916,0.052460,0.079544,0.724073,0.046241,0.046241,0.744939,0.050826,0.262384,0.217658,0.709112,0.263888,0.073161,NaN,0.871965
Y16,0.046241,0.280063,0.123695,0.046241,0.061742,0.046241,0.061890,0.046241,0.489789,0.138150,0.123514,0.046428,0.072110,0.065931,0.138150,0.061812,0.594321,0.061742,0.061645,0.046241,0.061890,0.046241,0.046241,0.254125,0.138669,0.046428,0.046241,0.046428,0.046241,0.046241,0.046241,0.065671,0.138509,0.117966,0.046241,0.061890,0.138313,0.046241,0.046241,0.046241,0.046241,0.046241,0.066187,0.147506,0.061987,0.064465,0.154835,0.176066,0.046241,0.123514,0.046241,0.046241,0.198428,0.046241,0.046241,0.280063,0.046241,0.061645,0.046428,0.272731,0.061890,0.046241,0.128792,NaN

In [5]:
df_matrix_opposite = 1 - df_matrix  # prob of team losing

df_matrix_opposite

,W05,Z15,Y12,Y04,Z08,Z02,X09,W02,X15,Z12,Z14,Y06,Y11,Y09,Y13,Y10,X16,X08,W09,Z06,X11,Z05,Z04,W15,Z13,X07,Y03,W04,X06,Y07,Y05,Z09,X13,Z11,Y02,X10,W13,W03,X03,X04,Z03,Z07,W10,W14,Y08,Z10,Y14,X14,W01,X12,X02,X05,W16,X01,Y01,Z16,Z01,W08,W07,Y15,W11,W06,W12,Y16
W05,NaN,0.045575,0.137533,0.627967,0.458153,0.912136,0.347733,0.657333,0.045575,0.164900,0.115418,0.359185,0.125665,0.246537,0.249500,0.231893,0.045575,0.235928,0.418956,0.449634,0.429684,0.712679,0.544657,0.047954,0.071531,0.358942,0.556439,0.502935,0.265210,0.170658,0.399102,0.143895,0.124642,0.078952,0.590211,0.315873,0.049136,0.275517,0.752691,0.404999,0.747749,0.260824,0.233494,0.057726,0.154560,0.255305,0.047954,0.052183,0.922941,0.078376,0.583184,0.814129,0.047954,0.918798,0.859755,0.047954,0.860700,0.257231,0.625825,0.047523,0.241544,0.632063,0.078639,0.045575
Z15,0.953759,NaN,0.863986,0.953759,0.925184,0.953759,0.938110,0.953759,0.323232,0.861850,0.876486,0.951279,0.858703,0.932892,0.861850,0.919755,0.282760,0.933185,0.920436,0.953759,0.933946,0.953759,0.953328,0.698795,0.848793,0.934206,0.953759,0.953572,0.953759,0.938355,0.953759,0.933414,0.743639,0.740513,0.953759,0.919031,0.840377,0.953759,0.953759,0.953759,0.953759,0.938355,0.917861,0.610432,0.924976,0.881755,0.707039,0.736454,0.953759,0.863721,0.953759,0.951279,0.658719,0.953759,0.953759,0.523474,0.953759,0.934329,0.934226,0.707388,0.919031,0.953759,0.867132,0.285931
Y12,0.859947,0.140703,NaN,0.872563,0.754762,0.953759,0.763852,0.953759,0.137339,0.586342,0.694248,0.755501,0.636690,0.735781,0.660476,0.729552,0.124533,0.736112,0.779913,0.824325,0.763852,0.870682,0.757752,0.174134,0.440248,0.778817,0.951279,0.796267,0.775543,0.778505,0.882190,0.735781,0.680410,0.683250,0.913164,0.738911,0.330455,0.894515,0.951279,0.869610,0.943644,0.754762,0.725167,0.345191,0.755386,0.858558,0.231665,0.413764,0.953759,0.551944,0.947856,0.863589,0.218848,0.953759,0.953759,0.140038,0.950205,0.742505,0.736695,0.176964,0.736239,0.882738,0.663723,0.125783
Y04,0.379532,0.045575,0.121950,NaN,0.214523,0.857314,0.346551,0.635049,0.045575,0.123157,0.098175,0.293528,0.123891,0.257357,0.158782,0.210987,0.045575,0.196954,0.469203,0.264669,0.198994,0.356697,0.257860,0.047523,0.047523,0.236758,0.676317,0.352511,0.314615,0.249329,0.550059,0.202058,0.089303,0.158830,0.449785,0.308962,0.047523,0.250173,0.750120,0.295388,0.509511,0.392110,0.399656,0.049605,0.216757,0.233327,0.045575,0.045575,0.874394,0.065578,0.672541,0.626848,0.045575,0.857751,0.915034,0.045575,0.783183,0.201776,0.328883,0.045575,0.238143,0.296124,0.071622,0.045575
Z08,0.607376,0.068008,0.252076,0.790233,NaN,0.940339,0.722123,0.869787,0.060998,0.261062,0.447390,0.500082,0.278199,0.473161,0.268374,0.295039,0.060998,0.684869,0.630888,0.774472,0.673993,0.746437,0.747806,0.138752,0.251214,0.825439,0.793531,0.758426,0.767360,0.846668,0.788027,0.684081,0.249344,0.353474,0.706022,0.555542,0.248604,0.830485,0.924497,0.781655,0.788117,0.628325,0.464902,0.104997,0.483744,0.523175,0.141337,0.144341,0.940339,0.345164,0.877977,0.750247,0.080851,0.940339,0.891074,0.074831,0.883292,0.734569,0.735688,0.140395,0.547367,0.790802,0.271099,0.060998
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Y15,0.951279,0.296889,0.824611,0.953759,0.864819,0.953759,0.886218,0.953759,0.279650,0.839893,0.802042,0.943419,0.799487,0.873879,0.830642,0.853220,0.274831,0.863068,0.877536,0.946491,0.876689,0.951279,0.952998,0.325278,0.700466,0.878282,0.953759,0.917415,0.946491,0.934329,0.951279,0.876537,0.690798,0.739693,0.953759,0.871606,0.629849,0.946491,0.953759,0.953759,0.953759,0.886718,0.872162,0.477696,0.873333,0.881755,0.331926,0.686332,0.953759,0.740761,0.949174,0.951279,0.309931,0.953759,0.953759,0.304136,0.953759,0.877751,0.924723,NaN,0.875684,0.953759,0.709068,0.276723
W11,0.758212,0.074295,0.269576,0.764978,0.448837,0.953759,0.737408,0.854250,0.066300,0.272885,0.368725,0.736914,0.295952,0.713008,0.271375,0.508704,0.061251,0.402396,0.804166,0.831567,0.767205,0.765229,0.653399,0.153913,0.267491,0.668210,0.921746,0.864886,0.852349,0.801338,0.758212,0.621173,0.283062,0.380870,0.917492,0.469969,0.269063,0.629098,0.927609,0.833372,0.858229,0.616916,0.234555,0.197465,0.555274,0.401820,0.133365,0.204360,0.953759,0.253142,0.882229,0.788724,0.129523,0.953759,0.960214,0.074295,0.956187,0.851874,0.743320,0.129880,NaN,0.679088,0.267786,0.061251
W06,0.373768,0.045575,0.114274,0.703699,0.214122,0.865825,0.358047,0.740018,0.045575,0.126562,0.138398,0.348592,0.213327,0.322376,0.113546,0.229284,0.035693,0.234096,0.360668,0.437451,0.215695,0.262414,0.259361,0.047954,0.064452,0.346518,0.553250,0.481915,0.348371,0.256253,0.443893,0.214072,0.071817,0.172886,0.540750,0.342813,0.113192,0.257604,0.787753,0.368542,0.463339,0.142788,0.226614,0.064203,0.242038,0.242474,0.058941,0.069822,0.870462,0.093999,0.712251,0.504185,0.047523,0.911025,0.844715,0.045575,0.834605,0.199785,0.388714,0.045575,0.325781,NaN,0.070910,0.045575
W12,0.912428,0.137803,0.345696,0.922287,0.725109,0.953759,0.917547,0.949174,0.192005,0.488532,0.596179,0.754762,0.542426,0.722330,0.448734,0.718320,0.125783,0.734368,0.772557,0.877436,0.774955,0.950536,0.854103,0.288640,0.331098,0.872568,0.951279,0.873370,0.820064,0.859666,0.928107,0.734745,0.460811,0.585756,0.913785,0.736239,0.194417,0.909828,0.951279,0.875199,0.937552,0.730577,0.715976,0.385154,0.754762,0.831253,0.283507,0.307176,0.953759,0.322084,0.947540,0.920456,0.275927,0.953759,0.953759,0.255061,0.949174,0.737616,0.782342,0.290888,0.736112,0.926839,NaN,0.128035
Y16,0.953759,0.719937,0.876305,0.953759,0.938258,0.953759,0.938110,0.953759,0.510211,0.861850,0.876486,0.953572,0.927890,0.934069,0.861850,0.938188,0.405679,0.938258,0.938355,0.953759,0.938110,0.953759,0.953759,0.745875,0.861331,0.953572,0.953759,0.953572,0.953759,0.953759,0.953759,0.934329,0.861491,0.882034,0.953759,0.938110,0.861687,0.953759,0.953759,0.953759,0.953759,0.953759,0.933813,0.852494,0.938013,0.935535,0.845165,0.823934,0.953759,0.876486,0.953759,0.953759,0.801572,0.953759,0.953759,0.719937,0.953759,0.938355,0.953572,0.727269,0.938110,0.953759,0.871208,NaN

In [6]:
import numpy as np

def simulate_tournament() -> dict:
    """
    Simulate the tournament in Kaggle submission format
    """
    # ROUND 1
    round_1 = {
        f'R1{region}{i}': np.random.choice(
            (f'{region}{i:02d}', f'{region}{17-i:02d}'), 
            p=(
                df_matrix.loc[f'{region}{i:02d}', f'{region}{17-i:02d}'], 
                df_matrix_opposite.loc[f'{region}{i:02d}', f'{region}{17-i:02d}']
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 8, 5, 4, 6, 3, 7, 2)
    }

    # ROUND 2
    round_2 = {
        f'R2{region}{i}': np.random.choice(
            (round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']), 
            p=(
                df_matrix.loc[round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']], 
                df_matrix_opposite.loc[round_1[f'R1{region}{i:01d}'], round_1[f'R1{region}{9-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 4, 3, 2)
    }

    # ROUND 3
    round_3 = {
        f'R3{region}{i}': np.random.choice(
            (round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']), 
            p=(
                df_matrix.loc[round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']], 
                df_matrix_opposite.loc[round_2[f'R2{region}{i:01d}'], round_2[f'R2{region}{5-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 2)
    }

    # ROUND 4
    round_4 = {
        f'R4{region}{i}': np.random.choice(
            (round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']), 
            p=(
                df_matrix.loc[round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']], 
                df_matrix_opposite.loc[round_3[f'R3{region}{i:01d}'], round_3[f'R3{region}{3-i:01d}']]
            )
        )
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, )
    }

    # ROUND 5
    round_5 = {
        'R5WX': np.random.choice(
            (round_4['R4W1'], round_4['R4X1']),
            p=(
                df_matrix.loc[round_4['R4W1'], round_4['R4X1']],
                df_matrix_opposite.loc[round_4['R4W1'], round_4['R4X1']],
            )
        ),
        'R5YZ': np.random.choice(
            (round_4['R4Y1'], round_4['R4Z1']),
            p=(
                df_matrix.loc[round_4['R4Y1'], round_4['R4Z1']],
                df_matrix_opposite.loc[round_4['R4Y1'], round_4['R4Z1']],
            )
        ),
    }

    # ROUND 6
    round_6 = {
        'R6CH': np.random.choice(
            (round_5['R5WX'], round_5['R5YZ']),
            p=(
                df_matrix.loc[round_5['R5WX'], round_5['R5YZ']],
                df_matrix_opposite.loc[round_5['R5WX'], round_5['R5YZ']],
            )
        ),
    }

    return round_1 | round_2 | round_3 | round_4 | round_5 | round_6  # merge the dictionaries (python >= 3.9)

simulate_tournament()

{'R1W1': 'W01',
 'R1W8': 'W08',
 'R1W5': 'W12',
 'R1W4': 'W13',
 'R1W6': 'W06',
 'R1W3': 'W03',
 'R1W7': 'W10',
 'R1W2': 'W02',
 'R1X1': 'X01',
 'R1X8': 'X09',
 'R1X5': 'X05',
 'R1X4': 'X13',
 'R1X6': 'X06',
 'R1X3': 'X03',
 'R1X7': 'X07',
 'R1X2': 'X02',
 'R1Y1': 'Y01',
 'R1Y8': 'Y09',
 'R1Y5': 'Y12',
 'R1Y4': 'Y04',
 'R1Y6': 'Y06',
 'R1Y3': 'Y03',
 'R1Y7': 'Y07',
 'R1Y2': 'Y02',
 'R1Z1': 'Z01',
 'R1Z8': 'Z08',
 'R1Z5': 'Z05',
 'R1Z4': 'Z04',
 'R1Z6': 'Z06',
 'R1Z3': 'Z03',
 'R1Z7': 'Z07',
 'R1Z2': 'Z02',
 'R2W1': 'W01',
 'R2W4': 'W12',
 'R2W3': 'W03',
 'R2W2': 'W10',
 'R2X1': 'X01',
 'R2X4': 'X05',
 'R2X3': 'X06',
 'R2X2': 'X07',
 'R2Y1': 'Y01',
 'R2Y4': 'Y04',
 'R2Y3': 'Y03',
 'R2Y2': 'Y07',
 'R2Z1': 'Z01',
 'R2Z4': 'Z04',
 'R2Z3': 'Z03',
 'R2Z2': 'Z02',
 'R3W1': 'W01',
 'R3W2': 'W03',
 'R3X1': 'X05',
 'R3X2': 'X06',
 'R3Y1': 'Y01',
 'R3Y2': 'Y03',
 'R3Z1': 'Z04',
 'R3Z2': 'Z02',
 'R4W1': 'W01',
 'R4X1': 'X05',
 'R4Y1': 'Y01',
 'R4Z1': 'Z02',
 'R5WX': 'W01',
 'R5YZ': 'Z02',
 'R6CH': 'Z02'}

In [7]:
from tqdm.autonotebook import trange

np.random.seed(22)

results = tuple(
    simulate_tournament()
    for _ in trange(30_000)  # set back to 30_000
)

len(results)

C:\Users\mhugh\AppData\Local\Temp\ipykernel_19584\1353165705.py:1: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import trange

  0%|          | 0/30000 [00:00<?, ?it/s]

30000

In [8]:
np.random.seed(23)

my_candidates = tuple(
    simulate_tournament()
    for _ in trange(20_000)  # set back to 20_000
)

len(my_candidates)

  0%|          | 0/20000 [00:00<?, ?it/s]

20000

In [9]:
def bracket_to_team_placements(bracket: dict) -> dict:
    """
    Convert bracket to dict of how many games each team won
    """
    round_1 = {
        bracket[f'R1{region}{i}']: 1
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 8, 5, 4, 6, 3, 7, 2)
    }

    round_2 = {
        bracket[f'R2{region}{i}']: 2
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 4, 3, 2)
    }

    round_3 = {
        bracket[f'R3{region}{i}']: 3
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, 2)
    }

    round_4 = {
        bracket[f'R4{region}{i}']: 4
        for region in ('W', 'X', 'Y', 'Z')
        for i in (1, )
    }

    round_5 = {
        bracket['R5WX']: 5,
        bracket['R5YZ']: 5,
    }

    round_6 = {
        bracket['R6CH']: 6,
    }

    return round_1 | round_2 | round_3 | round_4 | round_5 | round_6  # merge the dictionaries (python >= 3.9)

bracket_to_team_placements(results[0])

{'W01': 4,
 'W08': 1,
 'W05': 1,
 'W04': 2,
 'W06': 3,
 'W03': 1,
 'W07': 2,
 'W02': 1,
 'X01': 6,
 'X09': 1,
 'X05': 1,
 'X04': 2,
 'X11': 1,
 'X03': 3,
 'X07': 1,
 'X02': 2,
 'Y01': 5,
 'Y09': 1,
 'Y05': 1,
 'Y04': 2,
 'Y11': 1,
 'Y03': 3,
 'Y07': 1,
 'Y02': 2,
 'Z01': 2,
 'Z09': 1,
 'Z05': 3,
 'Z04': 1,
 'Z11': 2,
 'Z14': 1,
 'Z10': 1,
 'Z02': 4}

In [10]:
from tqdm.autonotebook import tqdm

team_placements = tuple(bracket_to_team_placements(result) for result in tqdm(results))

len(team_placements)

  0%|          | 0/30000 [00:00<?, ?it/s]

30000

In [11]:
team_all_placements = {
    team: np.array([team_placements_bracket.get(team, 0) for team_placements_bracket in team_placements])
    for team in ((f'{region}{i:02d}') for region in ('W', 'X', 'Y', 'Z') for i in range(1, 17))
}

team_all_placements

{'W01': array([4, 6, 5, ..., 1, 5, 3]),
 'W02': array([1, 3, 2, ..., 4, 3, 4]),
 'W03': array([1, 1, 1, ..., 1, 2, 2]),
 'W04': array([2, 1, 1, ..., 3, 2, 2]),
 'W05': array([1, 2, 2, ..., 1, 1, 1]),
 'W06': array([3, 2, 3, ..., 2, 1, 0]),
 'W07': array([2, 1, 0, ..., 0, 1, 0]),
 'W08': array([1, 0, 0, ..., 2, 1, 1]),
 'W09': array([0, 1, 1, ..., 0, 0, 0]),
 'W10': array([0, 0, 1, ..., 1, 0, 1]),
 'W11': array([0, 0, 0, ..., 0, 0, 1]),
 'W12': array([0, 0, 0, ..., 0, 0, 0]),
 'W13': array([0, 0, 0, ..., 0, 0, 0]),
 'W14': array([0, 0, 0, ..., 0, 0, 0]),
 'W15': array([0, 0, 0, ..., 0, 0, 0]),
 'W16': array([0, 0, 0, ..., 0, 0, 0]),
 'X01': array([6, 4, 4, ..., 3, 2, 5]),
 'X02': array([2, 2, 1, ..., 1, 1, 1]),
 'X03': array([3, 1, 2, ..., 6, 4, 2]),
 'X04': array([2, 1, 2, ..., 0, 1, 1]),
 'X05': array([1, 2, 1, ..., 2, 3, 2]),
 'X06': array([0, 3, 1, ..., 1, 1, 1]),
 'X07': array([1, 1, 0, ..., 0, 2, 0]),
 'X08': array([0, 0, 1, ..., 0, 0, 0]),
 'X09': array([1, 1, 0, ..., 1, 1, 1]),
 'X10': array([0, 0, 3, ..., 2, 0, 3]),
 'X11': array([1, 0, 0, ..., 0, 0, 0]),
 'X12': array([0, 0, 0, ..., 0, 0, 0]),
 'X13': array([0, 0, 0, ..., 1, 0, 0]),
 'X14': array([0, 0, 0, ..., 0, 0, 0]),
 'X15': array([0, 0, 0, ..., 0, 0, 0]),
 'X16': array([0, 0, 0, ..., 0, 0, 0]),
 'Y01': array([5, 2, 3, ..., 4, 4, 4]),
 'Y02': array([2, 1, 4, ..., 3, 2, 0]),
 'Y03': array([3, 3, 2, ..., 1, 3, 1]),
 'Y04': array([2, 1, 2, ..., 1, 1, 2]),
 'Y05': array([1, 4, 1, ..., 2, 2, 1]),
 'Y06': array([0, 1, 0, ..., 2, 1, 3]),
 'Y07': array([1, 2, 1, ..., 1, 0, 2]),
 'Y08': array([0, 0, 0, ..., 0, 0, 0]),
 'Y09': array([1, 1, 1, ..., 1, 1, 1]),
 'Y10': array([0, 0, 0, ..., 0, 1, 0]),
 'Y11': array([1, 0, 1, ..., 0, 0, 0]),
 'Y12': array([0, 0, 0, ..., 0, 0, 0]),
 'Y13': array([0, 0, 0, ..., 0, 0, 0]),
 'Y14': array([0, 0, 0, ..., 0, 0, 0]),
 'Y15': array([0, 0, 0, ..., 0, 0, 1]),
 'Y16': array([0, 0, 0, ..., 0, 0, 0]),
 'Z01': array([2, 3, 3, ..., 5, 3, 3]),
 'Z02': array([4, 5, 6, ..., 3, 6, 6]),
 'Z03': array([0, 2, 1, ..., 2, 2, 1]),
 'Z04': array([1, 1, 1, ..., 1, 2, 2]),
 'Z05': array([3, 2, 2, ..., 2, 0, 1]),
 'Z06': array([0, 0, 2, ..., 1, 0, 2]),
 'Z07': array([0, 0, 1, ..., 0, 1, 1]),
 'Z08': array([0, 0, 1, ..., 1, 1, 0]),
 'Z09': array([1, 1, 0, ..., 0, 0, 1]),
 'Z10': array([1, 1, 0, ..., 1, 0, 0]),
 'Z11': array([2, 1, 0, ..., 0, 1, 0]),
 'Z12': array([0, 0, 0, ..., 0, 1, 0]),
 'Z13': array([0, 0, 0, ..., 0, 0, 0]),
 'Z14': array([1, 0, 0, ..., 0, 0, 0]),
 'Z15': array([0, 0, 0, ..., 0, 0, 0]),
 'Z16': array([0, 0, 0, ..., 0, 0, 0])}

Get probabilities of surviving

In [12]:
team_model_probs = dict(
    (
        t, 
        np.array(tuple(
            (v >= round).mean()
            for round in range(1, 7)
        ))
    )
    for t, v in team_all_placements.items()
)

team_model_probs

{'W01': array([0.95573333, 0.88953333, 0.82983333, 0.7526    , 0.61066667,
        0.33333333]),
 'W02': array([0.95533333, 0.68846667, 0.54903333, 0.09733333, 0.0293    ,
        0.00806667]),
 'W03': array([9.41233333e-01, 3.64033333e-01, 1.06833333e-01, 1.49333333e-02,
        2.93333333e-03, 3.33333333e-04]),
 'W04': array([8.87466667e-01, 4.84666667e-01, 5.85000000e-02, 3.32666667e-02,
        5.73333333e-03, 6.00000000e-04]),
 'W05': array([9.22666667e-01, 4.92500000e-01, 7.21666667e-02, 3.11000000e-02,
        6.33333333e-03, 8.66666667e-04]),
 'W06': array([0.6741    , 0.5084    , 0.19746667, 0.0421    , 0.00843333,
        0.0014    ]),
 'W07': array([5.56300000e-01, 2.03900000e-01, 9.27000000e-02, 1.21666667e-02,
        2.13333333e-03, 3.00000000e-04]),
 'W08': array([6.15166667e-01, 6.90666667e-02, 2.62000000e-02, 8.83333333e-03,
        1.40000000e-03, 2.33333333e-04]),
 'W09': array([3.84833333e-01, 3.83666667e-02, 1.16333333e-02, 3.90000000e-03,
        7.33333333e-04, 3.33333333e-05]),
 'W10': array([4.43700000e-01, 1.02100000e-01, 2.39666667e-02, 1.56666667e-03,
        1.66666667e-04, 3.33333333e-05]),
 'W11': array([3.25900000e-01, 1.21800000e-01, 2.90666667e-02, 2.00000000e-03,
        1.00000000e-04, 0.00000000e+00]),
 'W12': array([0.07733333, 0.01553333, 0.00083333, 0.0001    , 0.        ,
        0.        ]),
 'W13': array([1.12533333e-01, 7.30000000e-03, 6.33333333e-04, 6.66666667e-05,
        0.00000000e+00, 0.00000000e+00]),
 'W14': array([5.87666667e-02, 5.76666667e-03, 6.33333333e-04, 3.33333333e-05,
        0.00000000e+00, 0.00000000e+00]),
 'W15': array([0.04466667, 0.00553333, 0.0003    , 0.        , 0.        ,
        0.        ]),
 'W16': array([0.04426667, 0.00303333, 0.0002    , 0.        , 0.        ,
        0.        ]),
 'X01': array([0.95546667, 0.88853333, 0.80196667, 0.539     , 0.1931    ,
        0.1086    ]),
 'X02': array([0.9563    , 0.65183333, 0.34836667, 0.12326667, 0.03063333,
        0.0097    ]),
 'X03': array([0.95326667, 0.79533333, 0.5101    , 0.24313333, 0.09146667,
        0.04406667]),
 'X04': array([9.07933333e-01, 2.93800000e-01, 5.96000000e-02, 2.04000000e-02,
        3.70000000e-03, 1.33333333e-04]),
 'X05': array([0.92313333, 0.6755    , 0.1057    , 0.04596667, 0.00943333,
        0.0019    ]),
 'X06': array([6.21800000e-01, 1.36333333e-01, 6.09666667e-02, 1.09333333e-02,
        1.46666667e-03, 3.00000000e-04]),
 'X07': array([5.74033333e-01, 2.46366667e-01, 4.48333333e-02, 4.90000000e-03,
        6.00000000e-04, 1.00000000e-04]),
 'X08': array([3.02833333e-01, 2.95000000e-02, 6.23333333e-03, 1.03333333e-03,
        1.00000000e-04, 0.00000000e+00]),
 'X09': array([6.97166667e-01, 7.93666667e-02, 2.44000000e-02, 8.30000000e-03,
        1.06666667e-03, 1.33333333e-04]),
 'X10': array([4.25966667e-01, 9.93666667e-02, 1.58000000e-02, 1.23333333e-03,
        2.66666667e-04, 3.33333333e-05]),
 'X11': array([3.78200000e-01, 6.32666667e-02, 1.94333333e-02, 1.70000000e-03,
        2.33333333e-04, 3.33333333e-05]),
 'X12': array([0.07686667, 0.01703333, 0.00116667, 0.        , 0.        ,
        0.        ]),
 'X13': array([9.20666667e-02, 1.36666667e-02, 8.66666667e-04, 6.66666667e-05,
        0.00000000e+00, 0.00000000e+00]),
 'X14': array([4.67333333e-02, 5.06666667e-03, 4.33333333e-04, 6.66666667e-05,
        0.00000000e+00, 0.00000000e+00]),
 'X15': array([4.37000000e-02, 2.43333333e-03, 6.66666667e-05, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]),
 'X16': array([4.45333333e-02, 2.60000000e-03, 6.66666667e-05, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]),
 'Y01': array([0.9541    , 0.8523    , 0.75673333, 0.61566667, 0.27866667,
        0.12176667]),
 'Y02': array([0.9539    , 0.7324    , 0.2649    , 0.09016667, 0.02866667,
        0.00553333]),
 'Y03': array([0.9529    , 0.7012    , 0.5744    , 0.15703333, 0.05023333,
        0.00826667]),
 'Y04': array([0.83913333, 0.41976667, 0.07986667, 0.03543333, 0.00903333,
        0.00176667]),
 'Y05': array([0.88413333, 0.52706667, 0.121     , 0.07093333, 0.01016667,
        0.00173333]),
 'Y06': array([7.44400000e-01, 2.53200000e-01, 6.78333333e-02, 1.31000000e-02,
        1.90000000e-03, 3.00000000e-04]),
 'Y07': array([7.44200000e-01, 2.23033333e-01, 7.96666667e-02, 1.07333333e-02,
        1.36666667e-03, 1.66666667e-04]),
 'Y08': array([2.97733333e-01, 3.14333333e-02, 9.13333333e-03, 1.40000000e-03,
        2.00000000e-04, 0.00000000e+00]),
 'Y09': array([7.02266667e-01, 1.13266667e-01, 2.89333333e-02, 4.33333333e-03,
        6.33333333e-04, 3.33333333e-05]),
 'Y10': array([2.55800000e-01, 4.03666667e-02, 7.13333333e-03, 5.00000000e-04,
        3.33333333e-05, 0.00000000e+00]),
 'Y11': array([0.2556    , 0.0399    , 0.00533333, 0.00026667, 0.        ,
        0.        ]),
 'Y12': array([0.11586667, 0.0173    , 0.00123333, 0.00013333, 0.        ,
        0.        ]),
 'Y13': array([0.16086667, 0.03586667, 0.00286667, 0.0003    , 0.        ,
        0.        ]),
 'Y14': array([0.0471    , 0.0057    , 0.00053333, 0.        , 0.        ,
        0.        ]),
 'Y15': array([0.0461, 0.0042, 0.0002, 0.    , 0.    , 0.    ]),
 'Y16': array([0.0459    , 0.003     , 0.00023333, 0.        , 0.        ,
        0.        ]),
 'Z01': array([0.9535    , 0.83866667, 0.67806667, 0.34083333, 0.19223333,
        0.05576667]),
 'Z02': array([0.954     , 0.89973333, 0.75943333, 0.51786667, 0.39336667,
        0.2894    ]),
 'Z03': array([0.8971    , 0.55393333, 0.15153333, 0.0443    , 0.0105    ,
        0.00156667]),
 'Z04': array([9.40500000e-01, 3.05900000e-01, 7.40333333e-02, 1.38666667e-02,
        2.60000000e-03, 1.66666667e-04]),
 'Z05': array([0.90033333, 0.66163333, 0.20776667, 0.05233333, 0.01553333,
        0.00263333]),
 'Z06': array([8.20566667e-01, 3.89466667e-01, 5.74666667e-02, 2.02333333e-02,
        3.50000000e-03, 5.66666667e-04]),
 'Z07': array([6.08500000e-01, 5.85666667e-02, 1.69333333e-02, 4.00000000e-03,
        5.33333333e-04, 1.00000000e-04]),
 'Z08': array([3.17366667e-01, 4.99000000e-02, 1.27666667e-02, 1.53333333e-03,
        2.66666667e-04, 0.00000000e+00]),
 'Z09': array([6.82633333e-01, 1.07800000e-01, 2.41666667e-02, 3.06666667e-03,
        3.33333333e-04, 0.00000000e+00]),
 'Z10': array([3.91500000e-01, 3.79000000e-02, 1.01666667e-02, 1.50000000e-03,
        2.33333333e-04, 3.33333333e-05]),
 'Z11': array([0.17943333, 0.0359    , 0.0028    , 0.0002    , 0.        ,
        0.        ]),
 'Z12': array([0.09966667, 0.02713333, 0.00246667, 0.00013333, 0.        ,
        0.        ]),
 'Z13': array([0.0595    , 0.00533333, 0.0005    , 0.        , 0.        ,
        0.        ]),
 'Z14': array([1.02900000e-01, 2.07000000e-02, 1.53333333e-03, 6.66666667e-05,
        0.00000000e+00, 0.00000000e+00]),
 'Z15': array([4.60000000e-02, 3.80000000e-03, 1.33333333e-04, 3.33333333e-05,
        0.00000000e+00, 0.00000000e+00]),
 'Z16': array([4.65000000e-02, 3.63333333e-03, 2.33333333e-04, 3.33333333e-05,
        0.00000000e+00, 0.00000000e+00])}

In [13]:
region_seed_to_id = dict(zip(df_seeds['Region Seed'], df_seeds['TeamID']))

df_model = pd.DataFrame({
    'Team': team_model_probs.keys()
})

df_model[[f'Round {i}' for i in range(1, 7)]] = np.array(tuple(df_model['Team'].map(team_model_probs)))

df_model.insert(1, 'TeamID', df_model['Team'].map(region_seed_to_id))

df_model.sort_values(by=['Round 6'], ascending=False, inplace=True, ignore_index=True)

df_model.head(10)

  Team  TeamID   Round 1   Round 2   Round 3   Round 4   Round 5   Round 6
0  W01    3376  0.955733  0.889533  0.829833  0.752600  0.610667  0.333333
1  Z02    3163  0.954000  0.899733  0.759433  0.517867  0.393367  0.289400
2  Y01    3417  0.954100  0.852300  0.756733  0.615667  0.278667  0.121767
3  X01    3400  0.955467  0.888533  0.801967  0.539000  0.193100  0.108600
4  Z01    3425  0.953500  0.838667  0.678067  0.340833  0.192233  0.055767
5  X03    3323  0.953267  0.795333  0.510100  0.243133  0.091467  0.044067
6  X02    3395  0.956300  0.651833  0.348367  0.123267  0.030633  0.009700
7  Y03    3261  0.952900  0.701200  0.574400  0.157033  0.050233  0.008267
8  W02    3181  0.955333  0.688467  0.549033  0.097333  0.029300  0.008067
9  Y02    3301  0.953900  0.732400  0.264900  0.090167  0.028667  0.005533

In [14]:
df_teams = pd.read_csv(r'..\data\unprocessed\kaggle\WTeams.csv')

df_teams

     TeamID        TeamName
0      3101     Abilene Chr
1      3102       Air Force
2      3103           Akron
3      3104         Alabama
4      3105     Alabama A&M
..      ...             ...
373    3476       Stonehill
374    3477  East Texas A&M
375    3478        Le Moyne
376    3479      Mercyhurst
377    3480    West Georgia

[378 rows x 2 columns]

In [15]:
id_to_team = dict(zip(df_teams['TeamID'], df_teams['TeamName']))

df_model.insert(df_model.columns.get_loc('TeamID') + 1, 'Name', df_model['TeamID'].map(id_to_team))

df_model.head(25)

,Team,TeamID,Name,Round 1,Round 2,Round 3,Round 4,Round 5,Round 6
0,W01,3376,South Carolina,0.955733,0.889533,0.829833,0.752600,0.610667,0.333333
1,Z02,3163,Connecticut,0.954000,0.899733,0.759433,0.517867,0.393367,0.289400
2,Y01,3417,UCLA,0.954100,0.852300,0.756733,0.615667,0.278667,0.121767
3,X01,3400,Texas,0.955467,0.888533,0.801967,0.539000,0.193100,0.108600
4,Z01,3425,USC,0.953500,0.838667,0.678067,0.340833,0.192233,0.055767
5,X03,3323,Notre Dame,0.953267,0.795333,0.510100,0.243133,0.091467,0.044067
6,X02,3395,TCU,0.956300,0.651833,0.348367,0.123267,0.030633,0.009700
7,Y03,3261,LSU,0.952900,0.701200,0.574400,0.157033,0.050233,0.008267
8,W02,3181,Duke,0.955333,0.688467,0.549033,0.097333,0.029300,0.008067
9,Y02,3301,NC State,0.953900,0.732400,0.264900,0.090167,0.028667,0.005533
10,Z05,3243,Kansas St,0.900333,0.661633,0.207767,0.052333,0.015533,0.002633
11,X05,3397,Tennessee,0.923133,0.675500,0.105700,0.045967,0.009433,0.001900
12,Y04,3124,Baylor,0.839133,0.419767,0.079867,0.035433,0.009033,0.001767
13,Y05,3279,Mississippi,0.884133,0.527067,0.121000,0.070933,0.010167,0.001733
14,Z03,3328,Oklahoma,0.897100,0.553933,0.151533,0.044300,0.010500,0.001567
15,W06,3452,West Virginia,0.674100,0.508400,0.197467,0.042100,0.008433,0.001400
16,W05,3104,Alabama,0.922667,0.492500,0.072167,0.031100,0.006333,0.000867
17,W04,3268,Maryland,0.887467,0.484667,0.058500,0.033267,0.005733,0.000600
18,Z06,3234,Iowa,0.820567,0.389467,0.057467,0.020233,0.003500,0.000567
19,W03,3314,North Carolina,0.941233,0.364033,0.106833,0.014933,0.002933,0.000333
20,W07,3435,Vanderbilt,0.556300,0.203900,0.092700,0.012167,0.002133,0.000300
21,X06,3276,Michigan,0.621800,0.136333,0.060967,0.010933,0.001467,0.000300
22,Y06,3199,Florida St,0.744400,0.253200,0.067833,0.013100,0.001900,0.000300
23,W08,3428,Utah,0.615167,0.069067,0.026200,0.008833,0.001400,0.000233
24,Z04,3246,Kentucky,0.940500,0.305900,0.074033,0.013867,0.002600,0.000167

Get public brackets

In [16]:
df_public = pd.read_parquet(f'..\data\preprocessed\womens_yahoo\yahoo_picks_{season}.parquet')

df_public.sort_values(by=['Round 6'], ascending=False, ignore_index=True).head(10)

,Team,TeamID,Region Seed,Seed,Region,Play In,Round 1,Round 2,Round 3,Round 4,Round 5,Round 6
0,South Carolina,3376,W01,1,W,False,0.9616,0.9028,0.8253,0.7071,0.5476,0.2395
1,UCLA,3417,Y01,1,Y,False,0.9763,0.9373,0.8342,0.6493,0.3158,0.1974
2,Connecticut,3163,Z02,2,Z,False,0.9591,0.8616,0.7572,0.4212,0.2913,0.1785
3,USC,3425,Z01,1,Z,False,0.9665,0.9211,0.8259,0.4419,0.2128,0.1182
4,Texas,3400,X01,1,X,False,0.9659,0.9028,0.7341,0.4630,0.1211,0.0546
5,Notre Dame,3323,X03,3,X,False,0.9361,0.7285,0.4534,0.2452,0.0877,0.0378
6,Duke,3181,W02,2,W,False,0.9482,0.7883,0.5522,0.1225,0.0529,0.0188
7,LSU,3261,Y03,3,Y,False,0.9385,0.7420,0.4315,0.1259,0.0433,0.0172
8,TCU,3395,X02,2,X,False,0.9494,0.7381,0.3422,0.1219,0.0447,0.0158
9,N.C. State,3301,Y02,2,Y,False,0.9527,0.7501,0.3745,0.0994,0.0313,0.0120

R1X1: (1, 16)
R2X1: (1, 8, 9, 16)
R3X1: (1, 4, 5, 8, 9, 12, 13, 16)
R4X1: (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)

R1X2: (2, 15)
R2X2: (2, 7, 10, 15)
R3X2: (2, 3, 6, 7, 10, 11, 14, 15)

R1X3: (3, 14)
R2X3: (3, 6, 11, 14)

R1X4: (4, 13)
R2X4: (4, 5, 12, 13)

R1X5: (5, 12)

R1X6: (6, 11)

R1X7: (7, 10)

R1X8: (8, 9)

Partition data into possible areas in advance

In [17]:
public_dict = {
    # ROUND 6
    'R6CH': df_public.loc[:, ['Region Seed', 'Region', 'Seed', 'Round 6']].rename(columns={'Round 6': 'P'}).reset_index(drop=True),

    # ROUND 5
    'R5WX': df_public.loc[df_public['Region'].isin(('W', 'X')), ['Region Seed', 'Region', 'Seed', 'Round 5']].rename(columns={'Round 5': 'P'}).reset_index(drop=True),
    'R5YZ': df_public.loc[df_public['Region'].isin(('Y', 'Z')), ['Region Seed', 'Region', 'Seed', 'Round 5']].rename(columns={'Round 5': 'P'}).reset_index(drop=True),
}

# ROUND 4
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R4{region}1'] = df_public.loc[df_public['Region'] == region, ['Region Seed', 'Region', 'Seed', 'Round 4']].rename(columns={'Round 4': 'P'}).reset_index(drop=True)

# ROUND 3
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R3{region}1'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((1, 4, 5, 8, 9, 12, 13, 16))), ['Region Seed', 'Region', 'Seed', 'Round 3']].rename(columns={'Round 3': 'P'}).reset_index(drop=True)
    public_dict[f'R3{region}2'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((2, 3, 6, 7, 10, 11, 14, 15))), ['Region Seed', 'Region', 'Seed', 'Round 3']].rename(columns={'Round 3': 'P'}).reset_index(drop=True)

# ROUND 2
for region in ('W', 'X', 'Y', 'Z'):
    public_dict[f'R2{region}1'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((1, 8, 9, 16))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}2'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((2, 7, 10, 15))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}3'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((3, 6, 11, 14))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)
    public_dict[f'R2{region}4'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((4, 5, 12, 13))), ['Region Seed', 'Region', 'Seed', 'Round 2']].rename(columns={'Round 2': 'P'}).reset_index(drop=True)

# ROUND 1
for region in ('W', 'X', 'Y', 'Z'):
    for i in range(1, 9):
        public_dict[f'R1{region}{i}'] = df_public.loc[(df_public['Region'] == region) & (df_public['Seed'].isin((i, 17-i))), ['Region Seed', 'Region', 'Seed', 'Round 1']].rename(columns={'Round 1': 'P'}).reset_index(drop=True)

for key, value in public_dict.items():  # make sure probabilities add to 1
    # print(value['P'].sum())

    value['P'] = value['P']/value['P'].sum()
    public_dict[key] = value

    # print(value['P'].sum())
    # print()

public_dict

{'R6CH':    Region Seed Region  Seed       P
 0          W05      W     5  0.0031
 1          Z15      Z    15  0.0005
 2          Y12      Y    12  0.0012
 3          Y04      Y     4  0.0040
 4          W11      W    11  0.0007
 ..         ...    ...   ...     ...
 59         Z01      Z     1  0.1182
 60         W08      W     8  0.0014
 61         W07      W     7  0.0009
 62         Y15      Y    15  0.0003
 63         W06      W     6  0.0012

 [64 rows x 4 columns],
 'R5WX':    Region Seed Region  Seed         P
 0          W05      W     5  0.006906
 1          W11      W    11  0.001501
 2          X09      X     9  0.002702
 3          W02      W     2  0.052948
 4          X15      X    15  0.001101
 5          W12      W    12  0.001301
 6          X16      X    16  0.000901
 7          X11      X    11  0.001401
 8          X08      X     8  0.002702
 9          W09      W     9  0.003103
 10         W15      W    15  0.001401
 11         X07      X     7  0.003103
 12         W04      W     4  0.011310
 13         X06      X     6  0.010710
 14         X13      X    13  0.002302
 15         W03      W     3  0.029126
 16         X10      X    10  0.001902
 17         W13      W    13  0.001301
 18         X03      X     3  0.087779
 19         X04      X     4  0.015414
 20         W10      W    10  0.003603
 21         W14      W    14  0.001802
 22         X14      X    14  0.001201
 23         W01      W     1  0.548093
 24         X12      X    12  0.001902
 25         X02      X     2  0.044740
 26         X05      X     5  0.025023
 27         W16      W    16  0.001802
 28         X01      X     1  0.121209
 29         W08      W     8  0.002702
 30         W07      W     7  0.002302
 31         W06      W     6  0.006706,
 'R5YZ':    Region Seed Region  Seed         P
 0          Z15      Z    15  0.001200
 1          Y12      Y    12  0.002001
 2          Y04      Y     4  0.010804
 3          Z08      Z     8  0.003301
 4          Z02      Z     2  0.291417
 5          Z12      Z    12  0.001401
 6          Z14      Z    14  0.001601
 7          Y06      Y     6  0.005802
 8          Y11      Y    11  0.001801
 9          Y09      Y     9  0.002201
 10         Y13      Y    13  0.002601
 11         Y10      Y    10  0.004802
 12         Z06      Z     6  0.014506
 13         Z05      Z     5  0.005102
 14         Z04      Z     4  0.012805
 15         Y03      Y     3  0.043317
 16         Z13      Z    13  0.001401
 17         Y07      Y     7  0.003902
 18         Y05      Y     5  0.003101
 19         Z09      Z     9  0.002101
 20         Z11      Z    11  0.002801
 21         Z16      Z    16  0.001200
 22         Y02      Y     2  0.031313
 23         Z03      Z     3  0.012405
 24         Z07      Z     7  0.001501
 25         Y08      Y     8  0.002001
 26         Z10      Z    10  0.001301
 27         Y14      Y    14  0.001601
 28         Y01      Y     1  0.315926
 29         Y16      Y    16  0.001301
 30         Z01      Z     1  0.212885
 31         Y15      Y    15  0.000600,
 'R4W1':    Region Seed Region  Seed         P
 0          W05      W     5  0.015918
 1          W11      W    11  0.003425
 2          W02      W     2  0.123413
 3          W12      W    12  0.003526
 4          W09      W     9  0.007455
 5          W15      W    15  0.003224
 6          W04      W     4  0.023877
 7          W03      W     3  0.062261
 8          W13      W    13  0.002922
 9          W10      W    10  0.008463
 10         W14      W    14  0.003425
 11         W01      W     1  0.712372
 12         W16      W    16  0.003224
 13         W08      W     8  0.006246
 14         W07      W     7  0.007858
 15         W06      W     6  0.012392,
 'R4X1':    Region Seed Region  Seed         P
 0          X09      X     9  0.007463
 1          X15      X    15  0.002521
 2          X16      X    16  0.002622
 3          X11      X    11  0.003026
 4          X08      X     8  0.006455
 5          X07      X     7  0.009279
 6          X06      X     6  0.026525
 7          X13      X    13  0.004236
 8          X10      X    10  0.005446
 9          X03      X     3  0.247302
 10         X04      X     4  0.040847
 11         X14      X    14  0.002824
 12         X12      X    12  0.003933
 13         X02      X     2  0.122945
 14         X05      X     5  0.047605
 15         X01      X     1  0.466969,
 'R4Y1':    Region Seed Region  Seed         P
 0          Y12      Y    12  0.004111
 1          Y04      Y     4  0.044019
 2          Y06      Y     6  0.020154
 3          Y11      Y    11  0.003209
 4          Y09      Y     9  0.004713
 5          Y13      Y    13  0.004713
 6          Y10      Y    10  0.007621
 7          Y03      Y     3  0.126241
 8          Y07      Y     7  0.010629
 9          Y05      Y     5  0.009626
 10         Y02      Y     2  0.099669
 11         Y08      Y     8  0.004612
 12         Y14      Y    14  0.003810
 13         Y01      Y     1  0.651058
 14         Y16      Y    16  0.002908
 15         Y15      Y    15  0.002908,
 'R4Z1':    Region Seed Region  Seed         P
 0          Z15      Z    15  0.003423
 1          Z08      Z     8  0.010469
 2          Z02      Z     2  0.423998
 3          Z12      Z    12  0.002919
 4          Z14      Z    14  0.003020
 5          Z06      Z     6  0.024562
 6          Z05      Z     5  0.010670
 7          Z04      Z     4  0.025871
 8          Z13      Z    13  0.002819
 9          Z09      Z     9  0.004127
 10         Z11      Z    11  0.004731
 11         Z16      Z    16  0.002819
 12         Z03      Z     3  0.028689
 13         Z07      Z     7  0.004027
 14         Z10      Z    10  0.003020
 15         Z01      Z     1  0.444836,
 'R3W1':   Region Seed Region  Seed         P
 0         W05      W     5  0.044845
 1         W12      W    12  0.007357
 2         W09      W     9  0.021566
 3         W04      W     4  0.068528
 4         W13      W    13  0.006752
 5         W01      W     1  0.831704
 6         W16      W    16  0.006752
 7         W08      W     8  0.012496,
 'R3W2':   Region Seed Region  Seed         P
 0         W11      W    11  0.008484
 1         W02      W     2  0.557721
 2         W15      W    15  0.007373
 3         W03      W     3  0.260883
 4         W10      W    10  0.026058
 5         W14      W    14  0.008484
 6         W07      W     7  0.029088
 7         W06      W     6  0.101909,
 'R3X1':   Region Seed Region  Seed         P
 0         X09      X     9  0.016658
 1         X16      X    16  0.005048
 2         X08      X     8  0.021100
 3         X13      X    13  0.008884
 4         X04      X     4  0.095406
 5         X12      X    12  0.008279
 6         X05      X     5  0.103483
 7         X01      X     1  0.741141,
 'R3X2':   Region Seed Region  Seed         P
 0         X15      X    15  0.006870
 1         X11      X    11  0.006466
 2         X07      X     7  0.027076
 3         X06      X     6  0.134472
 4         X10      X    10  0.015256
 5         X03      X     3  0.458072
 6         X14      X    14  0.006062
 7         X02      X     2  0.345726,
 'R3Y1':   Region Seed Region  Seed         P
 0         Y12      Y    12  0.008431
 1         Y04      Y     4  0.090635
 2         Y09      Y     9  0.011844
 3         Y13      Y    13  0.008431
 4         Y05      Y     5  0.029308
 5         Y08      Y     8  0.008933
 6         Y01      Y     1  0.837298
 7         Y16      Y    16  0.005119,
 'R3Y2':   Region Seed Region  Seed         P
 0         Y06      Y     6  0.110888
 1         Y11      Y    11  0.009642
 2         Y10      Y    10  0.014363
 3         Y03      Y     3  0.433407
 4         Y07      Y     7  0.038670
 5         Y02      Y     2  0.376155
 6         Y14      Y    14  0.009341
 7         Y15      Y    15  0.007533,
 'R3Z1':   Region Seed Region  Seed         P
 0         Z08      Z     8  0.018023
 1         Z12      Z    12  0.007551
 2         Z05      Z     5  0.040878
 3         Z04      Z     4  0.079541
 4         Z13      Z    13  0.007551
 5         Z09      Z     9  0.009263
 6         Z16      Z    16  0.005638
 7         Z01      Z     1  0.831555,
 'R3Z2':   Region Seed Region  Seed         P
 0         Z15      Z    15  0.007048
 1         Z02      Z     2  0.762384
 2         Z14      Z    14  0.007149
 3         Z06      Z     6  0.108941
 4         Z11      Z    11  0.008961
 5         Z03      Z     3  0.084776
 6         Z07      Z     7  0.011780
 7         Z10      Z    10  0.008961,
 'R2W1':   Region Seed Region  Seed         P
 0         W09      W     9  0.048018
 1         W01      W     1  0.910723
 2         W16      W    16  0.013316
 3         W08      W     8  0.027943,
 'R2W2':   Region Seed Region  Seed         P
 0         W02      W     2  0.796182
 1         W15      W    15  0.015655
 2         W10      W    10  0.062317
 3         W07      W     7  0.125846,
 'R2W3':   Region Seed Region  Seed         P
 0         W11      W    11  0.024775
 1         W03      W     3  0.735767
 2         W14      W    14  0.029022
 3         W06      W     6  0.210436,
 'R2W4':   Region Seed Region  Seed         P
 0         W05      W     5  0.401557
 1         W12      W    12  0.028011
 2         W04      W     4  0.546466
 3         W13      W    13  0.023966,
 'R2X1':   Region Seed Region  Seed         P
 0         X09      X     9  0.037269
 1         X16      X    16  0.010302
 2         X08      X     8  0.040602
 3         X01      X     1  0.911827,
 'R2X2':   Region Seed Region  Seed         P
 0         X15      X    15  0.014857
 1         X07      X     7  0.182434
 2         X10      X    10  0.056701
 3         X02      X     2  0.746008,
 'R2X3':   Region Seed Region  Seed         P
 0         X11      X    11  0.017182
 1         X06      X     6  0.229331
 2         X03      X     3  0.736305
 3         X14      X    14  0.017182,
 'R2X4':   Region Seed Region  Seed         P
 0         X13      X    13  0.025483
 1         X04      X     4  0.480028
 2         X12      X    12  0.027505
 3         X05      X     5  0.466984,
 'R2Y1':   Region Seed Region  Seed         P
 0         Y09      Y     9  0.026517
 1         Y08      Y     8  0.021495
 2         Y01      Y     1  0.941442
 3         Y16      Y    16  0.010546,
 'R2Y2':   Region Seed Region  Seed         P
 0         Y10      Y    10  0.035068
 1         Y07      Y     7  0.195438
 2         Y02      Y     2  0.753718
 3         Y15      Y    15  0.015776,
 'R2Y3':   Region Seed Region  Seed         P
 0         Y06      Y     6  0.202654
 1         Y11      Y    11  0.027644
 2         Y03      Y     3  0.745879
 3         Y14      Y    14  0.023824,
 'R2Y4':   Region Seed Region  Seed         P
 0         Y12      Y    12  0.028258
 1         Y04      Y     4  0.642096
 2         Y13      Y    13  0.040527
 3         Y05      Y     5  0.289119,
 'R2Z1':   Region Seed Region  Seed         P
 0         Z08      Z     8  0.035682
 1         Z09      Z     9  0.024393
 2         Z16      Z    16  0.011491
 3         Z01      Z     1  0.928435,
 'R2Z2':   Region Seed Region  Seed         P
 0         Z15      Z    15  0.014912
 1         Z02      Z     2  0.868111
 2         Z07      Z     7  0.095919
 3         Z10      Z    10  0.021058,
 'R2Z3':   Region Seed Region  Seed         P
 0         Z14      Z    14  0.028182
 1         Z06      Z     6  0.372828
 2         Z11      Z    11  0.035455
 3         Z03      Z     3  0.563535,
 'R2Z4':   Region Seed Region  Seed         P
 0         Z12      Z    12  0.033647
 1         Z05      Z     5  0.354249
 2         Z04      Z     4  0.584420
 3         Z13      Z    13  0.027685,
 'R1W1':   Region Seed Region  Seed         P
 0         W01      W     1  0.969453
 1         W16      W    16  0.030547,
 'R1W2':   Region Seed Region  Seed         P
 0         W02      W     2  0.958165
 1         W15      W    15  0.041835,
 'R1W3':   Region Seed Region  Seed         P
 0         W03      W     3  0.934798
 1         W14      W    14  0.065202,
 'R1W4':   Region Seed Region  Seed         P
 0         W04      W     4  0.923731
 1         W13      W    13  0.076269,
 'R1W5':   Region Seed Region  Seed         P
 0         W05      W     5  0.889463
 1         W12      W    12  0.110537,
 'R1W6':   Region Seed Region  Seed         P
 0         W11      W    11  0.138243
 1         W06      W     6  0.861757,
 'R1W7':   Region Seed Region  Seed         P
 0         W10      W    10  0.406069
 1         W07      W     7  0.593931,
 'R1W8':   Region Seed Region  Seed         P
 0         W09      W     9  0.504517
 1         W08      W     8  0.495483,
 'R1X1':   Region Seed Region  Seed         P
 0         X16      X    16  0.023456
 1         X01      X     1  0.976544,
 'R1X2':   Region Seed Region  Seed         P
 0         X15      X    15  0.039166
 1         X02      X     2  0.960834,
 'R1X3':   Region Seed Region  Seed         P
 0         X03      X     3  0.947949
 1         X14      X    14  0.052051,
 'R1X4':   Region Seed Region  Seed         P
 0         X13      X    13  0.076486
 1         X04      X     4  0.923514,
 'R1X5':   Region Seed Region  Seed         P
 0         X12      X    12  0.098692
 1         X05      X     5  0.901308,
 'R1X6':   Region Seed Region  Seed         P
 0         X11      X    11  0.083274
 1         X06      X     6  0.916726,
 'R1X7':   Region Seed Region  Seed         P
 0         X07      X     7  0.686751
 1         X10      X    10  0.313249,
 'R1X8':   Region Seed Region  Seed         P
 0         X09      X     9  0.442366
 1         X08      X     8  0.557634,
 'R1Y1':   Region Seed Region  Seed         P
 0         Y01      Y     1  0.977963
 1         Y16      Y    16  0.022037,
 'R1Y2':   Region Seed Region  Seed         P
 0         Y02      Y     2  0.957295
 1         Y15      Y    15  0.042705,
 'R1Y3':   Region Seed Region  Seed         P
 0         Y03      Y     3  0.943501
 1         Y14      Y    14  0.056499,
 'R1Y4':   Region Seed Region  Seed         P
 0         Y04      Y     4  0.913639
 1         Y13      Y    13  0.086361,
 'R1Y5':   Region Seed Region  Seed         P
 0         Y12      Y    12  0.125832
 1         Y05      Y     5  0.874168,
 'R1Y6':   Region Seed Region  Seed         P
 0         Y06      Y     6  0.841251
 1         Y11      Y    11  0.158749,
 'R1Y7':   Region Seed Region  Seed         P
 0         Y10      Y    10  0.217115
 1         Y07      Y     7  0.782885,
 'R1Y8':   Region Seed Region  Seed         P
 0         Y09      Y     9  0.531531
 1         Y08      Y     8  0.468469,
 'R1Z1':   Region Seed Region  Seed      P
 0         Z16      Z    16  0.026
 1         Z01      Z     1  0.974,
 'R1Z2':   Region Seed Region  Seed         P
 0         Z15      Z    15  0.032483
 1         Z02      Z     2  0.967517,
 'R1Z3':   Region Seed Region  Seed         P
 0         Z14      Z    14  0.069737
 1         Z03      Z     3  0.930263,
 'R1Z4':   Region Seed Region  Seed         P
 0         Z04      Z     4  0.922142
 1         Z13      Z    13  0.077858,
 'R1Z5':   Region Seed Region  Seed         P
 0         Z12      Z    12  0.106719
 1         Z05      Z     5  0.893281,
 'R1Z6':   Region Seed Region  Seed         P
 0         Z06      Z     6  0.852515
 1         Z11      Z    11  0.147485,
 'R1Z7':   Region Seed Region  Seed         P
 0         Z07      Z     7  0.698083
 1         Z10      Z    10  0.301917,
 'R1Z8':   Region Seed Region  Seed         P
 0         Z08      Z     8  0.614261
 1         Z09      Z     9  0.385739}

In [18]:
def fill_in_team(bracket: dict, round_: int, team: str, region: str, seed: int) -> dict:
    """
    Helper for simulate_public
    Fill in previous rounds of bracket for a team that wins in a future round
    """
    for r in range(1, min(round_ + 1, 4)):
        if seed > 2**(4-r):
            seed = 2**(5-r) + 1 - seed
        bracket[f'R{r}{region}{seed}'] = team

    if round_ >= 4:
        bracket[f'R4{region}1'] = team
    if round_ >= 5:
        if region in ('W', 'X'):
            bracket[f'R5WX'] = team
        else:
            bracket[f'R5YZ'] = team
    if round_ == 6:
        bracket[f'R6CH'] = team

    return bracket


def simulate_public():
    """
    Get bracket based on probabilities of winning each round
    """
    bracket = dict()

    # ROUND 6
    for matchup in ('R6CH', ):
        if not bracket.get(matchup):
            df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
            winner = df_matchup.loc[
                np.random.choice(
                    df_matchup.index,
                    p=df_matchup['P'],
                ),
                :
            ]
            bracket = fill_in_team(bracket, 6, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 5
    for matchup in ('R5WX', 'R5YZ'):
        if not bracket.get(matchup):
            df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
            winner = df_matchup.loc[
                np.random.choice(
                    df_matchup.index,
                    p=df_matchup['P'],
                ),
                :
            ]
            bracket = fill_in_team(bracket, 5, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 4
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 2):
            matchup = f'R4{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 4, winner['Region Seed'], winner['Region'], winner['Seed'])



    # ROUND 3
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 3):
            matchup = f'R3{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 3, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 2
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 5):
            matchup = f'R2{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 2, winner['Region Seed'], winner['Region'], winner['Seed'])

    # ROUND 1
    for region in ('W', 'X', 'Y', 'Z'):
        for seed in range(1, 9):
            matchup = f'R1{region}{seed}'
            if not bracket.get(matchup):
                df_matchup = public_dict[matchup]  # all the teams that could win a specific game slot
                winner = df_matchup.loc[
                    np.random.choice(
                        df_matchup.index,
                        p=df_matchup['P'],
                    ),
                    :
                ]
                bracket = fill_in_team(bracket, 1, winner['Region Seed'], winner['Region'], winner['Seed'])

    return dict(sorted(bracket.items()))

simulate_public()

{'R1W1': 'W01',
 'R1W2': 'W02',
 'R1W3': 'W03',
 'R1W4': 'W04',
 'R1W5': 'W05',
 'R1W6': 'W06',
 'R1W7': 'W07',
 'R1W8': 'W08',
 'R1X1': 'X01',
 'R1X2': 'X02',
 'R1X3': 'X03',
 'R1X4': 'X04',
 'R1X5': 'X05',
 'R1X6': 'X06',
 'R1X7': 'X07',
 'R1X8': 'X08',
 'R1Y1': 'Y01',
 'R1Y2': 'Y02',
 'R1Y3': 'Y03',
 'R1Y4': 'Y04',
 'R1Y5': 'Y05',
 'R1Y6': 'Y06',
 'R1Y7': 'Y07',
 'R1Y8': 'Y08',
 'R1Z1': 'Z01',
 'R1Z2': 'Z02',
 'R1Z3': 'Z03',
 'R1Z4': 'Z04',
 'R1Z5': 'Z05',
 'R1Z6': 'Z06',
 'R1Z7': 'Z07',
 'R1Z8': 'Z09',
 'R2W1': 'W01',
 'R2W2': 'W07',
 'R2W3': 'W03',
 'R2W4': 'W04',
 'R2X1': 'X01',
 'R2X2': 'X07',
 'R2X3': 'X03',
 'R2X4': 'X05',
 'R2Y1': 'Y01',
 'R2Y2': 'Y02',
 'R2Y3': 'Y03',
 'R2Y4': 'Y05',
 'R2Z1': 'Z01',
 'R2Z2': 'Z02',
 'R2Z3': 'Z03',
 'R2Z4': 'Z04',
 'R3W1': 'W01',
 'R3W2': 'W07',
 'R3X1': 'X01',
 'R3X2': 'X03',
 'R3Y1': 'Y01',
 'R3Y2': 'Y03',
 'R3Z1': 'Z01',
 'R3Z2': 'Z02',
 'R4W1': 'W01',
 'R4X1': 'X01',
 'R4Y1': 'Y03',
 'R4Z1': 'Z02',
 'R5WX': 'W01',
 'R5YZ': 'Z02',
 'R6CH': 'W01'}

In [19]:
np.random.seed(24)

public_brackets = tuple(simulate_public() for _ in trange(20_000))  # set back to 20_000

len(public_brackets)

  0%|          | 0/20000 [00:00<?, ?it/s]

20000

In [20]:
np.random.seed(25)

public_candidates = tuple(simulate_public() for _ in trange(20_000))  # set back to 20_000

len(public_candidates)

  0%|          | 0/20000 [00:00<?, ?it/s]

20000

In [21]:
simulation_data = {
    'results': results,
    'candidates': my_candidates + public_candidates,
    'public': public_brackets,
}

len(simulation_data)

3

In [ ]:
import pickle

with open(f'../data/simulations/womens/womens_simulation_{season}.pkl', 'wb') as f:
    pickle.dump(simulation_data, f)

'Done'

'Done'